__d(
  "AdsPEFilterOperatorConfig",
  ["fbt", "AdsGenericFilterOperatorValueCardinality"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e,
      u,
      c =
        ((e = {}),
        (e.AFTER = {
          valueCardinality: (u = r("AdsGenericFilterOperatorValueCardinality"))
            .SINGLE,
          text: s._(/*BTDS*/ "after"),
          operator: "AFTER",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.BEFORE = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "before"),
          operator: "BEFORE",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.IN_RANGE = {
          valueCardinality: u.RANGE,
          text: s._(/*BTDS*/ "is between"),
          operator: "IN_RANGE",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.CONTAIN = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "contains"),
          operator: "CONTAIN",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.CONTAINS_ANY = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "contains any of"),
          operator: "CONTAINS_ANY",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.CONTAINS_ALL = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "contains all of"),
          operator: "CONTAINS_ALL",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.NOT_CONTAINS_ANY = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "doesn't contain any of"),
          operator: "NOT_CONTAINS_ANY",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.EQUAL = {
          valueCardinality: u.SINGLE,
          shortText: s._(/*BTDS*/ "="),
          text: s._(/*BTDS*/ "is"),
          operator: "EQUAL",
          useFieldDelimiterInToken: !1,
          incompleteValue: "",
        }),
        (e.GREATER_THAN = {
          valueCardinality: u.SINGLE,
          shortText: s._(/*BTDS*/ ">"),
          text: s._(/*BTDS*/ "is greater than"),
          operator: "GREATER_THAN",
          useFieldDelimiterInToken: !1,
          incompleteValue: "",
        }),
        (e.IN = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "is"),
          operator: "IN",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.NOT_IN_RANGE = {
          valueCardinality: u.RANGE,
          text: s._(/*BTDS*/ "isn't between"),
          operator: "NOT_IN_RANGE",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.NOT_CONTAIN = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "doesn't contain"),
          operator: "NOT_CONTAIN",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.NOT_IN = {
          valueCardinality: u.SINGLE,
          shortText: s._(/*BTDS*/ "not"),
          text: s._(/*BTDS*/ "is not"),
          operator: "NOT_IN",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.NOT_EQUAL = {
          valueCardinality: u.SINGLE,
          shortText: s._(/*BTDS*/ "not"),
          text: s._(/*BTDS*/ "is not"),
          operator: "NOT_EQUAL",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.LESS_THAN = {
          valueCardinality: u.SINGLE,
          shortText: s._(/*BTDS*/ "\u003C"),
          text: s._(/*BTDS*/ "is less than"),
          operator: "LESS_THAN",
          useFieldDelimiterInToken: !1,
          incompleteValue: "",
        }),
        (e.STARTS_WITH = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "starts with"),
          operator: "STARTS_WITH",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        (e.ANY = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "one of"),
          operator: "ANY",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.ALL = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "all of"),
          operator: "ALL",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.NONE = {
          valueCardinality: u.SINGLE,
          text: s._(/*BTDS*/ "none of"),
          operator: "NONE",
          useFieldDelimiterInToken: !0,
          incompleteValue: [],
        }),
        (e.MATCH = {
          valueCardinality: u.SINGLE,
          shortText: s._(/*BTDS*/ "matches regex"),
          text: s._(/*BTDS*/ "(MySQL format) REGEX"),
          operator: "MATCH",
          useFieldDelimiterInToken: !0,
          incompleteValue: "",
        }),
        e),
      d = c;
    l.default = d;
  },
  226,
);
