__d(
  "SignalsConversionTypeaheadLoggingKeys",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      SIGNALS_CONVERSION_TYPEAHEAD_API_CONTAINER_LOAD_SUCCESS:
        "signals_conversion_typeahead_api_container_load_success",
      SIGNALS_CONVERSION_TYPEAHEAD_API_CONTAINER_LOAD_ERROR:
        "signals_conversion_typeahead_api_container_load_error",
      SIGNALS_CONVERSION_TYPEAHEAD_API_CUSTOM_CONVERSIONS_LOAD_ERROR:
        "signals_conversion_typeahead_api_custom_conversions_load_error",
      SIGNALS_CONVERSION_TYPEAHEAD_API_CUSTOM_CONVERSION_STATS_LOAD_ERROR:
        "signals_conversion_typeahead_api_custom_conversion_stats_load_error",
      SIGNALS_CONVERSION_TYPEAHEAD_API_CUSTOM_CONVERSION_STATS_LOAD_SUCCESS:
        "signals_conversion_typeahead_api_custom_conversion_stats_load_success",
      SIGNALS_CONVERSION_TYPEAHEAD_API_PIXEL_EVENT_STATS_LOAD_SUCCESS:
        "signals_conversion_typeahead_api_pixel_event_stats_load_success",
      SIGNALS_CONVERSION_TYPEAHEAD_API_PIXELS_LOAD_ERROR:
        "signals_conversion_typeahead_api_pixels_load_error",
      SIGNALS_CONVERSION_TYPEAHEAD_API_PIXELS_LOAD_SUCCESS:
        "signals_conversion_typeahead_api_pixels_load_success",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_COMPONENT_MOUNTED:
        "signals_conversion_typeahead_ui_component_mounted",
      SIGNALS_MARKETING_MESSAGES_CONVERSION_TYPEAHEAD_UI_COMPONENT_MOUNTED:
        "signals_marketing_messages_conversion_typeahead_ui_component_mounted",
      SINGALS_CONVERSION_TYPEAHEAD_UI_CONVERSION_EVENT_SELECTED:
        "signals_conversion_typeahead_ui_conversion_event_selected",
      SINGALS_MARKETING_MESSAGES_CONVERSION_TYPEAHEAD_UI_CONVERSION_EVENT_SELECTED:
        "signals_marketing_messages_conversion_typeahead_ui_conversion_event_selected",
      SINGALS_CONVERSION_TYPEAHEAD_UI_CONVERSION_EVENT_UNSELECTED:
        "signals_conversion_typeahead_ui_conversion_event_unselected",
      SINGALS_MARKETING_MESSAGES_CONVERSION_TYPEAHEAD_UI_CONVERSION_EVENT_UNSELECTED:
        "signals_marketing_messages_conversion_typeahead_ui_conversion_event_unselected",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_LINK_CLICKED_DIAGNOSTICS:
        "signals_conversion_typeahead_ui_link_clicked_diagnostics",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_LINK_CLICKED_PIXEL:
        "signals_conversion_typeahead_ui_link_clicked_pixel",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_PIXEL_SELECTED:
        "signals_conversion_typeahead_ui_pixel_selected",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_PIXEL_UNSELECTED:
        "signals_conversion_typeahead_ui_pixel_unselected",
      SIGNALS_MARKETING_MESSAGES_CONVERSION_TYPEAHEAD_UI_PIXEL_UNSELECTED:
        "signals_marketing_messages_conversion_typeahead_ui_pixel_unselected",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_PIXEL_TOOLTIP_TOGGLED:
        "signals_conversion_typeahead_ui_pixel_tooltip_toggled",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_CONVERSION_EVENT_TOOLTIP_TOGGLED:
        "signals_conversion_typeahead_ui_conversion_event_tooltip_toggled",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_PIXEL_LEARN_MORE_CLICKED:
        "signals_conversion_typeahead_ui_pixel_learn_more_clicked",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_CONVERSION_EVENT_LEARN_MORE_CLICKED:
        "signals_conversion_typeahead_ui_conversion_event_learn_more_clicked",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_ADD_AD_ACCOUNT_TO_PIXEL_LINK_CLICKED:
        "signals_conversion_typeahead_ui_add_ad_account_to_pixel_link_clicked",
      SIGNALS_CONVERSION_TYPEAHEAD_UI_PIXEL_SEARCH_STARTED:
        "signals_conversion_typeahead_ui_pixel_search_started",
      SIGNALS_MARKETING_MESSAGES_CONVERSION_TYPEAHEAD_UI_PIXEL_SEARCH_STARTED:
        "signals_marketing_messages_conversion_typeahead_ui_pixel_search_started",
      SIGNALS_CONVERSION_UI_PARTNER_PLATFORM_EVENT_LOAD_ERROR:
        "signals_conversion_ui_partner_platform_event_load_error",
      SIGNALS_CONVERSION_UI_PARTNER_PLATFORM_EVENT_TOOLTIP_TOGGLED:
        "signals_conversion_ui_partner_platform_event_tooltip_toggled",
      SIGNALS_CONVERSION_UI_PARTNER_PLATFORM_EVENT_LEARN_MORE_CLICKED:
        "signals_conversion_ui_partner_platform_event_learn_more_clicked",
      SIGNALS_CONVERSION_UI_PARTNER_PLATFORM_TOGGLE:
        "signals_conversion_ui_partner_platform_toggle",
      SIGNALS_CONVERSION_UI_PARTNER_PLATFORM_SELECT:
        "signals_conversion_ui_partner_platform_select",
    });
    i.default = e;
  },
  66,
);
