__d(
  "CreativeTextSuggestionsSource",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    var e = n("$InternalEnum")({
        LLM_BRAND_IDENTITY: "LLM_BRAND_IDENTITY",
        ADS_MANAGER_LLM_HEADLINE_HEURISTICS_V1:
          "ADS_MANAGER_LLM_HEADLINE_HEURISTICS_V1",
        LLM_HEADLINE_LLAMA4_HOOKS: "LLM_HEADLINE_LLAMA4_HOOKS",
        LLM_HEADLINE_GPT_OSS_HOOKS: "LLM_HEADLINE_GPT_OSS_HOOKS",
        LLM_V2_DPO_PPO_LONG: "LLM_V2_DPO_PPO_LONG",
        LLM_FC_PPO_LLAMA3_V1: "LLM_FC_PPO_LLAMA3_V1",
        LLM_UNIFIED_MULTILINGUAL_NON_EN: "LLM_UNIFIED_MULTILINGUAL_NON_EN",
        LLM_ORCHESTRATOR_MULTILINGUAL: "LLM_ORCHESTRATOR_MULTILINGUAL",
        LLM_BRAND_ALIGNER: "LLM_BRAND_ALIGNER",
        LLM_COHORT_LLAMA3_V1: "LLM_COHORT_LLAMA3_V1",
        LLM_UNIFIED_MULTILINGUAL: "LLM_UNIFIED_MULTILINGUAL",
        LLM_UNIFIED_MULTILINGUAL_DEEPER_FUNNEL_PPO_LLAMA3_1:
          "LLM_UNIFIED_MULTILINGUAL_DEEPER_FUNNEL_PPO_LLAMA3_1",
        LLM_DEEPER_FUNNEL_PPO: "LLM_DEEPER_FUNNEL_PPO",
        LLM_DEEPER_FUNNEL_PPO_LLAMA4: "LLM_DEEPER_FUNNEL_PPO_LLAMA4",
        LLM_DEEPER_FUNNEL_HOOKS_V0: "LLM_DEEPER_FUNNEL_HOOKS_V0",
        LLM_DEEPER_FUNNEL_HOOKS_V1: "LLM_DEEPER_FUNNEL_HOOKS_V1",
        LLM_FC_PPO_LLAMA3_V1_FOR_FB: "LLM_FC_PPO_LLAMA3_V1_FOR_FB",
        LLM_DEEPER_FUNNEL_PPO_SEQUENTIAL: "LLM_DEEPER_FUNNEL_PPO_SEQUENTIAL",
        LLM_DEEPER_FUNNEL_MM: "LLM_DEEPER_FUNNEL_MM",
        LLM_PPO_TEXT_IMAGE_RM: "LLM_PPO_TEXT_IMAGE_RM",
        LLM_BRAND_LLAMA4: "LLM_BRAND_LLAMA4",
        LLM_BRAND_GPT4O: "LLM_BRAND_GPT4O",
        LLM_BRAND_HISTORICAL_ADS_V2: "LLM_BRAND_HISTORICAL_ADS_V2",
        LLM_PERSONA_V2: "LLM_PERSONA_V2",
        LLM_PERSONA_GPT4O: "LLM_PERSONA_GPT4O",
        LLM_PERSONA_EDITABLE: "LLM_PERSONA_EDITABLE",
        LLM_PERSONA_EDITABLE_COMPOUND: "LLM_PERSONA_EDITABLE_COMPOUND",
        LLM_PERSONA_DEEPER_FUNNEL: "LLM_PERSONA_DEEPER_FUNNEL",
        LLM_PERSONA_V2_COMPOUND: "LLM_PERSONA_V2_COMPOUND",
        LLM_LLAMA4_SEGMENT_BASED: "LLM_LLAMA4_SEGMENT_BASED",
        LLM_CONVERTER_BASED_PERSONA: "LLM_CONVERTER_BASED_PERSONA",
        LLM_CONVERTER_BASED_PERSONA_COMPOUND:
          "LLM_CONVERTER_BASED_PERSONA_COMPOUND",
        LLM_LLAMA4_LANDING_PAGE_CONTEXT: "LLM_LLAMA4_LANDING_PAGE_CONTEXT",
        LLM_GPT4O_LANDING_PAGE_CONTEXT: "LLM_GPT4O_LANDING_PAGE_CONTEXT",
        LLM_PERSONA_IF_MORL: "LLM_PERSONA_IF_MORL",
        LLM_DEEPER_FUNNEL_PPO_LLAMA4_ARPG_HOOK:
          "LLM_DEEPER_FUNNEL_PPO_LLAMA4_ARPG_HOOK",
        LLM_TARGET_PERSONA_BASED_GEN_BUNDLED_V1:
          "LLM_TARGET_PERSONA_BASED_GEN_BUNDLED_V1",
        LLM_TARGET_PERSONA_BASED_GEN_BUNDLED_V2:
          "LLM_TARGET_PERSONA_BASED_GEN_BUNDLED_V2",
        HEADLINE_ARPG_OSS_BUNDLE: "HEADLINE_ARPG_OSS_BUNDLE",
        HEADLINE_ARPG_L4BASE_BUNDLE: "HEADLINE_ARPG_L4BASE_BUNDLE",
        LLM_DEEPER_FUNNEL_PPO_HOOK_RM_V0: "LLM_DEEPER_FUNNEL_PPO_HOOK_RM_V0",
        LLM_DEEPER_FUNNEL_PPO_HOOK_RM_V1: "LLM_DEEPER_FUNNEL_PPO_HOOK_RM_V1",
        LLM_UNIFIED_MULTILINGUAL_DEEPER_FUNNEL_PPO_LLAMA3_V2:
          "LLM_UNIFIED_MULTILINGUAL_DEEPER_FUNNEL_PPO_LLAMA3_V2",
        LLM_UNIFIED_PRIMARY_TEXT_WITH_PERSONA:
          "LLM_UNIFIED_PRIMARY_TEXT_WITH_PERSONA",
        LLM_UNIFIED_HEADLINE_WITH_PERSONA: "LLM_UNIFIED_HEADLINE_WITH_PERSONA",
        LLM_UNIFIED_PRIMARY_TEXT_WITH_SELLING_POINT:
          "LLM_UNIFIED_PRIMARY_TEXT_WITH_SELLING_POINT",
        LLM_UNIFIED_HEADLINE_WITH_SELLING_POINT:
          "LLM_UNIFIED_HEADLINE_WITH_SELLING_POINT",
        LLM_UNIFIED_PRIMARY_TEXT_WITH_MARKETING_ANGLE:
          "LLM_UNIFIED_PRIMARY_TEXT_WITH_MARKETING_ANGLE",
        LLM_UNIFIED_HEADLINE_WITH_MARKETING_ANGLE:
          "LLM_UNIFIED_HEADLINE_WITH_MARKETING_ANGLE",
        LLM_UNIFIED_PRIMARY_TEXT_WITH_MARKETING_ANGLE_BRAND_VOICE:
          "LLM_UNIFIED_PRIMARY_TEXT_WITH_MARKETING_ANGLE_BRAND_VOICE",
        LLM_UNIFIED_HEADLINE_WITH_MARKETING_ANGLE_BRAND_VOICE:
          "LLM_UNIFIED_HEADLINE_WITH_MARKETING_ANGLE_BRAND_VOICE",
        LLM_UNIFIED_PRIMARY_TEXT_WITH_SELLING_POINT_BRAND_VOICE:
          "LLM_UNIFIED_PRIMARY_TEXT_WITH_SELLING_POINT_BRAND_VOICE",
        LLM_UNIFIED_HEADLINE_WITH_SELLING_POINT_BRAND_VOICE:
          "LLM_UNIFIED_HEADLINE_WITH_SELLING_POINT_BRAND_VOICE",
        MOCK: "mock",
        TRANSLATION_LLAMA3_V1: "TRANSLATION_LLAMA3_V1",
        ADS_MANAGER_LLM_AUTOMATION_ALPHA: "ADS_MANAGER_LLM_AUTOMATION_ALPHA",
        ADS_MANAGER_LLM_AUTOMATION_ALPHA_DEEPER_FUNNEL_USER_COHORT_BATCH_GENERATION:
          "ADS_MANAGER_LLM_AUTOMATION_ALPHA_DEEPER_FUNNEL_USER_COHORT_BATCH_GENERATION",
        ADS_MANAGER_LLM_AUTOMATION_ALPHA_BRAND_ALIGNER_USER_COHORT_SEQUENTIAL_GENERATION:
          "ADS_MANAGER_LLM_AUTOMATION_ALPHA_BRAND_ALIGNER_USER_COHORT_SEQUENTIAL_GENERATION",
        ADS_MANAGER_LLM_AUTOMATION_ALPHA_BRAND_ALIGNER_USER_COHORT_BATCH_GENERATION:
          "ADS_MANAGER_LLM_AUTOMATION_ALPHA_BRAND_ALIGNER_USER_COHORT_BATCH_GENERATION",
        AUTOMATION_DEEPER_FUNNEL_PPO_SEQUENTIAL_TWO_STAGE:
          "AUTOMATION_DEEPER_FUNNEL_PPO_SEQUENTIAL_TWO_STAGE",
        AUTOMATION_REVIEWED_DEEPER_FUNNEL_PPO_SEQUENTIAL_TWO_STAGE:
          "AUTOMATION_REVIEWED_DEEPER_FUNNEL_PPO_SEQUENTIAL_TWO_STAGE",
        DIVERSITY: "diversity",
        PARAPHRASING: "paraphrasing",
        LLM_V0: "LLM_V0",
        LC_PPO: "LC_PPO",
        LC_PPO_V2: "LC_PPO_V2",
        LLM_V2: "LLM_V2",
        LLM_V2_LONG: "LLM_V2_LONG",
        LLM_V2_DPO: "LLM_V2_DPO",
        LLM_V2_DPO_PPO: "LLM_V2_DPO_PPO",
        LLM_SEMANTIC_VARIATIONS: "LLM_SEMANTIC_VARIATIONS",
        LLM_SEMANTIC_VARIATIONS_V_1_1: "LLM_SEMANTIC_VARIATIONS_V_1_1",
        LLM_SEMANTIC_VARIATIONS_V_1_2: "LLM_SEMANTIC_VARIATIONS_V_1_2",
        LLM_SEMANTIC_VARIATIONS_SINGLE_STAGE:
          "LLM_SEMANTIC_VARIATIONS_SINGLE_STAGE",
        LLM_BRAND_IDENTITY_V_1_1: "LLM_BRAND_IDENTITY_V_1_1",
        LLM_ADS_MANAGER_LLM_ORCHESTRATOR_V1:
          "LLM_ADS_MANAGER_LLM_ORCHESTRATOR_V1",
        LLM_ADS_MANAGER_LLM_ORCHESTRATOR_V2:
          "LLM_ADS_MANAGER_LLM_ORCHESTRATOR_V2",
        LLM_ADS_MANAGER_LLM_ORCHESTRATOR_V3:
          "LLM_ADS_MANAGER_LLM_ORCHESTRATOR_V3",
        LLM_V3: "LLM_V3",
        LLM_V3_LONG: "LLM_V3_LONG",
        LLM_APP_DESCRIPTION: "LLM_APP_DESCRIPTION",
        LLM_LC_PPO_LLAMA3_V1: "LLM_LC_PPO_LLAMA3_V1",
        LLM_LC_PPO_LLAMA3_V1_FOR_IG: "LLM_LC_PPO_LLAMA3_V1_FOR_IG",
        LLM_SFT_LLAMA3_V1: "LLM_SFT_LLAMA3_V1",
        LLM_PPO_ORCHESTRATOR_V1: "LLM_PPO_ORCHESTRATOR_V1",
        LLM_LIGHTHOUSE_LLAMA3_V1: "LLM_LIGHTHOUSE_LLAMA3_V1",
        LLM_ADS_MANAGER_LLM_PURPOSEFUL_GEN_SP_V1:
          "LLM_ADS_MANAGER_LLM_PURPOSEFUL_GEN_SP_V1",
        LLM_ADS_MANAGER_LLM_PURPOSEFUL_GEN_EMOTION_V1:
          "LLM_ADS_MANAGER_LLM_PURPOSEFUL_GEN_EMOTION_V1",
        LLM_IMPLICIT_BRAND_TONE_PRIMARY_TEXT:
          "LLM_IMPLICIT_BRAND_TONE_PRIMARY_TEXT",
        LLM_IMPLICIT_BRAND_TONE_HISTORICAL_ADS:
          "LLM_IMPLICIT_BRAND_TONE_HISTORICAL_ADS",
        LLM_ADS_MANAGER_LLM_TARGET_PERSONA_GEN_V1:
          "LLM_ADS_MANAGER_LLM_TARGET_PERSONA_GEN_V1",
        LLM_FREEFORM_BRAND_TONE: "LLM_FREEFORM_BRAND_TONE",
      }),
      l = e;
    i.default = l;
  },
  66,
);
