__d(
  "BaselTheme",
  [],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        "--background-context-pressed": "#2b30360d",
        "--base-colors-legacy-grayscale-gray-08": "#2b3036",
        "--base-colors-legacy-yellows-yellow-05": "#ffd600",
        "--base-colors-legacy-yellows-yellow-08": "#955900",
        "--border-accent": "#ffd600",
        "--decorative-ig-blue": "#0095f6",
        "--decorative-ig-green": "#1cd164",
        "--decorative-ig-lavender": "#d300c5",
        "--decorative-ig-orange": "#ff7a00",
        "--decorative-ig-pink": "#ff0169",
        "--decorative-ig-purple": "#7638fa",
        "--decorative-ig-red": "#fe1d37",
        "--decorative-ig-yellow": "#ffd600",
        "--fixed-always-dark": "#0c1014",
        "--fixed-always-dark-blur": "#2b303680",
        "--fixed-always-dark-blur-fallback": "#25292ef2",
        "--fixed-always-dark-weak": "#2b3036cc",
        "--fixed-always-light": "#ffffff",
        "--fixed-always-light-blur": "#ffffff26",
        "--fixed-always-light-blur-fallback": "#fffffff2",
        "--fixed-always-light-strong": "#dce0e5cc",
        "--fixed-always-light-stronger": "#a2a9b4cc",
        "--fixed-always-light-strongest": "#57606bcc",
        "--fixed-always-light-weak": "#fffffff2",
        "--fixed-always-light-weaker": "#ffffffbf",
        "--fixed-always-light-weakest": "#ffffff80",
        "--overlay-primary": "#0c1014b2",
        "--overlay-secondary": "#0c101480",
        "--status-info": "#d300c5",
        "--text-and-icon-primary-weaker": "#838a93",
        "--text-and-icon-secondary-weak": "#838a93",
        "--timeline-adjustments": "#db3f02",
        "--timeline-adjustments-strong": "#c53902",
        "--timeline-audio": "#d300c5",
        "--timeline-audio-strong": "#a30098",
        "--timeline-captions": "#4a5df9",
        "--timeline-captions-strong": "#4150f7",
        "--timeline-filters": "#0b6ed3",
        "--timeline-overlay": "#d90052",
        "--timeline-sound-effects": "#d50b84",
        "--timeline-sound-effects-strong": "#b80a72",
        "--timeline-text": "#7638fa",
        "--timeline-visual": "#7638fa",
        "--timeline-visual-strong": "#5818dc",
      },
      s = {
        "--spacing-10": "10px",
        "--spacing-12": "12px",
        "--spacing-14": "14px",
        "--spacing-16": "16px",
        "--spacing-2": "2px",
        "--spacing-20": "20px",
        "--spacing-24": "24px",
        "--spacing-28": "28px",
        "--spacing-32": "32px",
        "--spacing-4": "4px",
        "--spacing-6": "6px",
        "--spacing-8": "8px",
      },
      u = {
        "--radius-10": "10px",
        "--radius-12": "12px",
        "--radius-14": "14px",
        "--radius-16": "16px",
        "--radius-18": "18px",
        "--radius-2": "2px",
        "--radius-20": "20px",
        "--radius-24": "24px",
        "--radius-32": "32px",
        "--radius-4": "4px",
        "--radius-8": "8px",
        "--radius-9999": "9999px",
      },
      c = {
        "--shadow-md": "0 2px 16px rgba(12, 16, 20, 0.12)",
        "--shadow-on-media": "0 0 3px rgba(0, 0, 0, 0.4)",
        "--shadow-sm": "0 2px 8px rgba(12, 16, 20, 0.08)",
      },
      d = {
        "--body-1-font-size": "14px",
        "--body-1-letter-spacing": "-0.15px",
        "--body-1-line-height": "18px",
        "--body-2-font-size": "12px",
        "--body-2-letter-spacing": "0px",
        "--body-2-line-height": "16px",
        "--body-2-mono-font-size": "12px",
        "--body-2-mono-letter-spacing": "0px",
        "--body-2-mono-line-height": "14px",
        "--body-3-font-size": "10px",
        "--body-3-letter-spacing": "0px",
        "--body-3-line-height": "10px",
        "--body-lead-font-size": "16px",
        "--body-lead-large-font-size": "18px",
        "--body-lead-large-letter-spacing": "0px",
        "--body-lead-large-line-height": "28px",
        "--body-lead-letter-spacing": "0px",
        "--body-lead-line-height": "25px",
        "--display-1-font-size": "clamp(40px, 5.7vw, 82px)",
        "--display-1-letter-spacing": "0px",
        "--display-1-line-height": "1.025",
        "--display-2-compact-font-size": "38px",
        "--display-2-compact-letter-spacing": "-0.57px",
        "--display-2-compact-line-height": "43px",
        "--display-2-font-size": "46px",
        "--display-2-letter-spacing": "-0.69px",
        "--display-2-line-height": "54px",
        "--display-3-compact-font-size": "44px",
        "--display-3-compact-letter-spacing": "-0.88px",
        "--display-3-compact-line-height": "48px",
        "--display-3-font-size": "64px",
        "--display-3-letter-spacing": "-1.28px",
        "--display-3-line-height": "70px",
        "--eyebrow-font-size": "11px",
        "--eyebrow-letter-spacing": "1.32px",
        "--eyebrow-line-height": "16px",
        "--font-family-display":
          '"SF Pro Display", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
        "--font-family-editor": '"Instagram Editor", "SF Pro Display"',
        "--font-family-mono":
          'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
        "--font-family-text":
          '"SF Pro Text", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
        "--font-weight-bold": "700",
        "--font-weight-regular": "400",
        "--font-weight-semibold": "600",
        "--heading-1-font-size": "24px",
        "--heading-1-letter-spacing": "0.07px",
        "--heading-1-line-height": "30px",
        "--heading-2-font-size": "20px",
        "--heading-2-letter-spacing": "-0.45px",
        "--heading-2-line-height": "25px",
        "--label-font-size": "16px",
        "--label-letter-spacing": "-0.32px",
        "--label-line-height": "22px",
        "--prompt-body-lead-font-size": "19px",
        "--prompt-body-lead-letter-spacing": "-0.361px",
        "--prompt-body-lead-line-height": "26.6px",
        "--prompt-section-body-font-size": "15px",
        "--prompt-section-body-letter-spacing": "-0.165px",
        "--prompt-section-body-line-height": "24.6px",
        "--prompt-section-eyebrow-font-size": "9.5px",
        "--prompt-section-eyebrow-letter-spacing": "1.235px",
        "--prompt-section-eyebrow-line-height": "9.5px",
      },
      m = {
        "--background-blur": "#f8f9f999",
        "--background-blur-fallback": "#fffffff2",
        "--background-blur-hover": "#f0f2f4a8",
        "--background-blur-hover-fallback": "#f0f2f4f2",
        "--background-blur-menu": "#ffffff66",
        "--background-blur-strong": "#f8f9f9cc",
        "--background-blur-strong-fallback": "#fffffff2",
        "--background-elevated": "#f8f9f9",
        "--background-inverse": "#191c1f",
        "--background-inverse-context-menu-pressed": "#2b30360d",
        "--background-inverse-weak": "#363c44",
        "--background-inverse-weaker": "#a2a9b4",
        "--background-inverse-weakest": "#a2a9b4",
        "--background-menu-hover": "#0c10140d",
        "--background-primary": "#ffffff",
        "--background-raised": "#ffffff",
        "--background-recessed": "#e7eaee",
        "--background-secondary": "#f0f2f5",
        "--background-secondary-strong": "#e7eaee",
        "--background-secondary-stronger": "#dce0e5",
        "--border-primary": "#191c1f",
        "--border-primary-weak": "#57606b",
        "--border-primary-weaker": "#a2a9b4",
        "--border-secondary": "#e7eaee",
        "--border-tertiary": "#0c101426",
        "--bslds-gray-0300": "#f0f2f5",
        "--bslds-gray-0400": "#e7eaee",
        "--shadow-composer":
          "0 1px 2px rgba(12, 16, 20, 0.03), 0 8px 20px -6px rgba(12, 16, 20, 0.05), 0 24px 56px -12px rgba(12, 16, 20, 0.1), 0 48px 88px -32px rgba(12, 16, 20, 0.07)",
        "--slider-track": "#c5cbd3",
        "--status-alert": "#e0010d",
        "--status-alert-strong": "#5b010b",
        "--status-alert-weak": "#ffebed",
        "--status-info-strong": "#52004b",
        "--status-info-weak": "#f9dcf7",
        "--status-positive": "#128741",
        "--status-positive-strong": "#083f1d",
        "--status-positive-weak": "#e8fcf0",
        "--status-warning": "#ffbb00",
        "--status-warning-strong": "#664400",
        "--status-warning-weak": "#fff5cd",
        "--text-and-icon-borderless-button": "#4150f7",
        "--text-and-icon-borderless-button-stronger": "#2536d0",
        "--text-and-icon-borderless-button-weaker": "#b8cdff",
        "--text-and-icon-inverse": "#f8f9f9",
        "--text-and-icon-link": "#3143e3",
        "--text-and-icon-link-stronger": "#1f28ad",
        "--text-and-icon-link-weaker": "#a3bcff",
        "--text-and-icon-primary": "#0c1014",
        "--text-and-icon-primary-weak": "#57606b",
        "--text-and-icon-primary-weakest": "#a2a9b4",
        "--text-and-icon-secondary": "#686f78",
        "--text-and-icon-secondary-weaker": "#a2a9b4",
        "--text-and-icon-secondary-weakest": "#dce0e5",
        "--text-placeholder-on-glass": "#666666",
        "--text-primary": "#0c1014",
        "--text-secondary": "#686f78",
      },
      p = {
        "--background-blur": "#191c1f99",
        "--background-blur-fallback": "#0c1014f2",
        "--background-blur-hover": "#23272ca4",
        "--background-blur-hover-fallback": "#23272cf2",
        "--background-blur-menu": "#363c4466",
        "--background-blur-strong": "#25292ecc",
        "--background-blur-strong-fallback": "#25292ef2",
        "--background-elevated": "#191c1f",
        "--background-inverse": "#f8f9f9",
        "--background-inverse-context-menu-pressed": "#f8f9f90d",
        "--background-inverse-weak": "#c5cbd3",
        "--background-inverse-weaker": "#838a93",
        "--background-inverse-weakest": "#2b3036",
        "--background-menu-hover": "#ffffff26",
        "--background-primary": "#0c1014",
        "--background-raised": "#2b3036",
        "--background-recessed": "#2b3036",
        "--background-secondary": "#25292e",
        "--background-secondary-strong": "#363c44",
        "--background-secondary-stronger": "#48505b",
        "--border-primary": "#f8f9f9",
        "--border-primary-weak": "#a2a9b4",
        "--border-primary-weaker": "#57606b",
        "--border-secondary": "#2b3036",
        "--border-tertiary": "#ffffff26",
        "--bslds-gray-0300": "#25292e",
        "--bslds-gray-0400": "#2b3036",
        "--shadow-composer":
          "0 1px 2px rgba(0, 0, 0, 0.24), 0 8px 20px -6px rgba(0, 0, 0, 0.32), 0 24px 56px -12px rgba(0, 0, 0, 0.44), 0 48px 88px -32px rgba(0, 0, 0, 0.36)",
        "--slider-track": "#48505b",
        "--status-alert": "#fe7180",
        "--status-alert-strong": "#febdc5",
        "--status-alert-weak": "#5b010b",
        "--status-info-strong": "#f2b1ee",
        "--status-info-weak": "#52004b",
        "--status-positive": "#1cd164",
        "--status-positive-strong": "#b5f7c9",
        "--status-positive-weak": "#083f1d",
        "--status-warning": "#ffdc5a",
        "--status-warning-strong": "#ffecad",
        "--status-warning-weak": "#664400",
        "--text-and-icon-borderless-button": "#708dff",
        "--text-and-icon-borderless-button-stronger": "#a3bcff",
        "--text-and-icon-borderless-button-weaker": "#18208b",
        "--text-and-icon-inverse": "#0c1014",
        "--text-and-icon-link": "#85a1ff",
        "--text-and-icon-link-stronger": "#b8cdff",
        "--text-and-icon-link-weaker": "#1f28ad",
        "--text-and-icon-primary": "#f8f9f9",
        "--text-and-icon-primary-weak": "#a2a9b4",
        "--text-and-icon-primary-weakest": "#57606b",
        "--text-and-icon-secondary": "#a2a9b4",
        "--text-and-icon-secondary-weaker": "#57606b",
        "--text-and-icon-secondary-weakest": "#2b3036",
        "--text-placeholder-on-glass": "#c5cbd3",
        "--text-primary": "#f8f9f9",
        "--text-secondary": "#a2a9b4",
      },
      _ = babelHelpers.extends({}, m, e, d, s, u, c),
      f = babelHelpers.extends({}, p, e, d, s, u, c),
      g = babelHelpers.extends({}, f, { "--background-primary": "#000000" }),
      h = { x1y6n9o8: "x33vqc3 x1y6n9o8", $$css: !0 },
      y = { x1y6n9o8: "x4d8a6p x1y6n9o8", $$css: !0 },
      C = { x1y6n9o8: "x1dkl8ms x1y6n9o8", $$css: !0 };
    ((l.BaselThemeDark = h),
      (l.BaselThemeMarketing = y),
      (l.BaselThemeLight = C));
  },
  98,
);
