__d(
  "PolarisGenericStrings",
  ["fbt"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e = s._(/*BTDS*/ ""),
      u = s._(/*BTDS*/ "Failed to Load."),
      c = s._(/*BTDS*/ "Retry"),
      d = s._(/*BTDS*/ "OK"),
      m = s._(/*BTDS*/ "Close"),
      p = s._(/*BTDS*/ "Go to fullscreen mode"),
      _ = s._(/*BTDS*/ "Exit fullscreen mode"),
      f = s._(/*BTDS*/ "Cancel"),
      g = s._(/*BTDS*/ "Delete"),
      h = s._(/*BTDS*/ "Report"),
      y = s._(/*BTDS*/ "Hide"),
      C = s._(/*BTDS*/ "Report ad"),
      b = s._(/*BTDS*/ "Hide ad"),
      v = s._(/*BTDS*/ "Not interested"),
      S = s._(/*BTDS*/ "Back"),
      R = s._(/*BTDS*/ "Uploading\u2026"),
      L = s._(/*BTDS*/ "Skip"),
      E = s._(/*BTDS*/ "Done"),
      k = s._(/*BTDS*/ "Undo"),
      I = s._(/*BTDS*/ "Follow"),
      T = s._(/*BTDS*/ "Following"),
      D = s._(/*BTDS*/ "Verified"),
      x = s._(/*BTDS*/ "Tags"),
      $ = s._(/*BTDS*/ "Search"),
      P = s._(/*BTDS*/ "Play"),
      N = s._(/*BTDS*/ "Pause"),
      M = s._(/*BTDS*/ "Learn more"),
      w = s._(/*BTDS*/ "Next"),
      A = s._(/*BTDS*/ "Finish"),
      F = s._(/*BTDS*/ "Go back"),
      O = s._(/*BTDS*/ "Comments on this post have been limited."),
      B = s._(/*BTDS*/ "Something went wrong. Please try again."),
      W = s._(
        /*BTDS*/ "Something went wrong. If you have Ad blocker enabled, consider disabling it before trying again.",
      ),
      q = s._(/*BTDS*/ "Carousel"),
      U = s._(/*BTDS*/ "Video"),
      V = s._(/*BTDS*/ "Reel"),
      H = s._(/*BTDS*/ "Pinned post icon"),
      G = s._(/*BTDS*/ "Upcoming event icon"),
      z = s._(/*BTDS*/ "Checkmark outline icon"),
      j = s._(/*BTDS*/ "Checkmark filled icon"),
      K = s._(/*BTDS*/ "Down chevron icon"),
      Q = s._(/*BTDS*/ "Up chevron icon"),
      X = s._(/*BTDS*/ "Right chevron"),
      Y = s._(/*BTDS*/ "Left chevron"),
      J = s._(/*BTDS*/ "Calendar icon"),
      Z = s._(/*BTDS*/ "Play count icon"),
      ee = s._(/*BTDS*/ "Dismiss"),
      te = s._(/*BTDS*/ "Close"),
      ne = s._(/*BTDS*/ "Digital collectible"),
      re = s._(/*BTDS*/ "Save"),
      oe = s._(/*BTDS*/ "Saved"),
      ae = s._(/*BTDS*/ "View more comments"),
      ie = s._(/*BTDS*/ "Comments"),
      le = function (t) {
        return s._(/*BTDS*/ "View all {reply count} replies", [
          s._param("reply count", t),
        ]);
      },
      se = s._(/*BTDS*/ "Hide all replies"),
      ue = s._(/*BTDS*/ "Show more replies"),
      ce = s._(/*BTDS*/ "Couldn't post comment."),
      de = s._(/*BTDS*/ "Retry"),
      me = s._(/*BTDS*/ "Oops, something happened"),
      pe = s._(/*BTDS*/ "There's an issue and we're working on it"),
      _e = s._(/*BTDS*/ "Post"),
      fe = s._(/*BTDS*/ "Add a comment\u2026"),
      ge = s._(/*BTDS*/ "Continue"),
      he = s._(/*BTDS*/ "View Count Icon"),
      ye = s._(/*BTDS*/ "Back to Instagram"),
      Ce = s._(/*BTDS*/ "See more on Instagram"),
      be = s._(
        /*BTDS*/ "The link may be broken, or the profile may have been removed.",
      ),
      ve = s._(
        /*BTDS*/ "The link may be broken, or the profile may have been removed. Use the app to find what you\u2019re looking for.",
      );
    function Se(e) {
      return s._(/*BTDS*/ "{page_type} isn't available", [
        s._param("page_type", e),
      ]);
    }
    var Re = s._(/*BTDS*/ "Swipe to explore"),
      Le = s._(/*BTDS*/ "Explore photos and videos"),
      Ee = s._(/*BTDS*/ "Photo icon"),
      ke = s._(/*BTDS*/ "Why you're seeing this ad"),
      Ie = s._(/*BTDS*/ "About Instagram Ads");
    ((l.EMPTY_STRING = e),
      (l.FAILED_TO_LOAD_TEXT = u),
      (l.RETRY_TEXT = c),
      (l.OK_TEXT = d),
      (l.CLOSE_TEXT = m),
      (l.GO_FULLSCREEN_TEXT = p),
      (l.EXIT_FULLSCREEN_TEXT = _),
      (l.CANCEL_TEXT = f),
      (l.DELETE_TEXT = g),
      (l.REPORT_TEXT = h),
      (l.HIDE_TEXT = y),
      (l.REPORT_AD_TEXT = C),
      (l.HIDE_AD_TEXT = b),
      (l.NOT_INTERESTED_TEXT = v),
      (l.BACK_TEXT = S),
      (l.UPLOADING_TEXT = R),
      (l.SKIP_TEXT = L),
      (l.DONE_TEXT = E),
      (l.UNDO_TEXT = k),
      (l.FOLLOW_TEXT = I),
      (l.FOLLOWING_TEXT = T),
      (l.VERIFIED_TEXT = D),
      (l.TAG_TEXT = x),
      (l.SEARCH_TEXT = $),
      (l.ASSISTIVE_TEXT_PLAY_BUTTON = P),
      (l.ASSISTIVE_TEXT_PAUSE_BUTTON = N),
      (l.LEARN_MORE = M),
      (l.NEXT = w),
      (l.FINISH = A),
      (l.GO_BACK = F),
      (l.COMMENTING_LIMITED = O),
      (l.GENERIC_ERROR_MESSAGE = B),
      (l.AD_BLOCKER_ERROR_MESSAGE = W),
      (l.MEDIA_CAROUSEL_ALT = q),
      (l.PLAY_BUTTON_ALT = U),
      (l.REEL_ICON_ALT = V),
      (l.PINNED_POST_ICON_ALT = H),
      (l.UPCOMING_EVENT_ICON_ALT = G),
      (l.CHECKMARK_OUTLINE_ICON_ALT = z),
      (l.CHECKMARK_FILLED_ICON_ALT = j),
      (l.DOWN_CHEVRON_ALT = K),
      (l.UP_CHEVRON_ALT = Q),
      (l.RIGHT_CHEVRON = X),
      (l.LEFT_CHEVRON = Y),
      (l.CALENDAR_ICON_ALT = J),
      (l.PLAY_ICON_ALT = Z),
      (l.DISMISS_TEXT = ee),
      (l.ALT_TEXT_CLOSE_ICON = te),
      (l.DIGITAL_COLLECTIBLE_TEXT = ne),
      (l.SAVE_TEXT = re),
      (l.SAVED_TEXT = oe),
      (l.VIEW_MORE_COMMENTS_TEXT = ae),
      (l.COMMENTS_TEXT = ie),
      (l.VIEW_ALL_REPLIES_TEXT = le),
      (l.HIDE_ALL_REPLIES_TEXT = se),
      (l.SHOW_MORE_REPLIES_TEXT = ue),
      (l.COMMENT_CREATION_FAILURE_TEXT = ce),
      (l.COMMENT_CREATION_RETRY_TEXT = de),
      (l.CLIPS_PLAYER_FAILURE_TEXT = me),
      (l.CLIPS_PLAYER_FAILURE_SUBTEXT = pe),
      (l.POST_COMMENT_TEXT = _e),
      (l.COMMENT_PLACEHOLDER_TEXT = fe),
      (l.CONTINUE_TO = ge),
      (l.EYE_ICON_ALT = he),
      (l.BACK_TO_INSTAGRAM_TEXT = ye),
      (l.SEE_MORE_ON_INSTAGRAM_TEXT = Ce),
      (l.ERROR_404_DESCRIPTION = be),
      (l.ERROR_404_DESCRIPTION_WITH_UPSELL = ve),
      (l.errorPageTitle = Se),
      (l.SWIPE_TO_EXPLORE_TEXT = Re),
      (l.EXPLORE_PHOTOS_AND_VIDEOS_TEXT = Le),
      (l.PHOTO_ICON_ALT = Ee),
      (l.WAIST_TITLE = ke),
      (l.ABOUT_INSTAGRAM_ADS_TEXT = Ie));
  },
  226,
);
