__d(
  "PowerEditorEventCategory",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      AD_ACCOUNT_SETTINGS: "ad_account_settings",
      ACTION_DISPATCHED: "action_dispatched",
      API_CALL: "api_call",
      AD_CREATE: "ad_create",
      ADGROUP_EDIT: "ad_edit",
      CAMPAIGN_CREATE: "campaign_create",
      CAMPAIGN_EDIT: "campaign_edit",
      CAMPAIGN_GROUP_CREATE: "campaigngroup_create",
      CAMPAIGN_GROUP_EDIT: "campaigngroup_edit",
      CAMPAIGN_GROUP_TAG: "campaigngroup_tag",
      CTM_FUNNEL_IMPRESSION: "ctm_funnel_impression",
      CTM_FUNNEL_CLICK: "ctm_funnel_click",
      CTM_FUNNEL_ERROR: "ctm_funnel_error",
      CLICK_CREATE_BUTTON: "click_create_button",
      CREATION: "creation",
      DOWNLOAD: "download",
      DELETE: "delete",
      NES: "nes",
      FILTER: "filter",
      IMPORT_ADS: "import_ads",
      IMPORT_AD_SETS: "import_ad_sets",
      IMPORT_CAMPAIGNS: "import_campaigns",
      IMPORT_LIFECYCLE: "import_lifecycle",
      IMPORT_POLLING: "import_polling",
      PERFORMANCE_SUMMARY: "performance_summary",
      PRIVACY_INFO_CENTER: "privacy_info_center",
      NAVIGATE: "navigate",
      OBJECTIVES: "objectives",
      PAGE_POST: "page_post",
      PARSE_IMPORT: "parse_import",
      PREREQUISITES: "prerequisites",
      PERFORMANCE: "performance",
      PUBLISH: "publish",
      UPLOAD: "upload",
      BULK: "bulk",
      REACH_FREQUENCY: "reach_frequency",
      REACH_FREQUENCY_SHEET: "reach_frequency_sheet",
      START_YOUR_DAY: "start_your_day",
      USER_ACTION: "user_action",
      HELP_TRAY: "help_tray",
      RUN_STATUS: "run_status",
      CLIENT_EVENT: "client_event",
      ERROR: "errors",
      INSTAGRAM_PLACEMENT_ADOPTION: "instagram_placement_adoption",
      INSTREAM_VIDEOS_PLACEMENT_ADOPTION: "instream_videos_placement_adoption",
      PERFORMANCE_PREVIEW_CS: "performance_preview_cs",
      PERFORMANCE_CLIENT_SIDE_MINI_PREVIEW:
        "performance_client_side_mini_preview",
      PLANNER: "planner",
      PRELOADING: "preloading",
    });
    i.default = e;
  },
  66,
);
