__d(
  "BusinessAssetTypesLowercasePlural$FbtEnum",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
      "ad-account": "ad accounts",
      "ad-study": "lift studies",
      app: "apps",
      "block-list": "publisher block lists",
      brand: "businesses",
      "business-payout-account": "Payout accounts",
      "business-unit": "lines of business",
      "custom-conversion": "custom conversions",
      "event-source-group": "event source groups",
      "example-cat": "cats (do not translate)",
      "owned-domain": "domains",
      "news-page": "news Pages",
      "instagram-account-v2": "Instagram accounts",
      "leads-access": "leads access",
      "legal-entity": "legal entities",
      "monetization-property": "properties",
      "offline-event-set": "offline event sets",
      "events-dataset": "datasets",
      "business-locations-wrapper": "Page Structures",
      page: "Pages",
      "profile-plus": "profiles",
      "payout-method": "payment accounts",
      pixel: "pixels",
      "product-catalog": "catalogs",
      "registered-trademark": "registered trademarks",
      "shared-audience": "shared audiences",
      "sliced-event-source-group": "sliced event source groups",
      "threads-account": "Threads accounts",
      user: "users",
      "whatsapp-account": "WhatsApp accounts",
      "whatsapp-business-account": "WhatsApp accounts",
      "whatsapp-business-presence": "WhatsApp accounts",
      "business-resource-group": "business asset groups",
      "business-creative-folder": "business creative folders",
      "ads-event-source": "ads event sources",
      "seller-profile": "commerce accounts",
      "advanced-analytics-instance": "instances",
      "events-dataset-and-pixel": "datasets and pixels",
      "events-dataset-new": "datasets",
      "offsite-email-account": "email accounts",
      "creator-marketplace-brand-profile": "creator marketplace accounts",
      "mv4b-billable-account": "meta verified accounts",
      "marketplace-partner-billable-account": "marketplace partner accounts",
      "biz-ai-billable-account": "business AI accounts",
      "meta-business-agent-billable-account": "meta business agent accounts",
      "meta-one-billable-account": "meta one accounts",
    };
    a.exports = e;
  },
  null,
);
