__d(
  "BusinessAssetTypesUppercase$FbtEnum",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        "ad-account": "Ad Account",
        "ad-study": "Lift Study",
        app: "App",
        "block-list": "Publisher Block List",
        "white-list": "Publisher Allow List",
        brand: "Business",
        "business-payout-account": "Payout Account",
        "business-unit": "Line of Business",
        "custom-conversion": "Custom Conversion",
        "event-source-group": "Event Source Group",
        "example-cat": "Cat (do not translate)",
        "owned-domain": "Domain",
        "news-page": "News Page",
        "instagram-account-v2": "Instagram Account",
        "leads-access": "Leads Access",
        "monetization-property": "Property",
        "offline-event-set": "Offline Event Set",
        "events-dataset": "Dataset",
        "business-locations-wrapper": "Page Structure",
        page: "Page",
        "profile-plus": "Profile",
        "payout-method": "Payment Account",
        pixel: "Pixel",
        "product-catalog": "Catalog",
        "registered-trademark": "Registered Trademark",
        "shared-audience": "Shared Audience",
        "sliced-event-source-group": "Sliced Event Source Group",
        "threads-account": "Threads Account",
        user: "Person",
        "whatsapp-account": "WhatsApp Account",
        "whatsapp-business-account": "WhatsApp Account",
        "whatsapp-business-presence": "WhatsApp Business Presence",
        "business-resource-group": "Business Asset Group",
        "business-creative-folder": "Business Creative Folder",
        "dynamic-content-set": "Content Allow List",
        "ads-event-source": "Ads Event Source",
        "seller-profile": "Commerce Account",
        "legal-entity": "Legal Entity",
        "advanced-analytics-instance": "Instance",
        "events-dataset-new": "Dataset",
        "events-dataset-and-pixel": "Dataset and Pixel",
        "offsite-email-account": "Email Account",
        "creator-marketplace-brand-profile": "Creator Marketplace Account",
        "mv4b-billable-account": "Meta Verified Account",
        "marketplace-partner-billable-account": "Marketplace Partner Account",
        "biz-ai-billable-account": "Business AI Account",
        "meta-business-agent-billable-account": "Meta Business Agent Account",
        "meta-one-billable-account": "Meta One Account",
      },
      l = e;
    i.default = l;
  },
  66,
);
