__d(
  "AdsLocationMetaConstant",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = ["radiuses", "audience", "hasMax"],
      l = ["radiuses", "audience", "max"],
      s = ["radiuses", "audience", "value"],
      u = ["radiuses", "audience", "isDefault"],
      c = ["radiuses", "distance", "value"],
      d = ["radiuses", "distance", "isDefault"],
      m = ["distanceUnit"],
      p = ["radiuses", "per_location_radius"],
      _ = ["name"],
      f = ["selectedRadiusType"],
      g = ["showIneligibleLocations"],
      h = "audience",
      y = "distance",
      C = "marketing_area",
      b = "per_location",
      v = "unknown",
      S = "audience",
      R = "extra_data",
      L = "fixed_radius",
      E = "custom";
    ((i.AUDIENCE_HASMAX_PATH = e),
      (i.AUDIENCE_MAX_PATH = l),
      (i.AUDIENCE_VALUE_PATH = s),
      (i.AUDIENCE_IS_DEFAULT_PATH = u),
      (i.DISTANCE_VALUE_PATH = c),
      (i.DISTANCE_IS_DEFAULT_PATH = d),
      (i.DISTANCE_UNIT_PATH = m),
      (i.CUSTOM_PER_LOCATION_PATH = p),
      (i.NAME_PATH = _),
      (i.SELECTED_RADIUS_TYPE_PATH = f),
      (i.SHOW_INELIGIBLE_LOCATIONS_PATH = g),
      (i.AUDIENCE = h),
      (i.DISTANCE = y),
      (i.MARKETING_AREA = C),
      (i.PER_LOCATION = b),
      (i.UNKNOWN = v),
      (i.SUBFIELD_AUDIENCE = S),
      (i.SUBFIELD_EXTRA_DATA = R),
      (i.SUBFIELD_FIXED_RADIUS = L),
      (i.SUBFIELD_CUSTOM = E));
  },
  66,
);
