__d(
  "fbWebMinificationMap",
  ["WebBloksModel"],
  function (t, n, r, o, a, i, l) {
    var e = o("WebBloksModel").defineWebBloksMinificationMap({
        㐾: {
          logicalStyleId: "ig.components.BottomSheet",
          attrs: {
            adjust_screen_resizing_from_keyboard: ",",
            allow_panning_in_partial_state: "5",
            analytics_module: "#",
            content: "$",
            disable_animation_on_push: "3",
            disable_back_swipe: "1",
            disable_dismiss_on_tap_outside: ">",
            disable_dragging: "?",
            disable_popping_all_modals: "=",
            disable_vertical_panning: ";",
            extensions: "\x85",
            hide_back_button: "A",
            id: "!",
            is_full_screen_enabled: "&",
            on_back_press: ".",
            on_dismiss: "(",
            on_position_changed: "4",
            on_update_to_partially_opened_state: "-",
            partial_height_percentage: ")",
            perf_logging_id: "*",
            prevent_panning_in_partial_state: "6",
            renders_in_unsafe_area: "0",
            should_maintain_height_on_push: "2",
            title: "+",
            trailing_button_accessibility_label: "7",
            trailing_button_icon: "8",
            trailing_button_on_click: "9",
            trailing_button_text: ":",
          },
        },
        㑋: {
          logicalStyleId: "ig.components.Search",
          attrs: {
            analytics_module: "#",
            extensions: "\x85",
            id: "!",
            null_state_models: "$",
            on_keyword_change: "&",
            placeholder_text: "(",
            show_loading_indicator_for_server_fetches: ")",
          },
        },
        㑍: {
          logicalStyleId: "ig.components.Spinner",
          attrs: { extensions: "\x85", id: "!", state: "#", tint_color: "$" },
        },
        㑒: {
          logicalStyleId: "ig.components.ViewpointExtension",
          attrs: {
            follow_app_level_rule: "+",
            force_autorotate: ",",
            force_landscape_left: "-",
            force_landscape_right: ".",
            force_portrait: "0",
            id: "!",
            key: "#",
            level: ")",
            on_appear: "$",
            on_disappear: "&",
            on_update: "(",
            trigger_on_first_appear_only: "*",
          },
        },
        㑪: {
          logicalStyleId: "ig.data.SearchResultItem",
          attrs: {
            content: "#",
            follow_app_level_rule: "(",
            force_autorotate: ")",
            force_landscape_left: "*",
            force_landscape_right: "+",
            force_portrait: ",",
            id: "!",
            key: "$",
            search_keyword: "&",
          },
        },
        㑭: {
          logicalStyleId: "ig.style.SearchStyle",
          attrs: {
            follow_app_level_rule: "&",
            force_autorotate: "(",
            force_landscape_left: ")",
            force_landscape_right: "*",
            force_portrait: "+",
            id: "!",
            key: "#",
            search_keyword: "$",
          },
        },
        㓟: {
          logicalStyleId: "bk.components.BottomSheet",
          attrs: {
            accessibility_label: "(",
            adjust_screen_resizing_from_keyboard: "7",
            android_navigation_bar_color: ";",
            automatically_adjusts_content_for_keyboard_presentation: "8",
            background_color: "\x8C",
            background_color_hex: "P",
            button_style: ")",
            configuration: "?",
            content: "#",
            disable_animation_on_push: "=",
            disable_back_swipe: ">",
            disable_dismiss_on_tap_outside: "G",
            disable_dragging: "H",
            disable_popping_all_modals: "C",
            disable_vertical_panning: "B",
            extensions: "\x85",
            favor_inner_pan_gesture: "J",
            favour_inner_pan_gesture: "I",
            hide_back_button: "L",
            hide_divider: "N",
            hide_navbar: "M",
            id: "!",
            is_full_screen_enabled: "4",
            leading_button_accessibility_label: "D",
            leading_button_icon: "E",
            leading_button_on_click: "F",
            on_back_press: "K",
            on_click: "*",
            on_dismiss: "&",
            on_position_changed: "2",
            partial_height_percentage: "5",
            prevent_panning_in_partial_state: "3",
            props: "A",
            pull_handle_style: ":",
            renders_in_unsafe_area: "1",
            should_maintain_height_on_push: "6",
            status_bar_hidden: "O",
            text: "+",
            title: "$",
            trailing_button_accessibility_label: ",",
            trailing_button_icon: "9",
            trailing_button_on_click: "-",
            trailing_button_style: ".",
            trailing_button_text: "0",
          },
        },
        㗛: {
          logicalStyleId: "bk.fb.components.alert.Alert",
          attrs: {
            destructive_button: ")",
            extensions: "\x85",
            id: "!",
            message: "#",
            negative_button: "$",
            primary_button: "&",
            title: "(",
          },
        },
        㗜: {
          logicalStyleId: "bk.fb.components.alert.Button",
          attrs: { extensions: "\x85", id: "!", on_click: "#", text: "$" },
        },
        㘨: {
          logicalStyleId: "bk.data.contrib.screen.navbar.Fb",
          attrs: {
            custom_title: "$",
            custom_title_parseresult: "-",
            follow_app_level_rule: "4",
            force_autorotate: "5",
            force_landscape_left: "6",
            force_landscape_right: "7",
            force_portrait: "8",
            hide_leading_button: "&",
            hide_navbar_shadow: "#",
            id: "!",
            ios_status_bar_style: "3",
            is_left_align: ",",
            leading_button_custom_override: "(",
            on_back_press: "0",
            scroll_mode: "1",
            scroll_mode_if_pushed: "2",
            tint_color: ".",
            title_alignment: "+",
            trailing_button_override: "*",
            trailing_buttons: ")",
          },
        },
        㙋: {
          logicalStyleId: "bk.data.fb.screen.navbar.TrailingButton",
          attrs: {
            accessibility_identifier: "4",
            accessibility_label: ")",
            badge_config: "+",
            badge_count: ",",
            button_style: "5",
            color_icon: "7",
            disabled: "*",
            enabled: "#",
            follow_app_level_rule: ".",
            force_autorotate: "0",
            force_landscape_left: "1",
            force_landscape_right: "2",
            force_portrait: "3",
            icon: "$",
            icon_variant: "6",
            id: "!",
            on_click: "&",
            testing_id: "8",
            title: "(",
            title_color: "-",
          },
        },
        㚕: {
          logicalStyleId: "bk.data.fb.media.UploadMediaConfig",
          attrs: {
            copy_source_to_durable_sandbox: "6",
            follow_app_level_rule: ",",
            force_autorotate: "-",
            force_landscape_left: ".",
            force_landscape_right: "0",
            force_portrait: "1",
            id: "!",
            media_uri: "#",
            on_cancellation: "$",
            on_failure: "&",
            on_progress_updated: "(",
            on_success: ")",
            upload_as_png: "+",
            upload_asset_type: "2",
            upload_namespace: "*",
            video_container_type: "4",
            video_max_length: "5",
            video_upload_on_success: "3",
          },
        },
        㵴: {
          logicalStyleId: "bk.components.fb.fds.CheckBox",
          attrs: {
            body: "(",
            checked: "#",
            enabled: "$",
            extensions: "\x85",
            id: "!",
            on_click: "&",
            title: ")",
          },
        },
        㶚: {
          logicalStyleId: "bk.components.showreel.DynamicTextV2",
          attrs: {
            animation_progress: "2",
            animation_token_type: "3",
            background_color: "\x8C",
            background_corner_radius_multiplier: "6",
            bottom: "8",
            children: " ",
            container_background_color: "?",
            extensions: "\x85",
            fallback_text_size: "#",
            font_family: "0",
            font_weight: "1",
            horizontal_padding_ratio: "9",
            id: "!",
            invalidate_on_truncation: "5",
            max_number_of_lines: ",",
            max_text_size: "$",
            min_text_size: "&",
            on_token: "4",
            rich_text: "(",
            shadow_color: ">",
            side: ":",
            text_align: "+",
            text_size_granularity: ")",
            top: ";",
            truncated_text_size: "*",
            truncation_spans: "-",
            vertical_line_alignment: "7",
            vertical_padding_ratio: "=",
            wrap_vertically: ".",
          },
        },
        㹣: {
          logicalStyleId: "bk.data.consent.container.DialogOptions",
          attrs: {
            background_color: "\x8C",
            consent_prompt: "6",
            corner_radius: "#",
            follow_app_level_rule: ",",
            force_autorotate: "-",
            force_landscape_left: ".",
            force_landscape_right: "0",
            force_minimum_height_to_scale_to_content: "3",
            force_portrait: "1",
            handle_outside_tap_dismiss_action: "$",
            id: "!",
            "ignore-safe-area-inset-bottom": "4",
            "ignore-safe-area-inset-top": "5",
            is_enabled: "2",
            left_right_border_width: "&",
            "max-height": "(",
            "min-height": ")",
            theme: "*",
            theme_name: "+",
          },
        },
        䀝: {
          logicalStyleId: "bk.data.consent.container.ScreenOptions",
          attrs: {
            background_color: "\x8C",
            consent_prompt: "6",
            follow_app_level_rule: ")",
            force_autorotate: "*",
            force_landscape_left: "+",
            force_landscape_right: ",",
            force_portrait: "-",
            id: "!",
            "ignore-safe-area-inset-bottom": "2",
            "ignore-safe-area-inset-top": "3",
            insert_bottom_padding: "5",
            insert_ota_progress_bar_bottom_padding: "4",
            on_device_back_pressed_action: "#",
            should_use_shared_screem_container: ".",
            should_use_shared_screen_container: "0",
            theme: "&",
            theme_name: "(",
            transition_style: "1",
            type: "$",
          },
        },
        䀢: {
          logicalStyleId: "bk.data.consent.container.CloseScreenOptions",
          attrs: {
            follow_app_level_rule: "#",
            force_autorotate: "$",
            force_landscape_left: "&",
            force_landscape_right: "(",
            force_portrait: ")",
            id: "!",
          },
        },
        䄉: {
          logicalStyleId: "bk.data.screen.navbar.Fb",
          attrs: {
            back_button_hidden: "#",
            contribs: ":",
            fb_nav_override_id: "1",
            follow_app_level_rule: "4",
            force_autorotate: "5",
            force_landscape_left: "6",
            force_landscape_right: "7",
            force_portrait: "8",
            hidden: "$",
            id: "!",
            leading_button: "&",
            navbar_style: "(",
            primary_color: "9",
            scroll_mode: ")",
            scroll_mode_if_pushed: "*",
            shadow_hidden: "+",
            status_bar_style: "3",
            tint_color: ",",
            title: "-",
            title_component: ".",
            title_component_alignment: "2",
            trailing_buttons: "0",
          },
        },
        䄊: {
          logicalStyleId: "bk.data.screen.navbar.fb.LeadingButton",
          attrs: {
            accessibility_label: "#",
            follow_app_level_rule: "(",
            force_autorotate: ")",
            force_landscape_left: "*",
            force_landscape_right: "+",
            force_portrait: ",",
            icon: "$",
            id: "!",
            on_click: "&",
            testing_id: "-",
          },
        },
        䄍: {
          logicalStyleId: "bk.data.screen.navbar.fb.TrailingButton",
          attrs: {
            accessibility_label: "#",
            badge_count: "*",
            button_style: "1",
            disabled: "$",
            follow_app_level_rule: "+",
            force_autorotate: ",",
            force_landscape_left: "-",
            force_landscape_right: ".",
            force_portrait: "0",
            icon: "&",
            icon_variant: "2",
            id: "!",
            on_click: "(",
            testing_id: "3",
            title: ")",
          },
        },
        䄲: {
          logicalStyleId: "bk.data.screen.containerconfig.fullscreen.Fb",
          attrs: {
            analytics_destination_url: "$",
            android_edge_to_edge_config: "7",
            background_alpha: "9",
            disable_back_swipe: "5",
            disable_navbar_setup: "&",
            enable_transparent_background: "6",
            follow_app_level_rule: "-",
            force_autorotate: ".",
            force_landscape_left: "0",
            force_landscape_right: "1",
            force_portrait: "2",
            force_portrait_mode: "(",
            hide_tab_bar: ")",
            id: "!",
            keyboard_soft_input_mode: "*",
            navbar: "#",
            on_back_press: "4",
            renders_in_unsafe_area: "+",
            respect_safe_area_insets: ",",
            safe_area_padding: "3",
            status_bar_hidden: "8",
            wrapper_contribs: ":",
          },
        },
        䅡: {
          logicalStyleId: "bk.data.screen.containerconfig.bottomsheet.Fb",
          attrs: {
            android_edge_to_edge_config: "C",
            background: "#",
            background_color: "\x8C",
            background_dim_none: "M",
            collapsed_height: "$",
            disable_dismiss_on_tap_outside: "7",
            disable_dragging: "9",
            disable_expansion_if_content_fits_in_partial_height: "H",
            disable_expansion_when_content_fits_in_partial_height: "I",
            dismiss_on_swipe: "&",
            dismiss_on_touch_outside: "(",
            draggable: ")",
            expanded_height: "*",
            expanded_height_percentage: "E",
            favor_inner_pan_gesture: ";",
            favour_inner_pan_gesture: ":",
            fds_override_id: ">",
            follow_app_level_rule: "1",
            footer_component: "F",
            footer_component_string: "G",
            force_autorotate: "2",
            force_dark_mode: "8",
            force_landscape_left: "3",
            force_landscape_right: "4",
            force_portrait: "5",
            hide_top_handle: "?",
            id: "!",
            initial_loading_screen_height_percentage: "A",
            initial_state: "+",
            is_locked: "L",
            limit_sliding_by_anchors: "J",
            navbar: ".",
            on_back_press: "B",
            on_dismiss_start: "N",
            on_drag: ",",
            on_state_changed: "-",
            partial_height_percentage: "6",
            prevent_panning_in_partial_state: "0",
            skip_enter_animation: "K",
            soft_input_mode: "=",
            status_bar_hidden: "D",
          },
        },
        䅻: {
          logicalStyleId: "bk.data.screen.navbar.bottomsheet.Fb",
          attrs: {
            follow_app_level_rule: "+",
            force_autorotate: ",",
            force_landscape_left: "-",
            force_landscape_right: ".",
            force_portrait: "0",
            hide_back_button: "2",
            hide_header_divider: "1",
            hide_navbar: "3",
            id: "!",
            title: "#",
            trailing_button: "*",
            trailing_button_accessibility_label: "$",
            trailing_button_on_click: "&",
            trailing_button_style: "(",
            trailing_button_text: ")",
          },
        },
        䅼: {
          logicalStyleId: "bk.data.screen.navbar.bottomsheet.fb.TrailingButton",
          attrs: {
            accessibility_label: "#",
            badge_count: "0",
            button_style: "1",
            disabled: "2",
            follow_app_level_rule: ")",
            force_autorotate: "*",
            force_landscape_left: "+",
            force_landscape_right: ",",
            force_portrait: "-",
            hidden: ".",
            icon: "3",
            icon_variant: "5",
            id: "!",
            on_click: "$",
            testing_id: "6",
            text: "&",
            title: "4",
            type: "(",
          },
        },
        䋃: {
          logicalStyleId: "bk.components.PullToRefreshContainerFallback",
          attrs: { extensions: "\x85", id: "!", on_click: "#" },
        },
        䍒: {
          logicalStyleId: "bk.data.xs.SendTextMessageCTAOptions",
          attrs: { id: "!" },
        },
        帍: {
          logicalStyleId: "bk.components.cats.ReCaptchaWebView",
          attrs: {
            callback: "#",
            extensions: "\x85",
            id: "!",
            on_page_finished: "&",
            url: "$",
          },
        },
        幔: {
          logicalStyleId: "bk.data.wearables.FeatureToggles",
          attrs: {
            glanceables_include_padding: "#",
            id: "!",
            v124: "$",
            v125: "&",
            v128: "(",
            v129: ")",
          },
        },
        弲: {
          logicalStyleId: "bk.components.survey.RtfTextQuestion",
          attrs: { extensions: "\x85", html: "#", id: "!" },
        },
        愰: {
          logicalStyleId: "bk.components.cats.ReCaptchaWebViewV2",
          attrs: {
            callback: "#",
            captcha_client_config_name: "$",
            extensions: "\x85",
            id: "!",
            url: "&",
          },
        },
        拼: {
          logicalStyleId: "bk.components.cats.ArkoseWebView",
          attrs: {
            callback: "#",
            captcha_client_config_name: "$",
            extensions: "\x85",
            id: "!",
            url: "&",
          },
        },
      }),
      s = e;
    l.default = s;
  },
  98,
);
