__d(
  "AdsReportBuilderDimensionType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      OPTIMIZED_CUSTOM_EVENT_NAME: "optimized_custom_event_name",
      APP_OPTIMIZED_CUSTOM_EVENT_NAME: "app_optimized_custom_event_name",
      DELIVERY_AGE: "age",
      DELIVERY_COUNTRY: "country",
      DELIVERY_GENDER: "gender",
      DELIVERY_REGION_PREDICTION: "region",
      DELIVERY_REGION_PREDICTION_ID: "region_id",
      DELIVERY_DMA: "dma",
      DELIVERY_DMA_CODE: "dma_code",
      DELIVERY_COMSCORE_MARKET_CODE: "comscore_market_code",
      DELIVERY_COMSCORE_MARKET: "comscore_market",
      DELIVERY_IMPRESSION_DEVICE: "impression_device",
      DELIVERY_IS_VIDEO: "is_video",
      DELIVERY_PUBLISHER_PLATFORM: "publisher_platform",
      DELIVERY_DEVICE_PLATFORM: "device_platform",
      DELIVERY_PLATFORM_POSITION: "platform_position",
      DELIVERY_ACTIVITY_RECENCY: "activity_recency",
      DELIVERY_PLACE_PAGE_ID: "place_page_id",
      DELIVERY_PLACE_PAGE_NAME: "place_page_name",
      DELIVERY_PRODUCT_ID: "product_id",
      DELIVERY_MSA_SELLER_ID: "msa_seller_id",
      DELIVERY_MSA_SELLER_NAME: "msa_seller_name",
      DELIVERY_FREQUENCY_VALUE: "frequency_value",
      DELIVERY_OVERLAP_SEGMENT: "overlap_segment",
      DELIVERY_PLACEMENT_PATH: "placement_path",
      DELIVERY_HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE:
        "hourly_stats_aggregated_by_advertiser_time_zone",
      DELIVERY_HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE:
        "hourly_stats_aggregated_by_audience_time_zone",
      DELIVERY_IMAGE: "image_asset",
      DELIVERY_IMAGE_VALUE: "image_asset_value",
      DELIVERY_VIDEO: "video_asset",
      DELIVERY_VIDEO_VALUE: "video_asset_value",
      DELIVERY_LINK_URL: "link_url_asset",
      DELIVERY_LINK_URL_VALUE: "link_url_asset_value",
      DELIVERY_MEDIA: "media_asset",
      DELIVERY_BODY: "body_asset",
      DELIVERY_BODY_VALUE: "body_asset_value",
      DELIVERY_TITLE: "title_asset",
      DELIVERY_TITLE_VALUE: "title_asset_value",
      DELIVERY_DESCRIPTION: "description_asset",
      DELIVERY_DESCRIPTION_VALUE: "description_asset_value",
      DELIVERY_CALL_TO_ACTION: "call_to_action_asset",
      DELIVERY_CALL_TO_ACTION_VALUE: "call_to_action_asset_value",
      DELIVERY_RULE: "rule_asset",
      DELIVERY_RULE_VALUE: "rule_asset_value",
      REELS_TRENDING_TOPIC: "reels_trending_topic",
      SKAN_CONVERSION_ID: "skan_conversion_id",
      APP_ID: "app_id",
      IS_CONVERSION_ID_MODELED: "is_conversion_id_modeled",
      HSID: "hsid",
      FIDELITY_TYPE: "fidelity_type",
      COARSE_CONVERSION_VALUE: "coarse_conversion_value",
      REDOWNLOAD: "redownload",
      POSTBACK_SEQUENCE_INDEX: "postback_sequence_index",
      SKAN_CAMPAIGN_ID: "skan_campaign_id",
      SKAN_VERSION: "skan_version",
      DELIVERY_USER_SEGMENT: "user_segment_key",
      MEDIA_FORMAT: "media_format",
      MEDIA_ORIGIN_URL: "media_origin_url",
      MEDIA_ASSET_URL: "media_asset_url",
      MEDIA_TEXT_CONTENT: "media_text_content",
      MEDIA_CREATOR: "media_creator",
      PA_CREATOR_IG_HANDLE: "pa_creator_ig_handle",
      MEDIA_DESTINATION_URL: "media_destination_url",
      MDSA_LANDING_DESTINATION: "mdsa_landing_destination",
      LANDING_DESTINATION: "landing_destination",
      MEDIA_TYPE: "media_type",
      CONVERSION_DESTINATION: "conversion_destination",
      USER_PERSONA_ID: "user_persona_id",
      USER_PERSONA_NAME: "user_persona_name",
      INSTAGRAM_ADS_FOLLOW_TYPE: "instagram_ads_follow_type",
      INSTAGRAM_ADS_INSTAGRAM_MEDIA_PRODUCT_TYPE:
        "instagram_ads_instagram_media_product_type",
      INSTAGRAM_ADS_TIME_SINCE_CREATION_BUCKET:
        "instagram_ads_time_since_creation_bucket",
      IS_RENDERED_AS_DELAYED_SKIP_AD: "is_rendered_as_delayed_skip_ad",
      IS_AUTO_ADVANCE: "is_auto_advance",
      CREATIVE_RELAXATION_ASSET_TYPE: "creative_relaxation_asset_type",
      FLEXIBLE_FORMAT_ASSET_TYPE: "flexible_format_asset_type",
      GEN_AI_ASSET_TYPE: "gen_ai_asset_type",
      AD_EXTENSION_URL: "ad_extension_url",
      AD_EXTENSION_DOMAIN: "ad_extension_domain",
      CREATIVE_AUTOMATION_ASSET_ID: "creative_automation_asset_id",
      RTA_UGC_TOPIC: "rta_ugc_topic",
      ACTION_DEVICE: "action_device",
      ACTION_REACTION: "action_reaction",
      ACTION_DESTINATION: "action_destination",
      ACTION_EVENT_CHANNEL: "action_event_channel",
      ACTION_LINK_CLICK_DESTINATION: "action_link_click_destination",
      ACTION_VIDEO_TYPE: "action_video_type",
      ACTION_VIDEO_SOUND: "action_video_sound",
      ACTION_CAROUSEL_CARD_ID: "action_carousel_card_id",
      ACTION_CAROUSEL_CARD_NAME: "action_carousel_card_name",
      ACTION_CANVAS_COMPONENT_ID: "action_canvas_component_id",
      ACTION_CANVAS_COMPONENT_NAME: "action_canvas_component_name",
      ACTION_CATEGORY: "action_category",
      ACTION_BRAND: "action_brand",
      ACTION_TARGET_ID: "action_target_id",
      ACTION_CATEGORY_NAME: "action_category_name",
      ACTION_BRAND_NAME: "action_brand_name",
      STANDARD_EVENT_CONTENT_TYPE: "standard_event_content_type",
      SIGNAL_SOURCE_BUCKET: "signal_source_bucket",
      IS_BUSINESS_AI_ASSISTED: "is_business_ai_assisted",
      PROMOTED_PRODUCT_SET_RESULT: "promoted_product_set_result",
      META_DELIVERY_AD_ID: "delivery_ad_id",
      META_AD_ID: "ad_id",
      META_AD_NAME: "ad_name",
      META_ADSET_ID: "adset_id",
      META_ADSET_NAME: "adset_name",
      META_CAMPAIGN_ID: "campaign_id",
      META_CAMPAIGN_NAME: "campaign_name",
      META_ACCOUNT_ID: "account_id",
      META_ACCOUNT_NAME: "account_name",
      META_OBJECTIVE: "objective",
      META_RESULT_TYPE: "performance_indicator",
      META_CUSTOM_BREAKDOWN: "custom_breakdown",
      META_PAGE_ID: "page_id",
      META_PAGE_NAME: "page_name",
      META_CREATIVE_ASSET: "creative_asset",
      META_CREATIVE_HEADLINE: "creative_headline",
      META_CREATIVE_BODY: "creative_body",
      META_CREATIVE_DESCRIPTION: "creative_description",
      META_CREATIVE_WEBSITE_URL: "creative_website_url",
      CREATIVE_DIMENSION: "creative_fingerprint",
      META_CREATIVE_MEDIA_TYPE: "creative_media_type",
      META_ADSET_BID_TYPE: "adset_bid_type",
      META_ADSET_BID_VALUE: "adset_bid_value",
      META_BUDGET_TYPE: "budget_type",
      META_BUDGET_VALUE: "budget_value",
      META_ADSET_BUDGET_TYPE: "adset_budget_type",
      META_ADSET_BUDGET_VALUE: "adset_budget_value",
      META_CAMPAIGN_BUDGET_TYPE: "campaign_budget_type",
      META_CAMPAIGN_BUDGET_VALUE: "campaign_budget_value",
      META_BUYING_TYPE: "buying_type",
      META_DELIVERY_INFO: "delivery_info",
      META_DELIVERY_START_TYPE: "delivery_start",
      META_DELIVERY_END_TYPE: "delivery_end",
      META_AD_DELIVERY: "ad_delivery",
      META_ADSET_DELIVERY: "adset_delivery",
      META_CAMPAIGN_DELIVERY: "campaign_delivery",
      META_CALL_TO_ACTION: "call_to_action_type",
      PRODUCT_GROUP_CONTENT_ID_BREAKDOWN: "product_group_content_id_breakdown",
      PRODUCT_GROUP_ID: "product_group_id",
      PRODUCT_BRAND_BREAKDOWN: "product_brand_breakdown",
      PRODUCT_CATEGORY_BREAKDOWN: "product_category_breakdown",
      PRODUCT_CUSTOM_LABEL_0_BREAKDOWN: "product_custom_label_0_breakdown",
      PRODUCT_CUSTOM_LABEL_1_BREAKDOWN: "product_custom_label_1_breakdown",
      PRODUCT_CUSTOM_LABEL_2_BREAKDOWN: "product_custom_label_2_breakdown",
      PRODUCT_CUSTOM_LABEL_3_BREAKDOWN: "product_custom_label_3_breakdown",
      PRODUCT_CUSTOM_LABEL_4_BREAKDOWN: "product_custom_label_4_breakdown",
      PRODUCT_SET_ID_BREAKDOWN: "product_set_id_breakdown",
      PRODUCT_VENDOR_ID_BREAKDOWN: "product_vendor_id_breakdown",
      TIME_DAYS_1: "days_1",
      TIME_DAYS_7: "days_7",
      TIME_DAYS_14: "days_14",
      TIME_MONTHLY: "monthly",
      TIME_ALL_DAYS: "all_days",
      TIME_HOURS_1: "hour_utc",
      MARKETING_MESSAGES_BTN_NAME: "marketing_messages_btn_name",
      BREAKDOWN_AD_OBJECTIVE: "breakdown_ad_objective",
      CRM_ULT_ADVERTISER_ID: "crm_ult_advertiser_id",
      CRM_ADVERTISER_VERTICAL_ID: "crm_advertiser_vertical_id",
      CRM_ADVERTISER_SUBVERTICAL_ID: "crm_advertiser_subvertical_id",
      CRM_ADVERTISER_L12_TERRITORY_IDS: "crm_advertiser_l12_territory_ids",
      CRM_SALES_MANAGER_IDS: "crm_sales_manager_ids",
      IMPRESSION_VIEW_TIME_USER_HOUR: "impression_view_time_user_hour",
      IMPRESSION_VIEW_TIME_ADVERTISER_HOUR:
        "impression_view_time_advertiser_hour",
    });
    i.default = e;
  },
  66,
);
