__d(
  "AdsCreativeVideoGenTypes",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e,
      l = (e = n("$InternalEnum")).Mirrored([
        "CONCEPT_EDITOR",
        "VIDEO_EDITOR",
        "PRE_GEN",
        "PROGRESSIVE_SCRIPTING",
        "LOADING",
        "POST_GEN",
        "ERROR",
        "VIDEO_GEN_ERROR",
      ]),
      s = e.Mirrored(["EDIT_IMAGE_SELECTION", "EDIT_INDIVIDUAL_VIDEO"]),
      u = e.Mirrored(["EDIT", "UNDO"]),
      c = e.Mirrored(["LOADING", "SUCCESS", "ERROR"]),
      d = e.Mirrored(["FROM_SPEC", "FROM_API"]),
      m = e({
        EXISTING_FULL_VIDEO: "existing_full_video",
        EXISTING_PARTIAL_PREVIEW: "existing_partial_preview",
        FULL_VIDEO: "full_video",
        PARTIAL_PREVIEW: "partial_preview",
      }),
      p = e({
        NOT_APPLICABLE: "not_applicable",
        UNRESOLVED: "unresolved",
        FRESH_SERVE: "fresh_serve",
        PRE_EXISTING: "pre_existing",
        MISS: "miss",
        ERROR: "error",
        HIT_UNSPECIFIED: "hit_unspecified",
      }),
      _ = {
        clipsData: [],
        isApplyingEdits: !1,
        isMusicOptedIn: !1,
        isVoiceoverOptedIn: !1,
        lastAppliedClipsData: [],
        lastAppliedMusicAudioAssetId: "",
        lastAppliedMusicOptInState: !1,
        lastAppliedVoiceoverOptInState: !1,
        lastAppliedVoiceType: "",
        selectedMusicAudioAssetId: "",
        selectedVoiceType: "",
        hasFetchedBackendDataForFirstTime: !1,
        editPipelineRunType: u.EDIT,
      },
      f = e({
        REFINE_AI_INPUTS: "refine_ai_inputs",
        EXAMPLE_VIDEOS: "example_videos",
        NONE: "none",
      });
    ((i.VideoGenModalStep = l),
      (i.VideoGenNestedPanel = s),
      (i.EditPipelinRunType = u),
      (i.VideoGenToastType = c),
      (i.VideoStatusIDSource = d),
      (i.CacheHitStage = m),
      (i.PregenCacheOutcome = p),
      (i.videoEditableDataDefault = _),
      (i.ProgressiveScriptingRightContainerMode = f));
  },
  66,
);
