__d(
  "AdsCreativeVideoGenRecipeLabels",
  ["fbt"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e = s._(/*BTDS*/ "Studio showcase"),
      u = s._(/*BTDS*/ "Lifestyle showcase"),
      c = s._(/*BTDS*/ "UGC try-on"),
      d = s._(/*BTDS*/ "Slideshow"),
      m = s._(/*BTDS*/ "Background swaps"),
      p = s._(/*BTDS*/ "Website image showcase"),
      _ = s._(/*BTDS*/ "Immersive animation"),
      f = s._(/*BTDS*/ "UGC problem-solution"),
      g = s._(/*BTDS*/ "UGC problem-solution"),
      h = s._(/*BTDS*/ "UGC highlight"),
      y = s._(/*BTDS*/ "Multi-shot showcase"),
      C = s._(/*BTDS*/ "Hero shot"),
      b = s._(/*BTDS*/ "Dynamic motion"),
      v = s._(/*BTDS*/ "Highlight hook"),
      S = s._(/*BTDS*/ "Overlay hook"),
      R = s._(/*BTDS*/ "Trending hook"),
      L = s._(/*BTDS*/ "UGC Try-on"),
      E = s._(/*BTDS*/ "Simple animation"),
      k = s._(/*BTDS*/ "UGC PAS video"),
      I = s._(/*BTDS*/ "Multi-shot animation"),
      T = s._(
        /*BTDS*/ "Turns your image into a subtle motion video closing with your logo or CTA. Best when you have one strong image and want an on-brand video quickly.",
      ),
      D = s._(
        /*BTDS*/ "Adds natural movement to your image in a single scene. Best when you want the fastest, lightest way to get video from an image you already have.",
      ),
      x = s._(
        /*BTDS*/ "A short story based on images from your website. Pick this when your website has strong visuals and you want to turn them into a video.",
      ),
      $ = s._(
        /*BTDS*/ "A high-impact, single-scene video that spotlights your product or service in a clean, smooth motion. Best when you want to grab attention fast with one bold, polished moment.",
      ),
      P = s._(
        /*BTDS*/ "Turns your image into a multi-shot clip with different angles and close-ups. Use it when you want one image to feel more dynamic and cinematic.",
      ),
      N = s._(
        /*BTDS*/ "Shows your product in aspirational, real-world settings shoppers can picture themselves in. Use it when setting and lifestyle context add to the allure of your product.",
      ),
      M = s._(
        /*BTDS*/ "A polished, studio-lit video that shows your product from flattering angles on a clean backdrop. Choose it for a premium look without a photoshoot.",
      ),
      w = s._(
        /*BTDS*/ "Real people showing your product in an authentic, user-generated style. Great for building trust with new audiences.",
      ),
      A = s._(
        /*BTDS*/ "Your product stays constant while the background rotates through fresh, on-brand scenes. Choose it to show product detail along with visual variety.",
      ),
      F = s._(
        /*BTDS*/ "Sequences multiple product shots into one clean, animated video. Best when you have several good images and want a simple, versatile clip.",
      ),
      O = s._(
        /*BTDS*/ "A talking AI avatar clip that names a relatable problem and positions your product or service as the fix. Best for direct response ads that lead with a pain point.",
      ),
      B = s._(
        /*BTDS*/ "A talking AI avatar clip that drives home the top reason to choose your brand. Use it when one standout benefit makes the strongest hook.",
      ),
      W = s._(
        /*BTDS*/ "Moves the most engaging moment from your video to the first few seconds to capture viewers' attention. The rest of your video stays the same.",
      ),
      q = s._(
        /*BTDS*/ "Adds an overlay as text to the first few seconds of your video to highlight your key message and capture attention quickly. The rest of your video stays the same.",
      ),
      U = s._(
        /*BTDS*/ "Generates and adds a quick intro video hook based on what\u2019s trending. The rest of your video stays the same.",
      ),
      V = s._(/*BTDS*/ "Full-screen, short branded video"),
      H = s._(/*BTDS*/ "Your image, brought to life"),
      G = s._(/*BTDS*/ "Based on your website images"),
      z = s._(/*BTDS*/ "New background, elevated composition"),
      j = s._(/*BTDS*/ "More angles and details"),
      K = s._(/*BTDS*/ "Aspirational lifestyle scenes"),
      Q = s._(/*BTDS*/ "Professional product feature"),
      X = s._(/*BTDS*/ "Authentic video selfie feel"),
      Y = s._(/*BTDS*/ "Same product, multiple scenes"),
      J = s._(/*BTDS*/ "Multi-image product showcase"),
      Z = s._(/*BTDS*/ "AI avatar pitch"),
      ee = s._(/*BTDS*/ "AI avatar with top reason to buy"),
      te = {
        1: p,
        2: p,
        3: u,
        4: _,
        5: _,
        6: p,
        7: c,
        8: u,
        9: m,
        10: d,
        11: u,
        12: e,
        13: p,
        14: f,
        15: p,
        16: g,
        17: h,
        18: y,
        19: y,
        20: C,
        21: b,
      },
      ne = babelHelpers.extends({}, te, {
        4: E,
        5: E,
        7: L,
        14: k,
        18: I,
        19: I,
      });
    function re(e, t) {
      if (e == null) return null;
      var n = t ? te : ne;
      return n[String(e)];
    }
    var oe = {
        1: x,
        2: x,
        3: N,
        4: T,
        5: T,
        6: x,
        7: w,
        8: N,
        9: A,
        10: F,
        11: N,
        12: M,
        13: x,
        14: O,
        15: x,
        16: O,
        17: B,
        18: P,
        19: P,
        20: $,
        21: D,
      },
      ae = {
        26: { description: W, recipeLabel: v },
        27: { description: q, recipeLabel: S },
        28: { description: U, recipeLabel: R },
      },
      ie = {
        1: G,
        2: G,
        3: K,
        4: V,
        5: V,
        6: G,
        7: X,
        8: K,
        9: Y,
        10: J,
        11: K,
        12: Q,
        13: G,
        14: Z,
        15: G,
        16: Z,
        17: ee,
        18: j,
        19: j,
        20: z,
        21: H,
      };
    ((l.VARIANT_ID_TO_FBT_LABEL_MAP = te),
      (l.VARIANT_ID_TO_LEGACY_FBT_LABEL_MAP = ne),
      (l.getVideoGenRecipeLabel = re),
      (l.VARIANT_ID_TO_FBT_DESCRIPTION_MAP = oe),
      (l.VIDEO_GEN_RECIPE_TYPE_TO_FBT_TEXT_DETAILS_MAP = ae),
      (l.VARIANT_ID_TO_FBT_SUBTITLE_MAP = ie));
  },
  226,
);
