__d(
  "AdsAdditionalOptionsConsts",
  ["$InternalEnum", "immutable", "unsafeCast"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = (e = n("$InternalEnum"))({
        AdgroupAdFormat: "adgroupAdFormat",
        AdgroupCallToAction: "adgroupCallToAction",
        AdgroupConnectedSourcesCatalog: "adgroupConnectedSourcesCatalog",
        AdgroupIdentity: "adgroupIdentity",
        AdgroupMarketingMessageCarouselCardsEditor:
          "adgroupMarketingMessageCarouselCardsEditor",
        AdgroupOmnichannelDestinationSelector:
          "adgroupOmnichannelDestinationSelector",
        AdgroupProductEvents: "adgroupProductEvents",
        AdgroupWTWAFirstMessageTemplateEditor:
          "adgroupWTWAFirstMessageTemplateEditor",
        AdgroupWebsiteExtensions: "adgroupWebsiteExtensions",
      }),
      u = r("unsafeCast")(
        Object.fromEntries(
          s.members().map(function (e) {
            return [e.valueOf(), e.valueOf()];
          }),
        ),
      ),
      c = e({
        CampaignGroupBidStrategy: "campaignGroupBidStrategy",
        CampaignGroupBudgetScaling: "campaignGroupBudgetScaling",
        CampaignGroupBudgetStrategy: "campaignGroupBudgetStrategy",
        CampaignGroupBuyingType: "campaignGroupBuyingType",
        CampaignGroupCatalog: "campaignGroupCatalog",
        CampaignGroupDeliveryType: "campaignGroupDeliveryType",
        CampaignGroupObjective: "campaignGroupObjective",
        CampaignGroupRegulatedCategory: "campaignGroupRegulatedCategory",
        CampaignGroupScheduling: "campaignGroupScheduling",
        CampaignGroupSpendLimits: "campaignGroupSpendLimits",
        CampaignGroupTimeSuggestion: "campaignGroupTimeSuggestion",
      }),
      d = r("unsafeCast")(
        Object.fromEntries(
          c.members().map(function (e) {
            return [e.valueOf(), e.valueOf()];
          }),
        ),
      ),
      m = e({
        AdBreaksExclusion: "adBreaksExclusion",
        AdvantagePlusPlacements: "advantagePlusPlacements",
        Age: "age",
        AppStore: "appStore",
        AttributionCountType: "attributionCountType",
        PromotedApp: "promotedApp",
        MinAge: "minAge",
        AgeSuggestion: "ageSuggestion",
        AppAttributionWindow: "appAttributionWindow",
        Audience: "audience",
        AudienceExclusionF1: "audienceExclusionF1",
        AudienceInclusionF1: "audienceInclusionF1",
        AudienceSectionF2: "audienceSectionF2",
        AudienceSuggestionsSection: "audienceSuggestionsSection",
        MessageMarketingAudience: "messageMarketingAudience",
        MessengerMarketingMessageAudience: "messengerMarketingMessageAudience",
        BidStrategy: "bidStrategy",
        BillingEvent: "billingEvent",
        BlcMsaBudgetControl: "blcMsaBudgetControl",
        BlockList: "blockList",
        BrandSafety: "brandSafety",
        BrandSafetyAudienceNetworkFilter: "brandSafetyAudienceNetworkFilter",
        BrandSafetyBlockLists: "brandSafetyBlockLists",
        BrandSafetyCommentsOnAds: "brandSafetyCommentsOnAds",
        BrandSafetyContentFilter: "brandSafetyContentFilter",
        BrandSafetyContentTypeExclusion: "brandSafetyContentTypeExclusion",
        BrandSafetyFeedInventoryFilter: "brandSafetyFeedInventoryFilter",
        BrandSafetyInContentFilter: "brandSafetyInContentFilter",
        BrandSafetyMaturityRatingExclusions:
          "brandSafetyMaturityRatingExclusions",
        BrandSafetyNegativeKeywords: "brandSafetyNegativeKeywords",
        BrandSafetyTopicExclusions: "brandSafetyTopicExclusions",
        BudgetBidding: "budgetBidding",
        CaapAUFinserv: "caapAUFinserv",
        CaapINFinserv: "caapINFinserv",
        CaapSGUniversal: "caapSGUniversal",
        CaapUniversal: "caapUniversal",
        CaapTWFinserv: "caapTWFinserv",
        CaapTWUniversal: "caapTWUniversal",
        CampaignAttribution: "campaignAttribution",
        CampaignAttributionType: "campaignAttributionType",
        CampaignBudgetEndDate: "campaignBudgetEndDate",
        CampaignBudgetScaling: "campaignBudgetScaling",
        ConversionLocation: "conversionLocation",
        ConversionWindow: "conversionWindow",
        ConversionWindowFunnel: "conversionWindowFunnel",
        DailyBudgetScheduling: "dailyBudgetScheduling",
        DeliveryType: "deliveryType",
        DetailedTargeting: "detailedTargeting",
        DeviceAndOS: "deviceAndOS",
        DeviceType: "deviceType",
        Exclusions: "exclusions",
        ExperimentalLanguages: "experimentalLanguages",
        ExcludeAudiencesGoal: "excludeAudiencesGoal",
        ExcludeEngagedAudiencesGoal: "excludeEngagedAudiencesGoal",
        ExcludeCatalogueInteractionsF1: "excludeCatalogueInteractionsF1",
        FrequencyControlInterval: "frequencyControlInterval",
        Gender: "gender",
        InfoNeededFromLeads: "infoNeededFromLeads",
        InstallState: "installState",
        InstallStateF1: "installStateF1",
        InstallStateF2: "installStateF2",
        Languages: "languages",
        Locations: "locations",
        LookalikeInclusionsGoal: "lookalikeInclusionsGoal",
        ExistingCustomersInclusionsGoal: "existingCustomersInclusionsGoal",
        MessageMarketingBillingEvent: "messageMarketingBillingEvent",
        MessageMarketingConversionWindow: "messageMarketingConversionWindow",
        OptimizationGoal: "optimizationGoal",
        OptimizationGoalPGD: "optimizationGoalPGD",
        PlacementAutoManual: "placementAutoManual",
        PlacementControls: "placementControls",
        PlacementDeviceAndOS: "placementDeviceAndOS",
        PlacementPlatforms: "placementPlatforms",
        ReelsPlacementControls: "reelsPlacementControls",
        ReelsPlacementDeviceAndOS: "reelsPlacementDeviceAndOS",
        ReelsPlacementPlatforms: "reelsPlacementPlatforms",
        ReservationAgeTargeting: "reservationAgeTargeting",
        ReservationBidStrategySummaryF2: "reservationBidStrategySummaryF2",
        ReservationCampaignDurationSummaryF2:
          "reservationCampaignDurationSummaryF2",
        ReservationDeliveryTypeSummaryF2: "reservationDeliveryTypeSummaryF2",
        ReservationDetailedTargeting: "reservationDetailedTargeting",
        ReservationFrequencyControl: "reservationFrequencyControl",
        ReservationGenderTargeting: "reservationGenderTargeting",
        ReservationGetChargedSummaryF2: "reservationGetChargedSummaryF2",
        ReservationLanguagesTargeting: "reservationLanguagesTargeting",
        ReservationLocationsTargeting: "reservationLocationsTargeting",
        ReservationScheduling: "reservationScheduling",
        Scheduling: "scheduling",
        SeamlessASPAudience: "seamlessASPAudience",
        SeamlessASPPlacements: "seamlessASPPlacements",
        SeamlessASPPlacementsDetailed: "seamlessASPPlacementsDetailed",
        SearchThemes: "searchThemes",
        SequencedConversionWindow: "sequencedConversionWindow",
        SkippableAdsExclusion: "skippableAdsExclusion",
        SpendControls: "spendControls",
        TimeSuggestion: "timeSuggestion",
        AppInstallState: "appInstallState",
        ValueAdjustmentRule: "valueAdjustmentRule",
        DfcaDataSource: "dfcaDataSource",
        ValueAdjustmentRuleFederatedPlacement3B:
          "valueAdjustmentRuleFederatedPlacement3B",
        ValueAdjustmentRuleFederatedChannel3B:
          "valueAdjustmentRuleFederatedChannel3B",
        ValueAdjustmentRuleFederatedAudience:
          "valueAdjustmentRuleFederatedAudience",
        ValueRulesGoal: "valueRulesGoal",
        EngagedAudiencesInclusionsGoal: "engagedAudiencesInclusionsGoal",
        GoalSectionF2: "goalSectionF2",
      }),
      p = r("unsafeCast")(
        Object.fromEntries(
          m.members().map(function (e) {
            return [e.valueOf(), e.valueOf()];
          }),
        ),
      ),
      _ = { ADGROUP: u, CAMPAIGN_GROUP: d, CAMPAIGN: p },
      f = e.Mirrored(["F0", "F1", "F2"]),
      g = e({
        AudienceSectionF2: "audienceSectionF2",
        GoalSectionF2: "goalSectionF2",
        AudienceSuggestionsSection: "audienceSuggestionsSection",
        AlwaysVisibie: "alwaysVisibie",
        AutomaticPlacement: "automaticPlacement",
        BrandSafety: "brandSafety",
        Budget: "budget",
        BudgetAndDelivery: "budgetAndDelivery",
        CampaignGroupBudget: "campaignGroupBudget",
        Conversion: "conversion",
        Delivery: "delivery",
        Invisible: "invisible",
        AsaReportingAudienceSettings: "asaReportingAudienceSettings",
        PeCampaignGroupDetails: "peCampaignGroupDetails",
        Placement: "placement",
        Targeting: "targeting",
        ProgressiveDisclosurePlacement: "progressiveDisclosurePlacement",
      }),
      h = {
        audienceSectionF2: g.AudienceSectionF2,
        goalSectionF2: g.GoalSectionF2,
        audienceSuggestionsSection: g.AudienceSuggestionsSection,
        alwaysVisibie: g.AlwaysVisibie,
        automaticPlacement: g.AutomaticPlacement,
        brandSafety: g.BrandSafety,
        budget: g.Budget,
        budgetAndDelivery: g.BudgetAndDelivery,
        campaignGroupBudget: g.CampaignGroupBudget,
        conversion: g.Conversion,
        delivery: g.Delivery,
        invisible: g.Invisible,
        asaReportingAudienceSettings: g.AsaReportingAudienceSettings,
        peCampaignGroupDetails: g.PeCampaignGroupDetails,
        placement: g.Placement,
        targeting: g.Targeting,
        progressiveDisclosurePlacement: g.ProgressiveDisclosurePlacement,
      },
      y = r("immutable")
        .Map(babelHelpers.extends({}, u, d, p))
        .map(function (e) {
          return { isEditable: !1, isSticky: !1, hasEdited: !1 };
        });
    ((l.AdditionalOptions = _),
      (l.AdditionalOptionsFrictionLevels = f),
      (l.AdditionalOptionsSection = g),
      (l.AdditionalOptionsSections = h),
      (l.AdditionalOptionsDataProviderInitialState = y));
  },
  98,
);
