__d(
  "AdsSettingsDataLoaderFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      reporting_fields: [
        "default_account_overview_metrics",
        "default_account_overview_agegender_metrics",
        "default_account_overview_time_metrics",
        "default_account_overview_location_metrics",
        "default_builtin_column_preset",
        "default_column_preset",
        "default_nam_time_range",
        "column_suggestion_status",
        "last_used_columns",
        "onboarding_config",
        "has_seen_groups_column_flexing_experience",
        "has_seen_instagram_column_flexing_experience",
        "has_seen_leads_column_flexing_experience",
        "has_seen_shops_ads_metrics_onboarding_tour",
        "should_show_shops_ads_metrics_onboarding_tour",
        "shops_ads_metrics_onboarding_tour_close_count",
        "shops_ads_metrics_onboarding_tour_last_action_time",
        "saip_advertiser_setup_optimisation_guidance_state",
        "saip_advertiser_setup_optimisation_guidance_overall_state",
        "single_objective_column_flexing_status",
        "active_ads_quick_view_created",
        "had_delivery_quick_view_created",
        "actions_quick_view_created",
        "high_performing_quick_view_created",
        "value_optimized_qv_created",
        "budget_optimization_quick_view_created",
        "recently_used_quick_views",
        "has_used_quick_views_panel",
        "conditional_formatting_rules",
        "is_ads_manager_footer_row_shown",
        "is_ads_manager_footer_row_preference_set",
        "ads_manager_footer_row_toast_impressions",
        "text_gen_persona_opt_in_type",
        "value_qv_nux_impressions",
        "value_suggested_column_status",
        "ps_perf_charts_settings_config",
      ],
      fields: [
        "user_settings{default_account_overview_metrics,default_account_overview_agegender_metrics,default_account_overview_time_metrics,default_account_overview_location_metrics,default_builtin_column_preset,default_column_preset,default_nam_time_range,column_suggestion_status,last_used_columns,onboarding_config,has_seen_groups_column_flexing_experience,has_seen_instagram_column_flexing_experience,has_seen_leads_column_flexing_experience,has_seen_shops_ads_metrics_onboarding_tour,should_show_shops_ads_metrics_onboarding_tour,shops_ads_metrics_onboarding_tour_close_count,shops_ads_metrics_onboarding_tour_last_action_time,saip_advertiser_setup_optimisation_guidance_state,saip_advertiser_setup_optimisation_guidance_overall_state,single_objective_column_flexing_status,active_ads_quick_view_created,had_delivery_quick_view_created,actions_quick_view_created,high_performing_quick_view_created,value_optimized_qv_created,budget_optimization_quick_view_created,recently_used_quick_views,has_used_quick_views_panel,conditional_formatting_rules,is_ads_manager_footer_row_shown,is_ads_manager_footer_row_preference_set,ads_manager_footer_row_toast_impressions,text_gen_persona_opt_in_type,value_qv_nux_impressions,value_suggested_column_status,ps_perf_charts_settings_config}",
      ],
    });
    i.default = e;
  },
  66,
);
