__d(
  "VideoPlayerLoggerSource",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ABOUT_INSTAGRAM: "about_instagram",
      AD_LIBRARY: "ad_library",
      ADS: "ads",
      ADS_PREVIEW: "ads_preview",
      AIRWAVE_GCAST_WEB_RECEIVER_VIDEO_PLAYER:
        "airwave_gcast_web_receiver_video_player",
      AM_READINESS_VIDEO_PLAYER: "am_readiness_video_player",
      ANIMATED_IMAGE_SHARE: "animated_image_share",
      ANIMATED_SATP: "animated_satp",
      ASSET: "asset",
      ASSET_MANAGER: "asset_manager",
      AUDIO_DESCRIPTION: "audio_description",
      AUDIO_HOME: "audio_home",
      AUDIO_HOME_GET_CAUGHT_UP_INFINITE_SECTION:
        "audio_home_get_caught_up_infinite_section",
      AUDIO_HOME_GET_CAUGHT_UP_SECTION: "audio_home_get_caught_up_section",
      AUDIO_HOME_ORION_CTA: "audio_home_orion_cta",
      AUDIO_HOME_ORION_EXPLORE_TAB: "audio_home_orion_explore_tab",
      AUDIO_HOME_POPULAR_EPISODES_INFINITE_SECTION:
        "audio_home_popular_episodes_infinite_section",
      AUDIO_HOME_POPULAR_EPISODES_SECTION:
        "audio_home_popular_episodes_section",
      AUDIO_HOME_QP: "audio_home_qp",
      AUDIO_HOME_SUBSCRIBED_EPISODES_INFINITE_SECTION:
        "audio_home_subscribed_episodes_infinite_section",
      AUDIO_HOME_SUBSCRIBED_EPISODES_SECTION:
        "audio_home_subscribed_episodes_section",
      AUDIO_HOME_TRAILERS_INFINITE_SECTION:
        "audio_home_trailers_infinite_section",
      AUDIO_HOME_TRAILERS_SECTION: "audio_home_trailers_section",
      AYMT: "aymt",
      B2MV_RIFU_QP: "b2mv_rifu_qp",
      BALLOT: "ballot",
      BILLING_HUB: "billing_hub",
      BIZ_ART: "biz_art",
      BIZ_DUBBING_PLAYER: "biz_dubbing_player",
      BIZ_MENTIONS_AND_TAGS: "biz_mentions_and_tags",
      BIZ_STORIES_COMPOSER: "biz_stories_composer",
      BIZ_UNIFIED_PROGRAM_PREVIEW_PAGE: "biz_unified_program_preview_page",
      BLOKS_EMULATOR: "bloks_emulator",
      BOOKMARK: "bookmark",
      BRAND_RIGHTS_PROTECTION: "brand_rights_protection",
      BROADCAST_CHANNELS_CREATE_CHANNEL_NUX_CAROUSEL:
        "broadcast_channels_create_channel_nux_carousel",
      BROADCAST_REQUEST_ATTACHMENT: "broadcast_request_attachment",
      BULLETIN_AUDIO_PLAYER: "bulletin_audio_player",
      BUSINESS_FEED: "business_feed",
      BUY_AT: "buy_at",
      CAMERA_POST: "camera_post",
      CANDIDATE_PORTAL: "candidate_portal",
      CANDIDATE_VIDEOS: "candidate_videos",
      CATALOG_MANAGER: "catalog_manager",
      CHAINED: "chained",
      CHAINED_SUGGESTION: "chained_suggestion",
      CHANNEL: "channel",
      CHANNEL_TAB: "channel_tab",
      CHANNEL_TAB_LATEST_VIDEOS_CARD: "channel_tab_latest_videos_card",
      CHANNEL_TAB_LIVE_CARD: "channel_tab_live_card",
      CHANNEL_TAB_PLAYLIST_CARD: "channel_tab_playlist_card",
      CHANNEL_TAB_POPULAR_VIDEO_CARD: "channel_tab_popular_video_card",
      CHANNEL_TAB_SERIES_CARD: "channel_tab_series_card",
      CHANNEL_TAB_VIDEOS_CARD: "channel_tab_videos_card",
      CHAT_LLAMA: "chat_llama",
      CMS: "cms",
      COMMERCE_MANAGER: "commerce_manager",
      COMPASS_CURATION: "compass_curation",
      CONTINUE_WATCHING_RECOMMENDATION: "continue_watching_recommendation",
      CORPORATE_CARD_APPLICATION: "corporate_card_application",
      COWATCH: "cowatch",
      CREATOR_EXPLORE_FEED: "creator_explore_feed",
      CREATOR_STORE_AFFILIATE_LINKS: "creator_store_affiliate_links",
      CREATOR_STUDIO_INSPIRATION_HUB: "creator_studio_inspiration_hub",
      CREATOR_STUDIO_MIX_INSIGHTS_TRENDS: "creator_studio_mix_insights_trends",
      CREATOR_STUDIO_STARS_CUE_INSERTION_PREVIEW:
        "creator_studio_stars_cue_insertion_preview",
      CRICKET_MATCHES_AGGREGATION: "cricket_matches_aggregation",
      CROWDSOURCING_VIDEO_PREVIEW: "crowdsourcing_video_preview",
      CS_VIDEO_COMPOSER_CROSSPOSTING_REVIEW:
        "cs_video_composer_crossposting_review",
      CURATION: "curation",
      CURATION_QP: "curation_qp",
      DIFF_TOOL: "diff_tool",
      DIM_SUM: "dim_sum",
      DISCOVERY_HUBS_HEADER: "discovery_hubs_header",
      DOLLY_DISCOVERY_PAGE: "dolly_discovery_page",
      EMBEDDED: "embedded",
      EMBEDDED_PAGE_PLUGIN: "embedded_page_plugin",
      EMBEDDED_VIDEO: "embedded_video",
      EMBEDDED_VIDEO_FROM_UFI: "embedded_video_from_ufi",
      EMBEDDED_VIDEO_PREVIEW: "embedded_video_preview",
      ENT_MUTATOR_DEBUGGER_HELP_PAGE: "ent_mutator_debugger_help_page",
      ENTRY_POINT: "entry_point",
      ENTRY_POINT_NOTIFICATIONS: "entry_point_notifications",
      EP_TAKEDOWN_REQUEST_MANAGER: "ep_takedown_request_manager",
      EVENTS_COVER: "events_cover",
      EVENTS_HOSTS_REELS_CARD: "events_hosts_reels_card",
      EVENTS_LIVE_CTA: "events_live_cta",
      EVENTS_LIVE_VIDEO_SECTION: "events_live_video_section",
      EXTERNAL_DEEPLINK: "external_deeplink",
      FACEBOOK_DESIGN: "facebook_design",
      FAIR_SAM3_DEMO: "fair_sam3_demo",
      FAIR_VIDEO_SEAL_DEMO: "fair_video_seal_demo",
      FANDOM_CHALLENGE_ASSET: "fandom_challenge_asset",
      FB_REELS_AUDIO: "fb_reels_audio",
      FB_REELS_VIDEO_PREVIEW: "fb_reels_video_preview",
      FB_SHORTS_CHAINING_VIEWER: "fb_shorts_chaining_viewer",
      FB_SHORTS_CREATION_FEED_UNIT: "fb_shorts_creation_feed_unit",
      FB_SHORTS_IFR_SINGLE_VIDEO_FEED_UNIT:
        "fb_shorts_ifr_single_video_feed_unit",
      FB_SHORTS_NATIVE_IN_FEED_UNIT: "fb_shorts_native_in_feed_unit",
      FB_SHORTS_NATIVE_WATCH_IN_FEED_UNIT:
        "fb_shorts_native_watch_in_feed_unit",
      FB_SHORTS_PROFILE_VIEWER: "fb_shorts_profile_viewer",
      FB_SHORTS_RESHARE_FEED_UNIT: "fb_shorts_reshare_feed_unit",
      FB_SHORTS_UNIFIED_TOFU: "fb_shorts_unified_tofu",
      FB_SHORTS_VIEWER: "fb_shorts_viewer",
      FB_SHORTS_WATCH_PILL: "fb_shorts_watch_pill",
      FB_STORIES_NOTES: "fb_stories_notes",
      FEED: "feed",
      FEED_ANSWERSHEET: "feed_answersheet",
      FEED_STORY: "feed_story",
      FREELS_PROMOTION: "freels_promotion",
      FRIEND_COMMENT_SPARKS: "friend_comment_sparks",
      FULLSCREEN_COMPOSER_PREVIEW: "fullscreen_composer_preview",
      FUNDRAISER_COVER: "fundraiser_cover",
      GALLERY_CATALOG: "gallery_catalog",
      GALLERY_SGC: "gallery_sgc",
      GALLERY_UGC: "gallery_ugc",
      GAMEROOM_LIVE_VIDEO_HERO_BANNER: "gameroom_live_video_hero_banner",
      GAMEROOM_LIVE_VIDEO_TAB: "gameroom_live_video_tab",
      GAMEROOM_LIVE_VIDEO_THUMBNAIL: "gameroom_live_video_thumbnail",
      GAMES_ARENA_HERO: "games_arena_hero",
      GAMES_ARENA_VIDEOS_TAB: "games_arena_videos_tab",
      GAMES_AUDIENCE_NETWORK_ADS: "games_audience_network_ads",
      GAMES_FEATURED_HERO_BANNER: "games_featured_hero_banner",
      GAMES_FEED: "games_feed",
      GAMES_FEED_STORY_HEADER: "games_feed_story_header",
      GAMES_FEED_VOD_UNIT: "games_feed_vod_unit",
      GAMES_GAME_DETAILS: "games_game_details",
      GAMES_INSTANT_GAME_QUICK_PROMOTION: "games_instant_game_quick_promotion",
      GAMES_PROFILE: "games_profile",
      GAMES_STREAMER_DASHBOARD: "games_streamer_dashboard",
      GAMES_VERSE_DESTINATION: "games_verse_destination",
      GAMES_VIDEO_CLIPS_HOME: "games_video_clips_home",
      GAMES_VIDEO_CLIPS_HOME_IMMERSIVE_PLAYER:
        "games_video_clips_home_immersive_player",
      GAMES_VIDEO_CLIPS_HOME_MY_CLIPS: "games_video_clips_home_my_clips",
      GAMES_VIDEO_CLIPS_HOME_TOP_CLIPS: "games_video_clips_home_top_clips",
      GAMES_VIDEO_CLIPS_LIBRARY_PREVIEW_MODAL:
        "games_video_clips_library_preview_modal",
      GAMES_VIDEO_COMMUNITY_FEED: "games_video_community_feed",
      GAMES_VIDEO_COSTREAMERS_LIST: "games_video_costreamers_list",
      GAMES_VIDEO_EXPLORE_HOME: "games_video_explore_home",
      GAMES_VIDEO_HIGHLIGHT_VIDEO_PREVIEW:
        "games_video_highlight_video_preview",
      GAMES_VIDEO_HIGHLIGHT_VIDEO_TRANSITION:
        "games_video_highlight_video_transition",
      GAMES_VIDEO_HIGHLIGHTED_CLIPS_STREAMER_PAGE:
        "games_video_highlighted_clips_streamer_page",
      GAMES_VIDEO_HOME: "games_video_home",
      GAMES_VIDEO_HOME_HERO: "games_video_home_hero",
      GAMES_VIDEO_HOME_LEFT_RAIL: "games_video_home_left_rail",
      GAMES_VIDEO_HOME_SEE_ALL: "games_video_home_see_all",
      GAMES_VIDEO_HOME_STREAMER_HUB: "games_video_home_streamer_hub",
      GAMES_VIDEO_HOME_STREAMER_HUB_HERO: "games_video_home_streamer_hub_hero",
      GAMES_VIDEO_HOME_STREAMER_HUB_SCHEDULE:
        "games_video_home_streamer_hub_schedule",
      GAMES_VIDEO_HUB: "games_video_hub",
      GAMES_VIDEO_HUB_REDIRECT_NOTIFICATION:
        "games_video_hub_redirect_notification",
      GAMES_VIDEO_HUB_REDIRECT_UNKNOWN: "games_video_hub_redirect_unknown",
      GAMES_VIDEO_LIVE_RECOMMENDATION: "games_video_live_recommendation",
      GAMES_VIDEO_MIXER_US_QP_RECOMMENDED_LIVE:
        "games_video_mixer_us_qp_recommended_live",
      GAMES_VIDEO_PLAY_WITH_STREAMERS_LIVE:
        "games_video_play_with_streamers_live",
      GAMES_VIDEO_QP_RECOMMENDED_LIVE: "games_video_qp_recommended_live",
      GAMES_VIDEO_QP_US_RECOMMENDED_LIVE: "games_video_qp_us_recommended_live",
      GAMES_VIDEO_SEARCH_UNIT: "games_video_search_unit",
      GAMES_VIDEO_SINGLE_GAME: "games_video_single_game",
      GAMES_VIDEO_SOCIAL_PLUGIN: "games_video_social_plugin",
      GAMES_VIDEO_STREAMER_HUB: "games_video_streamer_hub",
      GAMES_VIDEO_STREAMER_SEARCH_UNIT: "games_video_streamer_unit",
      GAMES_VIDEO_THUMBNAIL_PREVIEW: "games_video_thumbnail_preview",
      GAMES_VIDEO_TOP_WEEKLY_CLIPS_STREAMER_PAGE:
        "games_video_top_weekly_clips_streamer_page",
      GAMES_VIDEO_VIEW_HIGHLIGHTS_CUE: "games_video_view_highlights_cue",
      GAMING_FOLLOWED_GAME_AGGREGATION: "gaming_followed_game_aggregation",
      GAMING_TOP_VIDEOS_AGGREGATION: "gaming_top_videos_aggregation",
      GENERIC_SHARE_ATTACHMENT_3P_VIDEO: "generic_share_attachment_3p_video",
      GET_CAUGHT_UP_QP: "get_caught_up_qp",
      GMS_HUB: "gms_hub",
      GOODWILL_PRODUCT_SYSTEM: "goodwill_product_system",
      GROUP_HIGHLIGHT_LIVE_AFFILIATE_PLAYER:
        "group_highlight_live_affiliate_player",
      GROUP_LIVE_VIDEO_MODULE: "group_live_video_module",
      GROUP_VIDEOS_AGGREGATION: "group_videos_aggregation",
      GROUPS_COVER: "groups_cover",
      GROUPS_FEATURED: "groups_featured",
      GROUPS_LATEST_VIDEOS: "groups_latest_videos",
      GROUPS_REELS_QP: "groups_reels_qp",
      GROUPS_WATCH_ALL: "groups_watch_all",
      GROUPS_WATCH_POPULAR: "groups_watch_popular",
      GUIDANCE_HUB: "guidance_hub",
      HASHTAG_DEEP_DIVE: "hashtag_deep_dive",
      HASHTAG_DESTINATION: "hashtag_destination",
      HELP_CENTER: "help_center",
      HERO_CATALOG: "hero_catalog",
      HERO_SGC: "hero_sgc",
      HERO_UGC: "hero_ugc",
      HORIZON_SHARES: "horizon_shares",
      HORIZON_WEB_LEARN_MORE: "horizon_web_learn_more",
      HORIZON_WEB_VIDEO_COVER: "horizon_web_video_cover",
      HORIZON_WEB_WORLD_REELS: "horizon_web_world_reels",
      HTML5: "html5",
      IGD_THREAD: "igd_thread",
      IGD_WEB_MUSIC_STICKER: "igd_web_music_sticker",
      INFO_HUB_VIDEO_RESULTS: "info_hub_video_results",
      INLINE: "inline",
      INLINE_END_SCREEN: "inline_end_screen",
      INLINE_PAUSE_SCREEN: "inline_pause_screen",
      INLINE_QP: "inline_qp",
      INSIGHTS: "insights",
      INSTANT_GAMES: "instant_games",
      INTERACTIVE_PLUGINS: "interactive_plugins",
      INTEREST_BASED_REELS_SPARKS: "interest_based_reels_sparks",
      INTERESTS_BLING_STRING: "interests_bling_string",
      INTERESTS_CUE_LISTPACK: "interests_cue_listpack",
      INTERESTS_FIXED_ENTRYPOINT: "interests_fixed_entrypoint",
      INTERESTS_FIXED_LISTPACK: "interests_fixed_listpack",
      INTERESTS_FOLLOW_CUE: "interests_follow_cue",
      INTERESTS_FOLLOW_EDGE_HEADER: "interests_follow_edge_header",
      INTERESTS_MANAGER: "interests_manager",
      INTERESTS_MULTIPLE_SUBTOPIC_CUE: "interests_multiple_subtopic_cue",
      INTERESTS_SPRING_BOARD: "interests_spring_board",
      INTERESTS_SUBTOPIC_AGGREGATION: "interests_subtopic_aggregation",
      INTERESTS_SUGGESTED_FOLLOW: "interests_suggested_follow",
      INTERESTS_WARION_BELT: "interests_warion_belt",
      INTERN_API_UNLABELLED_DATASETS: "intern_api_unlabelled_datasets",
      INTERN_CRM_CALL_RECORDING: "intern_crm_call_recording",
      INTERN_CURATION: "intern_curation",
      INTERN_EXAMPLE: "intern_example",
      INTERN_NEW_HIRE_ORIENTATION: "intern_new_hire_orientation",
      INTERVIEW_TRAINING_QUIZ: "interview_training_quiz",
      ISSUES_MODULE: "issues_module",
      JOBS_VISUAL_INTRO: "jobs_visual_intro",
      LANCELET: "lancelet",
      LIGHTWEIGHT_STATUS: "lightweight_status",
      LIGHTWEIGHT_STATUS_CONSUMPTION: "lightweight_status_consumption",
      LIGHTWEIGHT_STATUS_SELF_VIEW: "lightweight_status_self_view",
      LINEAR_CHANNEL: "linear_channel",
      LIVE_AUTOPLAY_WATCH_AND_SCROLL: "live_autoplay_watch_and_scroll",
      LIVE_BEEPER: "live_beeper",
      LIVE_CLIP: "live_clip",
      LIVE_CLIPS_CREATOR: "live_clips_creator",
      LIVE_CONTROL_PANEL: "live_control_panel",
      LIVE_DESTINATION_SCHEDULED_LIVES_QP:
        "live_destination_scheduled_lives_qp",
      LIVE_DESTINATION_THEMATIC_UPSELL_QP:
        "live_destination_thematic_upsell_qp",
      LIVE_DESTINATION_UPSELL_QP: "live_destination_upsell_qp",
      LIVE_EVERGREEN_QP: "live_evergreen_qp",
      LIVE_GAMING_RHC: "live_gaming_rhc",
      LIVE_HERO: "live_hero",
      LIVE_LINEAR: "live_linear",
      LIVE_MAP: "live_map",
      LIVE_MAP_LISTVIEW: "live_map_listview",
      LIVE_MAP_SIDEBAR: "live_map_sidebar",
      LIVE_MAP_TOOLTIP: "live_map_tooltip",
      LIVE_MAP_TOOLTIP_FROM_LISTVIEW: "live_map_tooltip_from_listview",
      LIVE_MAP_TOOLTIP_FROM_MAP: "live_map_tooltip_from_map",
      LIVE_MAP_TOOLTIP_FROM_WEBGL: "live_map_tooltip_from_webgl",
      LIVE_MSITE: "live_msite",
      LIVE_MUSIC_DESTINATION: "live_music_destination",
      LIVE_PAGE_UPCOMING_NEXT_UNIT: "live_page_upcoming_next_unit",
      LIVE_PRODUCER: "live_producer",
      LIVE_PYML: "live_pyml",
      LIVE_QP: "live_qp",
      LIVE_RHC: "live_rhc",
      LIVE_RING: "live_ring",
      LIVE_SHOPPING: "live_shopping",
      LIVE_SHOPPING_EVERGREEN_QP: "live_shopping_buyer_qp",
      LIVE_STUDIO: "live_studio",
      LIVE_STUDIO_POST_PRODUCTION: "live_studio_post_production",
      LIVE_VIDEO_BROADCAST: "live_video_broadcast",
      LIVE_VIDEO_PREVIEW: "live_video_preview",
      LIVING_ROOM: "living_room",
      LIVING_ROOM_COMMENTATING: "living_room_commentating",
      LIVING_ROOM_RECAP_FULLSCREEN: "living_room_recap_fullscreen",
      LIVING_ROOM_RECAP_INLINE: "living_room_recap_inline",
      LIVING_ROOM_UPSELL_BANNER: "living_room_upsell_banner",
      LOCAL_GUIDE: "local_guide",
      LOGIN_CHALLENGES_LANDING: "login_challenges_landing",
      LOOKBACK: "lookback",
      LUNA_PA_CONTENT: "luna_pa_content",
      MARKETPLACE_FEED_UNIT: "marketplace_feed_unit",
      MARKETPLACE_HSCROLL_UNIT: "marketplace_hscroll_unit",
      MARKETPLACE_IMMERSIVE_FEED: "marketplace_immersive_feed",
      MARKETPLACE_PROMOTIONAL_VIDEO: "marketplace_promotional_video",
      MARKETPLACE_REELS: "marketplace_reels",
      MARKETPLACE_TAB: "marketplace_tab",
      MBG_HUB: "mbg_hub",
      MBS_INSPIRATION_HUB: "mbs_inspiration_hub",
      MEDIA_COLLAGE: "media_collage",
      MEDIA_MATCH_SERVICE: "media_match_service",
      MEDIA_PLAYLIST_SHARE_STORY: "media_playlist_share_story",
      MEDIA_SYNC: "media_sync",
      MEDIA_VIEWER: "media_viewer",
      MEMORY_LEAK_TEST: "memory_leak_test",
      MESSAGING: "messaging",
      MESSENGER_COWATCH: "messenger_cowatch",
      MESSENGER_KIDS_CHALLENGES_INTERNAL_TOOL:
        "messenger_kids_challenges_internal_tool",
      MESSENGER_KIDS_DOT_COM: "messenger_kids_dot_com",
      MESSENGER_THREAD: "messenger_thread",
      META_AI_AUDIO_ONLY: "meta_ai_audio_only",
      META_AI_CREATOR_CONTENT: "meta_ai_creator_content",
      META_AI_HOME_FEED: "meta_ai_home_feed",
      META_AI_IMAGINE_CREATE: "meta_ai_imagine_create",
      META_AI_IMMERSIVE_FEED: "meta_ai_immersive_feed",
      META_AI_MISC: "meta_ai_misc",
      META_AI_REELS_VIEWER: "meta_ai_reels_viewer",
      META_AI_UNIFIED_CANVAS_POST: "meta_ai_unified_canvas_post",
      META_DOT_COM_CMS_PAGE: "meta_dot_com_cms_page",
      META_DOT_COM_UNKNOWN: "meta_dot_com_unknown",
      META_FAMILY_CENTER: "meta_family_center",
      METAGEN: "metagen",
      MISC: "misc",
      MLPP: "mlpp",
      MOBILE: "mobile",
      MOLO_WATCH_PERMALINK_BOTTOM_SHEET_LANDING:
        "molo_watch_permalink_bottom_sheet_landing",
      MOLO_WATCH_PERMALINK_BOTTOM_SHEET_VIDEOS:
        "molo_watch_permalink_bottom_sheet_videos",
      MOLO_WATCH_PERMALINK_HEADER: "molo_watch_permalink_header",
      MOLO_WATCH_PERMALINK_PROMO_UNIT: "molo_watch_permalink_promo_unit",
      MORC_CONSOLE: "morc_console",
      MOVIES_RECOMMENDED_MOVIES_QP: "movies_recommended_movies_qp",
      MP_BROWSE_FEED_UNIT: "mp_browse_feed_unit",
      MUSIC_AT_POST_LEVEL_EXPERIENCE_OVERLAY:
        "music_at_post_level_experience_overlay",
      MUSIC_DIGEST_QP: "music_digest_qp",
      MUSIC_DIGEST_SCREEN_ROW: "music_digest_screen_row",
      MUSIC_DIGEST_SCREEN_SPOTLIGHT: "music_digest_screen_spotlight",
      MUSIC_HOME: "music_home",
      MUSIC_HOME_DEEPLINK: "music_home_deeplink",
      MUSIC_HOME_ENTRY_AGGREGATION: "music_home_entry_aggregation",
      MUSIC_HOME_INTERNAL_BOOKMARK: "music_home_internal_bookmark",
      MUSIC_HOME_NEWSFEED_ATTACHMENT: "music_home_newsfeed_attachment",
      MUSIC_HOME_NEWSFEED_ATTACHMENT_TRENDING:
        "music_home_newsfeed_attachment_trending",
      MUSIC_HOME_NOTIFICATION: "music_home_notification",
      MUSIC_HOME_QP: "music_home_qp",
      MUSIC_HOME_QP_OVERLAY_HEADER: "music_home_qp_overlay_header",
      MUSIC_HOME_RICH_TILE: "music_home_rich_tile",
      MUSIC_HOME_SEARCH_SHORTCUT: "music_home_search_shortcut",
      MUSIC_HOME_SERP: "music_home_serp",
      MUSIC_HOME_SPRINGBOARD_UNIT: "music_home_springboard_unit",
      MUSIC_HOME_STATIONS_QP: "music_home_stations_qp",
      MUSIC_HOME_TAPPABLE_EDGE_HEADER: "music_home_tappable_edge_header",
      MUSIC_HOME_THIRD_PARTY_PIVOT: "music_home_third_party_pivot",
      MUSIC_HOME_UGC_CTA: "music_home_ugc_cta",
      MUSIC_HOME_UNKNOWN: "music_home_unknown",
      MUSIC_HOME_WATCH_CUE: "music_home_watch_cue",
      MUSIC_HOME_WATCH_CUE_ARTIST: "music_home_watch_cue_artist",
      MUSIC_HOME_WATCH_CUE_TRENDING: "music_home_watch_cue_trending",
      MUSIC_HOME_WATCH_PILL: "music_home_watch_pill",
      MUSIC_HOME_WATCH_PILL_FIX: "music_home_watch_pill_fix",
      MUSIC_HOME_WATCH_SEARCH: "music_home_watch_search",
      MUSIC_HOME_WATCH_SPOTLIGHT_UNIT: "music_home_watch_spotlight_unit",
      MUSIC_HOME_WATCH_STATIONS_UNIT: "music_home_watch_stations_unit",
      MUSIC_HOME_WATCH_SURFACE_PROMOTION_PILL:
        "music_home_watch_surface_promotion_pill",
      MUSIC_VIDEOS_CARD: "music_videos_card",
      MUSIC_VIDEOS_FEATURING_ARTIST_CARD: "music_videos_featuring_artist_card",
      MUSIC_VIDEOS_PLAYLISTS_CARD: "music_videos_playlists_card",
      MUSIC_VIDEOS_TAB: "music_videos_tab",
      MUSIC_WEEKLY_CHART: "music_weekly_chart",
      NEWS_TAB_COMPACT_DISPLAY: "news_tab_compact_display",
      NEWS_TAB_CURATED: "news_tab_curated",
      NEWSFEED_ACTION_LINK: "newsfeed_action_link",
      NEWSFEED_AD: "newsfeed_ad",
      NEWSFEED_EPISODE_UNIT: "newsfeed_episode_unit",
      NEWSFEED_PLAYLIST_VIDEO_UNIT: "newsfeed_playlist_video_unit",
      NEWSFEED_QP: "newsfeed_qp",
      NEWSFEED_SERIES_UNIT: "newsfeed_series_unit",
      NEWSFEED_SUBSCRIBE_MEGAPHONE: "newsfeed_subscribe_megaphone",
      NEWSFEED_SUBSCRIBE_UPSELL_QP: "newsfeed_subscribe_upsell_qp",
      NEWSFEED_SUBSCRIPTION_DIGEST_QP: "newsfeed_subscription_digest_qp",
      NEWSFEED_WEM_LEARNING_VIDEO_UNIT:
        "newsfeed_wem_learning_playlist_video_unit",
      NOT_SPECIFIED_PLEASE_FIX: "not_specified_please_fix",
      NOTIFICATIONS: "notifications",
      NPR_QP: "npr_qp",
      OCULUS: "oculus",
      OCULUS_GAMES: "oculus_games",
      OCULUS_HUB: "oculus_hub",
      OCULUS_RECOMMENDED_VIDEO_UNIT: "oculus_recommended_video_unit",
      OCULUS_TV_BROWSE_SURFACE_DECADE_PMV: "oculus_tv_browse_decades_pmv",
      OCULUS_TV_BROWSE_SURFACE_GENRE_PMV: "oculus_tv_browse_genres_pmv",
      OCULUS_TV_BROWSE_SURFACE_NEW_RELEASES_PMV:
        "oculus_tv_browse_new_releases_pmv",
      OCULUS_TV_BROWSE_SURFACE_POPULAR_PMV: "oculus_tv_browse_popular_pmv",
      OCULUS_TV_SEARCH: "oculus_tv_search",
      OFFERS_DETAIL: "offers_detail",
      PAGE_ADMIN_THINGS_YOU_SHOULD_DO_TIP:
        "page_admin_things_you_should_do_tip",
      PAGE_AUTOLOAD_WATCH_AND_SCROLL: "page_autoload_watch_and_scroll",
      PAGE_EPISODE_UPSELL: "page_episode_upsell",
      PAGE_LIVE_TAB: "page_live_tab",
      PAGE_LIVE_VIDEO_MODULE: "page_live_video_module",
      PAGE_MUSIC_VIDEOS_SPOTLIGHT: "page_music_videos_spotlight",
      PAGE_ROLES: "page_roles",
      PAGE_SERIES_ITEM: "page_series_item",
      PAGE_SPOTLIGHT: "page_spotlight",
      PAGE_TIMELINE_CHANNEL_TAB_VIDEOS_CARD:
        "page_timeline_channel_tab_videos_card",
      PAGE_TIMELINE_LIVE_CARD: "page_timeline_live_card",
      PAGE_TIMELINE_LIVE_NOW_DIALOG: "page_timeline_live_now_dialog",
      PAGE_TIMELINE_VIDEO_LIST_AGGREGATION:
        "page_timeline_video_list_aggregation",
      PAGE_UPSELL_CARDS: "page_upsell_cards",
      PAGES_COVER: "pages_cover",
      PAGES_COVER_HOVER: "pages_cover_hover",
      PAGES_FINCH_MAIN_VIDEO: "pages_finch_main_video",
      PAGES_FINCH_THUMBNAIL_VIDEO: "pages_finch_thumbnail_video",
      PAGES_FINCH_TRAILER: "pages_finch_trailer",
      PAGES_HOME_HERO: "pages_home_hero",
      PAGES_HOME_PMV_UNIT: "pages_home_pmv_unit",
      PAGES_MESSAGING_VIDEO: "pages_messaging_video",
      PAGES_TIMELINE_INLINE: "pages_timeline_inline",
      PAGES_TIMELINE_PAGES_COVER: "pages_timeline_pages_cover",
      PAGES_VIDEO_SET: "pages_video_set",
      PAID_CONTENT_PACKAGE_PERMALINK_COVER:
        "paid_content_package_permalink_cover",
      PDP_VIDEO: "pdp_video",
      PEOPLE_PORTAL: "people_portal",
      PERMALINK: "permalink",
      PIXELCLOUD_POST: "pixelcloud_post",
      PIXELCLOUD_POST_INBOX_PREVIEW: "pixelcloud_post_inbox_preview",
      PIXELCLOUD_PROJECT_POST_WIDGET: "pixelcloud_project_post_widget",
      PIXELCLOUD_PROJECT_PRESENTATION_SLIDE:
        "pixelcloud_project_presentation_slide",
      PLAYLIST_PAGE: "playlist_page",
      PLAYLISTS_CARD: "playlists_card",
      PLAYLISTS_TAB: "playlists_tab",
      PMV_BACK_CATALOG_QP: "pmv_back_catalog_qp",
      PMV_NEW_RELEASE_DIGEST: "pmv_new_release_digest",
      PMV_NEW_RELEASE_DIGEST_CHANNEL_VIEW:
        "pmv_new_release_digest_channel_view",
      PMV_NEW_RELEASE_QP: "pmv_new_release_qp",
      PMV_THIRD_PARTY_TRIGGERED_CTA: "pmv_third_party_triggered_cta",
      PMV_TOP_CHART_CTA: "pmv_top_chart_cta",
      PMV_UGC_CTA: "pmv_ugc_cta",
      PMV_YOUTUBE_STORY_LEVEL_CTA: "pmv_youtube_story_level_cta",
      PODCAST_HIGHLIGHT_FULL_EPISODE_CTA: "podcast_highlight_full_episode_cta",
      PODCASTS_ADMIN_PUBLISHED_VIEW: "podcasts_admin_published_view",
      PODCASTS_EPISODE_DEEPLINK: "podcast_episode_deplink",
      PODCASTS_EPISODE_PAGE: "podcasts_episode_page",
      PODCASTS_LISTEN_UP_QP: "podcasts_listen_up_qp",
      PODCASTS_ORION_SHOW_NAME: "podcasts_orion_show_name",
      PODCASTS_ORION_THUMBNAIL: "podcasts_orion_thumbnail",
      PODCASTS_PAGE_EPISODE_CARD: "podcasts_page_episode_card",
      PODCASTS_PROFILE_PLUS_EPISODE_CARD: "podcasts_profile_plus_episode_card",
      PODCASTS_PROFILE_PLUS_PINNED_FEATURE:
        "podcasts_profile_plus_pinned_feature",
      PODCASTS_SHOW_PAGE: "podcasts_show_page",
      PODCASTS_SINGLE_SHOW_DIGEST_QP: "podcasts_single_show_digest_qp",
      PODCASTS_TRAILER_CTA: "podcasts_trailer_cta",
      POE_QP: "poe_qp",
      PRODASH_OBJECT_INSIGHTS: "prodash_object_insights",
      PRODASH_WEB_MONETIZATION_ELIGIBILITY_PAGE:
        "prodash_web_monetization_eligibility_page",
      PROFILE_COVER: "profile_cover",
      PROFILE_FEATURED_SECTION: "profile_featured_section",
      PROFILE_OVERVIEW: "profile_overview",
      PROFILE_PLUS_LATEST_VIDEOS_CARD: "profile_plus_latest_videos_card",
      PROFILE_PLUS_LIVE_CARD: "profile_plus_live_card",
      PROFILE_PLUS_LIVE_VIDEOS_TAB: "profile_plus_live_videos_tab",
      PROFILE_PLUS_PINNED_PLAYLIST_CARD: "profile_plus_pinned_playlists_card",
      PROFILE_PLUS_PINNED_POPULAR_VIDEO_CARD:
        "profile_plus_pinned_popular_video_card",
      PROFILE_PLUS_PINNED_SERIES_CARD: "profile_plus_pinned_series_card",
      PROFILE_PLUS_PLAYLIST_CARD: "profile_plus_playlist_card",
      PROFILE_PLUS_POPULAR_VIDEO_CARD: "profile_plus_popular_video_card",
      PROFILE_PLUS_PRODUCT_TOUR: "profile_plus_product_tour",
      PROFILE_PLUS_SERIES_CARD: "profile_plus_sereis_card",
      PROFILE_PLUS_VIDEO_TAB: "profile_plus_video_tab",
      PROFILE_PLUS_VIDEOS_CARD: "profile_plus_videos_card",
      PROFILE_SWITCHER_ILLUSTRATION: "profile_switcher_illustration",
      PROFILE_VIDEO: "profile_video",
      PROFILE_VIDEO_HOVERCARD: "profile_video_hovercard",
      PROFILE_VIDEO_THUMB: "profile_video_thumb",
      PROTON: "proton",
      PUSH: "push",
      QP_MEDIA_HSCROLL: "qp_media_hscroll",
      QUICK_PROMOTION: "quick_promotion",
      REDIRECTED_WATCH_SERP: "redirected_watch_serp",
      REELS_ENDCARD_RELATED_REELS: "reels_endcard_related_reels",
      REELS_FROM_SIMILAR_CREATORS_QP: "reels_from_similar_creators_qp",
      REELS_MIDCARD_RELATED_REELS: "reels_midcard_related_reels",
      REELS_TRENDING_HASHTAG_QP: "reels_trending_hashtag_qp",
      RELATED_PUBLISHERS_CUE: "related_publishers_cue",
      RELATED_REELS_GRID: "related_reels_grid",
      REMOTE_LEARNING_INSTRUCTOR_HOME: "remote_learning_instructor_home",
      REPORT_FLOW: "report_flow",
      REPOSTED_REELS_PAGE: "reposted_reels_page",
      RESULTS: "results",
      RESULTS_VIDEO_PIVOT: "results_video_pivot",
      RESULTS_VIDEO_SCOPED: "results_video_scoped",
      RESULTS_VIDEO_SEARCH_BAR: "results_video_search_bar",
      REVIEW: "review",
      RL_HUB: "rl_hub",
      ROBOTICS_RTC_PAGE: "robotics_rtc_page",
      ROBOTICS_TOUR_GUIDE_PAGE: "robotics_tour_guide_page",
      ROOMS_TRAY: "rooms_tray",
      SAVED_DASHBOARD: "saved_dashboard",
      SAVED_VIDEOS_QP: "saved_videos_qp",
      SEARCH_LIVE_VIDEO_MODULE: "search_live_video_module",
      SEARCH_NULLSTATE: "null_state",
      SEARCH_NULLSTATE_TOP_CONTENT: "search_nullstate_top_content",
      SEARCH_RESULT_PAGE: "search_result_page",
      SERIES_CARD: "series_card",
      SERP_INLINE_PLAYER: "serp_inline_player",
      SERP_THUMBNAIL_PREVIEW: "serp_thumbnail_preview",
      SERP_VIDEOS_TAB: "serp_videos_tab",
      SHARED_REELS_LANDING_PAGE: "shared_reels_landing_page",
      SHORT_VIDEOS_SPOTLIGHT: "short_videos_spotlight",
      SHOW_CATALOG_CTA: "show_catalog_cta",
      SHOWS_CATALOG: "shows_catalog",
      SINGLE_PAGE_CHANNEL: "single_page_channel",
      SLIDESHOW: "slideshow",
      SMC_PREONBOARDING_PROMOTIONAL_VIDEO:
        "smc_preonboarding_promotional_video",
      SNOWLIFT: "snowlift",
      SOTTO_AGGREGATED_LIST: "sotto_aggregated_list",
      SOTTO_CATALOG: "sotto_catalog",
      SOTTO_CONSIDERATION_PAGE: "sotto_consideration_page",
      SOTTO_CONSIDERATION_PAGE_BROWSE_SHOWS_SECTION:
        "sotto_consideration_page_browse_shows_section",
      SOTTO_FOLLOWING_SECTION: "sotto_following_section",
      SOTTO_MOVIE: "sotto_movie",
      SOTTO_NONSUBSCRIBER_UPSELL: "sotto_nonsubscriber_upsell",
      SOTTO_PAGE_TOP_CTA: "sotto_page_top_cta",
      SOTTO_SEARCH_RESULT: "sotto_search_result",
      SOTTO_SHOW: "sotto_show",
      SOTTO_SHOWS_FRIENDS_ARE_FOLLOWING_SECTION:
        "sotto_shows_friends_are_following_section",
      SOTTO_WELCOME_MAT: "sotto_welcome_mat",
      SOUNDBITES_FEED_ITEM: "soundbites_feed_item",
      SOUNDBITES_QP: "soundbites_qp",
      SOUNDBITES_TILE: "soundbites_tile",
      SPOTLIGHT_FEATURED: "spotlight_featured",
      SPOTLIGHT_LIVE: "spotlight_live",
      SPOTLIGHT_POPULAR: "spotlight_popular",
      SPOTLIGHT_UNKNOWN: "spotlight_unknown",
      SRT_REVIEW: "srt_review",
      STAGES_WAITING_ROOM_ONDEMAND: "stages_waiting_room_ondemand",
      STARS_ELIGIBLE_CREATOR_ONBOARDING_UPSELL_VIDEO:
        "stars_eligible_creator_onboarding_upsell_video",
      STARS_INELIGIBLE_CREATOR_ONBOARDING_UPSELL_VIDEO:
        "stars_ineligible_creator_onboarding_upsell_video",
      STORES_ACQUISITIONS_RIFU: "stores_acquisitions_rifu",
      STORIES_VIDEO_PREVIEW: "stories_video_preview",
      STORY_TRAY_LIVE_DROPDOWN: "story_tray_live_dropdown",
      STORY_VIEWER_LIVE_CTA: "story_viewer_live_cta",
      STORY_VIEWER_LIVE_DROPDOWN: "story_viewer_live_dropdown",
      STORY_VIEWER_LIVE_STICKER: "story_viewer_live_sticker",
      STORY_VIEWER_LIVE_VIDEO_VIEW: "story_viewer_live_video_view",
      SUBS_SHARE_PROMOTIONAL_VIDEO_PREVIEW:
        "subs_share_promotional_video_preview",
      SUGGESTED_PAGES_TO_FOLLOW_AGG: "suggested_pages_to_follow_agg",
      SUGGESTED_SEARCHES_CUE: "suggested_searches_cue",
      SVR_TOOL: "svr_tool",
      TAHOE: "tahoe",
      TAHOE_COSTREAMING_THUMBNAIL: "tahoe_costreaming_thumbnail",
      TEXT_BASED_VIDEO_EDITOR_ON_COMET: "text_based_video_editor_on_comet",
      THREADS_AUDIO: "threads_audio",
      THREADS_COMPOSER: "threads_composer",
      THREADS_DM_LIGHTBOX: "threads_dm_lightbox",
      THREADS_INLINE: "threads_inline",
      THREADS_LIGHTBOX: "threads_lightbox",
      THREADS_WALL: "threads_wall",
      TIMEPASS: "timepass",
      TOP_10_SHARED_VIDEOS: "top_10_shared_videos",
      TOPIC_ANIMALS: "topic_animals",
      TOPIC_AUDIO: "topic_audio",
      TOPIC_BEAUTY: "topic_beauty",
      TOPIC_CHANNEL_LIVING_ROOM: "topic_channel_living_room",
      TOPIC_CRICKET: "topic_cricket",
      TOPIC_EPHEMERAL_DESTINATION: "topic_ephemeral_destination",
      TOPIC_FEED: "topic_feed",
      TOPIC_FOLLOWING: "topic_following",
      TOPIC_FOLLOWING_CONTINUE_WATCHING: "topic_following_continue_watching",
      TOPIC_FOLLOWING_LATEST: "topic_following_latest",
      TOPIC_FOLLOWING_NOT_WATCHED: "topic_following_not_watched",
      TOPIC_FOOD: "topic_food",
      TOPIC_GAMING: "topic_gaming",
      TOPIC_INTEREST: "topic_interest",
      TOPIC_LIVE: "topic_live",
      TOPIC_MUSIC: "topic_music",
      TOPIC_NEWS: "topic_news",
      TOPIC_SAVED_VIDEOS: "topic_saved_videos",
      TOPIC_SHOWS: "topic_shows",
      TOPIC_SPORTS: "topic_sports",
      TOPICS: "topics",
      TOUCHPOINT_TIP_CREATION_TEST_PLAN: "touchpoint_tip_creation_test_plan",
      TPFC: "tpfc",
      TRAILER_OG_ATTACHMENT: "trailer_og_attachment",
      TRAILER_TIMELINE_COLLECTIONS: "trailer_timeline_collections",
      TRAILER_TIMELINE_UNIT: "trailer_timeline_unit",
      TRANSPARENCY_CONTENT_LIBRARY: "transparency_content_library",
      TRIVIA_GAME_ADMIN_DASHBOARD: "trivia_game_admin_dashboard",
      TV: "tv",
      UFI_COMMENT_ATTACHMENT: "ufi_comment_attachment",
      UNIFIED_EDITOR: "unified_editor",
      UNIFIED_TOFU: "unified_tofu",
      UNKNOWN: "unknown",
      USER_TIMELINE_CHANNEL_TAB_VIDEOS_CARD:
        "user_timeline_channel_tab_videos_card",
      USER_TIMELINE_VIDEO_LIST_AGGREGATION:
        "user_timeline_video_list_aggregation",
      USER_VIDEO_TAB: "user_video_tab",
      VEP_SESSION: "vep_session",
      VEP_WAITING_ROOM: "vep_waiting_room",
      VIDEO_COMPOSER_CROSSPOSTING_REVIEW: "video_composer_crossposting_review",
      VIDEO_COPYRIGHT_PREVIEW: "video_copyright_preview",
      VIDEO_COPYRIGHT_SEGMENT_PREVIEW: "video_copyright_segment_preview",
      VIDEO_HOME_BADGING_SURFACE: "video_home_badging_surface",
      VIDEO_HOME_CATALOG: "video_home_catalog",
      VIDEO_HOME_CHANNEL: "video_home_channel",
      VIDEO_HOME_CHANNEL_TAB_VIDEOS_CARD: "video_home_channel_tab_videos_card",
      VIDEO_HOME_CRICKET: "video_home_cricket",
      VIDEO_HOME_EXPLORE: "discover",
      VIDEO_HOME_EXPLORE_TAB: "explore",
      VIDEO_HOME_INLINE: "video_home_inline",
      VIDEO_HOME_MY_WATCH: "video_home_my_watch",
      VIDEO_HOME_NOTIF_HUB: "notif_hub",
      VIDEO_HOME_PINEAPPLE_HOME: "video_home_pineapple_home",
      VIDEO_HOME_RAINBOW_QP: "video_home_rainbow_qp",
      VIDEO_HOME_THUMBNAIL_PREVIEW: "video_home_thumbnail_preview",
      VIDEO_HOME_TOP_SEARCHED_TV_MOVIES_KEYWORDS:
        "video_home_top_searched_tv_movies_keywords",
      VIDEO_HOME_TV_MOVIES: "video_home_tv_movies",
      VIDEO_HOME_VIDEO_LIST_AGGREGATION: "video_home_video_list_aggregation",
      VIDEO_HOME_VIDEO_NOT_FOUND: "video_home_video_not_found",
      VIDEO_HOME_WATCHLIST: "watchlist",
      VIDEO_INFRA_PORTAL_STARFOX_PLAYGROUND:
        "video_infra_portal_starfox_playground",
      VIDEO_INLINE_CHAINING: "video_inline_chaining",
      VIDEO_INSIGHTS_METADATA_SUMMARY: "video_insights_metadata_summary",
      VIDEO_INSIGHTS_MULTIVIEWER: "video_insights_multiviewer",
      VIDEO_INSIGHTS_OPSVIEW: "video_insights_opsview",
      VIDEO_INSPECTOR: "video_inspector",
      VIDEO_LIST: "video_list",
      VIDEO_LIST_AGGREGATION: "video_list_aggregation",
      VIDEO_LIST_AGGREGATION_PLAYLIST: "video_list_aggregation_playlist",
      VIDEO_LIST_AGGREGATION_SERIES: "video_list_aggregation_series",
      VIDEO_PAGE_SPOTLIGHT_UNIT: "video_page_spotlight_unit",
      VIDEO_PAGE_UNSPECIFIED: "video_page_unspecified",
      VIDEO_PAGE_VIDEO_LIST: "video_page_video_list",
      VIDEO_WALL: "video_wall",
      VIDEOHUB_FEATURED: "videohub_featured",
      VIDEOHUB_LIVE: "videohub_live",
      VIDEOHUB_PLAYLIST: "videohub_playlist",
      VIDEOS_CARD: "videos_card",
      VIDEOS_FEED_UNIT: "videos_feed_unit",
      VIDEOS_TAB: "videos_tab",
      VOICES_PODCAST: "voices_podcast",
      VOTING_INFORMATION_CENTER: "voting_information_center",
      WARION_AGGREGATION: "warion_aggregation",
      WATCH: "watch",
      WATCH_BOOKMARK_PROMOTION_QP: "watch_bookmark_promotion_qp",
      WATCH_CASTING_QP: "watch_casting_qp",
      WATCH_CONTINUE_WATCHING: "watch_continue_watching",
      WATCH_CONTINUE_WATCHING_QP: "watch_continue_watching_qp",
      WATCH_CREATOR_QP: "watch_creator_qp",
      WATCH_EPHEMERAL_DESTINATION_QP: "watch_ephemeral_destination_qp",
      WATCH_EVENT_VIDEO_CREATORS_QP: "watch_event_video_creators_qp",
      WATCH_EXPLORE_SURFACE_FEATURED_CURATION:
        "watch_explore_surface_featured_curation",
      WATCH_EXPLORE_SURFACE_GCU: "watch_explore_surface_gcu",
      WATCH_EXPLORE_SURFACE_INTEREST: "watch_explore_surface_interest",
      WATCH_EXPLORE_SURFACE_NEW_RELEASES_PMV:
        "watch_explore_surface_new_releases_pmv",
      WATCH_EXPLORE_SURFACE_PAGES: "watch_explore_surface_pages",
      WATCH_EXPLORE_SURFACE_POPULAR_PMV: "watch_explore_surface_popular_pmv",
      WATCH_EXPLORE_SURFACE_PYML: "watch_explore_surface_pyml",
      WATCH_EXPLORE_SURFACE_TOP_TEN: "watch_explore_surface_top_ten",
      WATCH_EXPLORE_SURFACE_TRENDING: "watch_explore_surface_trending",
      WATCH_EXPLORE_SURFACE_TRENDING_AUDIO:
        "watch_explore_surface_trending_audio",
      WATCH_EXPLORE_SURFACE_TRENDING_GAMING_LIVESTREAMERS:
        "watch_explore_surface_trending_gaming_livestreamers",
      WATCH_EXPLORE_SURFACE_TRENDING_GAMING_LIVESTREAMS:
        "watch_explore_surface_trending_gaming_livestreams",
      WATCH_EXPLORE_SURFACE_TRENDING_GAMING_VIDEOS:
        "watch_explore_surface_trending_gaming_videos",
      WATCH_EXPLORE_SURFACE_TRENDING_SUBTOPIC:
        "watch_explore_surface_trending_subtopic",
      WATCH_EXPLORE_SURFACE_TVM: "watch_explore_surface_tv_movie",
      WATCH_EXPLORE_TRENDING_REELS_CREATORS:
        "watch_explore_trending_reels_creators",
      WATCH_EXPLORE_TRENDING_UNIT: "watch_explore_trending_unit",
      WATCH_FEED_REELS_HSCROLL: "watch_feed_reels_hscroll",
      WATCH_HASHTAG_REELS_HSCROLL: "watch_hashtag_reels_hscroll",
      WATCH_HISTORY: "watch_history",
      WATCH_LIKED_VIDEOS: "watch_liked_videos",
      WATCH_NULLSTATE_DISCOVERY_GCU: "watch_nullstate_discovery_gcu",
      WATCH_NULLSTATE_DISCOVERY_INTEREST: "watch_nullstate_discovery_interest",
      WATCH_NULLSTATE_DISCOVERY_PYML: "watch_nullstate_discovery_pyml",
      WATCH_ORIGINALS_QP: "watch_originals_qp",
      WATCH_PERMALINK_BOTTOM_SHEET_LANDING:
        "watch_permalink_bottom_sheet_landing",
      WATCH_PERMALINK_BOTTOM_SHEET_VIDEOS:
        "watch_permalink_bottom_sheet_videos",
      WATCH_PERMALINK_HEADER: "watch_permalink_header",
      WATCH_PERMALINK_PROMO_UNIT: "watch_permalink_promo_unit",
      WATCH_PERMALINK_REELS_HSCROLL: "watch_permalink_reels_hscroll",
      WATCH_PREMIUM_CONTENT_QP: "watch_premium_content_qp",
      WATCH_RACIAL_INJUSTICE_QP: "watch_racial_injustice_qp",
      WATCH_RAINBOW_QP: "watch_rainbow_qp",
      WATCH_SCROLL: "watch_scroll",
      WATCH_SEARCH_DISCOVER: "watch_search_discover",
      WATCH_SOTTO_CATALOG_ENTRY_POINT: "watch_sotto_catalog_entry_point",
      WATCH_SOTTO_CATALOG_PROMOTION: "watch_sotto_catalog_promotion",
      WATCH_SUBTOPIC_CHANNEL: "watch_subtopic_channel",
      WATCH_SUGGESTED_PAGES_QP: "watch_suggested_pages_qp",
      WATCH_TOPIC_PILLS_TO_CHANNEL: "watch_topic_pills_to_channel",
      WATCH_TRENDING_CONTENT_VERTICALS_QP:
        "watch_trending_content_verticals_qp",
      WATCH_VIDEO_HIGHLIGHTS_QP: "watch_video_highlights_qp",
      WATCHLIST_AGGREGATION: "watchlist_aggregation",
      WHATSAPP_WEB_CHANNELS: "whatsapp_web_channels",
      WHATSAPP_WEB_STATUS_VIEWER: "whatsapp_web_status_viewer",
      WISP_WEBSITE: "wisp_website",
      WOODHENGE_COMET_SIGNUP: "woodhenge_comet_signup",
      WORK_CAPTIONS_REVIEW: "work_captions_review",
      WORK_CHAPTERS_EDITOR: "work_chapters_editor",
      WORK_EVENTS_BROADCASTS_TAB: "work_events_broadcasts_tab",
      WORK_TOP_OF_FEED_UNIT: "work_top_of_feed_unit",
      WORK_VIDEO_QP: "work_video_qp",
      WORK_WATCH_COLLECTIONS: "work_watch_collections",
      WORK_WATCH_COLLECTIONS_OFFICIAL: "work_watch_collections_official",
      WORK_WATCH_GROUPS: "work_watch_groups",
      WORK_WATCH_GROUPS_ALL: "work_watch_groups_all",
      WORK_WATCH_GROUPS_OUTER: "work_watch_groups_outer",
      WORK_WATCH_GROUPS_POPULAR: "work_watch_groups_popular",
      WORK_WATCH_HOME: "work_watch_home",
      WORK_WATCH_HOME_CAROUSEL: "work_watch_home_carousel",
      WORK_WATCH_HOME_CONTINUE_WATCHING: "work_watch_home_continue_watching",
      WORK_WATCH_HOME_EXPLORE_OTHER_GROUPS:
        "work_watch_home_explore_other_groups",
      WORK_WATCH_HOME_HEAR_ABOUT_LEADERS: "work_watch_home_hear_about_leaders",
      WORK_WATCH_HOME_POPULAR: "work_watch_home_popular",
      WORK_WATCH_HOME_RECENT_FROM_GROUPS: "work_watch_home_recent_from_groups",
      WORK_WATCH_HOME_RECENT_OTHER_GROUPS:
        "work_watch_home_recent_other_groups",
      WORK_WATCH_HOME_RECENTLY_LIVE: "work_watch_home_recently_live",
      WORK_WATCH_HOME_RECENTLY_WATCHED: "work_watch_home_recently_watched",
      WORK_WATCH_HOME_SAVED_VIDEOS: "work_watch_home_saved_videos",
      WORK_WATCH_LIVE: "work_watch_live",
      WORK_WATCH_LIVE_ALL: "work_watch_live_all",
      WORK_WATCH_LIVE_POPULAR: "work_watch_live_popular",
      WORKPLACE_INSIGHTS: "workplace_insights",
    });
    i.default = e;
  },
  66,
);
