__d(
  "AdsCreativeGenAIStringConstants",
  [
    "fbt",
    "AdsCreativeGenAIEligibilityUtils",
    "AdsLearnMore.react",
    "GeoLink.react",
    "GeoPill.react",
    "intlList",
    "react",
  ],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e,
      u = e || (e = o("react")),
      c = "1684513971952814",
      d = "2242593819546848",
      m = s._(/*BTDS*/ "AI"),
      p = s._(/*BTDS*/ "Meta AI"),
      _ = function (t) {
        return s._(/*BTDS*/ "{Meta AI ring icon}{Meta AI label}", [
          s._param("Meta AI ring icon", t),
          s._param("Meta AI label", p),
        ]);
      },
      f = s._(/*BTDS*/ "Continue"),
      g = s._(/*BTDS*/ "Restoring the previous variation..."),
      h = s._(/*BTDS*/ "Select all"),
      y = s._(/*BTDS*/ "Images generated by AI"),
      C = s._(/*BTDS*/ "Images from your destination URL"),
      b = s._(/*BTDS*/ "Ad account and catalog images"),
      v = s._(/*BTDS*/ "Replace image"),
      S = s._(/*BTDS*/ "Delete image"),
      R = s._(/*BTDS*/ "Generate videos");
    function L(e) {
      return s._(
        /*BTDS*/ '_j{"*":"Generate {number of selected videos} videos","_1":"Generate {number of selected videos} video"}',
        [s._plural(e), s._param("number of selected videos", e)],
      );
    }
    L.displayName = L.name + " [from " + i.id + "]";
    var E = s._(/*BTDS*/ "About video generation"),
      k = s._(/*BTDS*/ "These images will be used to create your videos."),
      I = s._(/*BTDS*/ "Image generation"),
      T = s._(/*BTDS*/ "Creative generation"),
      D = s._(/*BTDS*/ "Generated with AI"),
      x = s._(/*BTDS*/ "View terms"),
      $ =
        "https://www.facebook.com/legal/terms/ad_creative_generative_ai_terms",
      P = s._(
        /*BTDS*/ "This result is based on an experiment run between Dec 13, 2025 and Dec 16, 2025. It looked at 1.2 million ad groups across all industries and regions. The experiment showed that campaigns that used Advantage+ creative image generation for all ads saw 10\u0025 higher clickthrough rates and 6\u0025 higher conversion rates compared to those that did not. Results may vary.",
      ),
      N = "1413299579708509";
    function M(e) {
      return s._(
        /*BTDS*/ '_j{"*":"Accept {number of selected videos} videos","_1":"Accept {number of selected videos} video"}',
        [s._plural(e), s._param("number of selected videos", e)],
      );
    }
    M.displayName = M.name + " [from " + i.id + "]";
    function w(e) {
      var t = s._(/*BTDS*/ "Learn about image generation in Ads Manager");
      return s._(
        /*BTDS*/ "Image variations are generated with AI inspired by your original asset. Adding more image options to your ad can help customize your creative and reduce creative fatigue which can help increase performance. {link to learn more about generative AI image generation feature}",
        [
          s._param(
            "link to learn more about generative AI image generation feature",
            u.jsx(r("AdsLearnMore.react"), {
              cmsID: c,
              isStandalone: !0,
              label: t,
              onClick: e,
            }),
          ),
        ],
      );
    }
    w.displayName = w.name + " [from " + i.id + "]";
    var A = s._(/*BTDS*/ "Creative generation");
    function F(e) {
      var t = s._(/*BTDS*/ "Learn about creative generation in Ads Manager");
      return s._(
        /*BTDS*/ "Creative variations are generated with AI inspired by your original asset. Adding more creative options to your ad can help customize your creative and reduce creative fatigue which can help increase performance. {link to learn more about the generative AI creative generation feature}",
        [
          s._param(
            "link to learn more about the generative AI creative generation feature",
            u.jsx(r("AdsLearnMore.react"), {
              cmsID: c,
              isStandalone: !0,
              label: t,
              onClick: e,
            }),
          ),
        ],
      );
    }
    F.displayName = F.name + " [from " + i.id + "]";
    var O = s._(
      /*BTDS*/ "Meta does not make any warranties regarding the completeness, reliability and accuracy of creative generation.",
    );
    function B(e) {
      return s._(
        /*BTDS*/ "Videos are generated with AI from the images in your ad account, destination images we generate or the ones you upload. They showcase your product or services with narratives, are automatically tailored for each placement, and can help keep your ads fresh. {link to learn more about generative AI image generation feature}",
        [
          s._param(
            "link to learn more about generative AI image generation feature",
            u.jsx(r("AdsLearnMore.react"), {
              cmsID: d,
              isStandalone: !0,
              label: E,
              onClick: e,
            }),
          ),
        ],
      );
    }
    B.displayName = B.name + " [from " + i.id + "]";
    function W(e) {
      return s._(
        /*BTDS*/ "Upload as many images as you like. Clear product images, along with lifestyle images can improve video quality. We may not use all images when generating videos. {link to learn more about generative AI image generation feature}",
        [
          s._param(
            "link to learn more about generative AI image generation feature",
            u.jsx(r("AdsLearnMore.react"), {
              cmsID: d,
              isStandalone: !0,
              label: E,
              onClick: e,
            }),
          ),
        ],
      );
    }
    W.displayName = W.name + " [from " + i.id + "]";
    function q(e) {
      return s._(/*BTDS*/ "+ {number of selected assets} more", [
        s._param("number of selected assets", e),
      ]);
    }
    q.displayName = q.name + " [from " + i.id + "]";
    function U(e) {
      return s._(/*BTDS*/ "Recommended: {scene_type}", [
        s._param("scene_type", e),
      ]);
    }
    U.displayName = U.name + " [from " + i.id + "]";
    var V = s._(
        /*BTDS*/ "Meta does not make any warranties regarding the completeness, reliability and accuracy of image generation.",
      ),
      H = s._(/*BTDS*/ "Try it out"),
      G = s._(/*BTDS*/ "Advantage+ creative image generation"),
      z = function () {
        return s._(
          /*BTDS*/ "In our experiment, campaigns with all ads adding AI-generated images saw {percentage of Click-Through-Rate in \u003CGeoPill> component} and {percentage of CVR lift in \u003CGeoPill> component}",
          [
            s._param(
              "percentage of Click-Through-Rate in <GeoPill> component",
              u.jsx(r("GeoPill.react"), {
                label: s._(/*BTDS*/ "10\u0025 CTR lift"),
                status: "success",
                value: "10% CTR lift",
              }),
            ),
            s._param(
              "percentage of CVR lift in <GeoPill> component",
              u.jsx(r("GeoPill.react"), {
                label: s._(/*BTDS*/ "6\u0025 CVR lift"),
                status: "success",
                value: "6% CVR lift",
              }),
            ),
          ],
        );
      },
      j = s._(/*BTDS*/ ""),
      K = s._(/*BTDS*/ "Upload image"),
      Q = s._(/*BTDS*/ "Analyzing your image..."),
      X = s._(/*BTDS*/ "Edit"),
      Y = s._(/*BTDS*/ "Review and select"),
      J = s._(/*BTDS*/ "Review"),
      Z = function () {
        return s._(
          /*BTDS*/ "Some edits couldn't be applied. Make your edits again, then select {=m2} to save them",
          [
            s._implicitParam(
              "=m2",
              u.jsx("b", { children: s._(/*BTDS*/ "Apply all edits") }),
            ),
          ],
        );
      },
      ee = function () {
        return s._(
          /*BTDS*/ 'Voiceover edits couldn\'t be applied. Make your edits again, then select "Apply all edits" to save them',
        );
      },
      te = function () {
        return s._(/*BTDS*/ "{=m0} couldn't be applied", [
          s._implicitParam(
            "=m0",
            u.jsx("b", { children: s._(/*BTDS*/ "Music") }),
          ),
        ]);
      },
      ne = function () {
        return s._(/*BTDS*/ "{=m0} couldn't be applied in", [
          s._implicitParam(
            "=m0",
            u.jsx("b", { children: s._(/*BTDS*/ "Text") }),
          ),
        ]);
      },
      re = function () {
        return s._(/*BTDS*/ "{=m0} couldn't be applied in", [
          s._implicitParam(
            "=m0",
            u.jsx("b", { children: s._(/*BTDS*/ "Font") }),
          ),
        ]);
      },
      oe = s._(/*BTDS*/ "couldn't be removed"),
      ae = function (t) {
        return s._(/*BTDS*/ "Clip {clip index}", [
          s._param("clip index", t.toString()),
        ]);
      },
      ie = function (t) {
        return s._(/*BTDS*/ "{intl join of clip prefixes}", [
          s._param("intl join of clip prefixes", r("intlList")(t.map(ae))),
        ]);
      },
      le = function (t, n) {
        return s._(/*BTDS*/ "{error code text} {intl join of clip prefixes}", [
          s._param("error code text", t),
          s._param("intl join of clip prefixes", ie(n)),
        ]);
      },
      se = function (t, n) {
        return s._(/*BTDS*/ "{intl join of clip prefixes} {error code text}", [
          s._param("intl join of clip prefixes", ie(n)),
          s._param("error code text", t),
        ]);
      },
      ue = function (t, n) {
        var e,
          r,
          o,
          a = [
            t.includes("MUSIC_EDIT_ERROR") ? te() : null,
            n.has("TEXT_OVERLAY_ERROR")
              ? le(ne(), (e = n.get("TEXT_OVERLAY_ERROR")) != null ? e : [])
              : null,
            n.has("FONT_ERROR")
              ? le(re(), (r = n.get("FONT_ERROR")) != null ? r : [])
              : null,
            n.has("DELETE_ERROR")
              ? se(oe, (o = n.get("DELETE_ERROR")) != null ? o : [])
              : null,
          ];
        return a.filter(function (e) {
          return e != null;
        });
      },
      ce = s._(/*BTDS*/ "Examples"),
      de = s._(/*BTDS*/ "[Meta-Only] Debugger"),
      me = s._(/*BTDS*/ "Text"),
      pe = s._(
        /*BTDS*/ "Add multiple text options and we'll show the one we predict will perform best when your ad is delivered.",
      ),
      _e = s._(/*BTDS*/ "Generate new images"),
      fe = s._(
        /*BTDS*/ "[FB-Only] Image Generation is ineligible for your ad setup.",
      ),
      ge = s._(
        /*BTDS*/ "[FB-Only] Video Generation is ineligible for your ad setup.",
      ),
      he = s._(
        /*BTDS*/ "[FB-Only] Image Generation is ineligible due to link data missing.",
      ),
      ye = s._(
        /*BTDS*/ "[FB-Only] Video Generation is ineligible due to link data missing.",
      ),
      Ce = s._(
        /*BTDS*/ "[FB-Only] Video Generation is ineligible for optimization goal.",
      ),
      be = s._(
        /*BTDS*/ "[FB-Only] Image Generation is incompatible with DCO\/DLO ad product.",
      ),
      ve = s._(
        /*BTDS*/ "[FB-Only] Video Generation is incompatible with DCO\/DLO ad product.",
      ),
      Se = s._(
        /*BTDS*/ "[FB-Only] Image Generation is incompatible with ad with special category.",
      ),
      Re = s._(
        /*BTDS*/ "[FB-Only] Video Generation is incompatible with ad with special category.",
      ),
      Le = s._(
        /*BTDS*/ "[FB-Only] Image Generation is ineligible for advertisers in sensitive verticals.",
      ),
      Ee = s._(
        /*BTDS*/ "[FB-Only] Video Generation is ineligible for advertisers in sensitive verticals.",
      ),
      ke = s._(
        /*BTDS*/ "[FB-Only] Image Generation is ineligible for advertisers in trust tier 0 and 1",
      ),
      Ie = s._(
        /*BTDS*/ "[FB-Only] Video Generation is ineligible for advertisers in trust tier 0 and 1",
      ),
      Te = s._(
        /*BTDS*/ "[FB-Only] Image Generation is incompatible with Automatic App Ads and Flexible Format Ads.",
      ),
      De = s._(
        /*BTDS*/ "[FB-Only] Video Generation is incompatible with Automatic App Ads and Flexible Format Ads.",
      ),
      xe = s._(
        /*BTDS*/ "[FB-Only] Image Generation is incompatible with Shop Ads.",
      ),
      $e = s._(
        /*BTDS*/ "[FB-Only] Video Generation is incompatible with Shop Ads.",
      ),
      Pe = s._(
        /*BTDS*/ "[FB-Only] Image Generation is eligible for static single image ads only.",
      ),
      Ne = s._(
        /*BTDS*/ "[FB-Only] Video Generation is eligible for static single image ads only.",
      );
    function Me(e) {
      switch (e) {
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .DCO_OR_DLO_AD:
          return be;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .AAA_OR_FLEXIBLE_FORMAT_AD:
          return Te;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .REGULATED_CATEGORY:
          return Se;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .TRUST_TIER_AD_ACCOUNT:
          return ke;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .SHOP_AD:
          return xe;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .SENSITIVE_AD_ACCOUNT_VERTICAL:
          return Le;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .NOT_STATIC_SINGLE_IMAGE_AD:
          return Pe;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .NO_LINK_DATA:
          return he;
        default:
          return fe;
      }
    }
    function we(e) {
      switch (e) {
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .DCO_OR_DLO_AD:
          return ve;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .AAA_OR_FLEXIBLE_FORMAT_AD:
          return De;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .REGULATED_CATEGORY:
          return Re;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .TRUST_TIER_AD_ACCOUNT:
          return Ie;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .SHOP_AD:
          return $e;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .SENSITIVE_AD_ACCOUNT_VERTICAL:
          return Ee;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .NOT_STATIC_SINGLE_IMAGE_AD:
          return Ne;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .NO_LINK_DATA:
          return ye;
        case o("AdsCreativeGenAIEligibilityUtils").GenAIEntryIneligiblityReason
          .NON_ELIGIBLE_OPTIMIZATION_GOAL_FOR_VIDEO_GEN:
          return Ce;
        default:
          return ge;
      }
    }
    var Ae = "https://transparency.meta.com/policies/ad-standards/",
      Fe = "https://www.facebook.com/business/help/1749703022274336",
      Oe = function () {
        return s._(/*BTDS*/ "{About branding}", [
          s._param(
            "About branding",
            u.jsx(r("GeoLink.react"), {
              href: Fe,
              target: "_blank",
              children: s._(/*BTDS*/ "About branding"),
            }),
          ),
        ]);
      },
      Be = s._(
        /*BTDS*/ "We can automatically source branding from URLs you\u2019ve previously used, previous ads, information from your Facebook Page and your Shopify account. We\u2019ll match the fonts and colors we find to the most relevant available options. You can edit or turn this off at any time. {About branding}",
        [s._param("About branding", Oe())],
      ),
      We = function () {
        return s._(
          /*BTDS*/ "{Advertiser Standards} apply to edits you make. Results from image generation may vary.",
          [
            s._param(
              "Advertiser Standards",
              u.jsx(r("GeoLink.react"), {
                href: Ae,
                target: "_blank",
                children: s._(/*BTDS*/ "Advertising Standards"),
              }),
            ),
          ],
        );
      },
      qe = s._(/*BTDS*/ "Advantage+ creative video generation"),
      Ue = s._(/*BTDS*/ "Select images for your video"),
      Ve = s._(/*BTDS*/ "All video variations"),
      He = s._(/*BTDS*/ "Video generation"),
      Ge = s._(/*BTDS*/ "Images"),
      ze = s._(/*BTDS*/ "Music"),
      je = s._(/*BTDS*/ "Music Opt-in Switch"),
      Ke = s._(/*BTDS*/ "Clips"),
      Qe = s._(/*BTDS*/ "Add clip"),
      Xe = s._(/*BTDS*/ "Apply all edits"),
      Ye = s._(/*BTDS*/ "Undo changes"),
      Je = s._(/*BTDS*/ "Undo applied changes"),
      Ze = s._(/*BTDS*/ "Select a music track"),
      et = s._(/*BTDS*/ "Back to video generation"),
      tt = s._(/*BTDS*/ "Back to video variations"),
      nt = s._(/*BTDS*/ "Applying edits... This may take up to 2 minutes."),
      rt = s._(/*BTDS*/ "Upload more images to generate better videos"),
      ot = s._(
        /*BTDS*/ "We weren't able to find or access other images from your ad account and destination. To generate better videos, upload at least 5 images that highlight your product or service.",
      ),
      at = function () {
        return s._(
          /*BTDS*/ "{=m0} This image may lower the quality of your generated videos. For better results, upload an image with minimal text or overlays. {Images in video generation}",
          [
            s._param(
              "Images in video generation",
              u.jsx(r("GeoLink.react"), {
                href: Ae,
                target: "_blank",
                children: s._(/*BTDS*/ "About images in video generation"),
              }),
            ),
            s._implicitParam(
              "=m0",
              u.jsx("b", { children: s._(/*BTDS*/ "Low quality image") }),
            ),
          ],
        );
      },
      it = s._(
        /*BTDS*/ "Select at least 5 images to generate higher quality videos.",
      ),
      lt = s._(/*BTDS*/ "Voiceover"),
      st = s._(/*BTDS*/ "Stay on page"),
      ut = s._(
        /*BTDS*/ "Are you sure you want to go back? You haven't selected any images.",
      ),
      ct = s._(
        /*BTDS*/ "You'll need to select at least 1 image to generate videos.",
      ),
      dt = s._(/*BTDS*/ "Generating concepts failed"),
      mt = s._(/*BTDS*/ "Try again"),
      pt = s._(
        /*BTDS*/ "This result is based on an A\/B test run Dec 21, 2025 - Jan 3, 2026 on over 130,000 ads globally across regions and advertiser verticals where the beta product is available. The test compared advertisers who used the beta product against those who did not. Results may vary.",
      ),
      _t = s._(/*BTDS*/ "Adjust video settings"),
      ft = s._(/*BTDS*/ "Change the images used in your videos"),
      gt = s._(/*BTDS*/ "Customize"),
      ht = s._(/*BTDS*/ "1.9\u0025 CTR lift"),
      yt = s._(/*BTDS*/ "3.2\u0025 CVR lift"),
      Ct = s._(/*BTDS*/ "You"),
      bt = s._(/*BTDS*/ "Similar brands"),
      vt = s._(/*BTDS*/ "Ads with images & videos"),
      St = s._(/*BTDS*/ "Ads with only images");
    function Rt(e) {
      return s._(/*BTDS*/ "{pct}\u0025 video ads", [s._param("pct", e)]);
    }
    Rt.displayName = Rt.name + " [from " + i.id + "]";
    function Lt(e, t) {
      return s._(/*BTDS*/ "{val}\u0025 {metricName}", [
        s._param("val", e),
        s._param("metricName", t),
      ]);
    }
    Lt.displayName = Lt.name + " [from " + i.id + "]";
    function Et(e, t) {
      return s._(/*BTDS*/ "{value} {metricName}", [
        s._param("value", e),
        s._param("metricName", t),
      ]);
    }
    Et.displayName = Et.name + " [from " + i.id + "]";
    function kt(e) {
      return s._(
        /*BTDS*/ "Brands similar to yours run more video ads and see {metricLift}",
        [s._param("metricLift", e)],
      );
    }
    kt.displayName = kt.name + " [from " + i.id + "]";
    function It(e) {
      return s._(/*BTDS*/ "You could get up to {metricLift} with videos", [
        s._param("metricLift", e),
      ]);
    }
    It.displayName = It.name + " [from " + i.id + "]";
    var Tt = s._(/*BTDS*/ "34.5\u0025 CPA drop");
    function Dt(e) {
      return s._(
        /*BTDS*/ "Advertisers that use 9:16 video ads with audio on Reels see up to a {metricDrop} when compared to using image ads.",
        [s._param("metricDrop", e)],
      );
    }
    ((Dt.displayName = Dt.name + " [from " + i.id + "]"),
      (l.CMS_GEN_AI_VIDEO_GEN = d),
      (l.GEN_AI_BADGE_NAME = m),
      (l.GEN_AI_META_AI_BADGE_NAME = p),
      (l.getGenAIMetaAIPillValue = _),
      (l.COMMON_CONTINUE = f),
      (l.VIDEO_GEN_LOADING_DESCRIPTION_UNDO = g),
      (l.SELECT_ALL_VARIATIONS = h),
      (l.GENERATED_IMAGES_GROUP_TITLE = y),
      (l.DESTINATION_IMAGES_GROUP_TITLE = C),
      (l.CATALOG_IMAGES_GROUP_TITLE = b),
      (l.REPLACE_IMAGE_BUTTON_LABEL = v),
      (l.DELETE_IMAGE_BUTTON_LABEL = S),
      (l.GENERATE_VIDEOS_BUTTON_LABEL = R),
      (l.getGenerateVideosButtonLabel = L),
      (l.POSTGEN_SELECTION_DESCRIPTION = k),
      (l.GEN_AI_IMAGE_GEN_FEATURE_NAME = I),
      (l.GEN_AI_CREATIVE_GEN_FEATURE_NAME = T),
      (l.GEN_AI_IMAGE_GEN_POPOVER_HEADER = D),
      (l.GEN_AI_AD_CREATIVE_VIEW_TERMS_LABEL = x),
      (l.GEN_AI_AD_CREATIVE_TERMS_OF_USE_URL = $),
      (l.GEN_AI_INSIGHT_PANEL_TOOLTIP = P),
      (l.GEN_AI_A_PLUS_C_LEARN_ABOUT_CMS_ID = N),
      (l.getGenAIPrimaryButtonTextForSelectVideos = M),
      (l.getGenAIImageGenPopoverBodyContent = w),
      (l.GEN_AI_MEDIA_GEN_FEATURE_NAME = A),
      (l.getGenAIMediaGenPopoverBodyContent = F),
      (l.GEN_AI_MEDIA_GEN_POPOVER_DISCLAIMER = O),
      (l.getGenAIVideoGenPopoverBodyContent = B),
      (l.getGenAIVideoGenInputMediaSelectionsHeaderTooltip = W),
      (l.getMoreAssetsContent = q),
      (l.getReplaceImageSceneTypeText = U),
      (l.GEN_AI_IMAGE_GEN_POPOVER_DISCLAIMER = V),
      (l.GEN_AI_ENTRYPOINT_BUTTON_LABEL = H),
      (l.GEN_AI_MODAL_AUTO_GEN_HEADER = G),
      (l.getStylesGenAiModalImageGenInsight = z),
      (l.GEN_AI_EMPTY_STRING = j),
      (l.GEN_AI_MODAL_ASSET_PICKER_FILE_UPLAODER_BUTTON_LABEL = K),
      (l.GEN_AI_MEDIA_VARIATIONS_ANALYZING_STATE = Q),
      (l.EDIT_BUTTON_TEXT = X),
      (l.GEN_AI_REVIEW_CTA = Y),
      (l.GEN_AI_VIDEO_GEN_REVIEW_CTA = J),
      (l.GEN_AI_VIDEO_GEN_EDIT_VIDEO_ERROR_TITLE = Z),
      (l.GEN_AI_VIDEO_GEN_EDIT_VIDEO_VOICEOVER_ERROR_TITLE = ee),
      (l.makeErrorFBTsFromVideoAndSceneEditingErrorCodes = ue),
      (l.GEN_AI_HERO_EXAMPLE_POPOVER_SECONDARY_HEADER = ce),
      (l.GENI_AI_DEBUGGER_TOGGLE = de),
      (l.GEN_AI_TEXT_GENERATION_IN_CES_HEADER = me),
      (l.GEN_AI_TEXT_GENERATION_IN_CES_DESCRIPTION = pe),
      (l.GEN_AI_REGENERATION_SECTION_BUTTON_LABEL = _e),
      (l.GEN_AI_INCOMPATIBLE_GENERIC_MESSAGE = fe),
      (l.getInternalEntryDisabledMessage = Me),
      (l.getVideoGenInternalEntryDisabledMessage = we),
      (l.GEN_AI_ADVERTISER_ABOUT_BRANDING_LINK = Oe),
      (l.GENERATIVE_AI_BRANDING_TOOLTIP_CONTENT = Be),
      (l.getFluxEditAdvertisingStandardsDisclaimer = We),
      (l.GEN_AI_MODAL_VIDEO_GEN_HEADER = qe),
      (l.GEN_AI_MODAL_VIDEO_GEN_HEADER_EDIT_IMAGE_SELECTION = Ue),
      (l.GEN_AI_MODAL_VIDEO_GEN_HEADER_EDIT_INDIVIDUAL_VIDEO = Ve),
      (l.GEN_AI_VIDEO_GEN_FEATURE_NAME = He),
      (l.GEN_AI_VIDEO_GEN_VIDEO_VARIANTS_INPUT_IMAGE_HEADER = Ge),
      (l.GEN_AI_VIDEO_MUSIC_TITLE = ze),
      (l.GEN_AI_VIDEO_MUSIC_OPT_IN_SWITCH_LABEL = je),
      (l.GEN_AI_VIDEO_CLIPS_TITLE = Ke),
      (l.GEN_AI_VIDEO_ADD_CLIP_TITLE = Qe),
      (l.GEN_AI_VIDEO_APPLY_ALL_EDITS_TITLE = Xe),
      (l.GEN_AI_VIDEO_UNDO_CHANGES_TITLE = Ye),
      (l.GEN_AI_VIDEO_UNDO_APPLIED_CHANGES_TITLE = Je),
      (l.GEN_AI_VIDEO_GEN_MUSIC_DROPDOWN_PLACEHOLDER = Ze),
      (l.GEN_AI_VIDEO_GEN_EDIT_MEDIA_BACK_BUTTON_LABEL = et),
      (l.GEN_AI_VIDEO_GEN_EDIT_VIDEO_BACK_BUTTON_LABEL = tt),
      (l.GEN_AI_VIDEO_LOADING_REGEN_PRIMARY_DESCRIPTION = nt),
      (l.GEN_AI_VIDEO_GEN_UPLOAD_MORE_IMAGE_HEADER = rt),
      (l.GEN_AI_VIDEO_GEN_UPLOAD_MORE_IMAGE_MESSAGE = ot),
      (l.GEN_AI_VIDEO_GEN_LOW_QUALITY_IMAGE_WARNING = at),
      (l.GEN_AI_VIDEO_GEN_SELECT_ASSETS_WARNING_CARD = it),
      (l.VOICEOVER_LABEL = lt),
      (l.MEDIA_SELECTION_MODAL_STAY_ON_PAGE = st),
      (l.GEN_AI_VIDEO_GEN_SELECT_ASSETS_MODAL_HEADER = ut),
      (l.GEN_AI_VIDEO_GEN_SELECT_ASSETS_MODAL_DESCRIPTION = ct),
      (l.GEN_AI_VIDEO_GEN_CONCEPT_FAILED_TITLE = dt),
      (l.GEN_AI_VIDEO_GEN_CONCEPT_FAILED_BUTTON_LABEL = mt),
      (l.GEN_AI_VIDEO_GEN_PRE_LOADING_SCREEN_INSIGHT_TOOLTIP = pt),
      (l.GEN_AI_VIDEO_GEN_CUSTOMIZE_CARD_TITLE = _t),
      (l.GEN_AI_VIDEO_GEN_CUSTOMIZE_CARD_DESCRIPTION = ft),
      (l.GEN_AI_VIDEO_GEN_CUSTOMIZE_BUTTON_LABEL = gt),
      (l.GEN_AI_VIDEO_GEN_SIDE_PANE_CTR_PILL_LABEL = ht),
      (l.GEN_AI_VIDEO_GEN_SIDE_PANE_CVR_PILL_LABEL = yt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_YOU_LABEL = Ct),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_SIMILAR_BRANDS_LABEL = bt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_VIDEO_LABEL = vt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_IMAGE_ONLY_LABEL = St),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_VIDEO_ADS_PCT = Rt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_METRIC_PILL = Lt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_COMP_HEADLINE_VALUE = Et),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_COMP_HEADLINE = kt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_OWN_VIDEO_HEADLINE = It),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_REELS_CPA_DROP = Tt),
      (l.GEN_AI_VIDEO_GEN_INSIGHTS_REELS_HEADLINE = Dt));
  },
  226,
);
