__d(
  "WAWebGettersCaches",
  [
    "WAWebABProps",
    "WAWebDummyCacheMap",
    "WAWebEnvironment",
    "WAWebLruCacheMap",
  ],
  function (t, n, r, o, a, i, l) {
    var e = function () {
        var e = o("WAWebABProps").getABPropConfigValue(
          "web_getters_lru_cache_size_limit",
        );
        return e > 0
          ? new (o("WAWebLruCacheMap").LruCacheMap)({ sizeLimit: e })
          : r("WAWebEnvironment").isWindows
            ? new (o("WAWebDummyCacheMap").FakeCacheMap)()
            : new Map();
      },
      s = function () {
        return e();
      },
      u = function () {
        var e = o("WAWebABProps").getABPropConfigValue(
          "web_getters_lru_cache_size_limit",
        );
        return e > 0
          ? new (o("WAWebLruCacheMap").LruCacheMap)({ sizeLimit: e })
          : new Map();
      },
      c = s,
      d = s,
      m = s,
      p = s,
      _ = u,
      f = u,
      g = s,
      h = s,
      y = s,
      C = s,
      b = s,
      v = s,
      S = s,
      R = s,
      L = s,
      E = s,
      k = s,
      I = s,
      T = s,
      D = s,
      x = s,
      $ = s,
      P = s,
      N = s,
      M = s,
      w = s,
      A = s,
      F = s,
      O = s,
      B = s,
      W = s,
      q = s,
      U = s,
      V = s,
      H = s,
      G = s,
      z = s,
      j = s,
      K = s,
      Q = s,
      X = s,
      Y = s,
      J = s,
      Z = s,
      ee = s,
      te = s,
      ne = s,
      re = s,
      oe = s,
      ae = s,
      ie = s,
      le = s,
      se = s,
      ue = s,
      ce = s;
    ((l.createMessagesCache = c),
      (l.createFrontendMessagesCache = d),
      (l.createChatCache = m),
      (l.createFrontendChatCache = p),
      (l.createContactsCache = _),
      (l.createFrontendContactsCache = f),
      (l.createLabelsCache = g),
      (l.createMuteCache = h),
      (l.createPinInChatsCache = y),
      (l.createFrontendPinInChatsCache = C),
      (l.createMsgInfosCache = b),
      (l.createPollVotesCache = v),
      (l.createFrontendPollVotesCache = S),
      (l.createNewsletterPollVotesCache = R),
      (l.createFrontendNewsletterPollVotesCache = L),
      (l.createSettingsCache = E),
      (l.createStickerModelMdCache = k),
      (l.createMediaEditControllerCache = I),
      (l.createOrderCache = T),
      (l.createOrderItemCache = D),
      (l.createQuickReplyCache = x),
      (l.createFrontendQuickReplyCache = $),
      (l.createStatusCache = P),
      (l.createFrontendStatusCache = N),
      (l.createRecordingSessionCache = M),
      (l.createEventResponseCache = w),
      (l.createFrontendEventResponseCache = A),
      (l.createCartCache = F),
      (l.createCatalogCache = O),
      (l.createFrontendCatalogCache = B),
      (l.createUnjoinedSubgroupMetadataCache = W),
      (l.createPresenceCache = q),
      (l.createReactionsSendersCache = U),
      (l.createNewsletterMetadataCache = V),
      (l.createFrontendNewsletterMetadataCache = H),
      (l.createNewsletterLoadingStageManagerCache = G),
      (l.createBusinessProfileCache = z),
      (l.createFrontendBusinessProfileCache = j),
      (l.createCommandCache = K),
      (l.createPrimaryFeaturesCache = Q),
      (l.createPttPrefsCache = X),
      (l.createNoticeCache = Y),
      (l.createBizBroadcastCampaignCache = J),
      (l.createProfilePicThumbCache = Z),
      (l.createAttachMediaCache = ee),
      (l.createFrontendAttachMediaCache = te),
      (l.createConnCache = ne),
      (l.createStreamCache = re),
      (l.createNewsletterAdminInsightsCache = oe),
      (l.createCommentCache = ae),
      (l.createFrontendCommentCache = ie),
      (l.createGroupMetadataCache = le),
      (l.createFrontendGroupMetadataCache = se),
      (l.createTextStatusCache = ue),
      (l.createFrontendTextStatusCache = ce));
  },
  98,
);
