__d(
  "AdsMessengerWelcomeMessageFields",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      AD_ACCOUNT_ID: "ad_account_id",
      AUTOFILL_MESSAGE_EDITED: "autofill_message_edited",
      AUTO_FOLLOW_UP_MESSAGE_EDITED: "auto_follow_up_message_edited",
      NONE: "none",
      IMAGE_FORMAT: "image_format",
      INTRO_TEXT: "intro_text",
      LANDING_SCREEN_TYPE: "landing_screen_type",
      MEDIA_TYPE: "media_type",
      MESSAGE: "message",
      TEMPLATE_ID: "template_id",
      CTM_LEAD_GEN_TEMPLATE_ID: "ctm_lead_gen_template_id",
      TEXT_FORMAT: "text_format",
      TYPE: "type",
      USER_EDIT: "user_edit",
      VERSION: "version",
      VIDEO_FORMAT: "video_format",
      SURFACE: "surface",
      AUDIENCE: "audience",
      ICE_BREAKERS: "ice_breakers",
      QUICK_REPLIES: "quick_replies",
      CUSTOMER_ACTION_TYPE: "customer_action_type",
      IS_VISIBLE: "is_visible",
      IS_ELIGIBLE_FOR_CUSTOMIZED_GREETING:
        "is_eligible_for_customized_greeting",
      TEMPLATE_VERSION: "template_version",
      MESSAGE_DATA: "message_data",
      RECEIVING_APP_ID: "receiving_app_id",
      DEEPLINK_PAYLOAD: "deeplink_payload",
      IN_THREAD_CAROUSEL: "in_thread_carousel",
      IN_THREAD_MULTIPHOTO_CAROUSEL: "in_thread_multiphoto_carousel",
      TEXT: "text",
      IS_LEAD_GEN_MULTI_CHANNEL: "is_lead_gen_multi_channel",
      IS_CTM_IN_THREAD_1P: "is_ctm_in_thread_1p",
      PHONE_NUMBER: "phone_number",
      PRODUCT_INFO: "product_info",
      BANNER_CTA_TYPE: "banner_cta_type",
      AUTOFILL_MESSAGE: "autofill_message",
      CALL_PROMPT_DATA: "call_prompt_data",
      WELCOME_MESSAGE_EDITED: "welcome_message_edited",
      ICE_BREAKERS_EDITED: "ice_breakers_edited",
      IS_RTC_ENABLED: "is_rtc_enabled",
      IS_CALL_PROMPT_ENABLED: "is_call_prompt_enabled",
      CALL_PROMPT_MESSAGE: "call_prompt_message",
      IS_BIC_CALL_PROMPT_ENABLED: "is_bic_call_prompt_enabled",
      IS_WARM_CALL_PROMPT_ENABLED: "is_warm_call_prompt_enabled",
      ORIGINAL_LEAD_FORM_ID: "original_lead_form_id",
      CONTENT: "content",
      AUTO_REPLY: "auto_reply",
      AUTO_FOLLOW_UP: "auto_follow_up",
      AUTO_FOLLOW_UP_DISABLED: "auto_follow_up_disabled",
      WHATSAPP_FLOW_EDITED: "whatsapp_flow_edited",
      WHATSAPP_FLOW: "whatsapp_flow",
      HAS_AI_GENERATED_WELCOME_MESSAGE: "has_ai_generated_welcome_message",
      AI_GENERATED_WELCOME_MESSAGE_IMPRESSION:
        "ai_generated_welcome_message_impression",
      AI_GENERATED_ICEBREAKER_TOGGLE_ENABLED:
        "ai_generated_icebreaker_toggle_enabled",
      AI_GENERATED_ICEBREAKER_IMPRESSION: "ai_generated_icebreaker_impression",
      RECONSIDERATION: "reengagement",
      RECONSIDERATION_DISABLED: "reengagement_disabled",
      IG_BOOST_CTX_CONVO_STARTER_UPDATE_STATUS:
        "ig_boost_ctx_convo_starter_update_status",
      AUTOMATED_GREETING_MESSAGE_CTA: "automated_greeting_message_cta",
      PERFORMANCE_BOOSTER_ENABLED: "performance_booster_enabled",
      CTM_DEPRECATE_QUICK_REPLIES_ENABLED:
        "ctm_deprecate_quick_replies_enabled",
      IS_USER_EDITING: "is_user_editing",
      SHOW_NONE_ACTION_GUIDANCE_CARD: "show_none_action_guidance_card",
      SHOW_CONVERTED_QUICK_REPLIES_TO_ICEBREAKERS_GUIDANCE_CARD:
        "show_converted_quick_replies_to_icebreakers_guidance_card",
      LWI_WEB_AI_GENERATED_ICEBREAKERS_ENABLED:
        "lwi_web_ai_generated_icebreakers_enabled",
      IS_ELIGIBLE_FOR_LEVERAGING_INBOX_FAQS:
        "is_eligible_for_leveraging_inbox_faqs",
      IS_ELIGIBLE_FOR_AI_GENERATED_ICEBREAKERS:
        "is_eligible_for_ai_generated_icebreakers",
      URL: "url",
      FLOW_DATA: "flow_data",
      AI_REGENERATION_ID: "ai_regeneration_id",
      AI_GEN_CONVERSATION_MODEL_VERSION: "ai_gen_conversation_model_version",
      AI_GEN_NUDGE_MODEL_VERSION: "ai_gen_nudge_model_version",
      NUDGE_WAS_AI_GENERATED: "nudge_was_ai_generated",
      AI_GEN_WELCOME_MESSAGE_MODEL_VERSION:
        "ai_gen_welcome_message_model_version",
      APPLIED_RECOMMENDATIONS: "applied_recommendations",
    });
    i.default = e;
  },
  66,
);
