__d(
  "AdsCMURLValuesMap",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      account_settings: "account_settings",
      ad_group: "ad",
      audiences: "audiences",
      billing: "billing",
      campaign_group: "campaign",
      campaign: "adset",
      canvas_builder: "canvas_builder",
      creation: "creation",
      data_source: "data-sources",
      "delivery-insights": "delivery-insights",
      "custom-conversions": "custom-conversions",
      pixel: "pixel",
      account: "account",
      accounts: "accounts",
      pages: "pages",
      pixel_detail: "pixel_detail",
      media: "media",
      data_set: "data_set",
      rules: "rules",
      notifications: "notifications",
      targeting_insights: "targeting-insights",
      account_quality: "account_quality",
      billing_history: "billing_history",
      account_attribution_spec: "account_attribution",
      account_billing_settings: "account_billing",
      account_information: "information",
      account_notifications: "notification_preferences",
      account_roles: "roles",
      account_page_settings: "account_pages",
      ad_groups: "ads",
      audiences_manage: "manage",
      audience_detail_tab: "detail",
      creatives: "creatives",
      account_datasets_and_pixels: null,
      pixel_list_tab: "pixels",
      pixel_detail_tab: "detail",
      unified_pixel_tab: "facebook_pixel",
      conversion_list: "conversion_list",
      conversion_pixel_tab: "conversion_pixel",
      pixel_migration_tab: "pixel_migration",
      media_library_tab: "library",
      campaign_groups: "campaigns",
      campaigns: "adsets",
      account_history_tab: "history",
      campaign_group_history_tab: "history",
      campaign_history_tab: "history",
      adgroup_history_tab: "history",
      list_tab: "list",
      payment_methods: "payment_methods",
      rules_management_tab: "management",
      settings: "settings",
      spend_limit: "spend_limit",
      tracking_id: "reference_number",
      transactions: "transactions",
      transactions_by_page: "transactions_by_page",
      show_older_receipts: "show_older_receipts",
      table_overview: "table_overview",
      categories: "categories",
      markets: "markets",
      market_details: "market_details",
      targeting_insights_overview: "targeting_insights_overview",
      nota_fiscals: "nota_fiscals",
      account_name_template: "account_name_template",
      summary: "summary",
      transaction_details: "transaction_details",
      statement_details: "statement_details",
      meta_verified: null,
    });
    i.default = e;
  },
  66,
);
