__d(
  "AdsInstagramStoryPreviewConstants",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = 18,
      l = 42,
      s = 63,
      u = 86,
      c = 107,
      d = 5e3,
      m = 4,
      p = 28,
      _ = 15e3,
      f = 312,
      g = 8e3,
      h = 68,
      y = 50,
      C = 48,
      b = 24,
      v = 3,
      S = 565,
      R = 318,
      L = 18,
      E = 113,
      k = 6,
      I = 11,
      T = 250,
      D = 250,
      x = 44,
      $ = 25,
      P = 35,
      N = 0,
      M = 1,
      w = 0.5625,
      A = 0.8,
      F = 0.01,
      O = 9 / 16,
      B = 50,
      W = 50,
      q = 4e3,
      U = 0.5,
      V = 16,
      H = 13,
      G = 80,
      z = 20,
      j = "OPT_IN_BUTTON_CLICK_ACTION",
      K = "UPDATE_CAROUSEL_TYPE",
      Q = "SET_TIMER",
      X = "more",
      Y = "#262626",
      J = {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-evenly",
        height: "inherit",
      };
    ((i.BOTTOM_MARGIN_BASE = e),
      (i.BOTTOM_MARGIN_BASE_V2 = l),
      (i.BOTTOM_MARGIN_HAS_CTA = s),
      (i.BOTTOM_MARGIN_HAS_DISCLAIMER = u),
      (i.BOTTOM_MARGIN_HAS_CTA_HAS_DISCLAIMER = c),
      (i.CAROUSEL_DURATION_IN_MS = d),
      (i.CAROUSEL_INITIAL_SPACE = m),
      (i.CAROUSEL_INITIAL_SPACE_WITH_ELLIPSIS = p),
      (i.CAROUSEL_PRE_OPT_IN_VIDEO_MAX_DURATION_IN_MS = _),
      (i.CAROUSEL_SEGMENT_BAR_WIDTH = f),
      (i.DEFAULT_MEDIA_DURATION_IN_MS = g),
      (i.DYNAMIC_MEDIA_OFFSET_HEIGHT = h),
      (i.DYNAMIC_MEDIA_OFFSET_HEIGHT_ONE_LINE = y),
      (i.DYNAMIC_MEDIA_SCALED_OFFSET_HEIGHT = C),
      (i.DYNAMIC_MEDIA_SCALED_OFFSET_HEIGHT_ONE_LINE = b),
      (i.FORCE_DELIVERY_LIMIT = v),
      (i.FRAME_HEIGHT = S),
      (i.FRAME_WIDTH = R),
      (i.LINE_HEIGHT = L),
      (i.MAX_CAPTION_HEIGHT_WITH_FLAT_MEDIA = E),
      (i.MAX_CAPTION_LINE_COUNT = k),
      (i.MIN_SPACE = I),
      (i.PROGRESS_BAR_ANIMATION_DURATION_IN_MS = T),
      (i.TIMER_UPDATE_INTERVAL_IN_MS = D),
      (i.TOP_MARGIN = x),
      (i.UPDATE_TIMEOUT_IN_MS = $),
      (i.VIDEO_STORY_TRUNCATION_LENGTH_IN_SEC = P),
      (i.INITIAL_MEDIA_CARD_INDEX = N),
      (i.END_CARD_INDEX = M),
      (i.MAX_IG_STORY_MEDIA_RATIO = w),
      (i.MAX_IG_FEED_TALL_MEDIA_RATIO = A),
      (i.MEDIA_ASPECT_RATIO_TOLERNACE = F),
      (i.FULLSCREEN_MEDIA_ASPECT_RATIO = O),
      (i.NON_FULLSCREEN_MEDIA_HEADER_MARGIN = B),
      (i.CTA_STICKER_BOTTOM_MARGIN = W),
      (i.DEFAULT_END_SCENE_LENGTH_IN_MS = q),
      (i.INSTAGRAM_CAPTION_LETTER_SPACING = U),
      (i.CAPTION_HORIZONTAL_PADDLE = V),
      (i.IG_STORY_DEFAULT_FONT_SIZE = H),
      (i.IG_STORY_CAPTION_BOX_PADDING_SUM = G),
      (i.MAX_CARDS_IN_CAROUSEL_PREVIEW = z),
      (i.OPT_IN_BUTTON_CLICK_ACTION = j),
      (i.UPDATE_CAROUSEL_TYPE = K),
      (i.SET_TIMER = Q),
      (i.INSTAGRAM_CAPTION_ELLIPSIS = X),
      (i.GREY = Y),
      (i.INSTAGRAM_STORY_MEDIA_CONTAINER_STYLE = J));
  },
  66,
);
