__d(
  "MSGDataclassTypes.flow",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e,
      l = (e = n("$InternalEnum"))({
        LlmOutput: "llm_output",
        SendQuery: "send_query",
        StartTyping: "start_typing",
        StopTyping: "stop_typing",
        VideoAboutToFinish: "video_about_to_finish",
      }),
      s = e({ ChooseMultiple: "CHOOSE_MULTIPLE", ChooseOne: "CHOOSE_ONE" }),
      u = e({ VotingEnded: "VOTING_ENDED", VotingOpen: "VOTING_OPEN" }),
      c = e({
        PsiQueryPlan: "PSI_QUERY_PLAN",
        SummarizeInboxFnfMessages: "SUMMARIZE_INBOX_FNF_MESSAGES",
      }),
      d = e({ MetaAi: "META_AI" }),
      m = e({
        TapToConfirmCancelEvent: "TAP_TO_CONFIRM_CANCEL_EVENT",
        TapToConfirmCreateEvent: "TAP_TO_CONFIRM_CREATE_EVENT",
        TapToConfirmUpdateEvent: "TAP_TO_CONFIRM_UPDATE_EVENT",
      }),
      p = e({ Cancel: "CANCEL", Confirm: "CONFIRM", Other: "OTHER" }),
      _ = e({
        Cancelled: "CANCELLED",
        Confirmed: "CONFIRMED",
        Pending: "PENDING",
      }),
      f = e({ Create: "CREATE", Delete: "DELETE", Update: "UPDATE" }),
      g = e({
        Cancelled: "CANCELLED",
        Confirmed: "CONFIRMED",
        Pending: "PENDING",
      }),
      h = e({ Delete: "DELETE", Read: "READ", Write: "WRITE" }),
      y = e({ Action: "ACTION", Navigation: "NAVIGATION" }),
      C = e({ End: "END", Start: "START" }),
      b = e({
        CopyToClipboard: "COPY_TO_CLIPBOARD",
        FollowUpPrompt: "FOLLOW_UP_PROMPT",
        SendToChat: "SEND_TO_CHAT",
      }),
      v = e({
        Account: "ACCOUNT",
        Ad: "AD",
        Adset: "ADSET",
        Campaign: "CAMPAIGN",
        Creative: "CREATIVE",
      }),
      S = e({
        NotEligible: "NOT_ELIGIBLE",
        Ready: "READY",
        SetupRequired: "SETUP_REQUIRED",
      }),
      R = e({
        FacebookPage: "FACEBOOK_PAGE",
        FacebookProfile: "FACEBOOK_PROFILE",
      }),
      L = e({
        NotShared: "NOT_SHARED",
        Shared: "SHARED",
        SharedWithUnpublishedChanges: "SHARED_WITH_UNPUBLISHED_CHANGES",
      }),
      E = e({
        Archive: "ARCHIVE",
        Audio: "AUDIO",
        Document: "DOCUMENT",
        Html: "HTML",
        Markdown: "MARKDOWN",
        Pdf: "PDF",
        Spreadsheet: "SPREADSHEET",
        Svg: "SVG",
      }),
      k = e({ FbProfile: "FB_PROFILE" }),
      I = e({ ViewerName: "VIEWER_NAME" }),
      T = e({ MiniApp: "MINI_APP", StaticHtml: "STATIC_HTML" }),
      D = e({ None: "NONE", PhotoGallery: "PHOTO_GALLERY" }),
      x = e({
        Comment: "COMMENT",
        Default: "DEFAULT",
        Keyword: "KEYWORD",
        Method: "METHOD",
        Number: "NUMBER",
        Str: "STR",
      }),
      $ = e({
        Follow: "FOLLOW",
        Join: "JOIN",
        Leave: "LEAVE",
        Message: "MESSAGE",
        Unfollow: "UNFOLLOW",
        ViewDetails: "VIEW_DETAILS",
      }),
      P = e({
        CalendarEvent: "CALENDAR_EVENT",
        Group: "GROUP",
        InstagramAccount: "INSTAGRAM_ACCOUNT",
        Page: "PAGE",
        Person: "PERSON",
      }),
      N = e({
        AddAccount: "ADD_ACCOUNT",
        AddScope: "ADD_SCOPE",
        Connect: "CONNECT",
      }),
      M = e({ Dot: "DOT", HorizontalLine: "HORIZONTAL_LINE" }),
      w = e({
        Add: "ADD",
        Animate: "ANIMATE",
        Frame: "FRAME",
        Light: "LIGHT",
        Other: "OTHER",
        Retouch: "RETOUCH",
        Scene: "SCENE",
        Style: "STYLE",
      }),
      A = e({ Conversation: "CONVERSATION", MetaAi: "META_AI", Muse: "MUSE" }),
      F = e({
        CancelReasoning: "CANCEL_REASONING",
        CopyLink: "COPY_LINK",
        DownloadMedia: "DOWNLOAD_MEDIA",
        GenerateImage: "GENERATE_IMAGE",
        OpenFullView: "OPEN_FULL_VIEW",
        RemixMedia: "REMIX_MEDIA",
        UpgradeToSubs: "UPGRADE_TO_SUBS",
        UseTemplate: "USE_TEMPLATE",
      }),
      O = e({ ClientProvided: "CLIENT_PROVIDED", Inline: "INLINE" }),
      B = e({
        ProjectCreationBack: "PROJECT_CREATION_BACK",
        StartProject: "START_PROJECT",
      }),
      W = e({ Failed: "FAILED", Fetched: "FETCHED", Fetching: "FETCHING" }),
      q = e({ Failed: "FAILED", Generating: "GENERATING", Ready: "READY" }),
      U = e({ Animate: "ANIMATE", Imagine: "IMAGINE", Memu: "MEMU" }),
      V = e({
        Geoblock: "GEOBLOCK",
        MediaLabel: "MEDIA_LABEL",
        PostCover: "POST_COVER",
        PostLabel: "POST_LABEL",
        WarningScreens: "WARNING_SCREENS",
      }),
      H = e({ Negative: "NEGATIVE", Neutral: "NEUTRAL", Positive: "POSITIVE" }),
      G = e({ Pin: "PIN", Radius: "RADIUS" }),
      z = e({ Failed: "FAILED", Fetched: "FETCHED", Fetching: "FETCHING" }),
      j = e({ End: "END", Start: "START" }),
      K = e({ Circle: "CIRCLE", Square: "SQUARE", Vertical: "VERTICAL" }),
      Q = e({ Center: "CENTER", Top: "TOP" }),
      X = e({
        Complete: "COMPLETE",
        Running: "RUNNING",
        Synthesizing: "SYNTHESIZING",
      }),
      Y = e({ BigBrain: "BIG_BRAIN", Thinking: "THINKING" }),
      J = e({ BottomSheet: "BOTTOM_SHEET", InThread: "IN_THREAD" }),
      Z = e({
        Bing: "BING",
        Brave: "BRAVE",
        Google: "GOOGLE",
        HelpCenter: "HELP_CENTER",
        InHouse: "IN_HOUSE",
        Kss: "KSS",
        Mase: "MASE",
      }),
      ee = e({ Closed: "CLOSED", Open: "OPEN" }),
      te = e({
        Cheap: "CHEAP",
        Expensive: "EXPENSIVE",
        Moderate: "MODERATE",
        Splurge: "SPLURGE",
      }),
      ne = e({ MarketplaceListing: "MARKETPLACE_LISTING", Place: "PLACE" }),
      re = e({ Done: "DONE", InProgress: "IN_PROGRESS", Pending: "PENDING" }),
      oe = e({
        FullBody: "FULL_BODY",
        Headshot: "HEADSHOT",
        UpperBody: "UPPER_BODY",
      }),
      ae = e({ Landscape: "LANDSCAPE", Portrait: "PORTRAIT" }),
      ie = e({ GroupPost: "GROUP_POST", PagePost: "PAGE_POST" }),
      le = e({ Catalog: "CATALOG", Marketplace: "MARKETPLACE" }),
      se = e({ FbSocialSearch: "FB_SOCIAL_SEARCH" }),
      ue = e({ Allowed: "ALLOWED", NeedsConsent: "NEEDS_CONSENT" }),
      ce = e({
        Completed: "COMPLETED",
        InProgress: "IN_PROGRESS",
        Planned: "PLANNED",
        Stopped: "STOPPED",
      }),
      de = e({ Copy: "COPY", Send: "SEND" }),
      me = e({
        ContextualQuery: "CONTEXTUAL_QUERY",
        WriteWithAi: "WRITE_WITH_AI",
      }),
      pe = e({
        Completed: "COMPLETED",
        Failed: "FAILED",
        Init: "INIT",
        InProgress: "IN_PROGRESS",
        Unknown: "UNKNOWN",
      }),
      _e = e({
        FbGroup: "FB_GROUP",
        FbPage: "FB_PAGE",
        FbProfile: "FB_PROFILE",
        IgProfile: "IG_PROFILE",
        ThreadsProfile: "THREADS_PROFILE",
      }),
      fe = e({
        Facebook: "FACEBOOK",
        Instagram: "INSTAGRAM",
        Threads: "THREADS",
      }),
      ge = e({
        AiGenerated: "AI_GENERATED",
        CatalogProduct: "CATALOG_PRODUCT",
        FacebookPost: "FACEBOOK_POST",
        HealthProvider: "HEALTH_PROVIDER",
        ImageGen: "IMAGE_GEN",
        InstagramPost: "INSTAGRAM_POST",
        ThirdParty: "THIRD_PARTY",
        ThreadsCommunity: "THREADS_COMMUNITY",
        ThreadsPost: "THREADS_POST",
        ThreadsTrend: "THREADS_TREND",
        VmGenerated: "VM_GENERATED",
        WearablesAcsActivity: "WEARABLES_ACS_ACTIVITY",
        WearablesAcsJournal: "WEARABLES_ACS_JOURNAL",
        WearablesAcsRecommendation: "WEARABLES_ACS_RECOMMENDATION",
        WearablesAcsSpace: "WEARABLES_ACS_SPACE",
        WearablesAudioNotes: "WEARABLES_AUDIO_NOTES",
        WebReferenceImage: "WEB_REFERENCE_IMAGE",
      }),
      he = e({ Final: "FINAL", Live: "LIVE", Scheduled: "SCHEDULED" }),
      ye = e({ Euro: "EURO", Nfl: "NFL", WorldCup: "WORLD_CUP" }),
      Ce = e({
        Postseason: "POSTSEASON",
        Preseason: "PRESEASON",
        Regular: "REGULAR",
      }),
      be = e({
        Answer: "ANSWER",
        Refining: "REFINING",
        Researching: "RESEARCHING",
      }),
      ve = e({
        MetaSearch: "META_SEARCH",
        Thinking: "THINKING",
        WebSearch: "WEB_SEARCH",
      }),
      Se = e({ Details: "DETAILS" }),
      Re = e({ Sources: "SOURCES", Steps: "STEPS" }),
      Le = e({ Done: "DONE", Pending: "PENDING", Running: "RUNNING" }),
      Ee = e({
        AppleHealth: "APPLE_HEALTH",
        Gmail: "GMAIL",
        GoogleCalendar: "GOOGLE_CALENDAR",
        GoogleContacts: "GOOGLE_CONTACTS",
        GoogleDrive: "GOOGLE_DRIVE",
        GoogleHealthConnect: "GOOGLE_HEALTH_CONNECT",
        Opentable: "OPENTABLE",
        OutlookCalendar: "OUTLOOK_CALENDAR",
        OutlookContacts: "OUTLOOK_CONTACTS",
        OutlookMail: "OUTLOOK_MAIL",
        Ticketmaster: "TICKETMASTER",
      }),
      ke = e({
        Initiated: "INITIATED",
        Linked: "LINKED",
        Unlinked: "UNLINKED",
      }),
      Ie = e({ AiLookup: "AI_LOOKUP", ContextualMenu: "CONTEXTUAL_MENU" }),
      Te = e({
        Celebrity: "CELEBRITY",
        InfoTerm: "INFO_TERM",
        Movie: "MOVIE",
        Restaurant: "RESTAURANT",
        SportsTeam: "SPORTS_TEAM",
        TvShows: "TV_SHOWS",
      }),
      De = e({ Comparison: "COMPARISON", Segmented: "SEGMENTED" }),
      xe = e({
        AiGray: "AI_GRAY",
        Blue: "BLUE",
        Cyan: "CYAN",
        Green: "GREEN",
        Indigo: "INDIGO",
        Olive: "OLIVE",
        Orange: "ORANGE",
        Pink: "PINK",
        Purple: "PURPLE",
        Red: "RED",
        Rose: "ROSE",
        Shamrock: "SHAMROCK",
        Teal: "TEAL",
        Violet: "VIOLET",
        Yellow: "YELLOW",
      }),
      $e = e({
        Calendar: "CALENDAR",
        Chart: "CHART",
        Checklist: "CHECKLIST",
        Clock: "CLOCK",
        FigureRunning: "FIGURE_RUNNING",
        Food: "FOOD",
        Health: "HEALTH",
        Location: "LOCATION",
        Shopping: "SHOPPING",
        Travel: "TRAVEL",
        Weather: "WEATHER",
      }),
      Pe = e({ Dense: "DENSE", Sparse: "SPARSE" }),
      Ne = e({ Comparison: "COMPARISON" }),
      Me = e({ Down: "DOWN", Neutral: "NEUTRAL", Up: "UP" }),
      we = e({
        Favorable: "FAVORABLE",
        Neutral: "NEUTRAL",
        Unfavorable: "UNFAVORABLE",
      }),
      Ae = e({ Commentary: "COMMENTARY", PrimaryResponse: "PRIMARY_RESPONSE" }),
      Fe = e({ Reasoning: "REASONING", Responding: "RESPONDING" }),
      Oe = e({
        Deeplink: "DEEPLINK",
        Dismiss: "DISMISS",
        FollowUpPrompt: "FOLLOW_UP_PROMPT",
      }),
      Be = e({ Primary: "PRIMARY", Secondary: "SECONDARY" }),
      We = e({
        LoginRequired: "LOGIN_REQUIRED",
        VibesVideoBlock: "VIBES_VIDEO_BLOCK",
      }),
      qe = e({
        ArtifactCreation: "ARTIFACT_CREATION",
        CalendarAccess: "CALENDAR_ACCESS",
        CodeExecution: "CODE_EXECUTION",
        EmailAccess: "EMAIL_ACCESS",
        FileAccess: "FILE_ACCESS",
        HealthDataAccess: "HEALTH_DATA_ACCESS",
        ImageGeneration: "IMAGE_GENERATION",
        SocialContentAccess: "SOCIAL_CONTENT_ACCESS",
        SocialGraphAccess: "SOCIAL_GRAPH_ACCESS",
        VideoGeneration: "VIDEO_GENERATION",
      }),
      Ue = e({ Active: "ACTIVE", Ended: "ENDED" }),
      Ve = e({
        ClearDay: "CLEAR_DAY",
        ClearNight: "CLEAR_NIGHT",
        Cloud: "CLOUD",
        Foggy: "FOGGY",
        PartlyCloudyDay: "PARTLY_CLOUDY_DAY",
        PartlyCloudyNight: "PARTLY_CLOUDY_NIGHT",
        Rainy: "RAINY",
        RainySnow: "RAINY_SNOW",
        Thunderstorm: "THUNDERSTORM",
      }),
      He = e({ Copy: "COPY" }),
      Ge = e({
        Body: "BODY",
        Other: "OTHER",
        Recipient: "RECIPIENT",
        Sender: "SENDER",
        Subject: "SUBJECT",
      }),
      ze = e({ Email: "EMAIL", Message: "MESSAGE" }),
      je = e({
        CriticalUserMessage: "CRITICAL_USER_MESSAGE",
        Default: "DEFAULT",
        NonCriticalAdminXma: "NON_CRITICAL_ADMIN_XMA",
      }),
      Ke = e({
        AiLookup: "AI_LOOKUP",
        GenericPrompt: "GENERIC_PROMPT",
        Icebreakers: "ICEBREAKERS",
        MetaAiFabHint: "META_AI_FAB_HINT",
        MetaAiTextConversationStarter: "META_AI_TEXT_CONVERSATION_STARTER",
        MetaAiVoiceConversationStarter: "META_AI_VOICE_CONVERSATION_STARTER",
        NullStatePrompt: "NULL_STATE_PROMPT",
        SuggestedPrompt: "SUGGESTED_PROMPT",
        ThreadviewSuggestedPrompt: "THREADVIEW_SUGGESTED_PROMPT",
        ThreadviewUserInputPrompt: "THREADVIEW_USER_INPUT_PROMPT",
        ThreadSurfingPrompt: "THREAD_SURFING_PROMPT",
        TypeaheadSuggestedPrompt: "TYPEAHEAD_SUGGESTED_PROMPT",
        UserInputPrompt: "USER_INPUT_PROMPT",
      }),
      Qe = e({
        AttachmentWithLink: "ATTACHMENT_WITH_LINK",
        CarouselMultiPhoto: "CAROUSEL_MULTI_PHOTO",
        ReshareWithPhoto: "RESHARE_WITH_PHOTO",
        Satp: "SATP",
        SinglePhoto: "SINGLE_PHOTO",
        SinglePhotoSensitiveContent: "SINGLE_PHOTO_SENSITIVE_CONTENT",
        Text: "TEXT",
      }),
      Xe = e({
        DeleteAndInsertPakeMessage: "DELETE_AND_INSERT_PAKE_MESSAGE",
        DeleteBackupStateOnClient: "DELETE_BACKUP_STATE_ON_CLIENT",
        InitializeRestore: "INITIALIZE_RESTORE",
        IssueCheckBackupStateTask: "ISSUE_CHECK_BACKUP_STATE_TASK",
        LegacyRetroactiveBackup: "LEGACY_RETROACTIVE_BACKUP",
        RotateDeviceKeysStart: "ROTATE_DEVICE_KEYS_START",
        SyncDeviceCreationTimestamp: "SYNC_DEVICE_CREATION_TIMESTAMP",
        UpdateInitializeRestoreResult: "UPDATE_INITIALIZE_RESTORE_RESULT",
        UpdatePbqWithNeedsBackupUploadStatus:
          "UPDATE_PBQ_WITH_NEEDS_BACKUP_UPLOAD_STATUS",
        UpsertReenrollmentTrigger: "UPSERT_REENROLLMENT_TRIGGER",
        UpsertStatusTrigger: "UPSERT_STATUS_TRIGGER",
      }),
      Ye = e({ Message: "MESSAGE", Thread: "THREAD" }),
      Je = e({
        RemoveBackupItem: "REMOVE_BACKUP_ITEM",
        UpsertBackupItem: "UPSERT_BACKUP_ITEM",
      }),
      Ze = e({
        IneligibleForLabyrinth_11: "INELIGIBLE_FOR_LABYRINTH_11",
        NoOpenEpoch: "NO_OPEN_EPOCH",
        Ok: "OK",
        Outdated: "OUTDATED",
        RateLimited: "RATE_LIMITED",
      }),
      et = e({
        Echo: "ECHO",
        EncryptedPlaceholder: "ENCRYPTED_PLACEHOLDER",
        Open: "OPEN",
        Protobuf: "PROTOBUF",
      }),
      tt = e({
        BackupNotFound: "BACKUP_NOT_FOUND",
        ClientNotSupported: "CLIENT_NOT_SUPPORTED",
        DecryptionFailed: "DECRYPTION_FAILED",
        Unknown: "UNKNOWN",
      }),
      nt = e({
        InfiniteRetroactive: "INFINITE_RETROACTIVE",
        Realtime: "REALTIME",
        RealtimeDelayed: "REALTIME_DELAYED",
        Restore: "RESTORE",
        Retroactive: "RETROACTIVE",
        Retry: "RETRY",
      }),
      rt = e({ After: "AFTER", Before: "BEFORE" }),
      ot = e({
        ActionLog: "ACTION_LOG",
        Audio: "AUDIO",
        DisappearingMessage: "DISAPPEARING_MESSAGE",
        Ephemeral: "EPHEMERAL",
        File: "FILE",
        Gif: "GIF",
        MsgOpgP2PPayment: "MSG_OPG_P2P_PAYMENT",
        Permanent: "PERMANENT",
        Photo: "PHOTO",
        Raven: "RAVEN",
        RavenPermanent: "RAVEN_PERMANENT",
        RavenReadOnce: "RAVEN_READ_ONCE",
        RavenReplayable: "RAVEN_REPLAYABLE",
        RavenReplayed: "RAVEN_REPLAYED",
        RavenSeen: "RAVEN_SEEN",
        ShareIgClips: "SHARE_IG_CLIPS",
        ShareIgMedia: "SHARE_IG_MEDIA",
        ShareLink: "SHARE_LINK",
        Shh: "SHH",
        SkipEbPersistence: "SKIP_EB_PERSISTENCE",
        StoryReply: "STORY_REPLY",
        UnreadRaven: "UNREAD_RAVEN",
        Video: "VIDEO",
      }),
      at = e({
        Fts: "FTS",
        HistoryRestore: "HISTORY_RESTORE",
        MpsReadApis: "MPS_READ_APIS",
        NewMemberExport: "NEW_MEMBER_EXPORT",
        Reporting: "REPORTING",
      }),
      it = e({
        AlreadyUploaded: "ALREADY_UPLOADED",
        NeedsUpload: "NEEDS_UPLOAD",
        NotApplicable: "NOT_APPLICABLE",
      }),
      lt = e({
        PermanentFailure: "PERMANENT_FAILURE",
        RetryableException: "RETRYABLE_EXCEPTION",
        Success: "SUCCESS",
      }),
      st = e({ Fbn: "FBN", Instamadillo: "INSTAMADILLO", Unknown: "UNKNOWN" }),
      ut = e({
        GetMealDetails: "GET_MEAL_DETAILS",
        SuggestSimilarMeals: "SUGGEST_SIMILAR_MEALS",
        UpdateIngredients: "UPDATE_INGREDIENTS",
      }),
      ct = e({
        Landscape: "LANDSCAPE",
        Square: "SQUARE",
        Vertical: "VERTICAL",
      }),
      dt = e({
        FullBody: "FULL_BODY",
        Headshot: "HEADSHOT",
        UpperBody: "UPPER_BODY",
      }),
      mt = e({
        EditPrompt: "EDIT_PROMPT",
        NewMessage: "NEW_MESSAGE",
        Regenerate: "REGENERATE",
      }),
      pt = e({
        Daily: "DAILY",
        Hourly: "HOURLY",
        Monthly: "MONTHLY",
        Never: "NEVER",
        Weekly: "WEEKLY",
      }),
      _t = e({ Assistant: "ASSISTANT", User: "USER" }),
      ft = e({
        CanFeedbackOnBotResponse: "CAN_FEEDBACK_ON_BOT_RESPONSE",
        CanReadAloud: "CAN_READ_ALOUD",
        Copy: "COPY",
      }),
      gt = e({
        Memu: "MEMU",
        Synthetic: "SYNTHETIC",
        Unknown: "UNKNOWN",
        UserUploaded: "USER_UPLOADED",
      }),
      ht = e({ AskMetaAi: "ASK_META_AI", Summarize: "SUMMARIZE" }),
      yt = e({
        Address: "ADDRESS",
        FindNextGame: "FIND_NEXT_GAME",
        GetInfo: "GET_INFO",
        GetRestaurantInfo: "GET_RESTAURANT_INFO",
        LatestNews: "LATEST_NEWS",
        MenuHighlights: "MENU_HIGHLIGHTS",
        ResponseCard: "RESPONSE_CARD",
        Reviews: "REVIEWS",
        WhereToWatch: "WHERE_TO_WATCH",
      }),
      Ct = e({
        Celebrity: "CELEBRITY",
        Movie: "MOVIE",
        Restaurant: "RESTAURANT",
        SportsTeam: "SPORTS_TEAM",
        TvShows: "TV_SHOWS",
      }),
      bt = e({
        AiAnimatedPhoto: "AI_ANIMATED_PHOTO",
        AiMeme: "AI_MEME",
        AiMusicSongGen: "AI_MUSIC_SONG_GEN",
        AiVoiceNotes: "AI_VOICE_NOTES",
        CreatorDisclosedAi: "CREATOR_DISCLOSED_AI",
        ForwardedAi: "FORWARDED_AI",
        HiddenMetadata: "HIDDEN_METADATA",
        Imagine: "IMAGINE",
        MagicModBackdrop: "MAGIC_MOD_BACKDROP",
        MagicModRestyle: "MAGIC_MOD_RESTYLE",
        Memu: "MEMU",
        Micdrop: "MICDROP",
        ThirdPartyAi: "THIRD_PARTY_AI",
        ThirdPartyAiEdited: "THIRD_PARTY_AI_EDITED",
      }),
      vt = e({
        Compacting: "COMPACTING",
        Laughing: "LAUGHING",
        MakingSomething: "MAKING_SOMETHING",
        NeedsApproval: "NEEDS_APPROVAL",
        Online: "ONLINE",
        OutOfCredits: "OUT_OF_CREDITS",
        PlayingMusic: "PLAYING_MUSIC",
        Responding: "RESPONDING",
        TakingNotes: "TAKING_NOTES",
        WaitingForSubagents: "WAITING_FOR_SUBAGENTS",
        Working: "WORKING",
      }),
      St = e({ Background: "BACKGROUND", Foreground: "FOREGROUND" }),
      Rt = e({
        AllowAlways: "ALLOW_ALWAYS",
        AllowOnce: "ALLOW_ONCE",
        AllowSession: "ALLOW_SESSION",
        Deny: "DENY",
      }),
      Lt = e({
        Browser: "BROWSER",
        Checkout: "CHECKOUT",
        Connector: "CONNECTOR",
        Device: "DEVICE",
        Media: "MEDIA",
        Network: "NETWORK",
        Tool: "TOOL",
        Warning: "WARNING",
      }),
      Et = e({
        ConnectorAllActions: "CONNECTOR_ALL_ACTIONS",
        Destination: "DESTINATION",
        DestinationDomain: "DESTINATION_DOMAIN",
        Entity: "ENTITY",
        Recipient: "RECIPIENT",
      }),
      kt = e({
        BrowserAction: "BROWSER_ACTION",
        BrowserCheckout: "BROWSER_CHECKOUT",
        BrowserTaskConfirmation: "BROWSER_TASK_CONFIRMATION",
        Connector: "CONNECTOR",
        Device: "DEVICE",
        Network: "NETWORK",
        OutgoingMedia: "OUTGOING_MEDIA",
        ShopifyCheckout: "SHOPIFY_CHECKOUT",
        StripeLinkCheckout: "STRIPE_LINK_CHECKOUT",
      }),
      It = e({ StripeLink: "STRIPE_LINK" }),
      Tt = e({ Card: "CARD" }),
      Dt = e({ Details: "DETAILS", Inline: "INLINE" }),
      xt = e({ File: "FILE", Image: "IMAGE", Video: "VIDEO" }),
      $t = e({
        MarketplaceXmatCallFunction: "MARKETPLACE_XMAT_CALL_FUNCTION",
        MarketplaceXmaCallFunction: "MARKETPLACE_XMA_CALL_FUNCTION",
        ViewAllAiTasks: "VIEW_ALL_AI_TASKS",
        ViewSingleAiTask: "VIEW_SINGLE_AI_TASK",
        WatchPartySetUpNextGame: "WATCH_PARTY_SET_UP_NEXT_GAME",
        XmaCrmOptIn: "XMA_CRM_OPT_IN",
        XmaDailyGameChallengeJoin: "XMA_DAILY_GAME_CHALLENGE_JOIN",
        XmaDailyGameChallengeJoinAndPlay:
          "XMA_DAILY_GAME_CHALLENGE_JOIN_AND_PLAY",
        XmaDailyGameChallengePlay: "XMA_DAILY_GAME_CHALLENGE_PLAY",
        XmaDailyGameChallengeSeeLeaderboard:
          "XMA_DAILY_GAME_CHALLENGE_SEE_LEADERBOARD",
        XmaDisabledCta: "XMA_DISABLED_CTA",
        XmaGamePlay: "XMA_GAME_PLAY",
        XmaGenAiSearchPluginResponseSources:
          "XMA_GEN_AI_SEARCH_PLUGIN_RESPONSE_SOURCES",
        XmaHorizonGamingChallengeJoin: "XMA_HORIZON_GAMING_CHALLENGE_JOIN",
        XmaHorizonGamingChallengePlay: "XMA_HORIZON_GAMING_CHALLENGE_PLAY",
        XmaHorizonGamingChallengeSeeLeaderboard:
          "XMA_HORIZON_GAMING_CHALLENGE_SEE_LEADERBOARD",
        XmaHorizonGamingChallengeSeeMoreGames:
          "XMA_HORIZON_GAMING_CHALLENGE_SEE_MORE_GAMES",
        XmaHorizonGamingChallengeStartNewChallenge:
          "XMA_HORIZON_GAMING_CHALLENGE_START_NEW_CHALLENGE",
        XmaMetaAiDigestSeeSummary: "XMA_META_AI_DIGEST_SEE_SUMMARY",
        XmaMetaAiLocation: "XMA_META_AI_LOCATION",
        XmaMetaAiLookupEntity: "XMA_META_AI_LOOKUP_ENTITY",
        XmaMetaAiReminders: "XMA_META_AI_REMINDERS",
        XmaMetaAiSingleSubscription: "XMA_META_AI_SINGLE_SUBSCRIPTION",
        XmaMetaAiSubscriptions: "XMA_META_AI_SUBSCRIPTIONS",
        XmaMetaAiTask: "XMA_META_AI_TASK",
        XmaMobiclawMessagingConsent: "XMA_MOBICLAW_MESSAGING_CONSENT",
        XmaMomentAddedView: "XMA_MOMENT_ADDED_VIEW",
        XmaMsgExternalLinkShare: "XMA_MSG_EXTERNAL_LINK_SHARE",
        XmaMusicArtist: "XMA_MUSIC_ARTIST",
        XmaOpenNative: "XMA_OPEN_NATIVE",
        XmaP2POpenMessengerApp: "XMA_P2P_OPEN_MESSENGER_APP",
        XmaP2POpgTransfer: "XMA_P2P_OPG_TRANSFER",
        XmaPhoneNumber: "XMA_PHONE_NUMBER",
        XmaSharedAlbumViewer: "XMA_SHARED_ALBUM_VIEWER",
        XmaWebUrl: "XMA_WEB_URL",
      }),
      Pt = e({
        NoBranding: "NO_BRANDING",
        PaidPartnership: "PAID_PARTNERSHIP",
      }),
      Nt = e({
        Imagine: "IMAGINE",
        Imagineme: "IMAGINEME",
        Imaginev2: "IMAGINEV2",
      }),
      Mt = e({ Animate: "ANIMATE", AnimateImagineme: "ANIMATE_IMAGINEME" }),
      wt = e({
        AiAnimatedPhoto: "AI_ANIMATED_PHOTO",
        AiGeneratedSticker: "AI_GENERATED_STICKER",
        AiMeme: "AI_MEME",
        AiMusicMicDrop: "AI_MUSIC_MIC_DROP",
        AiMusicSongGen: "AI_MUSIC_SONG_GEN",
        AiSummaryBottomSheet: "AI_SUMMARY_BOTTOM_SHEET",
        AnimatedAiSticker: "ANIMATED_AI_STICKER",
        Avatar: "AVATAR",
        AvatarStyle_1: "AVATAR_STYLE_1",
        AvatarStyle_2: "AVATAR_STYLE_2",
        ContentBasedSparks: "CONTENT_BASED_SPARKS",
        ContentConversationStarter: "CONTENT_CONVERSATION_STARTER",
        ContentMention: "CONTENT_MENTION",
        ContentReply: "CONTENT_REPLY",
        ContentShare: "CONTENT_SHARE",
        ConversationStarter: "CONVERSATION_STARTER",
        DailyGamesScoreSharing: "DAILY_GAMES_SCORE_SHARING",
        DisappearingMessage: "DISAPPEARING_MESSAGE",
        EditMessage: "EDIT_MESSAGE",
        ForwardByAttachmentId: "FORWARD_BY_ATTACHMENT_ID",
        ForwardByMessageId: "FORWARD_BY_MESSAGE_ID",
        Hotlike: "HOTLIKE",
        IncludesLink: "INCLUDES_LINK",
        IncludesOffPlatformContent: "INCLUDES_OFF_PLATFORM_CONTENT",
        IncludesOnPlatformContent: "INCLUDES_ON_PLATFORM_CONTENT",
        InvokesGenAiResponse: "INVOKES_GEN_AI_RESPONSE",
        IsDialtone: "IS_DIALTONE",
        IsNotDialtone: "IS_NOT_DIALTONE",
        LightweightInteractionAsStoryReply:
          "LIGHTWEIGHT_INTERACTION_AS_STORY_REPLY",
        MagicModImage: "MAGIC_MOD_IMAGE",
        Mention: "MENTION",
        MessageForward: "MESSAGE_FORWARD",
        MessageReply: "MESSAGE_REPLY",
        MessageReshare: "MESSAGE_RESHARE",
        MetaAiEntitySuggestedPrompts: "META_AI_ENTITY_SUGGESTED_PROMPTS",
        MetaAiIntents: "META_AI_INTENTS",
        MetaAiReminder: "META_AI_REMINDER",
        MetaAiSubscription: "META_AI_SUBSCRIPTION",
        MsgrFriendsTabFeed: "MSGR_FRIENDS_TAB_FEED",
        MsgrSocialProfile: "MSGR_SOCIAL_PROFILE",
        MsysSend: "MSYS_SEND",
        MultitabEnv: "MULTITAB_ENV",
        NoteReply: "NOTE_REPLY",
        OffPlatform: "OFF_PLATFORM",
        OnPlatform: "ON_PLATFORM",
        PostReply: "POST_REPLY",
        PowerUp: "POWER_UP",
        QuicksnapReply: "QUICKSNAP_REPLY",
        Raven: "RAVEN",
        SentFromGenAiBot: "SENT_FROM_GEN_AI_BOT",
        ShareOfOriginalUserContent: "SHARE_OF_ORIGINAL_USER_CONTENT",
        SocialSticker: "SOCIAL_STICKER",
        SpectraGame: "SPECTRA_GAME",
        StoryReply: "STORY_REPLY",
        Superlative: "SUPERLATIVE",
        SuperReact: "SUPER_REACT",
        ThirdPartyReshare: "THIRD_PARTY_RESHARE",
        VanishMode: "VANISH_MODE",
        WriteWithMetaAi: "WRITE_WITH_META_AI",
        ZeroBalanceDetected: "ZERO_BALANCE_DETECTED",
      }),
      At = e({
        Imagine: "IMAGINE",
        ImagineRestyle: "IMAGINE_RESTYLE",
        Memu: "MEMU",
      }),
      Ft = e({ Reminder: "REMINDER", Subscription: "SUBSCRIPTION" }),
      Ot = e({
        Image: "image",
        Link_1p: "link_1p",
        Link_3p: "link_3p",
        Text: "text",
        Voice: "voice",
      }),
      Bt = e({ MessageBreaks: "MESSAGE_BREAKS", SideBySide: "SIDE_BY_SIDE" }),
      Wt = e({
        FathersDay: "FATHERS_DAY",
        FriendshipDay: "FRIENDSHIP_DAY",
        Graduation: "GRADUATION",
        JulyFourth: "JULY_FOURTH",
        MothersDay: "MOTHERS_DAY",
        NationalSelfie: "NATIONAL_SELFIE",
        PhIndependenceDay: "PH_INDEPENDENCE_DAY",
      }),
      qt = e({ Attribution: "ATTRIBUTION", Birthday: "BIRTHDAY" }),
      Ut = e({
        Clip: "CLIP",
        Comment: "COMMENT",
        Feed: "FEED",
        Live: "LIVE",
        LocationShare: "LOCATION_SHARE",
        MediaNote: "MEDIA_NOTE",
        Note: "NOTE",
        Profile: "PROFILE",
        ReelsAudio: "REELS_AUDIO",
        SocialContext: "SOCIAL_CONTEXT",
        Story: "STORY",
        StoryHighlight: "STORY_HIGHLIGHT",
      }),
      Vt = e({ Mention: "MENTION", Reply: "REPLY" }),
      Ht = e({
        Mention: "MENTION",
        React: "REACT",
        Reply: "REPLY",
        Share: "SHARE",
      }),
      Gt = e({
        AnimatedEmoji: "ANIMATED_EMOJI",
        Genmoji: "GENMOJI",
        Metamoji: "METAMOJI",
        Undefined: "UNDEFINED",
      }),
      zt = e({
        GenAiGetInfo: "GEN_AI_GET_INFO",
        GenAiReminder: "GEN_AI_REMINDER",
        GenAiThreadSurfing: "GEN_AI_THREAD_SURFING",
      }),
      jt = e({ Employer: "EMPLOYER", Seeker: "SEEKER" }),
      Kt = e({
        AnimatedThankImage: "ANIMATED_THANK_IMAGE",
        AnimatedThankImageWithTextMessage:
          "ANIMATED_THANK_IMAGE_WITH_TEXT_MESSAGE",
        Unknown: "UNKNOWN",
      }),
      Qt = e({
        AutoReply: "AUTO_REPLY",
        AutoReplyV2: "AUTO_REPLY_V2",
        BulkReply: "BULK_REPLY",
        Unknown: "UNKNOWN",
      }),
      Xt = e({
        AttachmentPreviewHeaderMedia: "ATTACHMENT_PREVIEW_HEADER_MEDIA",
        AttachmentPreviewMedia: "ATTACHMENT_PREVIEW_MEDIA",
      }),
      Yt = e({ Photo: "PHOTO" }),
      Jt = e({
        Camera: "CAMERA",
        ExpressionTray: "EXPRESSION_TRAY",
        GifTab: "GIF_TAB",
        MediaPicker: "MEDIA_PICKER",
        MediaPickerStack: "MEDIA_PICKER_STACK",
      }),
      Zt = e({ Messages: "MESSAGES", Retro: "RETRO", Simple: "SIMPLE" }),
      en = e({ Messages: "MESSAGES", Retro: "RETRO", Simple: "SIMPLE" }),
      tn = e({
        Accepted: "ACCEPTED",
        Deleted: "DELETED",
        Unactioned: "UNACTIONED",
      }),
      nn = e({
        CommentMentions: "COMMENT_MENTIONS",
        Ctm: "CTM",
        Cts: "CTS",
        Dating: "DATING",
        FbmInbox: "FBM_INBOX",
        FbGroups: "FB_GROUPS",
        FbHelpCenterXsMetaAi: "FB_HELP_CENTER_XS_META_AI",
        FbNotes: "FB_NOTES",
        FbSearch: "FB_SEARCH",
        Feed: "FEED",
        GamingHangouts: "GAMING_HANGOUTS",
        GenAiAssistant: "GEN_AI_ASSISTANT",
        GenAiFlAshImagine: "GEN_AI_FlASH_IMAGINE",
        GenAiLocation: "GEN_AI_LOCATION",
        GenAiMultiModal: "GEN_AI_MULTI_MODAL",
        GenAiSuggestedPrompts: "GEN_AI_SUGGESTED_PROMPTS",
        IgComment: "IG_COMMENT",
        IgExternalLink: "IG_EXTERNAL_LINK",
        IgFeed: "IG_FEED",
        IgLive: "IG_LIVE",
        IgNotes: "IG_NOTES",
        IgProfile: "IG_PROFILE",
        IgReels: "IG_REELS",
        IgStory: "IG_STORY",
        MagicMessenger: "MAGIC_MESSENGER",
        Mp: "MP",
        ProductHighlights: "PRODUCT_HIGHLIGHTS",
        Profile: "PROFILE",
        Psrib: "PSRIB",
        Rta: "RTA",
        Sharesheet: "SHARESHEET",
        Shorts: "SHORTS",
        SpectraAction: "SPECTRA_ACTION",
        SpectraGame: "SPECTRA_GAME",
        Srib: "SRIB",
        Ufi: "UFI",
        Watch: "WATCH",
        ZorroMessage: "ZORRO_MESSAGE",
      }),
      rn = e({ MsgrE2EeGenai: "MSGR_E2EE_GENAI" }),
      on = e({
        Grouppost: "GROUPPOST",
        Momentlink: "MOMENTLINK",
        Shareurl: "SHAREURL",
        Statusupdate: "STATUSUPDATE",
        Unifiedresponse: "UNIFIEDRESPONSE",
      }),
      an = e({
        DxmaPlaceholder: "DXMA_PLACEHOLDER",
        ExpiredPlaceholder: "EXPIRED_PLACEHOLDER",
        Grid: "GRID",
        Hscroll: "HSCROLL",
        Layered: "LAYERED",
        PilePrompt: "PILE_PROMPT",
        Placeholder: "PLACEHOLDER",
        Portrait: "PORTRAIT",
        SharedStack: "SHARED_STACK",
        Single: "SINGLE",
        Stack: "STACK",
        StackCard: "STACK_CARD",
        StandardDxma: "STANDARD_DXMA",
        Xcenter: "XCENTER",
      }),
      ln = e({
        Bump: "BUMP",
        Mention: "MENTION",
        Reply: "REPLY",
        Share: "SHARE",
      }),
      sn = e({
        AiWidget: "AI_WIDGET",
        GamePrediction: "GAME_PREDICTION",
        HorizonWeelXma: "HORIZON_WEEL_XMA",
        IgMediaShare: "IG_MEDIA_SHARE",
        MomentLink: "MOMENT_LINK",
        ThreadsPostShare: "THREADS_POST_SHARE",
      }),
      un = e({ XmaWebUrl: "XMA_WEB_URL" }),
      cn = e({ Mention: "MENTION", Reply: "REPLY" }),
      dn = e({
        Note: "NOTE",
        Prompt: "PROMPT",
        PromptResponse: "PROMPT_RESPONSE",
        Status: "STATUS",
      }),
      mn = e({
        FbContentShare: "FB_CONTENT_SHARE",
        FeelingsNote: "FEELINGS_NOTE",
        GameNote: "GAME_NOTE",
        GifNote: "GIF_NOTE",
        Marketplace: "MARKETPLACE",
        MoodsNote: "MOODS_NOTE",
        MusicNoteMusicOnly: "MUSIC_NOTE_MUSIC_ONLY",
        MusicNoteWithText: "MUSIC_NOTE_WITH_TEXT",
        PollNote: "POLL_NOTE",
        Status: "STATUS",
        TextNote: "TEXT_NOTE",
      }),
      pn = e({ Image: "IMAGE", Other: "OTHER", Video: "VIDEO" }),
      _n = e({ NonPhone: "NON_PHONE", PhoneBacked: "PHONE_BACKED" }),
      fn = e({ Connector: "CONNECTOR", Network: "NETWORK" }),
      gn = e({
        AntiValentines: "ANTI_VALENTINES",
        AvatarAngry: "AVATAR_ANGRY",
        AvatarCry: "AVATAR_CRY",
        AvatarLaugh: "AVATAR_LAUGH",
        AvatarLove: "AVATAR_LOVE",
        Celebration: "CELEBRATION",
        Fire: "FIRE",
        Giftwrap: "GIFTWRAP",
        Halloween: "HALLOWEEN",
        Love: "LOVE",
        NewYears: "NEW_YEARS",
        NomNomDash: "NOM_NOM_DASH",
        ValentinesDay: "VALENTINES_DAY",
      }),
      hn = e({
        BasicSuperReactAnimation: "BASIC_SUPER_REACT_ANIMATION",
        FbEmoji: "FB_EMOJI",
        None: "NONE",
        NonDefaultEmoji: "NON_DEFAULT_EMOJI",
      }),
      yn = e({ Media: "MEDIA", Text: "TEXT" }),
      Cn = e({
        Classifier: "CLASSIFIER",
        ReactiveEnforcement: "REACTIVE_ENFORCEMENT",
        RecipientParent: "RECIPIENT_PARENT",
        SenderParent: "SENDER_PARENT",
      }),
      bn = e({ Restore: "RESTORE", Takedown: "TAKEDOWN" }),
      vn = e({
        PermanentDelete: "PERMANENT_DELETE",
        SoftDeleteWithoutAppeal: "SOFT_DELETE_WITHOUT_APPEAL",
        SoftDeleteWithoutAppealParentUnviewable:
          "SOFT_DELETE_WITHOUT_APPEAL_PARENT_UNVIEWABLE",
        SoftDeleteWithAppeal: "SOFT_DELETE_WITH_APPEAL",
        SoftDeleteWithAppealParentUnviewable:
          "SOFT_DELETE_WITH_APPEAL_PARENT_UNVIEWABLE",
        Unknown: "UNKNOWN",
      }),
      Sn = e({
        FiveOptionStarRating: "FIVE_OPTION_STAR_RATING",
        IgTwoOptionCombined: "IG_TWO_OPTION_COMBINED",
        TwoOptionCombined: "TWO_OPTION_COMBINED",
        Unknown: "UNKNOWN",
      }),
      Rn = e({
        AntiBully: "ANTI_BULLY",
        Event: "EVENT",
        Fundraiser: "FUNDRAISER",
        Instagram: "INSTAGRAM",
        Location: "LOCATION",
        Page: "PAGE",
        People: "PEOPLE",
        Product: "PRODUCT",
        ResharedContent: "RESHARED_CONTENT",
        ResharedPost: "RESHARED_POST",
        Unknown: "UNKNOWN",
      }),
      Ln = e({
        AboveKeyboardEmojiLightWeight: "ABOVE_KEYBOARD_EMOJI_LIGHT_WEIGHT",
        AboveKeyboardSuggestedEmoji: "ABOVE_KEYBOARD_SUGGESTED_EMOJI",
        AboveKeyboardSuggestedEmojiText: "ABOVE_KEYBOARD_SUGGESTED_EMOJI_TEXT",
        AboveKeyboardSuggestedText: "ABOVE_KEYBOARD_SUGGESTED_TEXT",
        Avatar: "AVATAR",
        GifLightWeight: "GIF_LIGHT_WEIGHT",
        Photo: "PHOTO",
        PostLwrSuggestedReply: "POST_LWR_SUGGESTED_REPLY",
        QuickEmoji: "QUICK_EMOJI",
        QuickEmojiPalette: "QUICK_EMOJI_PALETTE",
        StickerLightWeight: "STICKER_LIGHT_WEIGHT",
        SuggestedEmoji: "SUGGESTED_EMOJI",
        SuggestedEmojiText: "SUGGESTED_EMOJI_TEXT",
        SuggestedReply: "SUGGESTED_REPLY",
        SuggestedText: "SUGGESTED_TEXT",
        Unspecified: "UNSPECIFIED",
        WriteWithAi: "WRITE_WITH_AI",
      }),
      En = e({
        Generating: "GENERATING",
        Imagining: "IMAGINING",
        RequestStart: "REQUEST_START",
        Searching: "SEARCHING",
        StreamingImage: "STREAMING_IMAGE",
        UnderstandingImage: "UNDERSTANDING_IMAGE",
      }),
      kn = e({
        BanUser: "BAN_USER",
        HideMessage: "HIDE_MESSAGE",
        RemoveMessage: "REMOVE_MESSAGE",
        RemoveUser: "REMOVE_USER",
        ReportMessage: "REPORT_MESSAGE",
        SuspendUser: "SUSPEND_USER",
      }),
      In = e({ Bar: "BAR", Baz: "BAZ", Foo: "FOO" }),
      Tn = e({ Bar: "BAR", Baz: "BAZ", Foo: "FOO" }),
      Dn = e({
        Error: "ERROR",
        Success: "SUCCESS",
        Transcribing: "TRANSCRIBING",
        UnsupportedLanguage: "UNSUPPORTED_LANGUAGE",
        Untranscribed: "UNTRANSCRIBED",
      }),
      xn = e({ Closed: "CLOSED", Open: "OPEN", Resolved: "RESOLVED" }),
      $n = e({
        Chat: "CHAT",
        Faq: "FAQ",
        Other: "OTHER",
        Post: "POST",
        Product: "PRODUCT",
        Unknown: "UNKNOWN",
      }),
      Pn = e({
        Chat: "CHAT",
        Faq: "FAQ",
        Other: "OTHER",
        Post: "POST",
        Pricelist: "PRICELIST",
        Product: "PRODUCT",
        Unknown: "UNKNOWN",
      }),
      Nn = e({
        Comment: "COMMENT",
        Default: "DEFAULT",
        Keyword: "KEYWORD",
        Method: "METHOD",
        Number: "NUMBER",
        Str: "STR",
      }),
      Mn = e({ Chevron: "CHEVRON" }),
      wn = e({ Circle: "CIRCLE", Square: "SQUARE" }),
      An = e({ Album: "ALBUM", Clips: "CLIPS", Video: "VIDEO" }),
      Fn = e({
        FbCommentMentionShare: "FB_COMMENT_MENTION_SHARE",
        FbEvent: "FB_EVENT",
        FbFeedPostPrivateReply: "FB_FEED_POST_PRIVATE_REPLY",
        FbFeedPostReactionReply: "FB_FEED_POST_REACTION_REPLY",
        FbFeedProductShare: "FB_FEED_PRODUCT_SHARE",
        FbFeedShare: "FB_FEED_SHARE",
        FbFeedVideoShare: "FB_FEED_VIDEO_SHARE",
        FbGamingCustomUpdate: "FB_GAMING_CUSTOM_UPDATE",
        FbGroupPost: "FB_GROUP_POST",
        FbPostMention: "FB_POST_MENTION",
        FbProducerStoryReply: "FB_PRODUCER_STORY_REPLY",
        FbProfileShare: "FB_PROFILE_SHARE",
        FbShort: "FB_SHORT",
        FbStoryMention: "FB_STORY_MENTION",
        FbStoryReply: "FB_STORY_REPLY",
        FbStoryShare: "FB_STORY_SHARE",
        IgClipsShare: "IG_CLIPS_SHARE",
        IgExternalLink: "IG_EXTERNAL_LINK",
        IgIgtvShare: "IG_IGTV_SHARE",
        IgMediaShare: "IG_MEDIA_SHARE",
        IgMultipostShare: "IG_MULTIPOST_SHARE",
        IgProfileShare: "IG_PROFILE_SHARE",
        IgReceiverFetch: "IG_RECEIVER_FETCH",
        IgShopShare: "IG_SHOP_SHARE",
        IgSingleVideoPostShare: "IG_SINGLE_VIDEO_POST_SHARE",
        IgStoryHighlightReaction: "IG_STORY_HIGHLIGHT_REACTION",
        IgStoryHighlightReply: "IG_STORY_HIGHLIGHT_REPLY",
        IgStoryPhotoHighlightShare: "IG_STORY_PHOTO_HIGHLIGHT_SHARE",
        IgStoryPhotoMention: "IG_STORY_PHOTO_MENTION",
        IgStoryPhotoShare: "IG_STORY_PHOTO_SHARE",
        IgStoryReaction: "IG_STORY_REACTION",
        IgStoryReply: "IG_STORY_REPLY",
        IgStoryVideoHighlightShare: "IG_STORY_VIDEO_HIGHLIGHT_SHARE",
        IgStoryVideoMention: "IG_STORY_VIDEO_MENTION",
        IgStoryVideoShare: "IG_STORY_VIDEO_SHARE",
        IgTextPostAppShare: "IG_TEXT_POST_APP_SHARE",
        LiveLocation: "LIVE_LOCATION",
        MsgAiBotSearchResult: "MSG_AI_BOT_SEARCH_RESULT",
        MsgAiContact: "MSG_AI_CONTACT",
        MsgCirclesMessaging: "MSG_CIRCLES_MESSAGING",
        MsgContact: "MSG_CONTACT",
        MsgEarlyAccessFbShare: "MSG_EARLY_ACCESS_FB_SHARE",
        MsgExternalLinkShare: "MSG_EXTERNAL_LINK_SHARE",
        MsgFile: "MSG_FILE",
        MsgGamePrediction: "MSG_GAME_PREDICTION",
        MsgGenAi_1PSearchResult: "MSG_GEN_AI_1P_SEARCH_RESULT",
        MsgGenAiMemuOnboardingResponse: "MSG_GEN_AI_MEMU_ONBOARDING_RESPONSE",
        MsgGenAiReminder: "MSG_GEN_AI_REMINDER",
        MsgGenAiRichResponse: "MSG_GEN_AI_RICH_RESPONSE",
        MsgGenAiSearchPluginResponse: "MSG_GEN_AI_SEARCH_PLUGIN_RESPONSE",
        MsgGenAiSubscription: "MSG_GEN_AI_SUBSCRIPTION",
        MsgGenAiTask: "MSG_GEN_AI_TASK",
        MsgIgMediaShare: "MSG_IG_MEDIA_SHARE",
        MsgLocationSharingDeprecated: "MSG_LOCATION_SHARING_DEPRECATED",
        MsgLocationSharingV2: "MSG_LOCATION_SHARING_V2",
        MsgManusGrowthReferral: "MSG_MANUS_GROWTH_REFERRAL",
        MsgMemoriesShare: "MSG_MEMORIES_SHARE",
        MsgMusicSticker: "MSG_MUSIC_STICKER",
        MsgOpgP2PPayment: "MSG_OPG_P2P_PAYMENT",
        MsgP2PPayment: "MSG_P2P_PAYMENT",
        MsgPhoneNumber: "MSG_PHONE_NUMBER",
        MsgPrivateXma: "MSG_PRIVATE_XMA",
        MsgReceiverFetch: "MSG_RECEIVER_FETCH",
        MsgReceiverFetchFallback: "MSG_RECEIVER_FETCH_FALLBACK",
        MsgReelsList: "MSG_REELS_LIST",
        MsgSharedAlbum: "MSG_SHARED_ALBUM",
        MsgSocialCueMemories: "MSG_SOCIAL_CUE_MEMORIES",
        MsgSupervisionInvite: "MSG_SUPERVISION_INVITE",
        None: "NONE",
        OcAvatarStaticSticker: "OC_AVATAR_STATIC_STICKER",
        RtcAudioCall: "RTC_AUDIO_CALL",
        RtcGroupAudioCall: "RTC_GROUP_AUDIO_CALL",
        RtcGroupVideoCall: "RTC_GROUP_VIDEO_CALL",
        RtcMissedAudioCall: "RTC_MISSED_AUDIO_CALL",
        RtcMissedGroupAudioCall: "RTC_MISSED_GROUP_AUDIO_CALL",
        RtcMissedGroupVideoCall: "RTC_MISSED_GROUP_VIDEO_CALL",
        RtcMissedVideoCall: "RTC_MISSED_VIDEO_CALL",
        RtcOngoingAudioCall: "RTC_ONGOING_AUDIO_CALL",
        RtcOngoingVideoCall: "RTC_ONGOING_VIDEO_CALL",
        RtcVideoCall: "RTC_VIDEO_CALL",
        Test: "TEST",
      }),
      On = e({
        ChevronDown: "CHEVRON_DOWN",
        DotsThreeHorizontal: "DOTS_THREE_HORIZONTAL",
        Fb: "FB",
        FbAlwaysWhite: "FB_ALWAYS_WHITE",
        FbInfoSmall: "FB_INFO_SMALL",
        None: "NONE",
      }),
      Bn = e({
        AutoPlayable: "AUTO_PLAYABLE",
        AutoPlayableWithAspectRatio: "AUTO_PLAYABLE_WITH_ASPECT_RATIO",
        BlurredImage: "BLURRED_IMAGE",
        BlurredPlayable: "BLURRED_PLAYABLE",
        Default: "DEFAULT",
        ImageWithPlayButton: "IMAGE_WITH_PLAY_BUTTON",
        InformTreatmentWithLabel: "INFORM_TREATMENT_WITH_LABEL",
        InformTreatmentWithWarningScreen:
          "INFORM_TREATMENT_WITH_WARNING_SCREEN",
        P2PPreviewImageWithTextOverlay: "P2P_PREVIEW_IMAGE_WITH_TEXT_OVERLAY",
        Placeholder: "PLACEHOLDER",
        Playable: "PLAYABLE",
        YoutubePlayer: "YOUTUBE_PLAYER",
      }),
      Wn = e({
        Accepted: "ACCEPTED",
        AlreadyPlayed: "ALREADY_PLAYED",
        Completed: "COMPLETED",
        Expired: "EXPIRED",
        Invited: "INVITED",
      }),
      qn = e({
        Arrived: "ARRIVED",
        Cancelled: "CANCELLED",
        Delayed: "DELAYED",
        Departed: "DEPARTED",
        OnTime: "ON_TIME",
        Unknown: "UNKNOWN",
      }),
      Un = e({ Draw: "DRAW", Option1: "OPTION1", Option2: "OPTION2" }),
      Vn = e({ Vote: "VOTE" }),
      Hn = e({
        MediaLabel: "MEDIA_LABEL",
        Misinformation: "MISINFORMATION",
        PostCover: "POST_COVER",
        PostLabel: "POST_LABEL",
        Private: "PRIVATE",
        Sensitive: "SENSITIVE",
        WarningScreens: "WARNING_SCREENS",
      }),
      Gn = e({ Accepted: "ACCEPTED", Ended: "ENDED", Invited: "INVITED" }),
      zn = e({
        Blur: "BLUR",
        Collage: "COLLAGE",
        InstagramIcon: "INSTAGRAM_ICON",
        Live: "LIVE",
        MessengerIcon: "MESSENGER_ICON",
        MultiPhoto: "MULTI_PHOTO",
        None: "NONE",
        Photo: "PHOTO",
        Pill: "PILL",
        ReelsIcon: "REELS_ICON",
        Video: "VIDEO",
        YoutubeShorts: "YOUTUBE_SHORTS",
        YoutubeVideo: "YOUTUBE_VIDEO",
      }),
      jn = e({
        Grid: "GRID",
        Hscroll: "HSCROLL",
        Portrait: "PORTRAIT",
        SharedStack: "SHARED_STACK",
        Single: "SINGLE",
        Vstack: "VSTACK",
      }),
      Kn = e({
        Active: "ACTIVE",
        Ended: "ENDED",
        Expired: "EXPIRED",
        Started: "STARTED",
      }),
      Qn = e({
        BlurredCircle: "BLURRED_CIRCLE",
        Default: "DEFAULT",
        DefaultWithGradient: "DEFAULT_WITH_GRADIENT",
        Rounded: "ROUNDED",
        TemplateAsset: "TEMPLATE_ASSET",
      }),
      Xn = e({ Paypal: "PAYPAL", Venmo: "VENMO" }),
      Yn = e({ Payment: "PAYMENT", Request: "REQUEST" }),
      Jn = e({
        LiveVideo: "LIVE_VIDEO",
        None: "NONE",
        ShortsVideo: "SHORTS_VIDEO",
        VodVideo: "VOD_VIDEO",
      }),
      Zn = e({ Ended: "ENDED", Missed: "MISSED", Started: "STARTED" }),
      er = e({ Audio: "AUDIO", Video: "VIDEO" }),
      tr = e({ Default: "DEFAULT", Overlay: "OVERLAY" }),
      nr = e({ Bold: "BOLD", Regular: "REGULAR" }),
      rr = e({ Daily: "DAILY", Weekly: "WEEKLY" }),
      or = e({
        Default: "DEFAULT",
        ExternalLinkIcon: "EXTERNAL_LINK_ICON",
        FacebookIcon: "FACEBOOK_ICON",
        InstagramIcon: "INSTAGRAM_ICON",
        ManusIcon: "MANUS_ICON",
        MessengerIcon: "MESSENGER_ICON",
        MetaAiIcon: "META_AI_ICON",
        MetaHorizonIcon: "META_HORIZON_ICON",
        OculusIcon: "OCULUS_ICON",
        ThreadsIcon: "THREADS_ICON",
        VibesIcon: "VIBES_ICON",
      }),
      ar = e({ Center: "CENTER", Left: "LEFT" }),
      ir = e({ Default: "DEFAULT" }),
      lr = e({
        FinalScore: "FINAL_SCORE",
        Generic: "GENERIC",
        Goal: "GOAL",
        RedCard: "RED_CARD",
      }),
      sr = e({
        None: "NONE",
        YoutubeShorts: "YOUTUBE_SHORTS",
        YoutubeVideo: "YOUTUBE_VIDEO",
      });
    ((i.AiBotEmbodimentTrigger = l),
      (i.BcnSlideMessagePollSelectionMode = s),
      (i.BcnSlideMessagePollStatus = u),
      (i.ClientInstructionType = c),
      (i.FoaUnifiedResponseSurfaceType = d),
      (i.GenAi3PExtCtaAnalyticsAction = m),
      (i.GenAi3PExtCtaKind = p),
      (i.GenAi3PExtCtaState = _),
      (i.GenAi3PExtCalendarEventOperation = f),
      (i.GenAi3PExtCalendarEventState = g),
      (i.GenAi3PExtConnectorPermissionRequestAction = h),
      (i.GenAiActionListRowType = y),
      (i.GenAiAddonActionAlignment = C),
      (i.GenAiAddonActionType = b),
      (i.GenAiAdsReferenceEntityType = v),
      (i.GenAiAffiliateAccountSetupStatus = S),
      (i.GenAiAffiliateIdentityType = R),
      (i.GenAiArtifactShareState = L),
      (i.GenAiArtifactType = E),
      (i.GenAiAvatarRowType = k),
      (i.GenAiClientResolvedValueType = I),
      (i.GenAiClippyArtifactType = T),
      (i.GenAiClippyFollowUpAttachmentType = D),
      (i.GenAiCodeBlockType = x),
      (i.GenAiCompactEntityActionType = $),
      (i.GenAiCompactEntityType = P),
      (i.GenAiConnectorActionKind = N),
      (i.GenAiDividerType = M),
      (i.GenAiFollowUpSuggestionCategory = w),
      (i.GenAiFollowUpSuggestionDestination = A),
      (i.GenAiFooterActionType = F),
      (i.GenAiHtmlCardAssetDelivery = O),
      (i.GenAiigBloomActionButtonType = B),
      (i.GenAiImageAssetQueryStatus = W),
      (i.GenAiImaginePrimitiveStatus = q),
      (i.GenAiImagineType = U),
      (i.GenAiInformTreatmentRenderingType = V),
      (i.GenAiLabelVariant = H),
      (i.GenAiMapItemMarkerType = G),
      (i.GenAiMapQueryStatus = z),
      (i.GenAiMediaHorizontalAlignment = j),
      (i.GenAiMediaShape = K),
      (i.GenAiMediaVerticalAlignment = Q),
      (i.GenAiMultiAgentPhase = X),
      (i.GenAiMultiAgentRenderingStyle = Y),
      (i.GenAiMultipleResponseLayoutType = J),
      (i.GenAiOrchestratorSearchEngine = Z),
      (i.GenAiPlaceDetailsItemOpeningStatus = ee),
      (i.GenAiPlaceDetailsItemPriceLevel = te),
      (i.GenAiPlaceDetailsItemType = ne),
      (i.GenAiPlanPhaseStatus = re),
      (i.GenAiPortraitStudioFraming = oe),
      (i.GenAiPostOrientation = ae),
      (i.GenAiPostType = ie),
      (i.GenAiProductSourceType = le),
      (i.GenAiProductSurface = se),
      (i.GenAiProfessionalConsentStatus = ue),
      (i.GenAiSearchPlannerStepStatus = ce),
      (i.GenAiSelectableTextAction = de),
      (i.GenAiSideChatContextualQueryIntent = me),
      (i.GenAiSlideDeckSlideStatus = pe),
      (i.GenAiSocialEntityItemType = _e),
      (i.GenAiSourceApp = fe),
      (i.GenAiSourcedItemType = ge),
      (i.GenAiSportsGameStatus = he),
      (i.GenAiSportsLeague = ye),
      (i.GenAiSportsSeasonType = Ce),
      (i.GenAiSubagentPhase = be),
      (i.GenAiThinkingStatusIcon = ve),
      (i.GenAiThinkingStatusSecondaryScreenId = Se),
      (i.GenAiThinkingStatusSecondaryScreenTabId = Re),
      (i.GenAiThinkingToolStatus = Le),
      (i.GenAiThirdPartyAccountLinkingIntegration = Ee),
      (i.GenAiThirdPartyAccountLinkingIntegrationStatus = ke),
      (i.GenAiThreadSurfingActionType = Ie),
      (i.GenAiThreadSurfingEntityType = Te),
      (i.GenAiThreadWidgetBarGraphMultiSeriesStyle = De),
      (i.GenAiThreadWidgetColorTheme = xe),
      (i.GenAiThreadWidgetIconName = $e),
      (i.GenAiThreadWidgetLineGraphDensity = Pe),
      (i.GenAiThreadWidgetLineGraphMultiSeriesStyle = Ne),
      (i.GenAiThreadWidgetTrendDirection = Me),
      (i.GenAiThreadWidgetTrendFavorability = we),
      (i.GenAiUnifiedResponseMessageGroupKind = Ae),
      (i.GenAiUnifiedResponseSectionType = Fe),
      (i.GenAiUpsellCardButtonAction = Oe),
      (i.GenAiUpsellCardButtonStyle = Be),
      (i.GenAiUpsellCardKind = We),
      (i.GenAiUpsellCardLoginCapability = qe),
      (i.GenAiVoicePreferenceCaptureCardState = Ue),
      (i.GenAiWeatherIconName = Ve),
      (i.GenAiWritingBlockAction = He),
      (i.GenAiWritingBlockFieldType = Ge),
      (i.GenAiWritingBlockKind = ze),
      (i.GenAiContextInjectionType = je),
      (i.GenAiPromptType = Ke),
      (i.ImmersivePostContentType = Qe),
      (i.MebSplitDatabaseExecutionType = Xe),
      (i.MpsBackupContentType = Ye),
      (i.MpsBackupOperation = Je),
      (i.MpsDeviceEpochStatus = Ze),
      (i.MpsEncryptedBackupMessageType = et),
      (i.MpsEncryptedPlaceholderErrorCode = tt),
      (i.MpsMessageBackupSource = nt),
      (i.MpsMessageRangeQueryDirection = rt),
      (i.MpsMessageTag = ot),
      (i.MpsQueryCaller = at),
      (i.MpsServerAttachmentUploadStatus = it),
      (i.MpsServerMessageUploadStatus = lt),
      (i.MpsUploadType = st),
      (i.SlvBasilConversationStarterType = ut),
      (i.SlvImagineImageOrientation = ct),
      (i.SlvPortraitStudioFraming = dt),
      (i.SlvPromptEditType = mt),
      (i.SlvReminderRecurrence = pt),
      (i.SlvResponseRole = _t),
      (i.SlvViewerAction = ft),
      (i.XmsgaiBotResponseImagineSource = gt),
      (i.XmsgaiInvocationOptions = ht),
      (i.XmsgaiLookupActionType = yt),
      (i.XmsgaiLookupEntityType = Ct),
      (i.XmsgaiProduct = bt),
      (i.XmsgAiAgentActivityStatus = vt),
      (i.XmsgApprovalAttentionMode = St),
      (i.XmsgApprovalDecisionKind = Rt),
      (i.XmsgApprovalIconKey = Lt),
      (i.XmsgApprovalLabelScope = Et),
      (i.XmsgApprovalPayloadType = kt),
      (i.XmsgApprovalPaymentMethod = It),
      (i.XmsgApprovalPaymentType = Tt),
      (i.XmsgApprovalRequestPresentation = Dt),
      (i.XmsgApprovalRequestPreviewAttachmentKind = xt),
      (i.XmsgctaType = $t),
      (i.XmsgContentBrandingOption = Pt),
      (i.Xmsge2EeGenAiEncryptedImageProductType = Nt),
      (i.Xmsge2EeGenAiEncryptedVideoProductType = Mt),
      (i.XmsgFeatureTags = wt),
      (i.XmsgGenAiBotResponseProductType = At),
      (i.XmsgGenAiBotSubscriptionProductType = Ft),
      (i.XmsgGenAiMessageType = Ot),
      (i.XmsgGenAiNestedUnifiedResponseType = Bt),
      (i.XmsgHighlightsTabMoment = Wt),
      (i.XmsgHighlightsTabReplySourceType = qt),
      (i.XmsgIgReceiverFetchContentType = Ut),
      (i.XmsgIgReceiverFetchXmaMediaNoteFetchParamsMessageType = Vt),
      (i.XmsgIgXmaActionType = Ht),
      (i.XmsgImageGlyphType = Gt),
      (i.XmsgInlineEntityType = zt),
      (i.XmsgMarketplaceJobsViewerRole = jt),
      (i.XmsgMarketplaceLightweightReplyType = Kt),
      (i.XmsgMarketplaceSmartRepliesTriggerType = Qt),
      (i.XmsgMediaDispatchKey = Xt),
      (i.XmsgMediaReactionType = Yt),
      (i.XmsgMediaSendOrigin = Jt),
      (i.XmsgMemoriesE2EeSendTemplateType = Zt),
      (i.XmsgMemoriesTemplateType = en),
      (i.XmsgMessageRequestStatus = tn),
      (i.XmsgMessageSendProductType = nn),
      (i.XmsgMessageStreamingProductType = rn),
      (i.XmsgMsgrReceiverFetchContentType = on),
      (i.XmsgMsgrReceiverFetchXmaLayoutType = an),
      (i.XmsgMsgrXmaActionType = ln),
      (i.XmsgMsgrXmaUnifiedQueryType = sn),
      (i.XmsgMustacheCtaType = un),
      (i.XmsgNoteMessageType = cn),
      (i.XmsgNoteModelType = dn),
      (i.XmsgNoteType = mn),
      (i.XmsgOculusMediaType = pn),
      (i.Xmsgp2MTextPaymentIdInteractionKind = _n),
      (i.XmsgPendingApprovalType = fn),
      (i.XmsgPowerUpStyle = gn),
      (i.XmsgReactionStyle = hn),
      (i.XmsgReportedMessageType = yn),
      (i.XmsgSpectraActionSource = Cn),
      (i.XmsgSpectraActionType = bn),
      (i.XmsgSpectraTakeDownActionType = vn),
      (i.XmsgStoryOverlayPollStyle = Sn),
      (i.XmsgStoryOverlayTagType = Rn),
      (i.XmsgStoryReplyType = Ln),
      (i.XmsgStreamStatusType = En),
      (i.XmsgSuggestedModerationActionType = kn),
      (i.XmsgTestEnum = In),
      (i.XmsgTestMinimalEnum = Tn),
      (i.XmsgTranscriptionStatus = Dn),
      (i.XmsgXmaArenaMarketStatus = xn),
      (i.XmsgXmaBizAiUnifiedResponseAttributionType = $n),
      (i.XmsgXmaBizAiUnifiedResponseSourceAttributionType = Pn),
      (i.XmsgXmaCodeBlockType = Nn),
      (i.XmsgXmaCompactGenericTemplateAccessoryType = Mn),
      (i.XmsgXmaCompactGenericTemplatePreviewStyle = wn),
      (i.XmsgXmaContentAttributionIcon = An),
      (i.XmsgXmaContentType = Fn),
      (i.XmsgXmaCtaIconType = On),
      (i.XmsgXmaCustomPreviewType = Bn),
      (i.XmsgXmaDailyGameChallengePlayerStatus = Wn),
      (i.XmsgXmaFlightStatusEnum = qn),
      (i.XmsgXmaGamePredictionOption = Un),
      (i.XmsgXmaGamePredictionType = Vn),
      (i.XmsgXmaGatingType = Hn),
      (i.XmsgXmaHorizonGamingChallengePlayerStatus = Gn),
      (i.XmsgXmaImageDecorationType = zn),
      (i.XmsgXmaLayoutType = jn),
      (i.XmsgXmaLiveLocationSessionState = Kn),
      (i.XmsgXmaMessagingAttachmentFaviconStyle = Qn),
      (i.XmsgXmaOpgP2pPaymentMethodType = Xn),
      (i.XmsgXmaOpgP2pTransactionType = Yn),
      (i.XmsgXmaOverlayContentType = Jn),
      (i.XmsgXmaRtcCallState = Zn),
      (i.XmsgXmaRtcCallType = er),
      (i.XmsgXmaStandardGenericBodyLayoutType = tr),
      (i.XmsgXmaStandardGenericBodyTitleStyle = nr),
      (i.XmsgXmaSubscriptionRecurrenceType = rr),
      (i.XmsgXmaSubtitleDecorationType = or),
      (i.XmsgXmaVStackLayoutHeaderAlignmentType = ar),
      (i.XmsgXmaVerifiedType = ir),
      (i.XmsgXmaWatchPartySoccerEventType = lr),
      (i.XmsgXmaYoutubePreviewMediaType = sr));
  },
  66,
);
