__d(
  "MessageMarketingIntegrityError",
  ["errorCode", "AdsError"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e = {
      MARKETING_MESSAGES__PHONE_NUMBER_MESSAGING_LIMIT_REACHED: 4017128,
      MARKETING_MESSAGES__REAL_NUMBER_DISPLAY_NAME_APPROVAL_FOR_WHATS_APP_BUSINESS: 4017127,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_IS_EMPTY: 4017129,
      MARKETING_MESSAGES__VIRTUAL_NUMBER_DISPLAY_NAME_APPROVAL_FOR_WHATS_APP_BUSINESS: 4017049,
      MARKETING_MESSAGES__WHATS_APP_BUSINESS_PHONE_NUMBER_UNVERIFIED: 4017092,
      MARKETING_MESSAGES__TEMPLATE_REVIEW_ISSUE: 4017014,
      MARKETING_MESSAGES__TEMPLATE_DISABLED: 4017034,
      MARKETING_MESSAGES__PROMOTED_WABA_UNAVAILABLE: 4017124,
      MARKETING_MESSAGES__WABA_POLICY_WARNING: 4017132,
      MARKETING_MESSAGES__PROMOTED_WABA_RESTRICTED: 4017126,
      ADS_MANAGER_MARKETING_MESSAGE__TEMPLATE_PAUSED_WITH_TARGETING_ISSUE: 4310007,
      MARKETING_MESSAGES__TEMPLATE_PAUSED_WITH_CONTENT_ISSUE: 4017134,
      MARKETING_MESSAGES__TEMPLATE_PAUSED: 4017031,
      MARKETING_MESSAGES__TEMPLATE_MEDIUM_QUALITY_SCORE_WITH_TARGETING_ISSUE: 4017135,
      MARKETING_MESSAGES__TEMPLATE_MEDIUM_QUALITY_SCORE_WITH_CONTENT_ISSUE: 4017136,
      MARKETING_MESSAGES__TEMPLATE_MEDIUM_QUALITY: 4017123,
      MARKETING_MESSAGES__PROMOTED_WABA_MISSING_FROM_USER: 4017138,
      ADS_MANAGER_MARKETING_MESSAGE__DUPLICATE_TEMPLATE_PAUSED_WITH_TARGETING_ISSUE: 4310008,
      ADS_MANAGER_MARKETING_MESSAGE__DUPLICATE_TEMPLATE_PAUSED_WITH_CONTENT_ISSUE: 4310009,
      MARKETING_MESSAGES__DUPLICATE_TEMPLATE_PAUSED: 4017144,
      MARKETING_MESSAGES__TEMPLATE_PAUSED_DUE_TO_UNKNOWN_REASON: 4017146,
      MARKETING_MESSAGES__TEMPLATE_PAUSED_DUE_TO_OTHER_AS_BLOCK_REASON: 4017147,
      MARKETING_MESSAGES__TEMPLATE_PAUSED_DUE_TO_NO_LONGER_NEEDED_REASON: 4017148,
      MARKETING_MESSAGES__DUPLICATE_TEMPLATE_PAUSED_DUE_TO_OTHER_AS_BLOCK_REASON: 4017149,
      MARKETING_MESSAGES__DUPLICATE_TEMPLATE_PAUSED_DUE_TO_UNKNOWN_REASON: 4017150,
      MARKETING_MESSAGES__DUPLICATE_TEMPLATE_PAUSED_DUE_TO_NO_LONGER_NEEDED_REASON: 4017151,
      MARKETING_MESSAGES__TEMPLATE_MEDIUM_QUALITY_DUE_TO_UNKNOWN_REASON: 4017153,
      MARKETING_MESSAGES__TEMPLATE_MEDIUM_QUALITY_DUE_TO_OTHER_AS_BLOCK_REASON: 4017154,
      MARKETING_MESSAGES__TEMPLATE_MEDIUM_QUALITY_DUE_TO_NO_LONGER_NEEDED_REASON: 4017152,
      MARKETING_MESSAGES__TEMPLATE_DISABLED_WITH_TARGETING_ISSUE: 4017156,
      MARKETING_MESSAGES__TEMPLATE_DISABLED_WITH_CONTENT_ISSUE: 4017157,
      MARKETING_MESSAGES__TEMPLATE_DISABLED_DUE_TO_UNKNOWN_REASON: 4017158,
      MARKETING_MESSAGES__TEMPLATE_DISABLED_DUE_TO_OTHER_AS_BLOCK_REASON: 4017159,
      MARKETING_MESSAGES__TEMPLATE_DISABLED_DUE_TO_NO_LONGER_NEEDED_REASON: 4017155,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_SIZE_BELOW_THRESHOLD: 4017161,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_SIZE_NOT_IDEAL: 4017254,
      MARKETING_MESSAGES__DEFAULT_SUBSCRIBER_POOL_IS_MISSING: 4017163,
      MARKETING_MESSAGES__TEMPLATE_REVIEW_ISSUE_WITH_NOT_ELIGIBLE_FOR_REVIEW: 4017170,
      MARKETING_MESSAGES__PROMOTED_WABA_RESTRICTED_AND_ELIGIBLE_FOR_APPEAL: 4017171,
      MARKETING_MESSAGES__TEMPLATE_IN_REVIEW_APPEAL_STATUS: 4017175,
      MARKETING_MESSAGES__PROMOTED_WABA_RESTRICTED_APPEAL_REVIEW_STATUS: 4017176,
      MARKETING_MESSAGES_TARGETING_CANNOT_BE_USED: 2909070,
      MARKETING_MESSAGES_PLACEMENT_CANNOT_BE_USED: 2909071,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_NO_LIFT_CRM_AUTOMATION_OFF: 4017190,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_CONTACT_SYNC_AUTOMATION_OFF: 4017189,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_SIZE_BELOW_RECOMMENDED_SIZE_AND_AUTOMATION_ON: 4017188,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_AUTOMATION_OFF: 4017187,
      MARKETING_MESSAGES__SUBSCRIBER_POOL_CONVERSION_SIGNAL_OFF: 4017192,
      MARKETING_MESSAGES__MESSENGER_PAGE_NOT_CONNECTED: 4017243,
      MARKETING_MESSAGES__MESSENGER_PAGE_MESSAGING_DISABLED: 4017245,
      MARKETING_MESSAGES__MESSENGER_SUBSCRIBER_POOL_MISSING: 4017246,
    };
    function u(t) {
      return e[t];
    }
    var c = (function (e) {
      function t(t, n, r) {
        return e.call(this, t, n, r) || this;
      }
      return (babelHelpers.inheritsLoose(t, e), t);
    })(r("AdsError"));
    ((l.messageMarketingErrorCode = u), (l.MessageMarketingAdsError = c));
  },
  98,
);
