__d(
  "VideoPlayerHTML5CaptionsDisplay",
  [
    "csx",
    "cx",
    "CSS",
    "CaptionSettings",
    "DOM",
    "DOMQuery",
    "VideoPlayerHTML5CaptionsDisplayStyle",
    "clearTimeout",
    "setTimeout",
  ],
  function (t, n, r, o, a, i, l, s, u) {
    var e = (function () {
      function e(e) {
        var t,
          n,
          a = this,
          i = e.append,
          l = e.areCaptionsAutogenerated,
          s = e.boundingBox,
          u = e.drawer,
          c = e.existingNodesContainer;
        ((this.$4 = null),
          (this.$5 = null),
          (this.$6 = ""),
          (this.$7 = null),
          (this.$8 = null),
          (this.$9 = !1),
          (this.$10 = null),
          (this.$12 = null));
        var d = (t = o("DOMQuery").scry(c, "._30vn")[0]) != null ? t : null,
          m = d && (n = o("DOMQuery").find(d, "._30vo")) != null ? n : null;
        (d || (d = r("DOM").create("div", { className: "_30vn hidden_elem" })),
          m ||
            ((m = r("DOM").create("span", { className: "_30vo hidden_elem" })),
            r("DOM").setContent(d, m)),
          (this.$1 = l),
          (this.$4 = d),
          (this.$5 = m),
          (this.$12 = i(d)),
          (this.$7 = u),
          (this.$8 = u.addListener("reposition", function (e) {
            return a.$13(e);
          })),
          (this.$11 = s),
          this.$14());
      }
      var t = e.prototype;
      return (
        (t.handleBoundingBoxChanged = function (t) {
          ((this.$11 = t), this.$14());
        }),
        (t.handleCaptionsChanged = function (t, n) {
          this.$9 || (this.$15(t), this.$16(n));
        }),
        (t.setAutogeneratedCaptionsOptions = function (t) {
          this.$2 = t;
        }),
        (t.setCaptionsStyle = function (t) {
          var e = this.$10,
            n = t || o("CaptionSettings").DefaultCaptionSettings;
          if (e)
            (e.setBackgroundColor(n.background.color),
              e.setBackgroundOpacity(n.background.opacity),
              e.setTextColor(n.text.color),
              e.setTextSize(n.text.size),
              e.setTextOpacity(n.text.opacity),
              e.setTextTypeface(n.text.typeface),
              e.setTextEdge(n.text.edge),
              e.updateStyle());
          else {
            var a = this.$5,
              i = this.$4;
            a &&
              i &&
              (this.$10 = new (r("VideoPlayerHTML5CaptionsDisplayStyle"))(
                a,
                i,
                n,
                "center",
              ));
          }
        }),
        (t.showCaptions = function () {
          var e = this,
            t = this.$4;
          t && o("CSS").removeClass(t, "hidden_elem");
          var n = this.$7;
          n && (n.reposition(), n.reserve());
          var a = this.$2;
          a != null &&
            this.$1 &&
            (this.$17(),
            r("clearTimeout")(this.$3),
            (this.$3 = r("setTimeout")(function () {
              ((e.$3 = null), e.$18());
            }, a.duration)));
        }),
        (t.hideCaptions = function () {
          var e = this.$4;
          e && o("CSS").addClass(e, "hidden_elem");
          var t = this.$7;
          (t && t.release(),
            this.$3 && (r("clearTimeout")(this.$3), (this.$3 = null)));
        }),
        (t.destroy = function () {
          var e = this.$8;
          e && (e.remove(), (this.$8 = null));
          var t = this.$7;
          t && (t.release(), t.removeAllListeners(), (this.$7 = null));
          var n = this.$12;
          (n && n(),
            (this.$4 = null),
            (this.$5 = null),
            this.$3 && (r("clearTimeout")(this.$3), (this.$3 = null)));
        }),
        (t.$14 = function () {
          var e = this.$11,
            t = this.$4;
          t &&
            (e.width < 350
              ? (o("CSS").removeClass(t, "_30vp"),
                o("CSS").addClass(t, "_30vq"))
              : e.width < 800
                ? (o("CSS").removeClass(t, "_30vp"),
                  o("CSS").removeClass(t, "_30vq"))
                : (o("CSS").removeClass(t, "_30vq"),
                  o("CSS").addClass(t, "_30vp")));
        }),
        (t.$18 = function () {
          ((this.$9 = !1),
            this.handleCaptionsChanged([], { textAlignment: "center" }));
        }),
        (t.$17 = function () {
          var e = this.$2;
          e != null &&
            (this.handleCaptionsChanged([e.text], { textAlignment: "center" }),
            (this.$9 = !0));
        }),
        (t.$13 = function (t) {
          var e = this.$4;
          e && r("DOM").setAttributes(e, { style: "bottom:" + t + "px;" });
        }),
        (t.$16 = function (t) {
          var e = t.textAlignment,
            n = this.$10;
          if (n) (n.setTextAlignment(e), n.updateStyle());
          else {
            var a = this.$5,
              i = this.$4;
            a &&
              i &&
              (this.$10 = new (r("VideoPlayerHTML5CaptionsDisplayStyle"))(
                a,
                i,
                o("CaptionSettings").DefaultCaptionSettings,
                e,
              ));
          }
        }),
        (t.$15 = function (t) {
          var e = t
              .map(function (e) {
                return e.trim();
              })
              .filter(function (e) {
                return !!e;
              })
              .join("\n")
              .trim(),
            n = this.$6;
          this.$6 = e;
          var a = this.$4,
            i = this.$5,
            l = this.$7;
          !a ||
            !i ||
            !l ||
            (this.$14(),
            e !== n && r("DOM").setContent(i, e),
            e
              ? (o("CSS").removeClass(i, "hidden_elem"),
                l.setHeight(a.offsetHeight))
              : (o("CSS").addClass(i, "hidden_elem"), l.setHeight(0)));
        }),
        e
      );
    })();
    l.default = e;
  },
  98,
);
