__d(
  "AdsUEditorCampaignGroupSectionPluginKeys",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = [
        "campaignGroupABTestSummarySection",
        "campaignGroupAccountControlsSection",
        "campaignGroupAccountErrorsSection",
        "campaignGroupAccountSpendLimitWarningSection",
        "campaignGroupAdLabelsSection",
        "campaignGroupAgencyFeeSection",
        "campaignGroupAllLevelsNameSection",
        "campaignGroupBudgetSection",
        "campaignGroupFrequencyControlSection",
        "campaignGroupCatalogGuidanceSection",
        "campaignGroupCTXBudgetCBOSimilarAdvertiserBasedRecommendationSection",
        "campaignGroupCTXBudgetCBOZeroConversionWarningSection",
        "campaignGroupCTXDynamicZOBudgetRecommendationSection",
        "campaignGroupCBOZeroConversionWarningSection",
        "campaignGroupHighCostWarningSection",
        "campaignGroupCollaborativeAdsSection",
        "campaignGroupDebugSection",
        "campaignGroupDetailsSection",
        "campaignGroupDisabledAdWarningContainer",
        "campaignGroupErrorsSection",
        "campaignGroupExistingCustomersReportingSection",
        "campaignGroupFragmentationGuidanceSection",
        "campaignGroupGuidanceMessagesGroupSection",
        "campaignGroupMessageMarketingNameSection",
        "campaignGroupNameSection",
        "campaignGroupInsightsSection",
        "campaignGroupPreflightRecommendationHubSection",
        "campaignGroupPromotedObjectSection",
        "campaignGroupRegulatedCategorySection",
        "campaignGroupSignalLossLimitsSection",
        "campaignGroupSKAdNetworkSection",
        "campaignGroupSplitTestConvergenceMessageSection",
        "campaignGroupSplitTestFreeformSection",
        "campaignGroupTestProgressCardSection",
        "campaignGroupToplineDetailsSection",
        "campaignGroupUnsupportedReasonSection",
        "campaignGroupZeroOutcomeBudgetGuidanceSection",
        "campaignGroupOutcomeForecasterEstimatesSection",
        "campaignGroupFrequencyEstimatesSection",
        "campaignGroupInformedCampaignCreationSection",
        "campaignGroupReelsTrendingAdsSection",
        "campaignGroupHp1PremiumSection",
        "campaignGroupLiveVideoAdSection",
      ],
      l = e;
    i.default = l;
  },
  66,
);
