__d(
  "VideoPlayerController",
  [
    "csx",
    "cx",
    "invariant",
    "Arbiter",
    "Banzai",
    "Bootloader",
    "CSS",
    "CVCv3VideoControllerHelper",
    "CaptionSettings",
    "CurrentUser",
    "DOM",
    "DOMDimensions",
    "DOMQuery",
    "DelegatedVideoPriorityAdjuster",
    "ErrorUtils",
    "EventEmitter",
    "FBLogger",
    "FullScreen",
    "LiveVideoCopyrightActionSubscription",
    "MediaController",
    "Parent",
    "Promise",
    "Run",
    "SRTVideoData",
    "ScriptPath",
    "ShakaConstants",
    "SphericalVideoPlayerEvents",
    "SubscriptionsHandler",
    "TahoeVariables.experimental",
    "URI",
    "VideoAsyncLoggerHelper",
    "VideoChannelViewChainLengthManager",
    "VideoControllerPlayingStateEmitter",
    "VideoLiveTrace",
    "VideoMimeTypes",
    "VideoPermalinkURI",
    "VideoPlaybackQuality",
    "VideoPlayerABRQualityTracker",
    "VideoPlayerApiEvents",
    "VideoPlayerConnectionQuality",
    "VideoPlayerExperiments",
    "VideoPlayerFormatsMap",
    "VideoPlayerHTML5Experiments",
    "VideoPlayerLogger",
    "VideoPlayerLoggerErrorStates",
    "VideoPlayerLoggerFallbackReasons",
    "VideoPlayerQualitiesArray",
    "VideoPlayerReasonTransitionHelper",
    "VideoPlayerResizeSettings",
    "VideoPlayerShakaBandwidthEstimator",
    "VideoPlayerShakaConfig",
    "VideoPlayerStateBasedLoggingEvents.experimental",
    "VideoPlayerUIComponentDrawer",
    "VideoPlayerUIComponentDrawerController",
    "VideoPlayerVolumeSettings",
    "VideoViewabilityKeyEvents",
    "VideoViewabilityLogging",
    "VideoVisibilityObserver",
    "VideosRenderingInstrumentation",
    "ViewportTrackingHelper",
    "Visibility",
    "WebSessionExtender",
    "XVideoDataControllerRouteBuilder",
    "canVideoPlayType",
    "clearInterval",
    "clearTimeout",
    "collectDataAttributes",
    "enumerate",
    "forwardEvent",
    "getContextualParent",
    "getElementPosition",
    "getFullScreenElement",
    "getVideoComponentName",
    "getViewportDimensions",
    "guid",
    "ifRequired",
    "logVideosClickTracking",
    "mapObject",
    "performanceAbsoluteNow",
    "requireWeak",
    "setInterval",
    "setTimeout",
    "uniqueID",
  ],
  function (t, n, r, o, a, i, l, s, u, c) {
    var e,
      d,
      m,
      p,
      _,
      f = null;
    r("requireWeak")("LiveVideoPlayerStore", function (e) {
      return (f = e);
    });
    var g = 1;
    function h() {
      return r("VideoPlayerHTML5Experiments").useMonotonicallyIncreasingTimers
        ? (d || (d = r("performanceAbsoluteNow")))()
        : Date.now();
    }
    function y(e) {
      var t,
        n = r("VideoPlayerFormatsMap");
      return e && (t = n[e]) != null ? t : null;
    }
    var C = (function (t) {
      function a(e, n) {
        var a,
          i,
          l = e.accessToken,
          s = e.ad_client_token,
          u = e.allowCrossPageTransition,
          c = e.alwaysShowCaptions,
          d = e.apiConfig,
          p = e.apiModule,
          f = e.autoplay_setting,
          g = e.broadcasterOrigin,
          y = e.broadcastId,
          C = e.captionsAutogeneratedIndicatorConfig,
          b = e.captionSettings,
          v = e.chaining_token,
          S = e.components,
          R = e.customLiveManifestUrlParams,
          L = e.customLoggingProps,
          E = e.device_id,
          k = e.disableLogging,
          I = e.iframeEmbedReferrer,
          T = e.immediateplay_reason,
          D = e.isAdsPreview,
          x = e.isBroadcast,
          $ = e.isBroadcaster,
          P = e.isInjectedAds,
          N = e.isInstreamAd,
          M = e.isReactPlayer,
          w = e.keepPlayingOnDialog,
          A = e.liveLinearChannelId,
          F = e.offsettype,
          O = e.offsetvalue,
          B = e.permalinkShareID,
          W = e.player_version,
          q = e.playerOrigin,
          U = e.playerSuborigin,
          V = e.playerSuboriginDerived,
          H = e.positionInUnit,
          G = e.projection,
          z = e.reaction_video_channel_subtype,
          j = e.reaction_video_channel_type,
          K = e.should_autoplay,
          Q = e.shouldLogVideoViewability,
          X = e.source,
          Y = e.trackingCodes,
          J = e.upstreamPlayerSource,
          Z = e.useInlineFallback,
          ee = e.video_channel_id,
          te = e.video_id,
          ne = e.video_ids,
          re = e.video_list_id,
          oe = e.video_path,
          ae = e.video_url,
          ie = e.video_urls,
          le = n.container_element,
          se = n.root_element,
          ue = n.video_element;
        if (
          ((i = t.call(this) || this),
          (i.$VideoPlayerController22 = !1),
          (i.$VideoPlayerController40 = !1),
          (i.$VideoPlayerController78 = new Set(
            r("VideoPlayerStateBasedLoggingEvents.experimental")
              .StateBasedLoggingEventNames,
          )),
          (i.$VideoPlayerController79 = 0),
          (i.$VideoPlayerController111 = []),
          (i.$VideoPlayerController117 = null),
          (i.$VideoPlayerController118 = null),
          (i.$VideoPlayerController119 = new (r("EventEmitter"))()),
          (i.$VideoPlayerController123 = null),
          (i.$VideoPlayerController125 = !1),
          (i.$VideoPlayerController153 = function () {
            i.$VideoPlayerController40 = !1;
            var e = i.getContainerNode(),
              t = i.isFullscreen();
            if (
              (o("CSS").conditionClass(e, "_1hwh", t),
              t
                ? (e.style.paddingBottom = "0")
                : (e.removeAttribute("data-fullscreen"),
                  (e.style.paddingBottom = i.$VideoPlayerController102)),
              !t &&
                i.$VideoPlayerController28 &&
                (i.$VideoPlayerController28.unsubscribe(),
                (i.$VideoPlayerController28 = null)),
              i.$VideoPlayerController39 != t)
            ) {
              (i.logFullscreenChanged(t),
                i.$VideoPlayerController14.setContext(
                  "player_format",
                  i.$VideoPlayerController126(t, i.$VideoPlayerController73),
                ));
              var n = o("DOMDimensions").getElementDimensions(e);
              (i.isPlayerVersion("silvercity") ||
                i.setVideoPlayerAPIDimensions(n.width, n.height),
                i.emit("toggleFullscreen"),
                t
                  ? i.removeOffsetStylings()
                  : (i.addOffsetStylings(),
                    r("Arbiter").inform("video_fullscreen_change", {})));
            }
            i.$VideoPlayerController39 = t;
          }),
          (i.emitHeartbeat = function () {
            if (!i.isState("playing") || !i.getVideoNode()) {
              (i.stopHeartbeat(), i.$VideoPlayerController20.stopUnifiedCVC());
              return;
            }
            (r("VideoPlayerHTML5Experiments").heartbeatSkipOnBuffering &&
              i.isBuffering()) ||
              i.getVideoAPI().logHeartbeat();
          }),
          (i.$VideoPlayerController165 = function () {
            if (
              !r("VideoPlayerExperiments").allowBufferingErrorForHiddenTab &&
              r("Visibility").isHidden()
            ) {
              (i.$VideoPlayerController164(),
                (i.$VideoPlayerController99 = r("setTimeout")(
                  i.$VideoPlayerController165,
                  i.$VideoPlayerController163(),
                )));
              return;
            }
            var e =
              i.getVideoAPI().isPaused() !== void 0
                ? !i.getVideoAPI().isPaused()
                : i.getState() === "playing";
            e &&
              (i.logError({
                error: "BUFFERING_TIMEOUT",
                message:
                  "video has been in buffering state for over " +
                  i.$VideoPlayerController163() +
                  "ms.",
                isPlayback: i.isPlayRequestPending(),
              }),
              i.$VideoPlayerController164(),
              i.emit("error", o("VideoPlayerLoggerFallbackReasons").TIMEOUT));
          }),
          (i.$VideoPlayerController114 = r("guid")()),
          (i.$VideoPlayerController48 = 0),
          (i.$VideoPlayerController26 = 0),
          (i.$VideoPlayerController25 = new Map()),
          (i.$VideoPlayerController81 = {}),
          L && i.setLogEntryPropertyGetters(L),
          K === void 0)
        ) {
          var ce = new Error(
            "Must pass should_autoplay to " + i.constructor.name + "!",
          );
          throw (ce.stack, ce);
        }
        ((i.$VideoPlayerController125 = k != null ? k : !1),
          (i.$VideoPlayerController124 = I),
          (i.$VideoPlayerController115 = H),
          (i.$VideoPlayerController24 = new (r(
            "VideoPlayerUIComponentDrawerController",
          ))()),
          (i.$VideoPlayerController13 = new Map()),
          (i.$VideoPlayerController61 = G),
          (i.$VideoPlayerController1 = l),
          (i.$VideoPlayerController71 = !!K),
          (i.$VideoPlayerController72 = T),
          (i.$VideoPlayerController8 = f),
          (i.$VideoPlayerController2 = s),
          (i.$VideoPlayerController55 = !1),
          (i.$VideoPlayerController91 = ue),
          (i.$VideoPlayerController70 = se),
          (i.$VideoPlayerController15 = le),
          (i.$VideoPlayerController35 = !1),
          (i.$VideoPlayerController36 = !1),
          (i.$VideoPlayerController60 = W),
          (i.$VideoPlayerController90 =
            (a = te != null ? te : ne == null ? void 0 : ne[0]) != null
              ? a
              : ""),
          (i.$VideoPlayerController93 =
            ae != null ? ae : ie == null ? void 0 : ie[0]),
          (i.$VideoPlayerController92 = oe),
          (i.$VideoPlayerController11 = v),
          (i.$VideoPlayerController87 = ee),
          (i.$VideoPlayerController88 = re),
          (i.$VideoPlayerController56 = B),
          (i.$VideoPlayerController57 = q),
          (i.$VideoPlayerController58 = U != null ? U : X),
          (i.$VideoPlayerController59 = V != null ? V : null),
          (i.$VideoPlayerController33 = x),
          (i.$VideoPlayerController41 = N),
          (i.$VideoPlayerController19 = R != null ? R : null),
          (i.$VideoPlayerController83 = Y),
          (i.$VideoPlayerController3 = c),
          (i.$VideoPlayerController75 =
            b == null ? o("CaptionSettings").DefaultCaptionSettings : b),
          (i.$VideoPlayerController76 = C),
          (i.$VideoPlayerController31 = r("uniqueID")()),
          (i.$VideoPlayerController67 = j),
          (i.$VideoPlayerController68 = z),
          (i.$VideoPlayerController118 = y),
          (i.$VideoPlayerController120 = D),
          (i.$VideoPlayerController121 = P),
          (i.$VideoPlayerController122 = w),
          (i.$VideoPlayerController5 = p),
          (i.$VideoPlayerController4 = d),
          (i.$VideoPlayerController77 =
            i.$VideoPlayerController5.getStartMutedFromConfig(
              i.$VideoPlayerController4,
            )),
          (i.$VideoPlayerController45 =
            i.$VideoPlayerController5.getStreamTypeFromConfig(
              i.$VideoPlayerController4,
            )),
          (i.$VideoPlayerController44 =
            i.$VideoPlayerController5.getIsServableViaFbmsFromConfig(
              i.$VideoPlayerController4,
            )),
          (i.$VideoPlayerController42 =
            i.$VideoPlayerController5.getIsPlayingLiveFromConfig(
              i.$VideoPlayerController4,
            )),
          (i.$VideoPlayerController43 =
            i.$VideoPlayerController5.getIsGamingFromConfig(
              i.$VideoPlayerController4,
            )),
          i.isLiveVideo() &&
            i.$VideoPlayerController5.getIsLiveTraceEnabledOnPlayer(
              i.$VideoPlayerController4,
            ) &&
            i.$VideoPlayerController118 != null &&
            (i.$VideoPlayerController117 = new (r("VideoLiveTrace"))(
              i.$VideoPlayerController118,
              i.$VideoPlayerController114,
              r("CurrentUser").getAccountID(),
            )),
          (i.$VideoPlayerController113 = !!Q),
          (i.$VideoPlayerController38 =
            i.$VideoPlayerController5.getIsSpherical(
              i.$VideoPlayerController4,
            )));
        var de = {
          is_ad: i.isAd(),
          is_live: i.$VideoPlayerController42,
          player_format: i.$VideoPlayerController126(i.isFullscreen(), X),
          connection_quality: o("VideoPlayerConnectionQuality").evaluate(
            function () {
              return r("VideoPlayerShakaBandwidthEstimator").getBandwidth();
            },
          ),
          is_spherical: i.$VideoPlayerController38,
          content_category: "general",
          latency_level: "normal",
          servable_via_fbms: void 0,
          servable_via_fmbs: void 0,
        };
        ((de.servable_via_fmbs = !1),
          (i.$VideoPlayerController14 = new (r("VideoPlayerShakaConfig"))(de)),
          (i.$VideoPlayerController123 = A),
          (i.$VideoPlayerController20 = new (r("CVCv3VideoControllerHelper"))(
            i,
          )),
          i.$VideoPlayerController125 && i.$VideoPlayerController20.disable(),
          l != null && i.$VideoPlayerController20.setAccessToken(l),
          i.$VideoPlayerController20.setLinearChannelID(A),
          i.$VideoPlayerController45 === "progressive"
            ? (i.$VideoPlayerController105 = r(
                "VideoPlayerExperiments",
              ).progressiveBufferingErrorTimeout)
            : i.isLiveVideo()
              ? (i.$VideoPlayerController105 = r(
                  "VideoPlayerExperiments",
                ).liveBufferingErrorTimeout)
              : (i.$VideoPlayerController105 = r(
                  "VideoPlayerExperiments",
                ).bufferingErrorTimeout),
          (i.$VideoPlayerController106 = i.$VideoPlayerController105),
          r("VideoPlayerExperiments").createVideoVisibilityObserver &&
            i.$VideoPlayerController127(),
          (i.$VideoPlayerController37 =
            i.$VideoPlayerController5.getIsFacecastAudioFromConfig(
              i.$VideoPlayerController4,
            )),
          (i.$VideoPlayerController85 = !!Z),
          (i.$VideoPlayerController97 = new Set()),
          (i.$VideoPlayerController98 = g),
          (i.$VideoPlayerController99 = null),
          (i.$VideoPlayerController100 = !!u),
          (i.$VideoPlayerController101 = !!M),
          (i.$VideoPlayerController102 =
            i.getContainerNode().style.paddingBottom),
          (i.$VideoPlayerController103 = F),
          (i.$VideoPlayerController104 = O),
          (i.$VideoPlayerController107 = !1),
          (i.$VideoPlayerController108 = !1),
          (i.$VideoPlayerController84 = J),
          (i.$VideoPlayerController23 = r("Arbiter").subscribe(
            "DOM/destroy",
            function (e, t) {
              o("Parent").bySelector(i.getVideoNode(), t) &&
                (i.pause("unloaded"), i.destroy());
            },
          )),
          (i.$VideoPlayerController18 = 0));
        var me = (m || (m = r("URI"))).getRequestURI(),
          pe = o("VideoPermalinkURI").parse(me),
          _e = parseFloat(me.getQueryData().t),
          fe = pe ? pe.video_id == i.$VideoPlayerController90 : !1;
        if (
          (_e &&
            fe &&
            i.$VideoPlayerController4 &&
            (i.$VideoPlayerController4.startTimestamp = _e),
          r("VideoPlayerHTML5Experiments")
            .useVpcPlayingStateForPrioritization &&
            i.$VideoPlayerController4 &&
            (i.$VideoPlayerController4.vpcPlayingStateEmitter = new (r(
              "VideoControllerPlayingStateEmitter",
            ))(i)),
          i.$VideoPlayerController14.getBool(
            "oz_www_safely_log_player_seeks",
            !1,
          ) &&
            i.$VideoPlayerController4 &&
            (i.$VideoPlayerController4.seekHandler = function (e) {
              i.isState("playing")
                ? (i.pause(), i.seek(e), i.play("seek_initiated"))
                : i.seek(e);
            }),
          (i.$VideoPlayerController112 = new (r(
            "DelegatedVideoPriorityAdjuster",
          ))()),
          r("VideoPlayerExperiments").adjustPriorityBasedOnAutoplayIndex &&
            i.$VideoPlayerController4 &&
            (i.$VideoPlayerController4.streamPriorityAdjuster =
              i.$VideoPlayerController112),
          (i.$VideoPlayerController17 = null),
          (i.$VideoPlayerController53 = null),
          (i.$VideoPlayerController73 = X),
          (i.$VideoPlayerController50 =
            E != null
              ? new (r("VideoPlayerLogger"))(X, { device_id: E })
              : new (r("VideoPlayerLogger"))(X)),
          i.$VideoPlayerController125 && i.$VideoPlayerController50.disable(),
          i.$VideoPlayerController73 === "tahoe" && i.focusOnContainerNode(),
          i.collectFeedTrackingData(),
          i.$VideoPlayerController50.setScriptPath(
            o("ScriptPath").getScriptPath(),
          ),
          i.$VideoPlayerController50.setFrameCountGetters(
            function () {
              return i.$VideoPlayerController91 != null
                ? o("VideoPlaybackQuality").getDroppedFrames(
                    i.$VideoPlayerController91,
                  )
                : null;
            },
            function () {
              return i.$VideoPlayerController91 != null
                ? o("VideoPlaybackQuality").getTotalFrames(
                    i.$VideoPlayerController91,
                  )
                : null;
            },
          ),
          (i.$VideoPlayerController63 = o(
            "VideosRenderingInstrumentation",
          ).retrieveRenderTime(i.getRootNode())),
          (i.$VideoPlayerController62 = h() - i.$VideoPlayerController63),
          d &&
            (d.subtitleDrawer = i.registerDrawer(
              r("VideoPlayerUIComponentDrawer").priorities.Subtitles,
              0,
            )),
          (i.$VideoPlayerController74 = "loading"),
          i.$VideoPlayerController128(!1),
          i.$VideoPlayerController5.isImplementationUnavailable(
            i.$VideoPlayerController85,
          ))
        )
          return (
            i.$VideoPlayerController129(),
            babelHelpers.assertThisInitialized(i)
          );
        if (
          (i.$VideoPlayerController130(),
          (i.$VideoPlayerController7 = new (r("SubscriptionsHandler"))()),
          i.$VideoPlayerController7.addSubscriptions(
            r("Banzai").subscribe(r("Banzai").SHUTDOWN, function () {
              (i.pause("unloaded"), i.destroy());
            }),
          ),
          i.$VideoPlayerController71 &&
            (r("VideoPlayerExperiments").delayAutoplayUntilAfterLoad
              ? i.$VideoPlayerController7.addSubscriptions(
                  o("Run").onAfterLoad(function () {
                    return i.$VideoPlayerController131();
                  }),
                )
              : i.$VideoPlayerController131()),
          (i.$VideoPlayerController21 = 0),
          (i.$VideoPlayerController69 = !1),
          (i.$VideoPlayerController27 = i.$VideoPlayerController132()),
          i.$VideoPlayerController7.addSubscriptions(
            r("Banzai").subscribe(r("Banzai").SHUTDOWN, function () {
              (i.pause("unloaded"), i.destroy());
            }),
          ),
          !i.$VideoPlayerController133())
        ) {
          var ge = new Set(["DialogX", "PhotoSnowlift", "Spotlight"]);
          i.$VideoPlayerController7.addSubscriptions(
            r("Arbiter").subscribe("layer_shown", function (e, t) {
              if (
                ge.has(t.type) &&
                (t.type !== "Spotlight" &&
                  r("Bootloader").loadModules(
                    ["VideoAutoplayControllerX"],
                    function (e) {
                      e.setShouldAutoplay(!1);
                    },
                    "VideoPlayerController",
                  ),
                (i.$VideoPlayerController21 += 1),
                r("VideoPlayerExperiments").ignoreDialogCounter ||
                  i.$VideoPlayerController21 > 0)
              ) {
                var n =
                  i.$VideoPlayerController73 === "tahoe" && i.isLiveVideo();
                i.isState("playing") &&
                  !(n && r("TahoeVariables.experimental").neverAutoPauseLive) &&
                  i.$VideoPlayerController122 !== !0 &&
                  (i.pause("page_visibility_initiated"),
                  (i.$VideoPlayerController69 = !0));
              }
            }),
            r("Arbiter").subscribe("layer_hidden", function (e, t) {
              ge.has(t.type) &&
                (r("VideoPlayerExperiments").addViewabilityFixEnabled
                  ? (i.$VideoPlayerController21 = Math.max(
                      0,
                      i.$VideoPlayerController21 - 1,
                    ))
                  : (i.$VideoPlayerController21 -= 1),
                i.$VideoPlayerController21 === 0 &&
                  (t.type !== "Spotlight" &&
                    r("Bootloader").loadModules(
                      ["VideoAutoplayControllerX"],
                      function (e) {
                        e.setShouldAutoplay(!0);
                      },
                      "VideoPlayerController",
                    ),
                  i.$VideoPlayerController69 &&
                    (i.play("page_visibility_initiated"),
                    (i.$VideoPlayerController69 = !1))));
            }),
          );
        }
        return (
          i.$VideoPlayerController7.addSubscriptions(
            r("Arbiter").subscribe("share_dialog_closed", function (e, t) {
              t.root &&
                i.$VideoPlayerController70 &&
                o("ViewportTrackingHelper").isDescendantOf(
                  i.$VideoPlayerController70,
                  t.root,
                ) &&
                i.mute();
            }),
          ),
          i.$VideoPlayerController7.addSubscriptions(
            o("Run").onLeave(function () {
              i.$VideoPlayerController100 ||
                (r("VideoPlayerExperiments").persistentWNSEnabled &&
                  i.$VideoPlayerController73 === "watch_scroll") ||
                i.cleanOnLeave();
            }),
          ),
          (i.$VideoPlayerController12 = S || []),
          i.$VideoPlayerController12.forEach(function (e) {
            var t = r("getVideoComponentName")(e) || "<MalformedComponent>";
            e && typeof e.enable == "function"
              ? r("VideoPlayerExperiments").enableComponentGuards
                ? (_ || (_ = r("ErrorUtils"))).applyWithGuard(
                    e.enable,
                    e,
                    [i],
                    null,
                    "VideoPlayerController Component Enable Guard: " + t,
                  )
                : e.enable(i)
              : r("FBLogger")("video").warn(
                  "no_enable_method_on_component: %s",
                  t,
                );
          }),
          (i.$VideoPlayerController52 = 1),
          (i.$VideoPlayerController94 = !1),
          i.$VideoPlayerController91 &&
            (i.shouldCalculateViewability()
              ? ((i.$VideoPlayerController94 =
                  r("VideoPlayerExperiments").enableViewabilityLogging ||
                  (r("VideoPlayerExperiments")
                    .enableVideoSampledViewabilityLogging &&
                    !!i.$VideoPlayerController113)),
                i.isInstreamAd() &&
                  (i.$VideoPlayerController94 =
                    i.$VideoPlayerController94 &&
                    (r("VideoPlayerExperiments")
                      .enableInstreamAdViewabilityLogging ||
                      (r("VideoPlayerExperiments")
                        .enableVideoSampledViewabilityLogging &&
                        !!i.$VideoPlayerController113))))
              : (i.$VideoPlayerController94 = r(
                  "VideoPlayerExperiments",
                ).enableViewabilityLoggingForOrganic)),
          i.$VideoPlayerController94 &&
            i.$VideoPlayerController91 &&
            (i.$VideoPlayerController95 = new (r("VideoViewabilityLogging"))(
              i,
              i.$VideoPlayerController91,
              i.$VideoPlayerController70,
              i.$VideoPlayerController15,
            )),
          (i.$VideoPlayerController32 = !1),
          (i.$VideoPlayerController34 = $),
          i.isLiveVideo() &&
            (i.$VideoPlayerController16 = r(
              "LiveVideoCopyrightActionSubscription",
            ).subscribe(i.getVideoID(), function (e) {
              if (e.live_video_copyright_action_subscribe != null) {
                var t =
                  e.live_video_copyright_action_subscribe.action.toLowerCase();
                switch (t) {
                  case "block":
                    if (i.$VideoPlayerController34 === !0) break;
                    (i.emit("blockVideo"), i.destroy());
                    break;
                  case "mute":
                    (i.emit("blockAudio", i.$VideoPlayerController34),
                      (i.$VideoPlayerController32 = !0),
                      i.$VideoPlayerController34 !== !0 && i.mute());
                    break;
                  case "unmute":
                    (i.emit("unblockAudio", i.$VideoPlayerController34),
                      (i.$VideoPlayerController32 = !1),
                      i.$VideoPlayerController34 !== !0 && i.unmute());
                    break;
                }
                i.$VideoPlayerController134(
                  e.live_video_copyright_action_subscribe.action,
                  e.live_video_copyright_action_subscribe.timestamp,
                );
              }
            })),
          i.$VideoPlayerController135(),
          i
        );
      }
      babelHelpers.inheritsLoose(a, t);
      var i = a.prototype;
      return (
        (i.$VideoPlayerController135 = function () {
          var e = "v:" + this.$VideoPlayerController31;
          (this.addListener("beginPlayback", function () {
            o("WebSessionExtender").subscribe(e, "video-on-blue");
          }),
            this.addListener("pausePlayback", function () {
              o("WebSessionExtender").unsubscribe(e);
            }),
            this.addListener("finishPlayback", function () {
              o("WebSessionExtender").unsubscribe(e);
            }));
        }),
        (i.setVideoPriorityAdjustment = function (t) {
          this.$VideoPlayerController112.notifyAdjustment(t);
        }),
        (i.addListener = function () {
          for (var e, n = arguments.length, r = new Array(n), o = 0; o < n; o++)
            r[o] = arguments[o];
          var a = (e = t.prototype.addListener).call.apply(e, [this].concat(r));
          return (
            r[0] === "visibilityChanged" && this.$VideoPlayerController127(),
            a
          );
        }),
        (i.setOverrideConfig = function (t) {
          this.$VideoPlayerController14.setOverrideConfig(t);
        }),
        (i.$VideoPlayerController127 = function () {
          var e = this;
          this.$VideoPlayerController109 ||
            (this.$VideoPlayerController91 || c(0, 3694),
            (this.$VideoPlayerController109 = new (r(
              "VideoVisibilityObserver",
            ))(this.$VideoPlayerController91)),
            this.$VideoPlayerController109.addListener(
              "visibilityChanged",
              function (t) {
                return e.emit("visibilityChanged", t);
              },
            ));
        }),
        (i.setAutoScrollIntoView = function (t) {
          this.$VideoPlayerController22 = !t;
        }),
        (i.setDetectionID = function (t) {
          this.$VideoPlayerController116 = t;
        }),
        (i.destroy = function (t) {
          var e = t != null ? t : {};
          if (!(this.isState("destroyed") || this.$VideoPlayerController36)) {
            ((this.$VideoPlayerController36 = !0),
              this.$VideoPlayerController109 &&
                (this.$VideoPlayerController109.destroy(),
                (this.$VideoPlayerController109 = null)));
            for (
              var n = this.$VideoPlayerController12 || [], o = n.length - 1;
              o >= 0;
              o--
            ) {
              var a = n[o],
                i = r("getVideoComponentName")(a) || "<MalformedComponent>";
              a && typeof a.disable == "function"
                ? r("VideoPlayerExperiments").enableComponentGuards
                  ? (_ || (_ = r("ErrorUtils"))).applyWithGuard(
                      a.disable,
                      a,
                      [this],
                      null,
                      "VideoPlayerController Component Disable Guard: " + i,
                    )
                  : a.disable(this)
                : r("FBLogger")("video").warn(
                    "no_disable_method_on_component: %s",
                    i,
                  );
            }
            (this.$VideoPlayerController86 && this.getVideoAPI().destroy(e),
              this.$VideoPlayerController50.stopCollectingVideoFramesInfo(),
              this.setState("destroyed"),
              this.$VideoPlayerController7.release(),
              e.skipRemoveAllListeners !== !0 && this.removeAllListeners(),
              this.$VideoPlayerController23 &&
                (this.$VideoPlayerController23.unsubscribe(),
                (this.$VideoPlayerController23 = null)),
              this.stopHeartbeat(),
              this.$VideoPlayerController20.stopUnifiedCVC(),
              this.$VideoPlayerController20.leave(),
              this.$VideoPlayerController16 &&
                (this.$VideoPlayerController16.unsubscribe(),
                (this.$VideoPlayerController16 = null)),
              this.$VideoPlayerController6 &&
                this.$VideoPlayerController6.release());
          }
        }),
        (i.collectFeedTrackingData = function () {
          var e = null;
          if (this.$VideoPlayerController83) {
            for (
              var t = { tn: "", "tn-debug": "," }, n = {}, a = 0;
              a < this.$VideoPlayerController83.length;
              a++
            ) {
              var i = JSON.parse(this.$VideoPlayerController83[a]);
              if (!Array.isArray(i))
                for (var l in i)
                  t[l] !== void 0
                    ? (n[l] === void 0 && (n[l] = []), n[l].push(i[l]))
                    : n[l] === void 0 && (n[l] = i[l]);
            }
            for (var s in t) n[s] !== void 0 && (n[s] = n[s].join(t[s]));
            e = { ft: n };
          } else {
            for (var u = !1, c = this.getRootNode(); c; ) {
              if (
                c instanceof Element &&
                o("CSS").matchesSelector(c, "._4oep")
              ) {
                u = !0;
                break;
              }
              c = r("getContextualParent")(c);
            }
            u
              ? (e = {})
              : this.isState("replayed")
                ? (e = r("collectDataAttributes")(window.event.target, ["ft"]))
                : (e = r("collectDataAttributes")(this.getRootNode(), ["ft"]));
          }
          this.$VideoPlayerController50.setFTData(e);
        }),
        (i.setStillFrameEnabled = function (t) {
          var e = this.getVideoAPI();
          e.setStillFrameEnabled != null && e.setStillFrameEnabled(t);
        }),
        (i.isFallbackRecoverable = function () {
          return !!this.$VideoPlayerController80;
        }),
        (i.setFallbackSources = function (t) {
          this.$VideoPlayerController80 = t;
        }),
        (i.setRelativeSphericalOrientation = function (t, n) {
          this.emit(
            o("SphericalVideoPlayerEvents").SET_RELATIVE_SPHERICAL_ORIENTATION,
            t,
            n,
          );
        }),
        (i.setSphericalOrientation = function (t, n) {
          this.emit(
            o("SphericalVideoPlayerEvents").SET_ABSOLUTE_SPHERICAL_ORIENTATION,
            t,
            n,
          );
        }),
        (i.setSphericalFieldOfView = function (t) {
          this.emit(o("SphericalVideoPlayerEvents").SET_FIELD_OF_VIEW, t);
        }),
        (i.isSpherical = function () {
          return this.$VideoPlayerController38;
        }),
        (i.getVideoPlayerID = function () {
          return this.$VideoPlayerController31;
        }),
        (i.focusOnContainerNode = function () {
          this.$VideoPlayerController15 &&
            this.$VideoPlayerController15.focus();
        }),
        (i.setLogEntryPropertyGetters = function (t) {
          var e = this;
          Object.keys(t).forEach(function (n) {
            var r = t[n];
            typeof r == "function"
              ? e.$VideoPlayerController25.set(n, r)
              : (e.$VideoPlayerController81[n] = r);
          });
        }),
        (i.removeLogEntryPropertyGetters = function (t) {
          var e = this,
            n;
          (typeof t == "string"
            ? (n = [t])
            : Array.isArray(t)
              ? (n = t)
              : (n = Object.keys(t)),
            n.forEach(function (t) {
              (e.$VideoPlayerController25.delete(t),
                delete e.$VideoPlayerController81[t]);
            }));
        }),
        (i.$VideoPlayerController130 = function () {
          var e = this;
          this.$VideoPlayerController5.onImplementationReady(
            this.getVideoNode(),
            function () {
              return e.onApiReady();
            },
          );
        }),
        (i.isImplementationUnavailable = function () {
          return (
            this.$VideoPlayerController5.isImplementationUnavailable(
              this.$VideoPlayerController85,
            ) && !this.$VideoPlayerController85
          );
        }),
        (i.getIsInChannel = function () {
          return this.$VideoPlayerController73 === "channel";
        }),
        (i.updateSource = function (t) {
          if (this.$VideoPlayerController73) {
            var e = y(this.$VideoPlayerController73),
              n = y(t);
            (this.$VideoPlayerController50.updateSource(t),
              this.$VideoPlayerController14.setContext(
                "player_format",
                this.$VideoPlayerController126(this.isFullscreen(), t),
              ),
              e &&
                e !== n &&
                this.$VideoPlayerController96 === !0 &&
                (r("VideoPlayerExperiments").delayFormatChangeEvent
                  ? this.isState("playing") &&
                    this.$VideoPlayerController39 !== !0
                    ? (this.logEvent("player_format_changed"),
                      (this.$VideoPlayerController47 = n))
                    : (this.$VideoPlayerController47 = e)
                  : this.logEvent("player_format_changed")),
              (this.$VideoPlayerController73 = t));
          }
        }),
        (i.getSource = function () {
          return this.$VideoPlayerController50.getSource();
        }),
        (i.getPlayerOrigin = function () {
          return this.$VideoPlayerController57;
        }),
        (i.getPlayerSuborigin = function () {
          return this.$VideoPlayerController58;
        }),
        (i.getUpstreamPlayerSource = function () {
          return this.$VideoPlayerController84;
        }),
        (i.hasLooped = function () {
          return this.$VideoPlayerController52 > 1;
        }),
        (i.$VideoPlayerController129 = function () {
          var e = {
            error: "IMPLEMENTATION_NOT_SUPPORTED",
            state: o("VideoPlayerLoggerErrorStates").PLAYER_FAILURE,
            error_description: "Implementation unavailable",
            error_user_info: this.getDebugInfo(),
          };
          (this.logEvent("error", e), (this.$VideoPlayerController71 = !1));
        }),
        (i.logError = function (t) {
          var e = (this.$VideoPlayerController46 = t),
            n = e.error,
            a = e.httpStatus,
            i = e.isPlayback,
            l = e.message,
            s = e.stack,
            u = e.url,
            c = this.getDebugInfo();
          s && (c.player.stack = s);
          var d = a == null || a === "" ? n : a;
          (delete c.player.loggedError, delete c.player.lastError);
          var m = {
            error: n,
            error_description: l,
            error_user_info: c,
            error_code: d,
            error_domain: n,
            resource_url: u,
            state: i
              ? o("VideoPlayerLoggerErrorStates").PLAYBACK_FAILURE
              : o("VideoPlayerLoggerErrorStates").PLAYER_FAILURE,
          };
          (a === 410 ||
            a === "410" ||
            ((this.$VideoPlayerController49 = this.logEvent("error", m)),
            this.destroy()),
            this.$VideoPlayerController38 &&
              Math.random() < 0.01 &&
              r("FBLogger")("360video").warn(
                "360 video player error: %s %s",
                n,
                l,
              ),
            i &&
              this.$VideoPlayerController55 &&
              this.$VideoPlayerController128(!1));
        }),
        (i.setRotation = function (t) {
          this.getVideoAPI().setRotation(t);
        }),
        (i.setDimensions = function (t, n) {
          var e = this.getContainerNode();
          ((e.style.width = t + "px"), (e.style.height = n + "px"));
          var o = this.getVideoNode();
          if (
            ((o.style.width = t + "px"),
            (o.style.height = n + "px"),
            this.isState("loading"))
          )
            this.$VideoPlayerController64 = { width: t, height: n };
          else {
            if (
              this.isPlayerVersion("silvercity") &&
              (this.$VideoPlayerController39 === !0 ||
                r("VideoPlayerResizeSettings").disable_flash_set_dimensions)
            )
              return;
            this.setVideoPlayerAPIDimensions(t, n);
          }
        }),
        (i.isPlayRequestPending = function () {
          return this.$VideoPlayerController55;
        }),
        (i.$VideoPlayerController128 = function (t) {
          this.$VideoPlayerController55 !== t &&
            ((this.$VideoPlayerController55 = t),
            this.emit("pendingPlayRequestChanged"));
        }),
        (i.updateAutoplayRestrained = function () {
          var e = this;
          r("ifRequired")("VideoPlayerHTML5Shaka", function (t) {
            var n = t.isAutoplayBandwidthRestrained(e.$VideoPlayerController42);
            e.$VideoPlayerController136(n);
          });
        }),
        (i.$VideoPlayerController136 = function (t) {
          t
            ? this.emit("turnOffAutoplay", { reason: "poor_network_quality" })
            : this.emit("resumeAutoplay", { reason: "poor_network_quality" });
          var e = this.getVideoAPI();
          e && e.setPreloadDisabled(t);
        }),
        (i.restoreStreamBufferSize = function () {
          var e = this.getVideoAPI();
          e && e.restoreStreamBufferSize();
        }),
        (i.getDataInsertionPosition = function () {
          return (
            this.$VideoPlayerController27 &&
            this.$VideoPlayerController27.getAttribute(
              "data-insertion-position",
            )
          );
        }),
        (i.getDataFt = function () {
          return (
            this.$VideoPlayerController27 &&
            this.$VideoPlayerController27.getAttribute("data-ft")
          );
        }),
        (i.play = function (t) {
          var e = this,
            n = null;
          t instanceof r("VideoPlayerReasonTransitionHelper")
            ? (n = t.getReason())
            : (n = t);
          var a = this.getVideoNodeNullable();
          if (
            a &&
            "scrollIntoView" in a &&
            n === "user_initiated" &&
            !this.$VideoPlayerController22
          ) {
            var i = this.getDOMPosition(),
              l = i.y >= 0,
              s = i.y + i.height <= r("getViewportDimensions")().height;
            l ? s || a.scrollIntoView(!1) : a.scrollIntoView(!0);
          }
          if (
            (this.$VideoPlayerController137(),
            this.$VideoPlayerController54 ||
              (this.$VideoPlayerController54 = n),
            (this.$VideoPlayerController110 = this.getOption(
              "VideoWithCommercialBreak",
              "controller",
            )),
            this.$VideoPlayerController110 &&
              this.$VideoPlayerController110.shouldPlayPreRollAds(n))
          ) {
            this.$VideoPlayerController110.schedulePreRollAds();
            return;
          }
          if (!this.$VideoPlayerController55) {
            this.$VideoPlayerController53 = this.$VideoPlayerController138();
            var u = this.$VideoPlayerController139({ debug_reason: n }),
              c = this.$VideoPlayerController73;
            (r("VideoPlayerExperiments").delayFormatChangeEvent &&
              c &&
              this.$VideoPlayerController96 === !0 &&
              this.$VideoPlayerController47 != null &&
              y(c) !== this.$VideoPlayerController47 &&
              this.$VideoPlayerController39 !== !0 &&
              (this.logEvent("player_format_changed"),
              (this.$VideoPlayerController47 = y(c))),
              r("VideoPlayerExperiments").logRequestedPlayingAsync
                ? o("VideoAsyncLoggerHelper").operateAsync(
                    function () {
                      e.logEvent("requested_playing", u);
                    },
                    ["started_playing", "unpaused"],
                    this.$VideoPlayerController119,
                  )
                : this.logEvent("requested_playing", u),
              (this.$VideoPlayerController96 = !0));
          }
          (this.$VideoPlayerController$p_140(n),
            this.emit("playRequested", n),
            this.sendPlayRequest(n),
            n === "loop_initiated" && this.$VideoPlayerController52++);
        }),
        (i.sendPlayRequest = function (t) {
          var e = this;
          if (this.isState("fallback")) {
            (this.emit("fallbackPlay"),
              r("VideoPlayerExperiments").endBufferingOnFallbackPlay &&
                this.$VideoPlayerController50.endBuffering());
            return;
          }
          (this.$VideoPlayerController128(!0),
            this.isState("loading")
              ? (this.$VideoPlayerController65 = { reason: t })
              : (!this.getVideoAPI().isMuted() &&
                  this.$VideoPlayerController51 === !0 &&
                  (r("VideoPlayerExperiments").logUnmutedAsync
                    ? o("VideoAsyncLoggerHelper").operateAsync(
                        function () {
                          e.logEvent("unmuted");
                        },
                        ["started_playing", "unpaused"],
                        this.$VideoPlayerController119,
                      )
                    : this.logEvent("unmuted")),
                (this.$VideoPlayerController51 = !1),
                this.$VideoPlayerController141(),
                this.getVideoAPI().play(t)));
        }),
        (i.getOriginalPlayReason = function () {
          return this.$VideoPlayerController54;
        }),
        (i.reset = function () {
          var t = this,
            r = (e || (e = n("Promise"))).resolve();
          if (
            this.isState("loading") ||
            (this.isState("fallback") && !this.isFallbackRecoverable())
          )
            return r;
          (this.resetPositions(), this.$VideoPlayerController142());
          var o = e.resolve();
          return (
            this.$VideoPlayerController86 &&
              this.$VideoPlayerController86.destroy != null &&
              (o = this.$VideoPlayerController86.destroy()),
            (this.$VideoPlayerController86 = null),
            this.setState("loading"),
            (r = o.then(function () {
              t.$VideoPlayerController130();
            })),
            r
          );
        }),
        (i.detachRootNode = function () {
          var e = this;
          this.$VideoPlayerController70 &&
            (r("DOM").remove(this.$VideoPlayerController70),
            !(this.isState("fallback") || this.isState("loading")) &&
              (this.setState("loading"),
              this.$VideoPlayerController5.onImplementationReady(
                this.getVideoNode(),
                function () {
                  return e.$VideoPlayerController143();
                },
              )));
        }),
        (i.getVideoAPI = function () {
          return (
            this.$VideoPlayerController86 || c(0, 3695),
            this.$VideoPlayerController86
          );
        }),
        (i.getVideoNodeNullable = function () {
          return this.$VideoPlayerController91;
        }),
        (i.getVideoNode = function () {
          return this.getVideoNodeNullable();
        }),
        (i.getRootNodeNullable = function () {
          return this.$VideoPlayerController70;
        }),
        (i.getRootNode = function () {
          return this.getRootNodeNullable();
        }),
        (i.getContainerNodeNullable = function () {
          return this.$VideoPlayerController15;
        }),
        (i.getContainerNode = function () {
          return this.getContainerNodeNullable();
        }),
        (i.getVideoResolution = function () {
          var e = this.getVideoNode();
          return { height: e.videoHeight, width: e.videoWidth };
        }),
        (i.$VideoPlayerController143 = function () {
          (this.setState("ready"),
            (this.$VideoPlayerController51 = !this.getVideoAPI().isMuted()),
            (this.$VideoPlayerController82 = !this.$VideoPlayerController3),
            this.getVideoAPI().setSubtitlesStyle != null &&
              this.getVideoAPI().setSubtitlesStyle(
                this.$VideoPlayerController75,
              ),
            this.getVideoAPI().setAutogeneratedCaptionsOptions != null &&
              this.getVideoAPI().setAutogeneratedCaptionsOptions(
                this.$VideoPlayerController76,
              ),
            this.$VideoPlayerController65 &&
              (this.sendPlayRequest(this.$VideoPlayerController65.reason),
              (this.$VideoPlayerController65 = null)),
            this.$VideoPlayerController64 &&
              (this.setDimensions(
                this.$VideoPlayerController64.width,
                this.$VideoPlayerController64.height,
              ),
              (this.$VideoPlayerController64 = null)),
            this.$VideoPlayerController66 === !0 &&
              (this.getVideoAPI().unmute(),
              (this.$VideoPlayerController66 = null)));
        }),
        (i.onApiReady = function () {
          var e = this;
          (this.$VideoPlayerController4 &&
            ((this.$VideoPlayerController4.id = this.$VideoPlayerController31),
            (this.$VideoPlayerController4.customLiveManifestUrlParams =
              this.$VideoPlayerController19),
            this.$VideoPlayerController80 &&
              (this.$VideoPlayerController4.fallbackSources =
                this.$VideoPlayerController80),
            (this.$VideoPlayerController4.playerOrigin =
              this.$VideoPlayerController57),
            (this.$VideoPlayerController4.playerSuborigin =
              this.$VideoPlayerController58),
            (this.$VideoPlayerController4.getSource = function () {
              return e.getSource();
            }),
            (this.$VideoPlayerController4.shakaConfig =
              this.$VideoPlayerController14),
            (this.$VideoPlayerController4.playerInstanceKey =
              this.$VideoPlayerController114),
            this.$VideoPlayerController117 &&
              (this.$VideoPlayerController4.videoLiveTrace =
                this.$VideoPlayerController117),
            (this.$VideoPlayerController4.disableLogging =
              this.$VideoPlayerController125)),
            (this.$VideoPlayerController86 = new this.$VideoPlayerController5(
              this.getVideoNode(),
              this.$VideoPlayerController4,
            )),
            this.$VideoPlayerController144(),
            this.getVideoAPI().setup(),
            this.$VideoPlayerController143());
          var t = { is_auto_played: this.isAutoplayable() };
          (this.logEvent("player_loaded", t),
            this.$VideoPlayerController86 &&
              this.$VideoPlayerController50.setABRQualityTracker(
                new (r("VideoPlayerABRQualityTracker"))(
                  this.$VideoPlayerController86.getLocalEstimator(),
                ),
              ));
          var n = this.getVideoProjection();
          (n && (this.$VideoPlayerController61 = n), this.emit("apiReady"));
        }),
        (i.getLocalEstimator = function () {
          return this.$VideoPlayerController86
            ? this.$VideoPlayerController86.getLocalEstimator()
            : null;
        }),
        (i.runOnApiReady = function (t) {
          (t === void 0 && (t = function () {}),
            this.isState("loading") ? this.once("apiReady", t) : t());
        }),
        (i.resetPositions = function () {
          this.$VideoPlayerController18 = 0;
        }),
        (i.getCurrentTimePosition = function () {
          if (this.isState("playing")) {
            var e = this.getVideoAPI().getCurrentTimePosition();
            e != null && e !== void 0 && (this.$VideoPlayerController18 = e);
          }
          return this.$VideoPlayerController18;
        }),
        (i.getBufferEndPosition = function () {
          if (this.isState("loading")) return 0;
          var e = this.getVideoAPI().getBufferEndPosition();
          return e != null ? e : this.getCurrentTimePosition();
        }),
        (i.$VideoPlayerController137 = function () {
          if (!this.$VideoPlayerController9) {
            o("VideoChannelViewChainLengthManager").registerChainingInfos(
              this.getVideoID(),
              this.$VideoPlayerController11,
            );
            var e = this.getVideoID();
            if (this.$VideoPlayerController11) {
              var t = this.$VideoPlayerController11.decode();
              e = t.root_id;
            }
            this.$VideoPlayerController9 = o(
              "VideoChannelViewChainLengthManager",
            ).getLoggingData(e);
          }
        }),
        (i.$VideoPlayerController145 = function (t) {
          this.$VideoPlayerController128(!1);
          var e = t.position;
          (e !== void 0 && (this.$VideoPlayerController18 = e),
            this.setState("playing"),
            this.areHLSActive() && this.$VideoPlayerController146(),
            this.startHeartbeat(),
            this.$VideoPlayerController20.startUnifiedCVC());
        }),
        (i.$VideoPlayerController147 = function (t) {
          var e = t.position;
          (this.$VideoPlayerController117 &&
            this.isState("playing") &&
            this.$VideoPlayerController117.onUpdateStatus(t),
            e !== void 0 && (this.$VideoPlayerController18 = e),
            (this.$VideoPlayerController17 =
              this.getVideoAPI().getCurrentlyPlayingVideoStreamInfoID()));
        }),
        (i.$VideoPlayerController148 = function (t) {
          return this.$VideoPlayerController97.has(t);
        }),
        (i.runOnceOnApiEventLogged = function (t, n) {
          if (this.$VideoPlayerController148(t)) n();
          else
            var e = this.addListener("apiEventLogged", function (r) {
              r === t && (n(), e.remove());
            });
        }),
        (i.$VideoPlayerController149 = function (t) {
          var e = t.event;
          (this.$VideoPlayerController97.add(e),
            delete t.event,
            this.logEvent(e, t),
            this.emit("apiEventLogged", e));
        }),
        (i.$VideoPlayerController150 = function () {
          (this.isState("finished") || this.setState("paused"),
            this.stopHeartbeat(),
            this.$VideoPlayerController20.stopUnifiedCVC());
        }),
        (i.$VideoPlayerController151 = function (t) {
          var e = t.position;
          e !== void 0 && (this.$VideoPlayerController18 = e);
        }),
        (i.$VideoPlayerController152 = function () {
          (this.setState("finished"),
            (this.$VideoPlayerController69 = !1),
            this.stopHeartbeat(),
            this.$VideoPlayerController20.stopUnifiedCVC());
        }),
        (i.getVolume = function () {
          return this.getVideoAPI().getVolume();
        }),
        (i.$VideoPlayerController126 = function (t, n) {
          var e;
          return t
            ? "full_screen"
            : n
              ? (e = y(n)) != null
                ? e
                : "unknown"
              : "inline";
        }),
        (i.logFullscreenChanged = function (t) {
          var e = {
            player_format: this.$VideoPlayerController126(
              t,
              this.$VideoPlayerController73,
            ),
          };
          r("VideoPlayerHTML5Experiments").enteredExitedFsLoggingFix
            ? this.logEvent(t ? "entered_fs" : "exited_fs", e)
            : this.logEvent(t ? "entered_fs" : "exited_fs");
        }),
        (i.setVideoPlayerAPIDimensions = function (t, n) {
          this.getVideoAPI().setDimensions != null &&
            this.getVideoAPI().setDimensions(t, n);
        }),
        (i.removeOffsetStylings = function () {
          var e = this.$VideoPlayerController104;
          e != null &&
            (this.$VideoPlayerController103 === 1
              ? (this.getVideoNode().style.setProperty("left", "0"),
                o("CSS").removeClass(this.getVideoNode(), "_blh"))
              : this.$VideoPlayerController103 === 0 &&
                (this.getVideoNode().style.setProperty("top", "0"),
                o("CSS").removeClass(this.getVideoNode(), "_bli")));
        }),
        (i.addOffsetStylings = function () {
          var e = this.$VideoPlayerController104;
          e != null &&
            (this.$VideoPlayerController103 === 1
              ? (this.getVideoNode().style.setProperty("left", e + "px"),
                o("CSS").addClass(this.getVideoNode(), "_blh"))
              : this.$VideoPlayerController103 === 0 &&
                (this.getVideoNode().style.setProperty("top", e + "px"),
                o("CSS").addClass(this.getVideoNode(), "_bli")));
        }),
        (i.hasDialog = function () {
          return this.$VideoPlayerController21 > 0;
        }),
        (i.isTahoe = function () {
          return this.$VideoPlayerController73 === "tahoe";
        }),
        (i.isFullscreen = function () {
          return (
            this.$VideoPlayerController40 ||
            (r("FullScreen").isFullScreen() &&
              this.$VideoPlayerController15 === r("getFullScreenElement")())
          );
        }),
        (i.toggleFullscreen = function () {
          var e = this,
            t = this.isFullscreen(),
            n = this.getContainerNode();
          r("FullScreen").toggleFullScreen(n) &&
            (t ||
              ((this.$VideoPlayerController40 = !0),
              n.setAttribute("data-fullscreen", "true")),
            o("CSS").addClass(n, "_1hwh"),
            (this.$VideoPlayerController28 = r("FullScreen").subscribe(
              "changed",
              function () {
                return e.$VideoPlayerController153();
              },
            )));
        }),
        (i.instreamVideoStart = function () {
          o("CSS").addClass(this.getContainerNode(), "_24pm");
        }),
        (i.instreamVideoEnd = function () {
          o("CSS").removeClass(this.getContainerNode(), "_24pm");
        }),
        (i.unmute = function () {
          (this.$VideoPlayerController34 !== !0 &&
            this.$VideoPlayerController32) ||
            (this.isState("loading")
              ? (this.$VideoPlayerController66 = !0)
              : (this.getVideoAPI().unmute(),
                r("VideoPlayerVolumeSettings").saveVolume(
                  r("VideoPlayerVolumeSettings").getLastVolumeBeforeMute(),
                ),
                this.$VideoPlayerController82 &&
                  this.getVideoAPI().areSubtitlesActive() &&
                  this.$VideoPlayerController154()));
        }),
        (i.isAudioBlocked = function () {
          return this.$VideoPlayerController32;
        }),
        (i.isMuted = function () {
          return this.$VideoPlayerController86
            ? this.getVideoAPI().isMuted()
            : this.$VideoPlayerController77;
        }),
        (i.mute = function () {
          (this.$VideoPlayerController82 &&
            !this.getVideoAPI().areSubtitlesActive() &&
            this.$VideoPlayerController154(),
            this.getVideoAPI().mute(),
            r("VideoPlayerVolumeSettings").saveVolume(0));
        }),
        (i.getMediaID = function () {
          return this.getVideoID();
        }),
        (i.getPlaybackDuration = function () {
          return this.getVideoAPI().getPlaybackDuration();
        }),
        (i.getPlayerFormat = function () {
          return this.$VideoPlayerController126(
            this.isFullscreen(),
            this.$VideoPlayerController73,
          );
        }),
        (i.getVideoID = function () {
          return this.$VideoPlayerController90;
        }),
        (i.getVideoChannelID = function () {
          return this.$VideoPlayerController87;
        }),
        (i.getVideoListID = function () {
          return this.$VideoPlayerController88;
        }),
        (i.getVideoURL = function () {
          return this.$VideoPlayerController93;
        }),
        (i.$VideoPlayerController144 = function () {
          var e = this,
            t = this.getVideoAPI(),
            n = new (r("SubscriptionsHandler"))();
          this.$VideoPlayerController6 = n;
          var o = {
            buffered: function () {
              return e.setBuffering(!1);
            },
            buffering: function () {
              return e.setBuffering(!0);
            },
            bufferingProgress: function (n) {
              return e.$VideoPlayerController155(n);
            },
            streamInterrupted: function () {
              return e.$VideoPlayerController50.startInterrupt();
            },
            streamResumed: function () {
              return e.$VideoPlayerController50.endInterrupt();
            },
            beginPlayback: function (n) {
              return e.$VideoPlayerController145(n);
            },
            updateStatus: function (n) {
              return e.$VideoPlayerController147(n);
            },
            logEvent: function (n) {
              return e.$VideoPlayerController149(n.logData);
            },
            pausePlayback: function () {
              return e.$VideoPlayerController150();
            },
            seekEnd: function (n) {
              return e.$VideoPlayerController151(n);
            },
            clickForTracking: function () {
              return r("logVideosClickTracking")(e.getVideoNode());
            },
            error: function (n) {
              return e.logError(n);
            },
            finishPlayback: function () {
              return e.$VideoPlayerController152();
            },
            networkInterrupted: function () {
              return e.$VideoPlayerController156();
            },
            networkResumed: function () {
              return e.$VideoPlayerController157();
            },
            replicaSwitch: function (n) {
              return e.switchReplicaSet(n);
            },
          };
          (n.addSubscriptions.apply(
            n,
            Object.keys(o).map(function (e) {
              return t.addListener(e, o[e]);
            }),
          ),
            n.addSubscriptions.apply(
              n,
              r("VideoPlayerApiEvents").map(function (n) {
                return r("forwardEvent")(t, e, n);
              }),
            ));
        }),
        (i.$VideoPlayerController142 = function () {
          this.$VideoPlayerController6 &&
            this.$VideoPlayerController6.release();
        }),
        (i.seek = function (t, n) {
          (this.emit("seekRequested", t, n), this.getVideoAPI().seek(t));
        }),
        (i.pause = function (t) {
          (this.isState("loading")
            ? (this.$VideoPlayerController65 = null)
            : this.isState("playing")
              ? this.getVideoAPI().pause(t)
              : this.$VideoPlayerController55 && this.getVideoAPI().pause(t),
            this.$VideoPlayerController128(!1),
            (this.$VideoPlayerController69 = !1),
            this.$VideoPlayerController158(t),
            this.emit("pauseRequested", t));
        }),
        (i.stopHeartbeat = function () {
          (r("clearInterval")(this.$VideoPlayerController30),
            (this.$VideoPlayerController30 = null),
            this.$VideoPlayerController20.stopUnifiedCVC());
        }),
        (i.startHeartbeat = function () {
          this.$VideoPlayerController30 ||
            !r("VideoPlayerHTML5Experiments").heartbeatIntervalMS ||
            (this.$VideoPlayerController30 = r("setInterval")(
              this.emitHeartbeat,
              r("VideoPlayerHTML5Experiments").heartbeatIntervalMS,
            ));
        }),
        (i.isPlayerVersion = function (t) {
          return (
            this.getPlayerVersion() === t ||
            (this.$VideoPlayerController101 &&
              this.$VideoPlayerController159(t) === this.getPlayerVersion())
          );
        }),
        (i.isHtml5Player = function () {
          return (
            this.isPlayerVersion("pleasantville") || this.isPlayerVersion("oz")
          );
        }),
        (i.isAutoplayable = function () {
          return this.$VideoPlayerController71;
        }),
        (i.getImmediatePlayReason = function () {
          return this.$VideoPlayerController72;
        }),
        (i.$VideoPlayerController160 = function () {
          return o("ViewportTrackingHelper").isVisible(this.getVideoNode(), 0);
        }),
        (i.$VideoPlayerController131 = function () {
          var e = this;
          if (r("Visibility").isHidden()) {
            var t = r("Visibility").once(r("Visibility").VISIBLE, function () {
              return e.$VideoPlayerController131();
            });
            r("VideoPlayerExperiments").unsubscribeImmediateplay &&
              this.$VideoPlayerController7.addSubscriptions(t);
          } else {
            if (
              !this.$VideoPlayerController160() &&
              this.$VideoPlayerController72 !== "watch_time_not_logged" &&
              this.$VideoPlayerController72 !== "gbm_not_logged_autploay"
            ) {
              r("FBLogger")("video").warn(
                "immediateplay on a hidden video player: %s %s %s %s",
                this.getPlayerOrigin(),
                this.getPlayerSuborigin(),
                this.getSource(),
                o("ScriptPath").getScriptPath(),
              );
              return;
            }
            this.play("autoplay_initiated");
          }
        }),
        (i.isBuffering = function () {
          return this.$VideoPlayerController35;
        }),
        (i.$VideoPlayerController161 = function () {
          var e = Math.floor(Date.now() / 1e3);
          ((this.$VideoPlayerController111 =
            this.$VideoPlayerController111.filter(function (t) {
              return t.time + 3 > e;
            })),
            this.$VideoPlayerController111.some(function (t) {
              return t.time === e ? ((t.count += 1), !0) : !1;
            }) || this.$VideoPlayerController111.push({ time: e, count: 1 }));
        }),
        (i.$VideoPlayerController162 = function () {
          var e = Math.floor(Date.now() / 1e3);
          return this.$VideoPlayerController111.reduce(function (t, n) {
            return (n.time + 3 > e ? n.count : 0) + t;
          }, 0);
        }),
        (i.$VideoPlayerController155 = function (t) {
          this.emit("bufferingProgress", t);
        }),
        (i.setBuffering = function (t) {
          if (t !== this.$VideoPlayerController35) {
            if (
              ((this.$VideoPlayerController35 = t),
              this.$VideoPlayerController35)
            ) {
              var e = r("ShakaConstants").numbers.buffering_count_threshold;
              if (
                e &&
                (this.$VideoPlayerController161(),
                this.$VideoPlayerController162() >= e)
              )
                return (
                  this.logError({
                    error: "EXCEED_BUFFER_FREQUENCY_THRESHOLD",
                    message:
                      "video has entered buffering state " +
                      e +
                      " times in the last 3 seconds.",
                    isPlayback: this.isPlayRequestPending(),
                  }),
                  this.emit("error", "EXCEED_BUFFER_FREQUENCY_THRESHOLD")
                );
              (this.$VideoPlayerController50.startBuffering(
                this.getCurrentTimePosition(),
              ),
                this.$VideoPlayerController163() &&
                  (this.$VideoPlayerController164(),
                  (this.$VideoPlayerController99 = r("setTimeout")(
                    this.$VideoPlayerController165,
                    this.$VideoPlayerController163(),
                  ))),
                this.$VideoPlayerController166());
            } else
              (this.$VideoPlayerController50.endBuffering(),
                this.$VideoPlayerController164(),
                this.isState("paused") && this.$VideoPlayerController167());
            this.emit("bufferingChanged");
          }
        }),
        (i.setVideoStreamOffset = function (t) {
          var e = this.getVideoAPI();
          typeof e.setVideoStreamOffset == "function" &&
            e.setVideoStreamOffset(t);
        }),
        (i.$VideoPlayerController164 = function () {
          this.$VideoPlayerController99 &&
            (r("clearTimeout")(this.$VideoPlayerController99),
            (this.$VideoPlayerController99 = null));
        }),
        (i.$VideoPlayerController167 = function () {
          this.$VideoPlayerController108 && this.play("network_resumed");
        }),
        (i.$VideoPlayerController166 = function () {
          this.$VideoPlayerController35 &&
            this.$VideoPlayerController107 &&
            this.isState("playing") &&
            this.pause("network_interrupted");
        }),
        (i.$VideoPlayerController$p_140 = function (t) {
          this.$VideoPlayerController108 = !1;
        }),
        (i.$VideoPlayerController158 = function (t) {
          t === "network_interrupted"
            ? (this.$VideoPlayerController108 = !0)
            : (this.$VideoPlayerController108 = !1);
        }),
        (i.$VideoPlayerController156 = function () {
          ((this.$VideoPlayerController107 = !0),
            this.$VideoPlayerController166());
        }),
        (i.$VideoPlayerController157 = function () {
          ((this.$VideoPlayerController107 = !1),
            this.$VideoPlayerController167());
        }),
        (i.isVideoPlaying = function () {
          return this.getState() === "playing";
        }),
        (i.isLiveVideo = function () {
          return this.$VideoPlayerController42;
        }),
        (i.isGaming = function () {
          return this.$VideoPlayerController43;
        }),
        (i.isVideo = function () {
          return !0;
        }),
        (i.isBroadcast = function () {
          return !!this.$VideoPlayerController33;
        }),
        (i.isInline = function () {
          return (
            !!this.$VideoPlayerController73 &&
            y(this.$VideoPlayerController73) === "inline" &&
            !this.isFullscreen()
          );
        }),
        (i.isFacecastAudio = function () {
          return this.$VideoPlayerController37;
        }),
        (i.isStreamInterrupted = function () {
          var e = this.$VideoPlayerController86;
          return !!(
            e &&
            e.isStreamInterrupted != null &&
            e.isStreamInterrupted()
          );
        }),
        (i.setVolume = function (t) {
          (this.$VideoPlayerController34 !== !0 &&
            this.$VideoPlayerController32) ||
            (r("VideoPlayerVolumeSettings").saveVolume(t),
            this.getVideoAPI().setVolume(t));
        }),
        (i.getDOMPosition = function () {
          var e = this.getRootNodeNullable();
          return e
            ? r("getElementPosition")(e)
            : { x: 0, y: 0, width: 0, height: 0 };
        }),
        (i.clickVideo = function () {
          (this.emit("clickVideo"), (this.$VideoPlayerController29 = !0));
        }),
        (i.mouseMove = function (t) {
          this.emit("mouseMove", t);
        }),
        (i.mouseUp = function (t) {
          this.emit("mouseUp", t);
        }),
        (i.mouseLeave = function (t) {
          this.emit("mouseLeave", t);
        }),
        (i.hasSeenClick = function () {
          return !!this.$VideoPlayerController29;
        }),
        (i.isAd = function () {
          return !!this.$VideoPlayerController2;
        }),
        (i.shouldCalculateViewability = function () {
          if (this.isAd()) return !0;
          var e = this.$VideoPlayerController50.getFTdata();
          if (e == null) return !1;
          var t = e.ft;
          return t == null ? !1 : !!t.ei;
        }),
        (i.isInstreamAd = function () {
          return !!this.$VideoPlayerController41;
        }),
        (i.getAdClientToken = function () {
          return this.$VideoPlayerController2;
        }),
        (i.getLastScrollDirection = function () {
          return (
            this.getOption(
              "VideoAutoplayControllerBase/VideoScrollTracker",
              "getLastScrollDirection",
            ) || null
          );
        }),
        (i.$VideoPlayerController168 = function () {
          var e = this,
            t = null,
            n = null,
            a = !1,
            i = null,
            l = null,
            s = null,
            u = null,
            c = null;
          if (!this.isState("loading") && !this.isState("fallback")) {
            (this.$VideoPlayerController17 === null &&
              (this.$VideoPlayerController17 =
                this.getVideoAPI().getCurrentlyPlayingVideoStreamInfoID()),
              (t = this.getVideoAPI().getEstimatedBandwidth()),
              (n = this.getVideoAPI().getAvailableVideoQualities().length),
              (a = this.getVideoAPI().getIsAbrEnabled()),
              (i = this.getPlaybackDuration()),
              (c = this.getAudioStreamId()));
            var d = this.getVideoAPI().getDimensionsForDevice();
            ((s = d && d.height),
              (l = d && d.width),
              (u = o("VideoPlayerConnectionQuality").evaluate(function () {
                return e.getVideoAPI().getEstimatedBandwidth();
              })));
          }
          var m = babelHelpers.extends({}, this.$VideoPlayerController81);
          this.$VideoPlayerController25.forEach(function (t, n) {
            m[n] = t(n, e);
          });
          var p = {};
          this.getOption(
            "SphericalVideoSpatialAudioController",
            "hasSpatialAudio",
          ) &&
            (p.audio_ch_conf = this.getOption(
              "SphericalVideoSpatialAudioController",
              "getSpatialAudioChannelLayout",
            ));
          var _ =
            this.isLiveVideo() &&
            !!f &&
            f.getIsRewound(this.getVideoPlayerID());
          return babelHelpers.extends(
            {
              ad_client_token: this.$VideoPlayerController2,
              available_qualities: n,
              access_token: this.$VideoPlayerController1,
              autoplay_eligible: this.isAutoplayable(),
              autoplay_setting: this.$VideoPlayerController8,
              broadcaster_origin: this.$VideoPlayerController98,
              projection: this.$VideoPlayerController61,
              player_version: this.getPlayerVersion(),
              flash_version: r("ifRequired")("Flash", function (e) {
                return e.getVersionString();
              }),
              video_id: this.getVideoID(),
              permalink_share_id: this.$VideoPlayerController56,
              player_state: this.$VideoPlayerController74,
              player_origin: this.$VideoPlayerController57,
              player_suborigin: this.$VideoPlayerController58,
              player_suborigin_derived: this.$VideoPlayerController59,
              playback_is_broadcast: this.$VideoPlayerController33,
              player_instance_key: this.$VideoPlayerController114,
              playback_duration: i,
              referrer: document.referrer,
              streaming_format: this.getStreamingFormat(),
              video_time_position: this.getCurrentTimePosition(),
              video_buffer_end_position: this.$VideoPlayerController86
                ? this.getBufferEndPosition()
                : 0,
              is_servable_via_fbms: this.$VideoPlayerController44,
              playback_is_live_streaming: this.$VideoPlayerController42,
              playback_is_drm: this.isDrm(),
              is_templated_manifest:
                this.isFBIsLiveTemplated() || this.isFBWasLive(),
              is_fbms: this.isFBMS(),
              is_predictive_playback: this.ispDASH(),
              is_live_video_rewound: _,
              last_scroll_direction: this.getLastScrollDirection(),
              video_channel_id: this.$VideoPlayerController87,
              video_list_id: this.$VideoPlayerController88,
              fb_manifest_identifier: this.getFbManifestIdentifier(),
              reaction_video_channel_type: this.$VideoPlayerController67,
              reaction_video_channel_subtype: this.$VideoPlayerController68,
              fbcdn_pop: this.$VideoPlayerController53,
              representation_id: this.$VideoPlayerController17,
              audio_representation_id: c,
              video_bandwidth: t,
              video_player_height: s,
              video_player_width: l,
              dash_perf_logging_enabled: this.$VideoPlayerController169(),
              data_connection_quality: u,
              is_abr_enabled: a,
              position_in_unit: this.$VideoPlayerController115,
              feed_position: this.getDataInsertionPosition(),
              upstream_player_source: this.$VideoPlayerController84,
              should_log_video_viewability: this.$VideoPlayerController113,
              detectionID: this.$VideoPlayerController116,
              is_ads_preview: this.$VideoPlayerController120,
              is_injected_ads: this.$VideoPlayerController121,
              live_linear_channel_id: this.$VideoPlayerController123,
            },
            this.$VideoPlayerController89,
            this.$VideoPlayerController9,
            m,
            p,
            { iframe_embed_referrer: this.$VideoPlayerController124 },
          );
        }),
        (i.$VideoPlayerController138 = function () {
          var e = this.getVideoInfo_DEPRECATED();
          if (!e) return null;
          var t = e.resourceUrl,
            n = /scontent-([a-z]+)\./.exec(t);
          return n ? n[1] : null;
        }),
        (i.getVideoInfo_DEPRECATED = function () {
          return this.isState("loading") || this.isState("fallback")
            ? null
            : this.getVideoAPI().getVideoInfo();
        }),
        (i.getDebugInfo = function () {
          var e = this.getVideoInfo_DEPRECATED(),
            t = {
              initializationTime: this.$VideoPlayerController62,
              initializationTimestamp: this.$VideoPlayerController63,
              version: this.getPlayerVersion(),
              stallCount:
                this.$VideoPlayerController50.getCumulativeStallCount(),
              stallTime: this.$VideoPlayerController50.getCumulativeStallTime(),
              inPlayStallCount:
                this.$VideoPlayerController50.getCumulativeInPlayStallCount(),
              inPlayStallTime:
                this.$VideoPlayerController50.getCumulativeInPlayStallTime(),
              interruptCount:
                this.$VideoPlayerController50.getCumulativeInterruptCount(),
              interruptTime:
                this.$VideoPlayerController50.getCumulativeInterruptTime(),
              state: this.$VideoPlayerController74,
              canPlayType: (p || (p = r("mapObject")))(
                r("VideoMimeTypes"),
                r("canVideoPlayType"),
              ),
              loggedError: this.$VideoPlayerController49,
              lastError: this.$VideoPlayerController46,
              droppedFrames:
                !!this.$VideoPlayerController86 &&
                this.$VideoPlayerController86.getDroppedFrames(),
              totalFrames:
                !!this.$VideoPlayerController86 &&
                this.$VideoPlayerController86.getTotalFrames(),
              videoSource:
                !!this.$VideoPlayerController86 &&
                this.$VideoPlayerController86.getVideoNodeSource(),
              viewabilityPercentage:
                !!this.$VideoPlayerController95 &&
                !(
                  r("VideoPlayerExperiments")
                    .organicViewabilityLoggingNoOrganicLogging && !this.isAd()
                ) &&
                this.$VideoPlayerController95.getViewability(),
              stack: void 0,
            },
            n = {
              videoID: this.getVideoID(),
              isDrm:
                this.$VideoPlayerController86 &&
                this.$VideoPlayerController86.isDrm(),
            };
          if (!e) return { player: t, currentVideo: n };
          var o = this.getVideoAPI().getDimensionsForDevice();
          return {
            currentVideo: babelHelpers.extends({}, n, {
              streamType: e.streamType,
              isLiveStream: e.isLiveStream,
              liveManifestUrl: e.liveManifestUrl,
              isHD: e.isHD,
              hasHD: e.hasHD,
              resourceUrl: e.resourceUrl,
              hasSubtitles: e.hasSubtitles,
              hasRateLimit: !!e.hasUnlimitedSrc,
              isRateLimited: e.hasUnlimitedSrc && !e.useUnlimitedSrc,
              tagHD: e.tagHD,
              tagSD: e.tagSD,
              projection: this.$VideoPlayerController61,
              streamId: this.$VideoPlayerController17,
              audioStreamId: this.getVideoAPI().getAudioStreamInfoIDDebug(),
              dashAudioFormat: this.getVideoAPI().getDashAudioConfiguration(),
            }),
            player: babelHelpers.extends({}, t, { dimensions: o }),
          };
        }),
        (i.getLastError = function () {
          return this.$VideoPlayerController46;
        }),
        (i.isAkamai = function () {
          var e = this.getVideoInfo_DEPRECATED();
          return e
            ? e.liveManifestUrl && e.liveManifestUrl.includes("akamaihd")
            : !1;
        }),
        (i.getLoggedError = function () {
          return this.$VideoPlayerController49;
        }),
        (i.getTotalFrames = function () {
          return this.$VideoPlayerController86
            ? this.$VideoPlayerController86.getTotalFrames()
            : 0;
        }),
        (i.getDroppedFrames = function () {
          return this.$VideoPlayerController86
            ? this.$VideoPlayerController86.getDroppedFrames()
            : 0;
        }),
        (i.getInterruptCount = function () {
          return this.$VideoPlayerController50.getCumulativeInterruptCount();
        }),
        (i.getInterruptTime = function () {
          return this.$VideoPlayerController50.getCumulativeInterruptTime();
        }),
        (i.getVideoStreamId = function () {
          return this.getVideoAPI().getCurrentlyPlayingVideoStreamInfoID();
        }),
        (i.getAudioStreamId = function () {
          return (
            this.getVideoAPI().getCurrentlyPlayingAudioStreamInfoID() ||
            this.getVideoAPI().getAudioStreamInfoIDDebug()
          );
        }),
        (i.getVideoTracks = function () {
          return this.getVideoAPI().getVideoTracksDebug();
        }),
        (i.getAudioDashFormat = function () {
          return this.getVideoAPI().getDashAudioConfigurationDebug();
        }),
        (i.getCumulativeStallCount = function () {
          return this.$VideoPlayerController50.getCumulativeStallCount();
        }),
        (i.getCumulativeStallTime = function () {
          return this.$VideoPlayerController50.getCumulativeStallTime();
        }),
        (i.getStallCount = function () {
          return this.$VideoPlayerController50.getStallCount();
        }),
        (i.getStreamType = function () {
          var e = this.getVideoInfo_DEPRECATED();
          return e ? e.streamType : "n/a";
        }),
        (i.hasSubtitles = function () {
          return this.getVideoAPI().hasSubtitles();
        }),
        (i.getVideoState = function () {
          return this.$VideoPlayerController74;
        }),
        (i.areSubtitlesActive = function () {
          return this.getVideoAPI().areSubtitlesActive();
        }),
        (i.areSubtitlesAutogenerated = function () {
          return this.getVideoAPI().areSubtitlesAutogenerated();
        }),
        (i.areHLSActive = function () {
          return this.getVideoAPI().areHLSActive();
        }),
        (i.toggleSubtitles = function () {
          (this.$VideoPlayerController154(),
            this.logEvent("caption_change"),
            (this.$VideoPlayerController82 = !1));
        }),
        (i.updateSubtitleStyle = function (t) {
          ((this.$VideoPlayerController75 = t),
            this.getVideoAPI() &&
              this.getVideoAPI().setSubtitlesStyle != null &&
              this.getVideoAPI().setSubtitlesStyle(t));
        }),
        (i.$VideoPlayerController154 = function () {
          (this.getVideoAPI().toggleSubtitles(),
            this.$VideoPlayerController141());
        }),
        (i.$VideoPlayerController141 = function () {
          this.hasSubtitles() && this.areSubtitlesActive()
            ? (this.$VideoPlayerController10 = "on")
            : (this.$VideoPlayerController10 = "off");
        }),
        (i.isHD = function () {
          return o("VideoPlayerQualitiesArray").isHDSelectedVideoQuality(
            this.getAvailableVideoQualities(),
            this.getSelectedVideoQuality(),
          );
        }),
        (i.hasHD = function () {
          var e = o("VideoPlayerQualitiesArray").getHighestVideoQuality(
            this.getAvailableVideoQualities(),
          );
          return e != null;
        }),
        (i.toggleHD = function () {
          var e = o(
            "VideoPlayerQualitiesArray",
          ).getPreferredVideoQualityForToggleHD(
            this.getAvailableVideoQualities(),
            this.getSelectedVideoQuality(),
          );
          e != null && this.setPreferredVideoQuality(e);
        }),
        (i.setPreferredVideoQuality = function (t) {
          this.getVideoAPI().setPreferredVideoQuality(t);
        }),
        (i.unsetPreferredVideoQuality = function () {
          this.getVideoAPI().unsetPreferredVideoQuality();
        }),
        (i.getPreferredVideoQuality = function () {
          var e;
          return (e = this.getVideoAPI().getPreferredVideoQuality()) != null
            ? e
            : null;
        }),
        (i.getSelectedVideoQuality = function () {
          var e;
          return (e = this.getVideoAPI().getSelectedVideoQuality()) != null
            ? e
            : null;
        }),
        (i.getAvailableVideoQualities = function () {
          return this.getVideoAPI().getAvailableVideoQualities();
        }),
        (i.getVideoProjection = function () {
          return this.getVideoAPI().getVideoProjection();
        }),
        (i.canAutoSelectVideoQuality = function () {
          return this.getVideoAPI().canAutoSelectVideoQuality();
        }),
        (i.switchToStreamType = function (t) {
          this.getVideoAPI().switchToStreamType(t);
        }),
        (i.$VideoPlayerController146 = function () {
          this.getVideoAPI().replaceVideoDataFromURL(
            r("XVideoDataControllerRouteBuilder")
              .buildUri(
                babelHelpers.extends(
                  { video_id: this.getVideoID(), scrubbing_preference: g },
                  this.$VideoPlayerController73 != null
                    ? { source: this.$VideoPlayerController73 }
                    : {},
                ),
              )
              .toString(),
          );
        }),
        (i.$VideoPlayerController139 = function (t) {
          var e = this.getVideoInfo_DEPRECATED();
          return e != null
            ? babelHelpers.extends(
                {
                  resource_url: e.resourceUrl,
                  liveStream: e.isLiveStream,
                  hd: e.isHD,
                },
                t,
              )
            : t;
        }),
        (i.$VideoPlayerController170 = function () {
          var e = this.getDOMPosition(),
            t = r("getViewportDimensions")().height,
            n = null;
          return (
            e.y <= 0
              ? (n = e.y)
              : e.y + e.height < t
                ? (n = 0)
                : (n = e.y + e.height - t),
            n
          );
        }),
        (i.logEvent = function (t, n) {
          if (t !== "displayed") {
            (this.$VideoPlayerController48++,
              this.$VideoPlayerController119.emit(t));
            var e = r("ShakaConstants").numbers.logging_log_event_limit;
            e &&
              this.$VideoPlayerController48 > e &&
              ((this.$VideoPlayerController125 = !0),
              this.$VideoPlayerController50 &&
                this.$VideoPlayerController50.disable());
            var o = ++this.$VideoPlayerController26,
              a = Object.assign(this.$VideoPlayerController168(), n),
              i = this.getOriginalPlayReason();
            if (
              (i && t !== "displayed" && (a.video_play_reason = i),
              t === "finished_playing" &&
                (a.viewport_distance = this.$VideoPlayerController170()),
              (t === "muted" ||
                t === "unmuted" ||
                t === "started_playing" ||
                t === "caption_change" ||
                t === "unpaused") &&
                (a.caption_state = this.$VideoPlayerController10),
              this.$VideoPlayerController94 &&
                !(
                  r("VideoPlayerExperiments")
                    .organicViewabilityLoggingNoOrganicLogging && !this.isAd()
                ) &&
                r("VideoViewabilityKeyEvents").Events.includes(t) &&
                ((a.current_viewability_percentage =
                  this.$VideoPlayerController95.getViewability()),
                this.$VideoPlayerController95.setLastLoggedViewability(
                  a.current_viewability_percentage,
                )),
              (a.event_seq_num = o),
              this.$VideoPlayerController78.has(t) &&
                (r("VideoPlayerExperiments").logSBLVpts &&
                  (a.vpts = (d || (d = r("performanceAbsoluteNow")))()),
                (a.seq_num = ++this.$VideoPlayerController79)),
              t === "played_for_three_seconds" &&
                ((a.detection_id = this.$VideoPlayerController116),
                this.emit("videoView/runFraudDetector")),
              t === "requested_playing")
            ) {
              var l = this.$VideoPlayerController117
                ? this.$VideoPlayerController117.getLiveTraceContext()
                : null;
              l != null &&
                ((a.live_trace_stream_id = l.streamId),
                (a.live_trace_stream_type = l.streamType),
                (a.live_trace_source_id = l.sourceId));
            }
            if (
              this.$VideoPlayerController117 &&
              (t === "paused" || t === "finished_playing" || t === "heart_beat")
            ) {
              var s = this.$VideoPlayerController117.getAndFlushTracedFrames();
              s != null && (a.frame_events = JSON.stringify(s));
            }
            var u = r("SRTVideoData").getInstance();
            u != null &&
              u.getJobID() &&
              ((a.srt_job_id = u.getJobID()),
              (a.srt_job_tracking_id = u.getJobTrackingID()));
            var c = this.$VideoPlayerController50.logEvent(t, a);
            return (this.emit("debug/vpcLogEvent", c), c);
          }
        }),
        (i.getState = function () {
          return this.$VideoPlayerController74;
        }),
        (i.getStreamingFormat = function () {
          var e = this.getVideoInfo_DEPRECATED() || {};
          return e.streamType || this.$VideoPlayerController45;
        }),
        (i.setPlaybackRate = function (t) {
          this.getVideoAPI().setPlaybackRate != null &&
            this.getVideoAPI().setPlaybackRate(t);
        }),
        (i.getPlaybackRate = function () {
          return this.getVideoAPI().getPlaybackRate != null
            ? this.getVideoAPI().getPlaybackRate()
            : 1;
        }),
        (i.setState = function (t) {
          this.isState("destroyed") ||
            (this.isState("fallback") && !this.isFallbackRecoverable()) ||
            ((this.$VideoPlayerController74 = t),
            this.$VideoPlayerController74 === "fallback" &&
              (o("CSS").addClass(this.getRootNode(), "_3-n5"),
              this.$VideoPlayerController142()),
            this.emit("stateChange"));
        }),
        (i.isState = function (t) {
          return this.$VideoPlayerController74 === t;
        }),
        (i.isIntentionallyViewing = function () {
          return this.isState("playing") && !this.isMuted();
        }),
        (i.abortLoading = function (t) {
          this.isState("loading") ||
            this.isState("fallback") ||
            (r("VideoPlayerExperiments")
              .seekZeroWhenAbortLoadingFinishedVideos &&
              !(
                r("VideoPlayerExperiments").seekZeroOnlyVodVideo &&
                this.$VideoPlayerController42
              ) &&
              this.isState("finished") &&
              this.seek(0),
            this.getVideoAPI().abortLoading(t || {}),
            this.stopHeartbeat(),
            this.$VideoPlayerController20.stopUnifiedCVC());
        }),
        (i.preload = function () {
          this.isState("loading") ||
            this.isState("fallback") ||
            this.getVideoAPI().preload();
        }),
        (i.getPlayerVersion = function () {
          var e;
          this.$VideoPlayerController86 && (e = this.getVideoAPI());
          var t =
              e && e.getUpdatedPlayerVersion != null
                ? e.getUpdatedPlayerVersion.bind(e)
                : this.$VideoPlayerController5.getPlayerVersion,
            n = t ? t() : this.$VideoPlayerController60;
          return this.$VideoPlayerController101
            ? this.$VideoPlayerController159(n)
            : n;
        }),
        (i.$VideoPlayerController159 = function (t) {
          switch (t) {
            case "silvercity":
              return "react_silvercity";
            case "pleasantville":
              return "react_pleasantville";
            case "oz":
              return "react_oz";
            default:
              return "react";
          }
        }),
        (i.registerOption = function (t, n, r, o) {
          var e = this.$VideoPlayerController13.get(t);
          if (
            (e || ((e = new Map()), this.$VideoPlayerController13.set(t, e)),
            e.has(n))
          ) {
            var a = new Error(
              "An option can only be registered once for each component",
            );
            throw (a.stack, a);
          }
          (e.set(n, { getter: r, setter: o }), this.emit("optionsChange"));
        }),
        (i.unregisterOption = function (t, n) {
          var e = this.$VideoPlayerController13.get(t);
          if (!e) {
            var r = new Error(
              'The component "' + t + '" has no options registered',
            );
            throw (r.stack, r);
          }
          if (!e.has(n)) {
            var o = new Error(
              'The component "' + t + '" has no option "' + n + '" registered',
            );
            throw (o.stack, o);
          }
          (e.delete(n),
            e.size || this.$VideoPlayerController13.delete(t),
            this.emit("optionsChange"));
        }),
        (i.getComponents = function () {
          return this.$VideoPlayerController13.keys();
        }),
        (i.getOptions = function (t) {
          var e = this.$VideoPlayerController13.get(t);
          return e ? e.keys() : r("enumerate")([]);
        }),
        (i.hasOption = function (t, n) {
          var e = this.$VideoPlayerController13.get(t);
          return !!e && e.has(n);
        }),
        (i.getOption = function (t, n) {
          var e = this.$VideoPlayerController13.get(t);
          if (e) {
            var r = e.get(n);
            if (r) return r.getter();
          }
        }),
        (i.setOption = function (t, n, r) {
          var e = this.$VideoPlayerController13.get(t);
          if (!e) {
            var o = new Error("Component not registered");
            throw (o.stack, o);
          }
          var a = e.get(n);
          if (!a) {
            var i = new Error("Option not registered");
            throw (i.stack, i);
          }
          var l = a.setter;
          if (l) return l(r);
          var s = new Error("Read-only option");
          throw (s.stack, s);
        }),
        (i.showDebugOverlayView = function (t) {
          this.emit("showDebugOverlay", t);
        }),
        (i.$VideoPlayerController132 = function () {
          var e = o("DOMQuery").scry(this.$VideoPlayerController70, "^._5pat");
          return e.length ? e[0] : null;
        }),
        (i.registerDrawer = function (t, n) {
          return this.$VideoPlayerController24.register(t, n);
        }),
        (i.getVideoPath = function () {
          return this.$VideoPlayerController92;
        }),
        (i.setAllowCrossPageTransition = function (t) {
          this.$VideoPlayerController100 = t;
        }),
        (i.cleanOnLeave = function () {
          (this.pause("unloaded"), this.destroy());
        }),
        (i.switchReplicaSet = function (t) {
          var e = this.isState("playing");
          (this.getVideoAPI().switchReplicaSet(t.replica, {
            url: t.url,
            status: t.status,
            timestamp: t.timestamp,
          }),
            e && this.play("autoplay_initiated"));
        }),
        (i.switchToFullVideo = function () {
          var e = this;
          (this.pause("unloaded"),
            this.getVideoAPI()
              .reloadDashManifest()
              .done(function () {
                (e.play(
                  new (r("VideoPlayerReasonTransitionHelper"))(
                    "user_initiated",
                  ),
                ),
                  e.emit("switchedToFullVideo"));
              }));
        }),
        (i.$VideoPlayerController133 = function () {
          return (
            this.getIsInChannel() ||
            this.$VideoPlayerController73 === "living_room" ||
            this.$VideoPlayerController73 === "topic_channel_living_room" ||
            this.$VideoPlayerController57 === "intern_curation" ||
            this.$VideoPlayerController57 === "games_video_hub"
          );
        }),
        (i.getDashAudioConfiguration = function () {
          return this.getVideoAPI().getDashAudioConfiguration();
        }),
        (i.setEnableLiveheadCatchup = function (t) {
          var e = this.getVideoAPI();
          e && e.setEnableLiveheadCatchup(t);
        }),
        (i.setIsLiveRewindActive = function (t) {
          var e = this.getVideoAPI();
          e && e.setIsLiveRewindActive(t);
        }),
        (i.isFBWasLive = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return !!(e && e.isFBWasLive());
        }),
        (i.isFBIsLiveTemplated = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return !!(e && e.isFBIsLiveTemplated());
        }),
        (i.getFbManifestIdentifier = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return e ? e.getFbManifestIdentifier() : "";
        }),
        (i.isDrm = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return e && e.isDrm();
        }),
        (i.isFBMS = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return !!(e && e.isFBMS());
        }),
        (i.ispDASH = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return !!(e && e.ispDASH());
        }),
        (i.isLiveheadCatchupEnabled = function () {
          var e = this.getVideoAPI();
          return e ? e.isLiveheadCatchupEnabled() : !1;
        }),
        (i.getBandwidthEstimate = function () {
          var e = this.getVideoAPI();
          return e ? e.getBandwidthEstimate() : null;
        }),
        (i.getSeekableRanges = function () {
          var e = this.getVideoAPI();
          return e ? e.getSeekableRanges() : null;
        }),
        (i.isBroadcaster = function () {
          return this.$VideoPlayerController34 || !1;
        }),
        (i.isWatchAndScroll = function () {
          return this.$VideoPlayerController73 === "watch_scroll";
        }),
        (i.$VideoPlayerController169 = function () {
          var e = this.$VideoPlayerController86 && this.getVideoAPI();
          return e ? e.isDashPerfLoggingEnabled() : null;
        }),
        (i.$VideoPlayerController134 = function (t, n) {
          c(0, 54449);
        }),
        (i.$VideoPlayerController163 = function () {
          return this.isPlayRequestPending()
            ? this.$VideoPlayerController105
            : this.$VideoPlayerController106;
        }),
        a
      );
    })(r("MediaController"));
    l.default = C;
  },
  98,
);
