__d(
  "AdsAPIAdgroupImageLayerRecords",
  [
    "ApiAdCreativeImageLayerSpecFields",
    "ApiAdCreativeImageTextOverlayContentFields",
    "immutable",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s,
      u,
      c,
      d,
      m,
      p,
      _ = (d = r("immutable")).Record(
        ((e = {}),
        (e[(m = r("ApiAdCreativeImageTextOverlayContentFields")).HIGH_PRICE] =
          void 0),
        (e[m.LOW_PRICE] = void 0),
        (e[m.PRICE] = void 0),
        (e[m.AUTO_SHOW_ENROLL_STATUS] = void 0),
        (e[m.TYPE] = "price"),
        e),
      ),
      f = d.Record(
        ((s = {}),
        (s[(p = r("ApiAdCreativeImageLayerSpecFields")).LAYER_TYPE] = "image"),
        (s[p.IMAGE_SOURCE] = "catalog"),
        (s[p.PAD_IMAGE] = void 0),
        (s[p.CROP_IMAGE] = void 0),
        s),
      ),
      g = "DF0005",
      h = "FFFFFF",
      y = d.Record(
        ((u = {}),
        (u[p.LAYER_TYPE] = "text_overlay"),
        (u[p.CONTENT] = _()),
        (u[p.FLOAT_WITH_MARGIN] = void 0),
        (u[p.OPACITY] = 100),
        (u[p.OVERLAY_POSITION] = "top_left"),
        (u[p.OVERLAY_SHAPE] = "rectangle"),
        (u[p.SHAPE_COLOR] = g),
        (u[p.TEXT_COLOR] = h),
        (u[p.TEXT_FONT] = "open_sans_bold"),
        u),
      ),
      C = d.Record(
        ((c = {}),
        (c[p.LAYER_TYPE] = "frame_overlay"),
        (c[p.BLENDING_MODE] = "normal"),
        (c[p.FRAME_AUTO_SHOW_ENROLL_STATUS] = void 0),
        (c[p.FRAME_IMAGE_HASH] = null),
        (c[p.FRAME_SOURCE] = "custom"),
        (c[p.OPACITY] = 100),
        (c[p.OVERLAY_POSITION] = "center"),
        (c[p.SCALE] = 100),
        c),
      );
    ((l.makeTextOverlayLayerContentRecord = _),
      (l.makeImageLayerRecord = f),
      (l.DEFAULT_SHAPE_COLOR = g),
      (l.DEFAULT_TEXT_COLOR = h),
      (l.makeTextOverlayLayerRecord = y),
      (l.makeFrameOverlayLayerRecord = C));
  },
  98,
);
