__d(
  "adExperienceInfoEnumConversionUtilGraphQLQueryUtilAndromedaQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          { defaultValue: null, kind: "LocalArgument", name: "ad_account_id" },
        ],
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "profile_pic_uri",
          storageKey: null,
        },
        r = [t],
        o = [
          {
            alias: null,
            args: [
              {
                kind: "Variable",
                name: "ad_account_id",
                variableName: "ad_account_id",
              },
            ],
            concreteType: "XFBSAIPAdAccountExperienceInfoData",
            kind: "LinkedField",
            name: "xfb_andromeda_XShopsAdsSAIPAdAccountExperienceInfoController",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "saip_experience",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "saip_experiences",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cms_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "coupon_amount_cents",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "cms_name",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "brand_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "has_connected_third_party_marketing_tag",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "ShopAdOpportunityOnboardingRecommendation",
                kind: "LinkedField",
                name: "saoff_onboarding_recommendations",
                plural: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "Page",
                    kind: "LinkedField",
                    name: "fb_page",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "display_name",
                        storageKey: null,
                      },
                      t,
                      n,
                      {
                        alias: null,
                        args: null,
                        concreteType: "AdBusiness",
                        kind: "LinkedField",
                        name: "business",
                        plural: !1,
                        selections: r,
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBInstagramBusinessAsset",
                    kind: "LinkedField",
                    name: "ig_asset",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "name",
                        storageKey: null,
                      },
                      t,
                      n,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "ShopifyApplicationInstallation",
                    kind: "LinkedField",
                    name: "shopify_application_installation",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "shop_domain",
                        storageKey: null,
                      },
                      t,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBShopAdOpportunity",
                    kind: "LinkedField",
                    name: "shop_ad_opportunity",
                    plural: !1,
                    selections: r,
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "onboarding_cohort",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "adExperienceInfoEnumConversionUtilGraphQLQueryUtilAndromedaQuery",
          selections: o,
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "adExperienceInfoEnumConversionUtilGraphQLQueryUtilAndromedaQuery",
          selections: o,
        },
        params: {
          id: "24908543868768334",
          metadata: {},
          name: "adExperienceInfoEnumConversionUtilGraphQLQueryUtilAndromedaQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
