__d(
  "AdsBusinessInstagramAccountStoreSourceServerQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "business_id",
        },
        t = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "legacy_account_id",
        },
        n = { defaultValue: !1, kind: "LocalArgument", name: "skip_ibta" },
        r = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "legacy_account_id",
          },
        ],
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        a = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "threads_user_id",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "threads_user_profile_pic",
            storageKey: null,
          },
        ],
        i = {
          alias: null,
          args: [
            {
              kind: "Variable",
              name: "business_id",
              variableName: "business_id",
            },
          ],
          concreteType: "InstagramUserV2",
          kind: "LinkedField",
          name: "instagram_accounts",
          plural: !0,
          selections: [
            o,
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "has_profile_pic",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "legacy_instagram_user_id",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_authorized_for_political",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_professional_account",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_private",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_published",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "profile_picture_url",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "username",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_shopping_onsite_checkout_enabled",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "shopping_review_status",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_ctd_leads_targeting_eligible",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_ctd_purchase_targeting_eligible",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "eimu_id",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "has_create_ads_access",
              storageKey: null,
            },
            {
              alias: null,
              args: [
                {
                  kind: "Variable",
                  name: "ad_account_id",
                  variableName: "legacy_account_id",
                },
              ],
              kind: "ScalarField",
              name: "is_connected_to_ad_account",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_shopless_ig_account",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "XFBInstagramConnectedThreadsUserResponse",
              kind: "LinkedField",
              name: "instagram_connected_threads_user",
              plural: !1,
              selections: a,
              storageKey: null,
            },
            {
              condition: "skip_ibta",
              kind: "Condition",
              passingValue: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "XFBInstagramBackedThreadsUserResponse",
                  kind: "LinkedField",
                  name: "instagram_backed_threads_user",
                  plural: !1,
                  selections: a,
                  storageKey: null,
                },
              ],
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "instagram_account_type",
              storageKey: null,
            },
          ],
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e, t, n],
          kind: "Fragment",
          metadata: null,
          name: "AdsBusinessInstagramAccountStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [i],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [t, e, n],
          kind: "Operation",
          name: "AdsBusinessInstagramAccountStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [i, o],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "27305628145698149",
          metadata: {},
          name: "AdsBusinessInstagramAccountStoreSourceServerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
