__d(
  "AdsBusinessConstraintsAdAccountDataStoreLoadedQuery.graphql",
  ["AdAccount-ad_target_geo_locations_as_locations_api_spec_object-resolver"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          {
            kind: "Literal",
            name: "attribute_types",
            value: [
              "BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_MIN_AGE",
              "BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_GEO_LOCATIONS",
              "BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_EXCLUDED_GEO_LOCATIONS",
              "BUSINESS_CONSTRAINTS_PLACEMENT_EXCLUSIONS",
            ],
          },
        ],
        t = {
          kind: "InlineFragment",
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "as_integer",
              storageKey: null,
            },
          ],
          type: "XFBAdvertiserProfileIntegerBasedAttributeValue",
          abstractKey: null,
        },
        r = {
          kind: "InlineFragment",
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "as_multi_string",
              storageKey: null,
            },
          ],
          type: "XFBAdvertiserProfileMultiStringBasedAttributeValue",
          abstractKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "key",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "country",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "region",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "region_id",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "radius",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "distance_unit",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "latitude",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "longitude",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "primary_city_id",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "primary_city",
          storageKey: null,
        },
        g = [l, a, i, s, u],
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [],
          kind: "Fragment",
          metadata: null,
          name: "AdsBusinessConstraintsAdAccountDataStoreLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "AdAccount",
                  kind: "LinkedField",
                  name: "loaded_ad_accounts",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: e,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "advertiser_profile_editable_attributes",
                      plural: !0,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "value",
                          plural: !1,
                          selections: [
                            t,
                            r,
                            {
                              kind: "InlineFragment",
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAdTargetGeoLocations",
                                  kind: "LinkedField",
                                  name: "as_ad_target_geo_locations",
                                  plural: !1,
                                  selections: [
                                    {
                                      alias: null,
                                      args: null,
                                      fragment: {
                                        args: null,
                                        kind: "FragmentSpread",
                                        name: "AdAccountAdTargetGeoLocationsAsLocationsApiSpecObjectResolver",
                                      },
                                      kind: "RelayResolver",
                                      name: "as_location_api_spec_object",
                                      resolverModule: n(
                                        "AdAccount-ad_target_geo_locations_as_locations_api_spec_object-resolver",
                                      ).as_location_api_spec_object,
                                      path: "loaded_ad_accounts.advertiser_profile_editable_attributes.value.as_ad_target_geo_locations.as_location_api_spec_object",
                                    },
                                  ],
                                  storageKey: null,
                                },
                              ],
                              type: "XFBAdvertiserProfileAdTargetGeoLocationsBasedAttribute",
                              abstractKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                      ],
                      storageKey:
                        'advertiser_profile_editable_attributes(attribute_types:["BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_MIN_AGE","BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_GEO_LOCATIONS","BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_EXCLUDED_GEO_LOCATIONS","BUSINESS_CONSTRAINTS_PLACEMENT_EXCLUSIONS"])',
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [],
          kind: "Operation",
          name: "AdsBusinessConstraintsAdAccountDataStoreLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "AdAccount",
                  kind: "LinkedField",
                  name: "loaded_ad_accounts",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: e,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "advertiser_profile_editable_attributes",
                      plural: !0,
                      selections: [
                        o,
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "value",
                          plural: !1,
                          selections: [
                            o,
                            t,
                            r,
                            {
                              kind: "InlineFragment",
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAdTargetGeoLocations",
                                  kind: "LinkedField",
                                  name: "as_ad_target_geo_locations",
                                  plural: !1,
                                  selections: [
                                    {
                                      name: "as_location_api_spec_object",
                                      args: null,
                                      fragment: {
                                        kind: "InlineFragment",
                                        selections: [
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType: "XFBAdTargetCity",
                                            kind: "LinkedField",
                                            name: "cities",
                                            plural: !0,
                                            selections: [a, i, l, s, u, c, d],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            kind: "ScalarField",
                                            name: "country_groups",
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType: "XFBAdTargetCountry",
                                            kind: "LinkedField",
                                            name: "countries",
                                            plural: !0,
                                            selections: [
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "country_code",
                                                storageKey: null,
                                              },
                                            ],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetCustomLocation",
                                            kind: "LinkedField",
                                            name: "custom_locations",
                                            plural: !0,
                                            selections: [
                                              i,
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "address_string",
                                                storageKey: null,
                                              },
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "custom_type",
                                                storageKey: null,
                                              },
                                              d,
                                              m,
                                              p,
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "min_population",
                                                storageKey: null,
                                              },
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "max_population",
                                                storageKey: null,
                                              },
                                              c,
                                              _,
                                              f,
                                              u,
                                              l,
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "country_group",
                                                storageKey: null,
                                              },
                                            ],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            kind: "ScalarField",
                                            name: "location_types",
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType: "XFBAdTargetRegion",
                                            kind: "LinkedField",
                                            name: "regions",
                                            plural: !0,
                                            selections: [a, l, i],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType: "XFBAdTargetZipCode",
                                            kind: "LinkedField",
                                            name: "zips",
                                            plural: !0,
                                            selections: [a, i, _, f, u, l],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetElectoralDistrict",
                                            kind: "LinkedField",
                                            name: "electoral_districts",
                                            plural: !0,
                                            selections: [
                                              l,
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "deprecation_code",
                                                storageKey: null,
                                              },
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "electoral_district",
                                                storageKey: null,
                                              },
                                              a,
                                              i,
                                            ],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetPoliticalDistrict",
                                            kind: "LinkedField",
                                            name: "political_districts",
                                            plural: !0,
                                            selections: [l, a, i],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType: "XFBAdTargetPlace",
                                            kind: "LinkedField",
                                            name: "places",
                                            plural: !0,
                                            selections: [
                                              l,
                                              d,
                                              a,
                                              m,
                                              p,
                                              i,
                                              _,
                                              f,
                                              c,
                                              u,
                                            ],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoMarket",
                                            kind: "LinkedField",
                                            name: "geo_markets",
                                            plural: !0,
                                            selections: [
                                              l,
                                              a,
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "market_type",
                                                storageKey: null,
                                              },
                                              i,
                                            ],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetLocationExpansion",
                                            kind: "LinkedField",
                                            name: "location_expansion",
                                            plural: !1,
                                            selections: [
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "allowed",
                                                storageKey: null,
                                              },
                                              {
                                                alias: null,
                                                args: null,
                                                kind: "ScalarField",
                                                name: "intent",
                                                storageKey: null,
                                              },
                                            ],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetLocationCluster",
                                            kind: "LinkedField",
                                            name: "location_cluster_ids",
                                            plural: !0,
                                            selections: [a],
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "large_geo_areas",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "medium_geo_areas",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "small_geo_areas",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "metro_areas",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "subcities",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "neighborhoods",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                          {
                                            alias: null,
                                            args: null,
                                            concreteType:
                                              "XFBAdTargetGeoEntity",
                                            kind: "LinkedField",
                                            name: "subneighborhoods",
                                            plural: !0,
                                            selections: g,
                                            storageKey: null,
                                          },
                                        ],
                                        type: "XFBAdTargetGeoLocations",
                                        abstractKey: null,
                                      },
                                      kind: "RelayResolver",
                                      storageKey: null,
                                      isOutputType: !0,
                                    },
                                  ],
                                  storageKey: null,
                                },
                              ],
                              type: "XFBAdvertiserProfileAdTargetGeoLocationsBasedAttribute",
                              abstractKey: null,
                            },
                          ],
                          storageKey: null,
                        },
                        h,
                      ],
                      storageKey:
                        'advertiser_profile_editable_attributes(attribute_types:["BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_MIN_AGE","BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_GEO_LOCATIONS","BUSINESS_CONSTRAINTS_AUDIENCE_CONTROLS_EXCLUDED_GEO_LOCATIONS","BUSINESS_CONSTRAINTS_PLACEMENT_EXCLUSIONS"])',
                    },
                    h,
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
        },
        params: {
          cacheID: "e008ced8b180729c7e8a87441ca03cab",
          id: null,
          metadata: {},
          name: "AdsBusinessConstraintsAdAccountDataStoreLoadedQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
