__d(
  "AdsPromoAdsPageOfferItemsStoreSourceServerLoadedQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_blocked_by_detected_offer_toggle",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_deleted",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offeritem_title",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offeritem_description",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "code",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "sub_vertical_type",
          storageKey: null,
        },
        l = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "currency",
            storageKey: null,
          },
        ],
        s = {
          alias: null,
          args: null,
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "fixed_amount_off",
          plural: !1,
          selections: l,
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "max_discount",
          plural: !1,
          selections: l,
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "min_subtotal",
          plural: !1,
          selections: l,
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "min_quantity",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "percent_off",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "detection_sources",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_offer_synced_from_shopify",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offer_ingestion_partner_platform",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value_type",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "applicable_product_features",
          storageKey: null,
        },
        y = {
          alias: "offeritem_valid_start_date",
          args: null,
          kind: "ScalarField",
          name: "promo_ads_valid_start_date",
          storageKey: null,
        },
        C = {
          alias: "offeritem_valid_end_date",
          args: null,
          kind: "ScalarField",
          name: "promo_ads_valid_end_date",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          concreteType: "XFBTPromoOfferDomainValidationStatus",
          kind: "LinkedField",
          name: "promo_ads_domain_validation_status",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "domain",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_v3_quality_passing",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "validation_status",
              storageKey: null,
            },
          ],
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [],
          kind: "Fragment",
          metadata: null,
          name: "AdsPromoAdsPageOfferItemsStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "XFBPromoOfferItemsByPage",
                  kind: "LinkedField",
                  name: "loaded_promo_ads_page_offer_items",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "OfferItem",
                      kind: "LinkedField",
                      name: "promo_offer_items_container",
                      plural: !0,
                      selections: [
                        { kind: "RequiredField", field: e, action: "THROW" },
                        t,
                        n,
                        r,
                        o,
                        {
                          alias: null,
                          args: null,
                          concreteType: "OfferCouponCode",
                          kind: "LinkedField",
                          name: "public_coupon_code",
                          plural: !1,
                          selections: [a],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "sub_vertical_class",
                          plural: !1,
                          selections: [i],
                          storageKey: null,
                        },
                        s,
                        u,
                        c,
                        d,
                        m,
                        { kind: "RequiredField", field: p, action: "THROW" },
                        _,
                        f,
                        g,
                        h,
                        y,
                        C,
                        b,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [],
          kind: "Operation",
          name: "AdsPromoAdsPageOfferItemsStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "XFBPromoOfferItemsByPage",
                  kind: "LinkedField",
                  name: "loaded_promo_ads_page_offer_items",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "OfferItem",
                      kind: "LinkedField",
                      name: "promo_offer_items_container",
                      plural: !0,
                      selections: [
                        e,
                        t,
                        n,
                        r,
                        o,
                        {
                          alias: null,
                          args: null,
                          concreteType: "OfferCouponCode",
                          kind: "LinkedField",
                          name: "public_coupon_code",
                          plural: !1,
                          selections: [a, e],
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: null,
                          kind: "LinkedField",
                          name: "sub_vertical_class",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              kind: "ScalarField",
                              name: "__typename",
                              storageKey: null,
                            },
                            i,
                          ],
                          storageKey: null,
                        },
                        s,
                        u,
                        c,
                        d,
                        m,
                        p,
                        _,
                        f,
                        g,
                        h,
                        y,
                        C,
                        b,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
        },
        params: {
          cacheID: "23d4440fa62b1530c6836e669b0f5ffe",
          id: null,
          metadata: {},
          name: "AdsPromoAdsPageOfferItemsStoreSourceServerLoadedQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
