__d(
  "AdsPromoAdsPageOfferItemsStoreSourceFragment.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
        {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "amount",
          storageKey: null,
        },
        {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "currency",
          storageKey: null,
        },
      ];
      return {
        argumentDefinitions: [
          { defaultValue: null, kind: "LocalArgument", name: "page_id" },
        ],
        kind: "Fragment",
        metadata: null,
        name: "AdsPromoAdsPageOfferItemsStoreSourceFragment",
        selections: [
          {
            alias: null,
            args: null,
            concreteType: "OfferItem",
            kind: "LinkedField",
            name: "promo_offer_items_container",
            plural: !0,
            selections: [
              {
                kind: "RequiredField",
                field: {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "id",
                  storageKey: null,
                },
                action: "THROW",
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_blocked_by_detected_offer_toggle",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_deleted",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "offeritem_title",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "offeritem_description",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "OfferCouponCode",
                kind: "LinkedField",
                name: "public_coupon_code",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "code",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: null,
                kind: "LinkedField",
                name: "sub_vertical_class",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "sub_vertical_type",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "fixed_amount_off",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "max_discount",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "min_subtotal",
                plural: !1,
                selections: e,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "min_quantity",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "percent_off",
                storageKey: null,
              },
              {
                kind: "RequiredField",
                field: {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "detection_sources",
                  storageKey: null,
                },
                action: "THROW",
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_offer_synced_from_shopify",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "offer_ingestion_partner_platform",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "value_type",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "applicable_product_features",
                storageKey: null,
              },
              {
                alias: "offeritem_valid_start_date",
                args: null,
                kind: "ScalarField",
                name: "promo_ads_valid_start_date",
                storageKey: null,
              },
              {
                alias: "offeritem_valid_end_date",
                args: null,
                kind: "ScalarField",
                name: "promo_ads_valid_end_date",
                storageKey: null,
              },
              {
                alias: null,
                args: [
                  {
                    kind: "Variable",
                    name: "page_id",
                    variableName: "page_id",
                  },
                ],
                concreteType: "XFBTPromoOfferDomainValidationStatus",
                kind: "LinkedField",
                name: "promo_ads_domain_validation_status",
                plural: !0,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "domain",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "is_v3_quality_passing",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "validation_status",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        type: "XFBPromoOfferItemsByPage",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
