__d(
  "AdsPromoAdsPageOfferItemsStoreSourceServerQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "account_id" },
        t = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "ad_spec_coupon_codes",
        },
        n = { defaultValue: null, kind: "LocalArgument", name: "catalog_id" },
        r = { defaultValue: null, kind: "LocalArgument", name: "page_id" },
        o = { defaultValue: null, kind: "LocalArgument", name: "pixel_id" },
        a = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "product_set_id",
        },
        i = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "secondary_page_id",
        },
        l = { defaultValue: null, kind: "LocalArgument", name: "sources" },
        s = { kind: "Variable", name: "page_id", variableName: "page_id" },
        u = [
          { kind: "Variable", name: "account_id", variableName: "account_id" },
          {
            kind: "Variable",
            name: "ad_spec_coupon_codes",
            variableName: "ad_spec_coupon_codes",
          },
          { kind: "Variable", name: "catalog_id", variableName: "catalog_id" },
          s,
          { kind: "Variable", name: "pixel_id", variableName: "pixel_id" },
          {
            kind: "Variable",
            name: "product_set_id",
            variableName: "product_set_id",
          },
          {
            kind: "Variable",
            name: "secondary_page_id",
            variableName: "secondary_page_id",
          },
          { kind: "Variable", name: "sources", variableName: "sources" },
        ],
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_blocked_by_detected_offer_toggle",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_deleted",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offeritem_title",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offeritem_description",
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "code",
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "sub_vertical_type",
          storageKey: null,
        },
        h = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "currency",
            storageKey: null,
          },
        ],
        y = {
          alias: null,
          args: null,
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "fixed_amount_off",
          plural: !1,
          selections: h,
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "max_discount",
          plural: !1,
          selections: h,
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          concreteType: "CurrencyAmount",
          kind: "LinkedField",
          name: "min_subtotal",
          plural: !1,
          selections: h,
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "min_quantity",
          storageKey: null,
        },
        S = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "percent_off",
          storageKey: null,
        },
        R = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "detection_sources",
          storageKey: null,
        },
        L = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_offer_synced_from_shopify",
          storageKey: null,
        },
        E = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "offer_ingestion_partner_platform",
          storageKey: null,
        },
        k = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "value_type",
          storageKey: null,
        },
        I = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "applicable_product_features",
          storageKey: null,
        },
        T = {
          alias: "offeritem_valid_start_date",
          args: null,
          kind: "ScalarField",
          name: "promo_ads_valid_start_date",
          storageKey: null,
        },
        D = {
          alias: "offeritem_valid_end_date",
          args: null,
          kind: "ScalarField",
          name: "promo_ads_valid_end_date",
          storageKey: null,
        },
        x = {
          alias: null,
          args: [s],
          concreteType: "XFBTPromoOfferDomainValidationStatus",
          kind: "LinkedField",
          name: "promo_ads_domain_validation_status",
          plural: !0,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "domain",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "is_v3_quality_passing",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "validation_status",
              storageKey: null,
            },
          ],
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [e, t, n, r, o, a, i, l],
          kind: "Fragment",
          metadata: null,
          name: "AdsPromoAdsPageOfferItemsStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: u,
              concreteType: "XFBPromoOfferItemsByPage",
              kind: "LinkedField",
              name: "xfb_promo_offer_items_by_page",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "OfferItem",
                  kind: "LinkedField",
                  name: "promo_offer_items_container",
                  plural: !0,
                  selections: [
                    { kind: "RequiredField", field: c, action: "THROW" },
                    d,
                    m,
                    p,
                    _,
                    {
                      alias: null,
                      args: null,
                      concreteType: "OfferCouponCode",
                      kind: "LinkedField",
                      name: "public_coupon_code",
                      plural: !1,
                      selections: [f],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "sub_vertical_class",
                      plural: !1,
                      selections: [g],
                      storageKey: null,
                    },
                    y,
                    C,
                    b,
                    v,
                    S,
                    { kind: "RequiredField", field: R, action: "THROW" },
                    L,
                    E,
                    k,
                    I,
                    T,
                    D,
                    x,
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [r, i, l, e, n, o, a, t],
          kind: "Operation",
          name: "AdsPromoAdsPageOfferItemsStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: u,
              concreteType: "XFBPromoOfferItemsByPage",
              kind: "LinkedField",
              name: "xfb_promo_offer_items_by_page",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "OfferItem",
                  kind: "LinkedField",
                  name: "promo_offer_items_container",
                  plural: !0,
                  selections: [
                    c,
                    d,
                    m,
                    p,
                    _,
                    {
                      alias: null,
                      args: null,
                      concreteType: "OfferCouponCode",
                      kind: "LinkedField",
                      name: "public_coupon_code",
                      plural: !1,
                      selections: [f, c],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: null,
                      kind: "LinkedField",
                      name: "sub_vertical_class",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "__typename",
                          storageKey: null,
                        },
                        g,
                      ],
                      storageKey: null,
                    },
                    y,
                    C,
                    b,
                    v,
                    S,
                    R,
                    L,
                    E,
                    k,
                    I,
                    T,
                    D,
                    x,
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "27853758700929865",
          metadata: {},
          name: "AdsPromoAdsPageOfferItemsStoreSourceServerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
