__d(
  "BillingAutoReloadAmountScreenQuery.graphql",
  ["BillingAutoReloadAmountScreenQuery_facebookRelayOperation"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "paymentAccountID",
          },
          {
            defaultValue: null,
            kind: "LocalArgument",
            name: "paymentMethodID",
          },
        ],
        t = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "paymentAccountID",
          },
        ],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "auto_reload_status",
          storageKey: null,
        },
        o = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "amount_with_offset",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "currency",
            storageKey: null,
          },
        ],
        a = [
          {
            kind: "InlineDataFragmentSpread",
            name: "BillingCurrencyAmount_amount",
            selections: o,
            args: null,
            argumentDefinitions: [],
          },
        ],
        i = [
          {
            alias: null,
            args: null,
            concreteType: "CurrencyAmount",
            kind: "LinkedField",
            name: "reload_amount",
            plural: !1,
            selections: a,
            storageKey: null,
          },
        ],
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_in_cool_off_period",
          storageKey: null,
        },
        s = [{ kind: "Variable", name: "id", variableName: "paymentMethodID" }],
        u = [
          { kind: "Literal", name: "intent", value: "AUTO_RELOAD" },
          {
            kind: "Variable",
            name: "payment_legacy_account_id",
            variableName: "paymentAccountID",
          },
        ],
        c = [
          {
            alias: "prepay_details_for_auto_reload",
            args: u,
            concreteType: "AdAccountPrepayDetail",
            kind: "LinkedField",
            name: "prepay_funding_details",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "max_acceptable_amount",
                plural: !1,
                selections: a,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "min_acceptable_amount",
                plural: !1,
                selections: a,
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        m = [
          {
            alias: null,
            args: null,
            concreteType: "CurrencyAmount",
            kind: "LinkedField",
            name: "reload_amount",
            plural: !1,
            selections: o,
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "description",
            storageKey: null,
          },
        ],
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        _ = [
          {
            alias: "prepay_details_for_auto_reload",
            args: u,
            concreteType: "AdAccountPrepayDetail",
            kind: "LinkedField",
            name: "prepay_funding_details",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "max_acceptable_amount",
                plural: !1,
                selections: o,
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "CurrencyAmount",
                kind: "LinkedField",
                name: "min_acceptable_amount",
                plural: !1,
                selections: o,
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ];
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "BillingAutoReloadAmountScreenQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "BillingAutoReloadInfo",
                          kind: "LinkedField",
                          name: "auto_reload_info",
                          plural: !1,
                          selections: [
                            {
                              args: null,
                              kind: "FragmentSpread",
                              name: "BillingSelectAutoReloadPresetAmountRow_autoReloadInfo",
                            },
                            r,
                            {
                              alias: null,
                              args: null,
                              concreteType: "CurrencyAmount",
                              kind: "LinkedField",
                              name: "auto_reload_amount",
                              plural: !1,
                              selections: a,
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "CurrencyAmount",
                              kind: "LinkedField",
                              name: "auto_reload_trigger_threshold",
                              plural: !1,
                              selections: a,
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "XFBAutoReloadPills",
                              kind: "LinkedField",
                              name: "auto_reload_pill_amounts",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAutoReloadPillData",
                                  kind: "LinkedField",
                                  name: "pill_one",
                                  plural: !1,
                                  selections: i,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAutoReloadPillData",
                                  kind: "LinkedField",
                                  name: "pill_two",
                                  plural: !1,
                                  selections: i,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAutoReloadPillData",
                                  kind: "LinkedField",
                                  name: "pill_three",
                                  plural: !1,
                                  selections: i,
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            l,
                          ],
                          storageKey: null,
                        },
                      ],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: s,
              concreteType: null,
              kind: "LinkedField",
              name: "node",
              plural: !1,
              selections: [
                {
                  kind: "InlineFragment",
                  selections: c,
                  type: "ExternalCreditCard",
                  abstractKey: null,
                },
                {
                  kind: "InlineFragment",
                  selections: c,
                  type: "LPMCredential",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "BillingAutoReloadAmountScreenQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "payment_account",
              plural: !1,
              selections: [
                d,
                {
                  alias: null,
                  args: null,
                  concreteType: null,
                  kind: "LinkedField",
                  name: "billable_account",
                  plural: !1,
                  selections: [
                    d,
                    {
                      kind: "InlineFragment",
                      selections: [
                        {
                          alias: null,
                          args: null,
                          concreteType: "BillingAutoReloadInfo",
                          kind: "LinkedField",
                          name: "auto_reload_info",
                          plural: !1,
                          selections: [
                            {
                              alias: null,
                              args: null,
                              concreteType: "XFBAutoReloadPills",
                              kind: "LinkedField",
                              name: "auto_reload_pill_amounts",
                              plural: !1,
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAutoReloadPillData",
                                  kind: "LinkedField",
                                  name: "pill_one",
                                  plural: !1,
                                  selections: m,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAutoReloadPillData",
                                  kind: "LinkedField",
                                  name: "pill_two",
                                  plural: !1,
                                  selections: m,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAutoReloadPillData",
                                  kind: "LinkedField",
                                  name: "pill_three",
                                  plural: !1,
                                  selections: m,
                                  storageKey: null,
                                },
                              ],
                              storageKey: null,
                            },
                            r,
                            {
                              alias: null,
                              args: null,
                              concreteType: "CurrencyAmount",
                              kind: "LinkedField",
                              name: "auto_reload_amount",
                              plural: !1,
                              selections: o,
                              storageKey: null,
                            },
                            {
                              alias: null,
                              args: null,
                              concreteType: "CurrencyAmount",
                              kind: "LinkedField",
                              name: "auto_reload_trigger_threshold",
                              plural: !1,
                              selections: o,
                              storageKey: null,
                            },
                            l,
                          ],
                          storageKey: null,
                        },
                      ],
                      type: "AdAccount",
                      abstractKey: null,
                    },
                    p,
                  ],
                  storageKey: null,
                },
                p,
              ],
              storageKey: null,
            },
            {
              alias: null,
              args: s,
              concreteType: null,
              kind: "LinkedField",
              name: "node",
              plural: !1,
              selections: [
                d,
                {
                  kind: "InlineFragment",
                  selections: _,
                  type: "ExternalCreditCard",
                  abstractKey: null,
                },
                {
                  kind: "InlineFragment",
                  selections: _,
                  type: "LPMCredential",
                  abstractKey: null,
                },
                p,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: n("BillingAutoReloadAmountScreenQuery_facebookRelayOperation"),
          metadata: {},
          name: "BillingAutoReloadAmountScreenQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
