__d(
  "CliientAdAccountOverrideShopsAdsInstagramAccountsResolverFragment.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "username",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "profile_picture",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "uri",
              storageKey: null,
            },
          ],
          storageKey: null,
        };
      return {
        argumentDefinitions: [],
        kind: "Fragment",
        metadata: { vultureHash: "qy65B6pzw9bUlNlwmnCWi6hXt1Y=" },
        name: "CliientAdAccountOverrideShopsAdsInstagramAccountsResolverFragment",
        selections: [
          {
            alias: null,
            args: null,
            concreteType: "InstagramUserV2",
            kind: "LinkedField",
            name: "instagram_accounts",
            plural: !0,
            selections: [
              e,
              t,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "profile_pic",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "MiniShopStorefront",
                kind: "LinkedField",
                name: "mini_shop_storefront",
                plural: !1,
                selections: [
                  e,
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "title",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "shop_status",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "shop_product_count",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "CommerceMerchantSettings",
                    kind: "LinkedField",
                    name: "commerce_merchant_settings",
                    plural: !1,
                    selections: [
                      e,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "shop_ads_capabilities",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        concreteType: "ProductCatalog",
                        kind: "LinkedField",
                        name: "shop_catalog",
                        plural: !1,
                        selections: [e, n],
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "display_name",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "onsite_checkout_enabled_countries",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "Page",
                    kind: "LinkedField",
                    name: "page",
                    plural: !1,
                    selections: [e, n, r],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "InstagramUserV2",
                    kind: "LinkedField",
                    name: "ig_user",
                    plural: !1,
                    selections: [
                      e,
                      t,
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "legacy_instagram_user_id",
                        storageKey: null,
                      },
                      r,
                    ],
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "workspace_id",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        type: "AdAccount",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
