__d(
  "MiniShopStorefrontMiniShopStorefrontSpecResolver.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "profile_picture",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "uri",
              storageKey: null,
            },
          ],
          storageKey: null,
        };
      return {
        argumentDefinitions: [],
        kind: "Fragment",
        metadata: { vultureHash: "kdZV558b2kQwMeX74StARhGFwyA=" },
        name: "MiniShopStorefrontMiniShopStorefrontSpecResolver",
        selections: [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "__typename",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "CommerceMerchantSettings",
            kind: "LinkedField",
            name: "commerce_merchant_settings",
            plural: !1,
            selections: [
              e,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "shop_ads_capabilities",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "ProductCatalog",
                kind: "LinkedField",
                name: "product_catalog",
                plural: !1,
                selections: [e, t],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "display_name",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "onsite_checkout_enabled_countries",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          e,
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "title",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "Page",
            kind: "LinkedField",
            name: "page",
            plural: !1,
            selections: [e, t, n],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            concreteType: "InstagramUserV2",
            kind: "LinkedField",
            name: "ig_user",
            plural: !1,
            selections: [
              e,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "username",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "ig_user_id_fbv1_do_not_use",
                storageKey: null,
              },
              n,
            ],
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "shop_active_promotions",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "shop_product_count",
            storageKey: null,
          },
          {
            alias: "shop_status",
            args: null,
            kind: "ScalarField",
            name: "shop_status_spec",
            storageKey: null,
          },
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "workspace_id",
            storageKey: null,
          },
        ],
        type: "MiniShopStorefront",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
