__d(
  "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerLoadedQuery.graphql",
  ["MiniShopStorefront-mini_shop_storefront_spec-resolver"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        t = {
          alias: "name",
          args: null,
          kind: "ScalarField",
          name: "page_name",
          storageKey: null,
        },
        r = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
        ],
        o = {
          alias: "picture",
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "profile_picture",
          plural: !1,
          selections: r,
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "profile_picture",
          plural: !1,
          selections: r,
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [],
          kind: "Fragment",
          metadata: null,
          name: "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "Page",
                  kind: "LinkedField",
                  name: "loaded_pages",
                  plural: !0,
                  selections: [
                    e,
                    t,
                    o,
                    {
                      alias: null,
                      args: null,
                      concreteType: "MiniShopStorefront",
                      kind: "LinkedField",
                      name: "mini_shop_storefront",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          fragment: {
                            args: null,
                            kind: "FragmentSpread",
                            name: "MiniShopStorefrontMiniShopStorefrontSpecResolver",
                          },
                          kind: "RelayResolver",
                          name: "mini_shop_storefront_spec",
                          resolverModule: n(
                            "MiniShopStorefront-mini_shop_storefront_spec-resolver",
                          ).mini_shop_storefront_spec,
                          path: "loaded_pages.mini_shop_storefront.mini_shop_storefront_spec",
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [],
          kind: "Operation",
          name: "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "Page",
                  kind: "LinkedField",
                  name: "loaded_pages",
                  plural: !0,
                  selections: [
                    e,
                    t,
                    o,
                    {
                      alias: null,
                      args: null,
                      concreteType: "MiniShopStorefront",
                      kind: "LinkedField",
                      name: "mini_shop_storefront",
                      plural: !1,
                      selections: [
                        {
                          name: "mini_shop_storefront_spec",
                          args: null,
                          fragment: {
                            kind: "InlineFragment",
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "__typename",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "CommerceMerchantSettings",
                                kind: "LinkedField",
                                name: "commerce_merchant_settings",
                                plural: !1,
                                selections: [
                                  e,
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "shop_ads_capabilities",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType: "ProductCatalog",
                                    kind: "LinkedField",
                                    name: "product_catalog",
                                    plural: !1,
                                    selections: [e, a],
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "display_name",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "onsite_checkout_enabled_countries",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                              e,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "title",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "Page",
                                kind: "LinkedField",
                                name: "page",
                                plural: !1,
                                selections: [e, a, i],
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "InstagramUserV2",
                                kind: "LinkedField",
                                name: "ig_user",
                                plural: !1,
                                selections: [
                                  e,
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "username",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "ig_user_id_fbv1_do_not_use",
                                    storageKey: null,
                                  },
                                  i,
                                ],
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "shop_active_promotions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "shop_product_count",
                                storageKey: null,
                              },
                              {
                                alias: "shop_status",
                                args: null,
                                kind: "ScalarField",
                                name: "shop_status_spec",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "workspace_id",
                                storageKey: null,
                              },
                            ],
                            type: "MiniShopStorefront",
                            abstractKey: null,
                          },
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        e,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
        },
        params: {
          cacheID: "2fc22b08242492aafb5c8007f4f85024",
          id: null,
          metadata: {},
          name: "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerLoadedQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
