__d(
  "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerQuery.graphql",
  ["MiniShopStorefront-mini_shop_storefront_spec-resolver"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = [{ defaultValue: null, kind: "LocalArgument", name: "ids" }],
        t = [{ kind: "Variable", name: "ids", variableName: "ids" }],
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        o = {
          alias: "name",
          args: null,
          kind: "ScalarField",
          name: "page_name",
          storageKey: null,
        },
        a = [
          {
            alias: null,
            args: null,
            kind: "ScalarField",
            name: "uri",
            storageKey: null,
          },
        ],
        i = {
          alias: "picture",
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "profile_picture",
          plural: !1,
          selections: a,
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          concreteType: "Image",
          kind: "LinkedField",
          name: "profile_picture",
          plural: !1,
          selections: a,
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: e,
          kind: "Fragment",
          metadata: null,
          name: "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                {
                  kind: "InlineFragment",
                  selections: [
                    r,
                    o,
                    i,
                    {
                      alias: null,
                      args: null,
                      concreteType: "MiniShopStorefront",
                      kind: "LinkedField",
                      name: "mini_shop_storefront",
                      plural: !1,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          fragment: {
                            args: null,
                            kind: "FragmentSpread",
                            name: "MiniShopStorefrontMiniShopStorefrontSpecResolver",
                          },
                          kind: "RelayResolver",
                          name: "mini_shop_storefront_spec",
                          resolverModule: n(
                            "MiniShopStorefront-mini_shop_storefront_spec-resolver",
                          ).mini_shop_storefront_spec,
                          path: "nodes.mini_shop_storefront.mini_shop_storefront_spec",
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  type: "Page",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: e,
          kind: "Operation",
          name: "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerQuery",
          selections: [
            {
              alias: null,
              args: t,
              concreteType: null,
              kind: "LinkedField",
              name: "nodes",
              plural: !0,
              selections: [
                l,
                r,
                {
                  kind: "InlineFragment",
                  selections: [
                    o,
                    i,
                    {
                      alias: null,
                      args: null,
                      concreteType: "MiniShopStorefront",
                      kind: "LinkedField",
                      name: "mini_shop_storefront",
                      plural: !1,
                      selections: [
                        {
                          name: "mini_shop_storefront_spec",
                          args: null,
                          fragment: {
                            kind: "InlineFragment",
                            selections: [
                              l,
                              {
                                alias: null,
                                args: null,
                                concreteType: "CommerceMerchantSettings",
                                kind: "LinkedField",
                                name: "commerce_merchant_settings",
                                plural: !1,
                                selections: [
                                  r,
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "shop_ads_capabilities",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    concreteType: "ProductCatalog",
                                    kind: "LinkedField",
                                    name: "product_catalog",
                                    plural: !1,
                                    selections: [r, s],
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "display_name",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "onsite_checkout_enabled_countries",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "onsite_checkout_enabled_for_shops_ads_supported_countries",
                                    storageKey: null,
                                  },
                                ],
                                storageKey: null,
                              },
                              r,
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "title",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "Page",
                                kind: "LinkedField",
                                name: "page",
                                plural: !1,
                                selections: [r, s, u],
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                concreteType: "InstagramUserV2",
                                kind: "LinkedField",
                                name: "ig_user",
                                plural: !1,
                                selections: [
                                  r,
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "username",
                                    storageKey: null,
                                  },
                                  {
                                    alias: null,
                                    args: null,
                                    kind: "ScalarField",
                                    name: "ig_user_id_fbv1_do_not_use",
                                    storageKey: null,
                                  },
                                  u,
                                ],
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "shop_active_promotions",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "shop_product_count",
                                storageKey: null,
                              },
                              {
                                alias: "shop_status",
                                args: null,
                                kind: "ScalarField",
                                name: "shop_status_spec",
                                storageKey: null,
                              },
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "workspace_id",
                                storageKey: null,
                              },
                            ],
                            type: "MiniShopStorefront",
                            abstractKey: null,
                          },
                          kind: "RelayResolver",
                          storageKey: null,
                          isOutputType: !0,
                        },
                        r,
                      ],
                      storageKey: null,
                    },
                  ],
                  type: "Page",
                  abstractKey: null,
                },
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "26751156994550180",
          metadata: {},
          name: "ShopAdsPageToCommerceMerchantSettingsStoreSourceServerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
