__d(
  "SignalsLoadAdAccountSignalSourceContainersStoreSourceServerLoadedQuery.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        t = {
          alias: null,
          args: null,
          concreteType: "XFBSignalContainerdCluster",
          kind: "LinkedField",
          name: "cluster",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "pixel_id",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "data_set_id",
              storageKey: null,
            },
            {
              alias: null,
              args: null,
              concreteType: "XFBSignalContainerdAppInfo",
              kind: "LinkedField",
              name: "app",
              plural: !1,
              selections: [
                e,
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "object_store_urls",
                  storageKey: null,
                },
              ],
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        n = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_bapi_domains",
          storageKey: null,
        },
        r = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "signal_containers_id",
          storageKey: null,
        },
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "last_fired_time",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "server_last_fired_time",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "name",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_unavailable",
          storageKey: null,
        },
        s = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_eligible_for_value_optimization",
          storageKey: null,
        },
        u = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_bwi_eligible",
          storageKey: null,
        },
        c = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_bwp_eligible",
          storageKey: null,
        },
        d = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "signal_setup_recommendation_ent_id",
          storageKey: null,
        },
        m = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_signal_setup_recommended_share_to_biz",
          storageKey: null,
        },
        p = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_access_to_shared_event_names_only",
          storageKey: null,
        },
        _ = {
          alias: null,
          args: null,
          concreteType: "XFBSignalContainersOwnerAdAccount",
          kind: "LinkedField",
          name: "owner_ad_account",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "account_id",
              storageKey: null,
            },
          ],
          storageKey: null,
        },
        f = {
          alias: null,
          args: null,
          concreteType: "XFBSignalContainersOwnerBusiness",
          kind: "LinkedField",
          name: "owner_business",
          plural: !1,
          selections: [
            {
              alias: null,
              args: null,
              kind: "ScalarField",
              name: "business_id",
              storageKey: null,
            },
            i,
          ],
          storageKey: null,
        },
        g = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "is_offline_active",
          storageKey: null,
        },
        h = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "business_object_id",
          storageKey: null,
        },
        y = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "creation_time",
          storageKey: null,
        },
        C = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "revenue_events_last_56d",
          storageKey: null,
        },
        b = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_custom_attribution_source",
          storageKey: null,
        },
        v = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "has_eligible_custom_attribution_source",
          storageKey: null,
        };
      return {
        fragment: {
          argumentDefinitions: [],
          kind: "Fragment",
          metadata: null,
          name: "SignalsLoadAdAccountSignalSourceContainersStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType:
                    "XFBXSignalsLoadAdAccountSignalSourceContainersController",
                  kind: "LinkedField",
                  name: "loaded_signals_load_ad_account_signal_source_containers",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBSignalContainers",
                      kind: "LinkedField",
                      name: "signal_containers",
                      plural: !0,
                      selections: [
                        t,
                        n,
                        r,
                        o,
                        a,
                        i,
                        l,
                        s,
                        u,
                        c,
                        d,
                        m,
                        p,
                        _,
                        f,
                        g,
                        h,
                        y,
                        C,
                        b,
                        v,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [],
          kind: "Operation",
          name: "SignalsLoadAdAccountSignalSourceContainersStoreSourceServerLoadedQuery",
          selections: [
            {
              kind: "ClientExtension",
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType:
                    "XFBXSignalsLoadAdAccountSignalSourceContainersController",
                  kind: "LinkedField",
                  name: "loaded_signals_load_ad_account_signal_source_containers",
                  plural: !0,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBSignalContainers",
                      kind: "LinkedField",
                      name: "signal_containers",
                      plural: !0,
                      selections: [
                        t,
                        n,
                        r,
                        o,
                        a,
                        i,
                        l,
                        s,
                        u,
                        c,
                        d,
                        m,
                        p,
                        _,
                        f,
                        g,
                        h,
                        y,
                        C,
                        b,
                        v,
                        e,
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
              ],
            },
          ],
        },
        params: {
          cacheID: "26dc0009a88de34f4079be727462de60",
          id: null,
          metadata: {},
          name: "SignalsLoadAdAccountSignalSourceContainersStoreSourceServerLoadedQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    a.exports = e;
  },
  null,
);
