__d(
  "SignalsLoadAdAccountSignalSourceContainersStoreSourceFragment.graphql",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = {
        alias: null,
        args: null,
        kind: "ScalarField",
        name: "name",
        storageKey: null,
      };
      return {
        argumentDefinitions: [],
        kind: "Fragment",
        metadata: null,
        name: "SignalsLoadAdAccountSignalSourceContainersStoreSourceFragment",
        selections: [
          {
            alias: null,
            args: null,
            concreteType: "XFBSignalContainers",
            kind: "LinkedField",
            name: "signal_containers",
            plural: !0,
            selections: [
              {
                alias: null,
                args: null,
                concreteType: "XFBSignalContainerdCluster",
                kind: "LinkedField",
                name: "cluster",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "pixel_id",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "data_set_id",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "XFBSignalContainerdAppInfo",
                    kind: "LinkedField",
                    name: "app",
                    plural: !1,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "id",
                        storageKey: null,
                      },
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "object_store_urls",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "has_bapi_domains",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "signal_containers_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "last_fired_time",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "server_last_fired_time",
                storageKey: null,
              },
              e,
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_unavailable",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_eligible_for_value_optimization",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_bwi_eligible",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_bwp_eligible",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "signal_setup_recommendation_ent_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_signal_setup_recommended_share_to_biz",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "has_access_to_shared_event_names_only",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBSignalContainersOwnerAdAccount",
                kind: "LinkedField",
                name: "owner_ad_account",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "account_id",
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                concreteType: "XFBSignalContainersOwnerBusiness",
                kind: "LinkedField",
                name: "owner_business",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "business_id",
                    storageKey: null,
                  },
                  e,
                ],
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "is_offline_active",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "business_object_id",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "creation_time",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "revenue_events_last_56d",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "has_custom_attribution_source",
                storageKey: null,
              },
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "has_eligible_custom_attribution_source",
                storageKey: null,
              },
            ],
            storageKey: null,
          },
        ],
        type: "XFBXSignalsLoadAdAccountSignalSourceContainersController",
        abstractKey: null,
      };
    })();
    a.exports = e;
  },
  null,
);
