__d(
  "SYDMetricSnapshotWidgetContainerQuery.graphql",
  ["relay-runtime"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = (function () {
      var e = { defaultValue: null, kind: "LocalArgument", name: "accountID" },
        t = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "shouldPrefetchSYDUris",
        },
        n = {
          defaultValue: null,
          kind: "LocalArgument",
          name: "useEntrypointForWidgetModal",
        },
        r = [
          {
            kind: "Variable",
            name: "legacy_account_id",
            variableName: "accountID",
          },
        ],
        o = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "type",
          storageKey: null,
        },
        a = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "id",
          storageKey: null,
        },
        i = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "__typename",
          storageKey: null,
        },
        l = {
          alias: null,
          args: null,
          kind: "ScalarField",
          name: "metric_type",
          storageKey: null,
        },
        s = [a],
        u = [
          {
            alias: null,
            args: null,
            concreteType: "AdCampaign",
            kind: "LinkedField",
            name: "campaign",
            plural: !1,
            selections: s,
            storageKey: null,
          },
          l,
          i,
        ],
        c = {
          kind: "ClientEdgeToClientObject",
          backingField: {
            name: "selected_ad_account",
            args: null,
            fragment: null,
            kind: "RelayResolver",
            storageKey: null,
            isOutputType: !1,
          },
          linkedField: {
            alias: null,
            args: null,
            concreteType: "ClientAdAccount",
            kind: "LinkedField",
            name: "selected_ad_account",
            plural: !1,
            selections: [
              {
                name: "override_currency",
                args: null,
                fragment: {
                  kind: "InlineFragment",
                  selections: [
                    {
                      name: "__relay_model_instance",
                      args: null,
                      fragment: {
                        kind: "InlineFragment",
                        selections: s,
                        type: "ClientAdAccount",
                        abstractKey: null,
                      },
                      kind: "RelayResolver",
                      storageKey: null,
                      isOutputType: !1,
                    },
                  ],
                  type: "ClientAdAccount",
                  abstractKey: null,
                },
                kind: "RelayResolver",
                storageKey: null,
                isOutputType: !0,
              },
              a,
            ],
            storageKey: null,
          },
        },
        d = [
          {
            alias: null,
            args: null,
            concreteType: "AdCampaign",
            kind: "LinkedField",
            name: "campaign",
            plural: !1,
            selections: [
              {
                alias: null,
                args: null,
                kind: "ScalarField",
                name: "name",
                storageKey: null,
              },
              {
                alias: "adgroups_for_image_thumbnail",
                args: [
                  { kind: "Literal", name: "first", value: 3 },
                  {
                    kind: "Literal",
                    name: "orderby",
                    value: ["reverse_start_time"],
                  },
                ],
                concreteType: "AdCampaignAdgroupsConnection",
                kind: "LinkedField",
                name: "adgroups",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdCampaignAdgroupsEdge",
                    kind: "LinkedField",
                    name: "edges",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        concreteType: "Adgroup",
                        kind: "LinkedField",
                        name: "node",
                        plural: !1,
                        selections: [
                          {
                            alias: "thumbnail_image",
                            args: [
                              { kind: "Literal", name: "height", value: 24 },
                              { kind: "Literal", name: "width", value: 24 },
                            ],
                            concreteType: "Image",
                            kind: "LinkedField",
                            name: "preview_image",
                            plural: !1,
                            selections: [
                              {
                                alias: null,
                                args: null,
                                kind: "ScalarField",
                                name: "uri",
                                storageKey: null,
                              },
                            ],
                            storageKey: "preview_image(height:24,width:24)",
                          },
                          a,
                        ],
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: 'adgroups(first:3,orderby:["reverse_start_time"])',
              },
              a,
              {
                alias: null,
                args: null,
                concreteType: "AdDeliveryStatusNode",
                kind: "LinkedField",
                name: "delivery_status",
                plural: !1,
                selections: [
                  {
                    alias: null,
                    args: null,
                    kind: "ScalarField",
                    name: "status",
                    storageKey: null,
                  },
                  {
                    alias: null,
                    args: null,
                    concreteType: "AdDeliverySubstatusNode",
                    kind: "LinkedField",
                    name: "substatuses",
                    plural: !0,
                    selections: [
                      {
                        alias: null,
                        args: null,
                        kind: "ScalarField",
                        name: "text",
                        storageKey: null,
                      },
                    ],
                    storageKey: null,
                  },
                ],
                storageKey: null,
              },
            ],
            storageKey: null,
          },
          c,
          l,
          {
            alias: "metric_reach",
            args: [{ kind: "Literal", name: "metric_type", value: "REACH" }],
            kind: "ScalarField",
            name: "metric",
            storageKey: 'metric(metric_type:"REACH")',
          },
          {
            alias: "metric_cpm",
            args: [{ kind: "Literal", name: "metric_type", value: "CPM" }],
            kind: "ScalarField",
            name: "metric",
            storageKey: 'metric(metric_type:"CPM")',
          },
          {
            alias: "metric_spend",
            args: [{ kind: "Literal", name: "metric_type", value: "SPEND" }],
            kind: "ScalarField",
            name: "metric",
            storageKey: 'metric(metric_type:"SPEND")',
          },
          c,
          {
            alias: "metric_results",
            args: [{ kind: "Literal", name: "metric_type", value: "RESULTS" }],
            kind: "ScalarField",
            name: "metric",
            storageKey: 'metric(metric_type:"RESULTS")',
          },
          {
            alias: "metric_cost_per",
            args: [
              {
                kind: "Literal",
                name: "metric_type",
                value: "COST_PER_RESULT",
              },
            ],
            kind: "ScalarField",
            name: "metric",
            storageKey: 'metric(metric_type:"COST_PER_RESULT")',
          },
        ];
      return {
        fragment: {
          argumentDefinitions: [e, t, n],
          kind: "Fragment",
          metadata: null,
          name: "SYDMetricSnapshotWidgetContainerQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [
                {
                  args: null,
                  kind: "FragmentSpread",
                  name: "SYDMetricSnapshotWidgetContent_fragment",
                },
              ],
              storageKey: null,
            },
          ],
          type: "Query",
          abstractKey: null,
        },
        kind: "Request",
        operation: {
          argumentDefinitions: [e, n, t],
          kind: "Operation",
          name: "SYDMetricSnapshotWidgetContainerQuery",
          selections: [
            {
              alias: null,
              args: r,
              concreteType: "AdAccount",
              kind: "LinkedField",
              name: "ad_account",
              plural: !1,
              selections: [
                {
                  alias: null,
                  args: null,
                  concreteType: "XFBSYDMetricSnapshotFields",
                  kind: "LinkedField",
                  name: "metric_snapshot_widget_data",
                  plural: !1,
                  selections: [
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBSYDMetricSnapshotFilterOption",
                      kind: "LinkedField",
                      name: "filter_options",
                      plural: !0,
                      selections: [
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "label",
                          storageKey: null,
                        },
                        o,
                      ],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBSYDMetricSnapshotFilterOption",
                      kind: "LinkedField",
                      name: "selected_filter_option",
                      plural: !1,
                      selections: [o],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "AdCampaign",
                      kind: "LinkedField",
                      name: "campaigns",
                      plural: !0,
                      selections: [a, i],
                      storageKey: null,
                    },
                    {
                      alias: null,
                      args: null,
                      concreteType: "XFBSYDMetrics",
                      kind: "LinkedField",
                      name: "metrics",
                      plural: !0,
                      selections: [
                        l,
                        {
                          alias: null,
                          args: null,
                          kind: "ScalarField",
                          name: "aggregate_value_by_metric_type",
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "XFBAdCampaignWithSYDMetrics",
                          kind: "LinkedField",
                          name: "highest_campaign",
                          plural: !1,
                          selections: u,
                          storageKey: null,
                        },
                        {
                          alias: null,
                          args: null,
                          concreteType: "XFBAdCampaignWithSYDMetrics",
                          kind: "LinkedField",
                          name: "lowest_campaign",
                          plural: !1,
                          selections: u,
                          storageKey: null,
                        },
                        {
                          condition: "useEntrypointForWidgetModal",
                          kind: "Condition",
                          passingValue: !1,
                          selections: [
                            {
                              if: null,
                              kind: "Defer",
                              label:
                                "SYDMetricSnapshotWidgetMetricTile_fragment$defer$SYDMetricSnapshotWidgetModal_fragment",
                              selections: [
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAdCampaignWithSYDMetrics",
                                  kind: "LinkedField",
                                  name: "highest_campaign",
                                  plural: !1,
                                  selections: d,
                                  storageKey: null,
                                },
                                {
                                  alias: null,
                                  args: null,
                                  concreteType: "XFBAdCampaignWithSYDMetrics",
                                  kind: "LinkedField",
                                  name: "lowest_campaign",
                                  plural: !1,
                                  selections: d,
                                  storageKey: null,
                                },
                                l,
                              ],
                            },
                          ],
                        },
                      ],
                      storageKey: null,
                    },
                  ],
                  storageKey: null,
                },
                {
                  alias: null,
                  args: null,
                  kind: "ScalarField",
                  name: "currency_code_enum",
                  storageKey: null,
                },
                a,
              ],
              storageKey: null,
            },
          ],
        },
        params: {
          id: "26766153766324315",
          metadata: {},
          name: "SYDMetricSnapshotWidgetContainerQuery",
          operationKind: "query",
          text: null,
        },
      };
    })();
    (n("relay-runtime").PreloadableQueryRegistry.set(e.params.id, e),
      (a.exports = e));
  },
  null,
);
