__d(
  "AdCreativeSourceActionType",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      AWPT_MIGRATION_ENABLE_PE: "AWPT_MIGRATION_ENABLE_PE",
      AWPT_MIGRATION_ENBALE_CATALOG_CONSISTENCY:
        "AWPT_MIGRATION_ENBALE_CATALOG_CONSISTENCY",
      BACKFILL: "BACKFILL",
      DEFAULT: "DEFAULT",
      DEFAULT_OPT_IN: "DEFAULT_OPT_IN",
      DUPLICATION_UPGRADE: "DUPLICATION_UPGRADE",
      MANUAL: "MANUAL",
      MULTI_PHOTO_GENERATED: "MULTI_PHOTO_GENERATED",
      OPTIMISED_MULTI_POST_GENERATED: "OPTIMISED_MULTI_POST_GENERATED",
      SCJ_ADS_GENERATED: "SCJ_ADS_GENERATED",
      SITE_LINKS_GENERATED: "SITE_LINKS_GENERATED",
      SOFT_DEFAULT_ON: "SOFT_DEFAULT_ON",
      STICKY: "STICKY",
      UNKNOWN: "UNKNOWN",
    });
    i.default = e;
  },
  66,
);
