__d(
  "AdsCreativeBadgeConstants",
  ["fbt", "react"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e,
      u,
      c,
      d,
      m,
      p,
      _,
      f,
      g,
      h,
      y,
      C,
      b = C || (C = o("react")),
      v = s._(/*BTDS*/ "Create new info label"),
      S = s._(
        /*BTDS*/ "Info labels should highlight information likely to interest people (example: free shipping).",
      ),
      R = s._(
        /*BTDS*/ "Info labels will show up on the most relevant placement. We'll show 1 to 3 info labels per ad placement, depending on performance. Final rendering and interaction may vary.",
      ),
      L = s._(/*BTDS*/ "Create info labels"),
      E = s._(/*BTDS*/ "Info labels"),
      k = s._(/*BTDS*/ "Done"),
      I = s._(
        /*BTDS*/ "Help your business stand out and build trust with customers by using info labels to highlight important information. Create as many info labels as you'd like and we'll automatically decide whether to show them based on potential performance lift.",
      ),
      T =
        ((e = {}),
        (e.shipping_policy = s._(/*BTDS*/ "Free shipping")),
        (e.payment_options = s._(/*BTDS*/ "Payment options")),
        (e.return_policy = s._(/*BTDS*/ "Return policy")),
        e),
      D =
        ((u = {}),
        (u.shipping_policy = s._(
          /*BTDS*/ "Showcase when you offer free shipping.",
        )),
        (u.payment_options = s._(
          /*BTDS*/ "Tell people how they can pay securely.",
        )),
        (u.return_policy = s._(
          /*BTDS*/ "Showcase when you offer free returns.",
        )),
        u),
      x = s._(/*BTDS*/ "Info label type"),
      $ = s._(/*BTDS*/ "Select info label type"),
      P = s._(/*BTDS*/ "Optional"),
      N = s._(
        /*BTDS*/ 'The information you provide here helps our system automatically build info labels likely to improve your ad performance. The phrasing you see in these questions may produce info labels such as "free 2-day shipping."',
      ),
      M =
        ((c = {}),
        (c[1] = s._(/*BTDS*/ "1")),
        (c[2] = s._(/*BTDS*/ "2")),
        (c[3] = s._(/*BTDS*/ "3")),
        (c[4] = s._(/*BTDS*/ "4")),
        (c[5] = s._(/*BTDS*/ "5")),
        (c[6] = s._(/*BTDS*/ "6")),
        c),
      w = s._(/*BTDS*/ "Shipping timeframe for free shipping"),
      A = s._(/*BTDS*/ "Add number"),
      F = s._(/*BTDS*/ "Add timeframe"),
      O = s._(/*BTDS*/ "Free shipping applies only to orders over"),
      B = s._(/*BTDS*/ "Add price"),
      W = s._(/*BTDS*/ "Order value"),
      q = s._(/*BTDS*/ "Payment methods you accept"),
      U = s._(/*BTDS*/ "Select all that apply"),
      V =
        ((d = {}),
        (d.affirm = s._(/*BTDS*/ "Affirm")),
        (d.afterpay = s._(/*BTDS*/ "Afterpay")),
        (d.amazon_pay = s._(/*BTDS*/ "Amazon Pay")),
        (d.apple_pay = s._(/*BTDS*/ "Apple Pay")),
        (d.google_pay = s._(/*BTDS*/ "Google Pay")),
        (d.klarna = s._(/*BTDS*/ "Klarna")),
        (d.paypal = s._(/*BTDS*/ "PayPal")),
        d),
      H = s._(/*BTDS*/ "return policy window"),
      G = s._(/*BTDS*/ "Add number"),
      z = s._(/*BTDS*/ "Add timeframe"),
      j = s._(/*BTDS*/ "Returns are accepted within"),
      K = s._(/*BTDS*/ "of purchase"),
      Q = s._(/*BTDS*/ "Show return policy"),
      X = s._(/*BTDS*/ "Placeholder Checkbox Label"),
      Y = s._(/*BTDS*/ "Optional"),
      J = s._(
        /*BTDS*/ "The information you provide here helps our system automatically build info labels likely to improve your ad performance. The phrasing you see in these questions may produce info labels such as \u201cfree 2-day returns.\u201d",
      ),
      Z = s._(/*BTDS*/ "Show shipping policy"),
      ee = s._(/*BTDS*/ "Remove"),
      te = function (t) {
        return s._(/*BTDS*/ "Info label {badge item index} information", [
          s._param("badge item index", t),
        ]);
      },
      ne = s._(/*BTDS*/ "Remove all"),
      re = s._(/*BTDS*/ "Are returns free?"),
      oe = s._(/*BTDS*/ "Select"),
      ae = s._(/*BTDS*/ "Yes"),
      ie = s._(/*BTDS*/ "No"),
      le = s._(/*BTDS*/ "Is shipping free?"),
      se = s._(/*BTDS*/ "Select"),
      ue = s._(/*BTDS*/ "Yes"),
      ce = s._(/*BTDS*/ "No"),
      de = ["shipping_policy", "payment_options", "return_policy"],
      me = s._(/*BTDS*/ "Facebook will automatically adjust phrasing"),
      pe = s._(/*BTDS*/ "Next"),
      _e = s._(/*BTDS*/ "Info labels"),
      fe = s._(/*BTDS*/ "Turn on info labels"),
      ge = s._(/*BTDS*/ "Add info labels"),
      he = s._(
        /*BTDS*/ "Help your business stand out and build trust with customers by using info labels to highlight important information. Turn on as many info labels as you\u2019d like and we\u2019ll automatically decide whether to show them based on potential performance lift.",
      ),
      ye = s._(/*BTDS*/ "Done"),
      Ce = s._(/*BTDS*/ "Save"),
      be = s._(/*BTDS*/ "From your profile"),
      ve = s._(/*BTDS*/ "Info labels"),
      Se = function (t, n) {
        return s._(/*BTDS*/ "Brand highlights ({selected}\/{total})", [
          s._param("selected", t),
          s._param("total", n),
        ]);
      },
      Re = s._(
        /*BTDS*/ "Show a number range of interactions from your website, like purchases, site visits or ad views, on your Instagram and Facebook ads.",
      ),
      Le = s._(
        /*BTDS*/ "By opting into these info labels, you allow Meta to use pixel and Conversions API data to source this information and display these info labels on your ads. You can opt out at any time by visiting this page again.",
      ),
      Ee = s._(/*BTDS*/ "Learn more about how we use pixel data"),
      ke = [
        "number_range_of_ad_views",
        "number_range_of_purchases",
        "number_range_of_site_visits",
      ],
      Ie =
        ((m = {}),
        (m.number_range_of_purchases = s._(
          /*BTDS*/ "Number range of purchases",
        )),
        (m.number_range_of_site_visits = s._(
          /*BTDS*/ "Number range of site visits",
        )),
        (m.number_range_of_ad_views = s._(/*BTDS*/ "Number range of ad views")),
        m),
      Te = function (t, n) {
        return s._(/*BTDS*/ "App highlights ({selected}\/{total})", [
          s._param("selected", t),
          s._param("total", n),
        ]);
      },
      De = s._(
        /*BTDS*/ "App highlights use public App Store information to showcase the number of interactions with your app.",
      ),
      xe = [
        "editors_choice",
        "app_rating",
        "app_rank_install_count",
        "mobile_app_store_screenshot",
      ],
      $e =
        ((p = {}),
        (p.editors_choice = s._(/*BTDS*/ "Editor's Choice")),
        (p.app_rating = s._(/*BTDS*/ "App rating")),
        (p.app_rank_install_count = s._(/*BTDS*/ "App rank install count")),
        (p.mobile_app_store_screenshot = s._(
          /*BTDS*/ "Mobile app store screenshot",
        )),
        p),
      Pe = s._(/*BTDS*/ "Social cues"),
      Ne = s._(
        /*BTDS*/ "Social cues help show excitement around your brand. We recommend using all of the social cues available.",
      ),
      Me = s._(/*BTDS*/ "Business information"),
      we = function (t, n) {
        return s._(/*BTDS*/ "Business information ({selected}\/{total})", [
          s._param("selected", t),
          s._param("total", n),
        ]);
      },
      Ae = function (t, n) {
        return s._(/*BTDS*/ "Social cues ({selected}\/{total})", [
          s._param("selected", t),
          s._param("total", n),
        ]);
      },
      Fe = s._(
        /*BTDS*/ "This information comes from the About section of the Facebook Page or Instagram business account associated with each ad. Select the info labels you\u2019d like to turn on and when needed, update on the relevant Facebook Page or Instagram business account.",
      ),
      Oe = function (t, n, r, o) {
        return o
          ? s._(
              /*BTDS*/ "This information comes from the About section of your Facebook Page {facebook page name in info labels flow} or Instagram business account{instagram account name in info labels flow}. You can update this information on Facebook or Instagram.",
              [
                s._param(
                  "facebook page name in info labels flow",
                  b.jsx("b", { children: t ? " " + t : "" }),
                ),
                s._param(
                  "instagram account name in info labels flow",
                  b.jsx("b", { children: n ? " " + n : "" }),
                ),
              ],
            )
          : r
            ? s._(
                /*BTDS*/ "This information comes from the About section of your Facebook Page {facebook page name in info labels flow} or Instagram business account{instagram account name in info labels flow}. Select the info labels you\u2019d like to turn on and when needed, update on Facebook or Instagram.",
                [
                  s._param(
                    "facebook page name in info labels flow",
                    b.jsx("b", { children: t ? " " + t : "" }),
                  ),
                  s._param(
                    "instagram account name in info labels flow",
                    b.jsx("b", { children: n ? " " + n : "" }),
                  ),
                ],
              )
            : s._(
                /*BTDS*/ "This info comes from the About section of your Facebook Page {facebook page name in info labels flow} or Instagram business account. Select the info labels you'd like to turn on and when needed, update on Facebook or Instagram.",
                [
                  s._param(
                    "facebook page name in info labels flow",
                    b.jsx("b", { children: t }),
                  ),
                ],
              );
      },
      Be = [
        "ig_account_joining_date",
        "page_operating_hours",
        "page_price_range",
        "page_store_location",
      ],
      We =
        ((_ = {}),
        (_.ig_account_joining_date = s._(/*BTDS*/ "Date joined Instagram")),
        (_.page_operating_hours = s._(/*BTDS*/ "Store hours of operation")),
        (_.page_price_range = s._(/*BTDS*/ "Store price range")),
        (_.page_store_location = s._(/*BTDS*/ "Store location")),
        _),
      qe = [
        "ig_account_followers",
        "page_check_ins",
        "page_follows",
        "page_likes",
        "page_messenger_response_time",
        "page_ratings",
        "page_recent_check_ins",
      ],
      Ue =
        ((f = {}),
        (f.ig_account_followers = s._(/*BTDS*/ "Instagram followers")),
        (f.page_check_ins = s._(/*BTDS*/ "Page check-ins")),
        (f.page_follows = s._(/*BTDS*/ "Page follows")),
        (f.page_likes = s._(/*BTDS*/ "Page likes")),
        (f.page_messenger_response_time = s._(
          /*BTDS*/ "Page Messenger response time",
        )),
        (f.page_ratings = s._(/*BTDS*/ "Page ratings")),
        (f.page_recent_check_ins = s._(/*BTDS*/ "Recent Page check-ins")),
        f),
      Ve = s._(
        /*BTDS*/ "Sample preview shows how the info label you've selected will appear on your ad.",
      ),
      He = s._(/*BTDS*/ "Sample preview"),
      Ge = s._(
        /*BTDS*/ "Sample preview is for illustration only. Info labels will show up on the most relevant placement. Final rendering and interaction may vary. By enabling info labels, you acknowledge that we'll automatically use information from your Page and Instagram business account, and you confirm that this information is current and accurate.",
      ),
      ze = "/images/creative_products/creative_info_label_preview_",
      je = "/images/creative_products/creative_badge_preview_",
      Ke = ".png",
      Qe = "/images/creative_products/creative_badge_preview_sample.png",
      Xe = "/images/creative_products/creative_badge_preview_sample_igfeed.svg",
      Ye = 1224,
      Je = "417274223564313",
      Ze = "1720288338140238",
      et = function (t) {
        return s._(/*BTDS*/ '_j{"*":"Days","_1":"Day"}', [s._plural(t)]);
      },
      tt = function (t) {
        return s._(/*BTDS*/ '_j{"*":"Weeks","_1":"Week"}', [s._plural(t)]);
      },
      nt = function (t) {
        return s._(/*BTDS*/ '_j{"*":"Months","_1":"Month"}', [s._plural(t)]);
      },
      rt =
        ((g = {}),
        (g["Facebook Feed"] = s._(/*BTDS*/ "Facebook Feed")),
        (g["Instagram Feed"] = s._(/*BTDS*/ "Instagram Feed")),
        g),
      ot = ["Free Shipping", "Return Policy", "Payment Options"],
      at =
        ((h = {}),
        (h["Free Shipping"] = s._(/*BTDS*/ "Free shipping")),
        (h["Return Policy"] = s._(/*BTDS*/ "Return policy")),
        (h["Payment Options"] = s._(/*BTDS*/ "Payment options")),
        h),
      it =
        ((y = {}),
        (y["Free Shipping"] = s._(/*BTDS*/ "Free shipping")),
        (y["Return Policy"] = s._(/*BTDS*/ "X-day free returns")),
        (y["Payment Options"] = s._(/*BTDS*/ "PayPal accepted")),
        y),
      lt = s._(/*BTDS*/ "Info labels added from existing information"),
      st = s._(
        /*BTDS*/ "Shopping details and payment options info labels have been automatically added. Please review to make sure they're accurate.",
      ),
      ut = s._(/*BTDS*/ "No info labels were added"),
      ct = s._(
        /*BTDS*/ "We couldn't find the required information to automatically add info labels. Please manually add return policy, shipping information, and payment options info labels.",
      );
    ((l.CREATIVE_BADGE_ADD_CALL_OUT_BUTTON_MODAL_LABEL = v),
      (l.CREATIVE_BADGE_MODAL_PREVIEW_CARD_DESCRIPTION = S),
      (l.CREATIVE_BADGE_MODAL_PREVIEW_CARD_FOOTER = R),
      (l.CREATIVE_BADGE_CALL_OUTS_MODAL_TITLE = L),
      (l.CREATIVE_BADGE_CALL_OUTS_PREVIEW_TITLE = E),
      (l.CREATIVE_BADGE_MODAL_PRIMARY_BUTTON_LABEL = k),
      (l.CREATIVE_BADGE_MODAL_SUBTITLE = I),
      (l.CREATIVE_BADGE_INFO_TYPES_LABELS = T),
      (l.CREATIVE_BADGE_INFO_TYPES_DESCRIPTIONS = D),
      (l.BADGE_INFO_TYPE_LABEL = x),
      (l.BADGE_INFO_TYPE_PLACEHOLDER = $),
      (l.BADGE_SHIPPING_OPTIONS_TITLE = P),
      (l.BADGE_SHIPPING_OPTIONS_TITLE_TOOLTIP = N),
      (l.CREATIVE_BADGE_FREE_SHIPPING_DAYS_LABELS = M),
      (l.FREE_SHIPPING_TEXT = w),
      (l.DAY_SELECTOR_PLACEHOLDER_TEXT = A),
      (l.TIMEFRAME_SELECTOR_PLACEHOLDER_TEXT = F),
      (l.FREE_SHIPPING_PRICE_TEXT = O),
      (l.FREE_SHIPPING_PRICE_INPUT_PLACEHOLDER_TEXT = B),
      (l.FREE_SHIPPING_ORDER_VALUE_LABEL = W),
      (l.PAYMENT_METHODS_ACCEPTED = q),
      (l.PAYMENT_OPTIONS_PLACEHOLDER_TEXT = U),
      (l.CREATIVE_BADGE_PAYMENT_OPTIONS_LABELS = V),
      (l.RETURN_POLICY_WINDOW_LABEL = H),
      (l.RETURN_POLICY_WINDOW_PLACEHOLDER = G),
      (l.RETURN_POLICY_WINDOW_UNIT_LABEL = z),
      (l.RETURN_POLICY_PREFIX_TEXT = j),
      (l.RETURN_POLICY_SUFFIX_TEXT = K),
      (l.RETURN_POLICY_ENABLE_CHECKBOX_LABEL = Q),
      (l.RETURN_POLICY_CHECKBOX_PLACEHOLDER_LABEL = X),
      (l.RETURN_POLICY_CHECKBOX_HEADER = Y),
      (l.RETURN_POLICY_TOOLTIP_CONTENT = J),
      (l.SHIPPING_POLICY_ENABLE_CHECKBOX_LABEL = Z),
      (l.BADGE_ITEM_REMOVE_LABEL = ee),
      (l.getCreativeBadgeItemTitle = te),
      (l.REMOVE_ALL_BADGE_BUTTON_LABEL = ne),
      (l.FREE_RETURNS_LABEL = re),
      (l.FREE_RETURNS_PLACEHOLDER_TEXT = oe),
      (l.FREE_RETURNS_RESPONSE_LABEL = ae),
      (l.NON_FREE_RETURNS_RESPONSE_LABEL = ie),
      (l.FREE_SHIPPING_LABEL = le),
      (l.FREE_SHIPPING_PLACEHOLDER_TEXT = se),
      (l.FREE_SHIPPING_RESPONSE_LABEL = ue),
      (l.NON_FREE_SHIPPING_RESPONSE_LABEL = ce),
      (l.CREATIVE_MANUAL_BADGE_INFO_TYPES = de),
      (l.CALL_OUTS_TOOLTIP_HEADING = me),
      (l.BASE_MODAL_PRIMARY_BUTTON_TEXT = pe),
      (l.BASE_MODAL_UPDATED_HEADER_TEXT = _e),
      (l.BASE_MODAL_HEADER_TEXT = fe),
      (l.AUTOMATED_LABEL_MODAL_HEADER_TEXT = ge),
      (l.BASE_MODAL_HEADER_DESCRIPTION_TEXT = he),
      (l.BASE_MODAL_DONE_BUTTON_TEXT = ye),
      (l.BASE_MODAL_SAVE_BUTTON_TEXT = Ce),
      (l.FROM_PROFILE_STEP_TEXT = be),
      (l.BASE_MODAL_STEPPER_HEADER = ve),
      (l.getBrandHighlightsFromProfileHeader = Se),
      (l.BRAND_HIGHLIGHTS_FROM_PROFILE_DESCRIPTION = Re),
      (l.BRAND_HIGHLIGHTS_FROM_PROFILE_DISCLAIMER = Le),
      (l.BRAND_HIGHLIGHTS_FROM_PROFILE_DISCLAIMER_LINK = Ee),
      (l.BRAND_HIGHLIGHTS_FROM_PROFILE_OPTIONS = ke),
      (l.BRAND_HIGHLIGHTS_FROM_PROFILE_LABELS_MAP = Ie),
      (l.getAppHighlightsFromProfileHeader = Te),
      (l.APP_HIGHLIGHTS_FROM_PROFILE_DESCRIPTION = De),
      (l.APP_HIGHLIGHTS_FROM_PROFILE_OPTIONS = xe),
      (l.APP_HIGHLIGHTS_FROM_PROFILE_LABELS_MAP = $e),
      (l.SOCIAL_CUES_FROM_PROFILE_HEADER = Pe),
      (l.SOCIAL_CUES_FROM_PROFILE_DESCRIPTION = Ne),
      (l.BUSINESS_INFO_FROM_PROFILE_HEADER = Me),
      (l.getBusinessInfoFromProfileHeader = we),
      (l.getSocialCuesFromProfileHeader = Ae),
      (l.BUSINESS_INFO_FROM_PROFILE_BULK_EDIT_SUBTITLE = Fe),
      (l.getBusinessInfoFromProfileSubtitle = Oe),
      (l.BUSINESS_INFO_FROM_PROFILE_OPTIONS = Be),
      (l.BUSINESS_INFO_FROM_PROFILE_LABELS_MAP = We),
      (l.SOCIAL_CUES_FROM_PROFILE_OPTIONS = qe),
      (l.SOCIAL_CUES_FROM_PROFILE_LABELS_MAP = Ue),
      (l.PREVIEW_SECTION_TOOLTIP_TEXT = Ve),
      (l.PREVIEW_SECTION_HEADER_TEXT = He),
      (l.PREVIEW_SECTION_FOOTER_TEXT = Ge),
      (l.PREVIEW_IMAGE_SOURCE_PATH_PREFIX_V2 = ze),
      (l.PREVIEW_IMAGE_SOURCE_PATH_PREFIX = je),
      (l.PREVIEW_IMAGE_SOURCE_PATH_SUFFIX = Ke),
      (l.CREATIVE_BADGE_MODAL_PREVIEW_IMAGE_SOURCE = Qe),
      (l.CREATIVE_BADGE_MODAL_PREVIEW_IG_FEED_IMAGE_SOURCE = Xe),
      (l.CREATIVE_BADGE_MODAL_WIDTH = Ye),
      (l.CREATIVE_BADGE_HELPCENTER_ID = Je),
      (l.CREATIVE_BADGE_LEARN_MORE_ABOUT_PIXEL_DATA_HELPCENTER_ID = Ze),
      (l.getCreativeBadgeDaysLabel = et),
      (l.getCreativeBadgeWeekLabel = tt),
      (l.getCreativeBadgeMonthLabel = nt),
      (l.CREATIVE_BADGE_PREVIEW_PLACEMENT_LABELS = rt),
      (l.SHOPPING_DETAILS_AND_PAYMENT_OPTIONS = ot),
      (l.CREATIVE_BADGE_SHOPPING_DETAILS_AND_PAYMENT_LABELS = at),
      (l.CREATIVE_BADGE_MANUAL_CALLOUTS_DISPLAY_TEXT = it),
      (l.CREATIVE_BADGE_AUTOFILL_SUCCESS_TOASTER_HEADING = lt),
      (l.CREATIVE_BADGE_AUTOFILL_SUCCESS_TOASTER_DESCRIPTION = st),
      (l.CREATIVE_BADGE_AUTOFILL_FAILURE_TOASTER_HEADING = ut),
      (l.CREATIVE_BADGE_AUTOFILL_FAILURE_TOASTER_DESCRIPTION = ct));
  },
  226,
);
