__d(
  "getSUITextUniform.bui",
  ["cssVar", "BUIPrivateThemeTypeSelectors", "BUIPrivateThemeUtils"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    function e(e, t) {
      var n,
        r,
        a,
        i,
        l = e.type.fontFamily,
        s = o("BUIPrivateThemeUtils").isGeo(e),
        u = s ? "700" : void 0,
        c = o("BUIPrivateThemeTypeSelectors").fontTypeSelector(e),
        d = c.body,
        m = c.body1,
        p = c.body2,
        _ = c.body3,
        f = c.dataDisplay,
        g = c.display,
        h = c.header1,
        y = c.header2,
        C = c.header3,
        b = c.header4,
        v = c.small,
        S = c.title,
        R = s ? d : m;
      return {
        display: babelHelpers.extends(
          { fontFamily: l },
          (n = f != null ? f : g) != null ? n : R,
        ),
        header1: babelHelpers.extends({ fontWeight: u, fontFamily: l }, h),
        header2: babelHelpers.extends({ fontWeight: u, fontFamily: l }, y),
        header3: babelHelpers.extends({ fontWeight: u, fontFamily: l }, C),
        header4: babelHelpers.extends({ fontWeight: u, fontFamily: l }, b),
        body1: babelHelpers.extends(
          { fontFamily: l },
          (r = d != null ? d : m) != null ? r : R,
        ),
        body1_DEPRECATED: { fontFamily: l, fontSize: 16, lineHeight: 20 },
        body2: babelHelpers.extends(
          { fontFamily: l },
          (a = d != null ? d : p) != null ? a : R,
        ),
        body2_DEPRECATED: { fontFamily: l, fontSize: 14, lineHeight: 18 },
        body3: babelHelpers.extends(
          { fontFamily: l },
          (i = d != null ? d : _) != null ? i : R,
        ),
        body3_DEPRECATED: { fontFamily: l, fontSize: 13, lineHeight: 17 },
        meta1: { fontFamily: l, fontSize: 12, lineHeight: 16 },
        heading: { fontFamily: l, fontSize: 24, lineHeight: 32 },
        subheading: { fontFamily: l, fontSize: 20, lineHeight: 24 },
        headline: babelHelpers.extends({ fontFamily: l }, S != null ? S : R),
        regular: babelHelpers.extends({ fontFamily: l }, d != null ? d : R),
        regularUI: { fontFamily: l, fontSize: 14, lineHeight: 16 },
        large: { fontFamily: l, fontSize: 16, lineHeight: 20 },
        letterSpacing: "normal",
        medium: { fontFamily: l, fontSize: 14, lineHeight: 18 },
        shade: {
          dark: "#1d2129",
          light: "#90949c",
          link: "#365899",
          medium: "#4b4f56",
          white: "#FFFFFF",
        },
        small: babelHelpers.extends({ fontFamily: l }, v != null ? v : R),
        color: {
          primary: t,
          secondary: t,
          blueLink: t,
          negative: t,
          positive: t,
          disabled: t,
          disabledDark: "#373737",
          interactive: "#1877F2",
          placeholder: "#8D949E",
          primaryDark: "#cccccc",
          secondaryDark: "#4A4A4A",
          white: "#FFFFFF",
        },
        units: s ? "relative" : "absolute",
        xlarge: { fontFamily: l, fontSize: 18, lineHeight: 24 },
        xsmall: { fontFamily: l, fontSize: 11, lineHeight: 14 },
        xxlarge: { fontFamily: l, fontSize: 24, lineHeight: 30 },
      };
    }
    l.default = e;
  },
  98,
);
