__d(
  "AdsCommonTargetingProperties",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        ageMax: null,
        ageMin: null,
        ageRange: null,
        ageMinLimit: null,
        alternateAutoTargetingOption: null,
        appInstallState: null,
        installStateApplication: null,
        behaviors: null,
        brandSafetyContentFilterLevels: null,
        catalogBasedTargeting: null,
        cities: null,
        countries: null,
        connections: null,
        conjunctiveUserAdclusters: null,
        contextualTargetingCategories: null,
        customAudiences: null,
        prospectingAudience: null,
        dynamicAudienceIds: null,
        educationMajors: null,
        educationSchools: null,
        educationStatuses: null,
        ethnicAffinity: null,
        engagementSpecs: null,
        excludedBrandSafetyContentTypes: null,
        excludedConnections: null,
        excludedCustomAudiences: null,
        excludedDynamicAudienceIds: null,
        excludedEngagementSpecs: null,
        excludedProductAudienceSpecs: null,
        excludedPublisherCategories: null,
        excludedPublisherListIDs: null,
        excludedUserAdclusters: null,
        excludedUserDevice: null,
        exclusions: null,
        familyStatuses: null,
        fbDealID: null,
        flexibleSpec: null,
        friendsOfConnections: null,
        followProfiles: null,
        followProfilesNegative: null,
        gatekeepers: null,
        genders: null,
        generation: null,
        homeOwnership: null,
        homeType: null,
        homeValue: null,
        householdComposition: null,
        income: null,
        industries: null,
        interestedIn: null,
        interests: null,
        instreamVideoSkippableExcluded: null,
        keywords: null,
        lifeEvents: null,
        locTargeting: null,
        locales: null,
        maxGradYear: null,
        minAndroidVersion: null,
        maxAndroidVersion: null,
        minGradYear: null,
        minIosVersion: null,
        maxIosVersion: null,
        minWindowsVersion: null,
        maxWindowsVersion: null,
        mobileDevices: null,
        mobileOperatingSystem: null,
        moms: null,
        netWorth: null,
        officeType: null,
        pageTypes: null,
        politics: null,
        productAudienceSpecs: null,
        radiusIfValid: null,
        relationshipStatuses: null,
        regions: null,
        sex: null,
        syndicatedCustomAudiencesLibrary: null,
        targetAllGraduationYears: null,
        targetingCountry: null,
        userAdclusters: null,
        userOs: null,
        wifiOnly: null,
        workEmployers: null,
        workPositions: null,
        zips: null,
        geoLocations: null,
        excludedGeoLocations: null,
        timezones: null,
        targetingOptimization: null,
        placePageSetIDs: null,
        targetingRelaxationTypes: null,
        targetingAutomation: null,
        targetingAutomationIndividualSettingAge: null,
        targetingAutomationIndividualSettingGender: null,
        tafeCaMitigationStrategy: null,
        marektingMessageTargeting: null,
        marketingMessageChannels: null,
        subscriberUniverse: null,
        userAgeUnknown: null,
      },
      l = e;
    i.default = l;
  },
  66,
);
