__d(
  "AdsInstagramReelsAdPreviewConstants",
  ["$InternalEnum", "justknobx"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = "instagram_reels_ad_preview_caption",
      s = 0.5,
      u = 246,
      c = r("justknobx")._("4629") ? 1 : 2,
      d = 1,
      m = 230,
      p = "instagram_reels_ad_preview_cta",
      _ = "instagram_reels_ad_preview_cta_content",
      f = "instagram_reels_ad_preview_cta_chevron",
      g = n("$InternalEnum").Mirrored(["BOTTOM", "TOP", "SANDWICH"]),
      h = n("$InternalEnum").Mirrored(["TOAST", "PILL"]),
      y = n("$InternalEnum").Mirrored([
        "LONG",
        "SHORT",
        "FIT_CONTENT",
        "MID_SCENE",
        "MID_SCENE_LEGACY",
      ]),
      C = n("$InternalEnum").Mirrored(["LEFT_IN", "BOTTOM_UP"]),
      b = "instagram_reels_ad_preview_gradient_bottom",
      v = "instagram_reels_ad_preview_gradient_top",
      S = 565,
      R = 318,
      L = "instagram_reels_ad_preview_media_video",
      E = "instagram_reels_ad_preview_media_src",
      k = "instagram_reels_ad_preview_carousel_media",
      I = "instagram_reels_ad_preview_avatar",
      T = "instagram_reels_ad_preview_sponsored",
      D = "instagram_reels_ad_preview_attribute_pill_sponsored",
      x = "instagram_reels_ad_preview_attribute_pill_ai_label",
      $ = "instagram_reels_ad_preview_attribute_pill_upcoming_event",
      P = "instagram_reels_ad_preview_attribute_pill_app_rating",
      N = "instagram_reels_ad_preview_username",
      M = "instagram_reels_ad_preview_lead_form_spotlight",
      w = "instagram_reels_ad_preview_top_row",
      A = 1500,
      F = 1,
      O = 220,
      B = 10,
      W = 400,
      q = "HelveticaNeue, Helvetica Neue, Helvetica, sans-serif",
      U = "... ",
      V = "";
    ((l.IG_REELS_AD_PREVIEW_CAPTION_ID = e),
      (l.IG_REELS_AD_PREVIEW_CAPTION_LETTER_SPACING = s),
      (l.IG_REELS_AD_PREVIEW_CAPTION_MAX_LINE_WIDTH = u),
      (l.IG_REELS_AD_PREVIEW_CAPTION_MAX_LINES = c),
      (l.IG_REELS_AD_PREVIEW_GRID_CAPTION_MAX_LINES = d),
      (l.IG_REELS_AD_PREVIEW_DISCLAIMER_MAX_LINE_WIDTH = m),
      (l.IG_REELS_AD_PREVIEW_CTA_ID = p),
      (l.IG_REELS_AD_PREVIEW_CTA_CONTENT_ID = _),
      (l.IG_REELS_AD_PREVIEW_CTA_CHEVRON_ID = f),
      (l.IGReelsAdsPreviewCTAPosition = g),
      (l.IGReelsAdsPreviewCTAType = h),
      (l.IGReelsAdsPreviewCTALength = y),
      (l.IGReelsAdsPreviewCTAPositionAnimationType = C),
      (l.IG_REELS_AD_PREVIEW_GRADIENT_BOTTOM_ID = b),
      (l.IG_REELS_AD_PREVIEW_GRADIENT_TOP_ID = v),
      (l.IG_REELS_AD_PREVIEW_MEDIA_FRAME_HEIGHT = S),
      (l.IG_REELS_AD_PREVIEW_MEDIA_FRAME_WIDTH = R),
      (l.IG_REELS_AD_PREVIEW_MEDIA_VIDEO_ID = L),
      (l.IG_REELS_AD_PREVIEW_MEDIA_SOURCE_ID = E),
      (l.IG_REELS_AD_PREVIEW_CAROUSEL_MEDIA = k),
      (l.IG_REELS_AD_PREVIEW_AVATAR_ID = I),
      (l.IG_REELS_AD_PREVIEW_SPONSORED_ID = T),
      (l.IG_REELS_AD_PREVIEW_ATTRIBUTE_PILL_SPONSORED_ID = D),
      (l.IG_REELS_AD_PREVIEW_ATTRIBUTE_PILL_AI_LABEL_ID = x),
      (l.IG_REELS_AD_PREVIEW_ATTRIBUTE_PILL_UPCOMING_EVENT_ID = $),
      (l.IG_REELS_AD_PREVIEW_ATTRIBUTE_PILL_APP_RATING_ID = P),
      (l.IG_REELS_AD_PREVIEW_USERNAME_ID = N),
      (l.IG_REELS_AD_PREVIEW_LEAD_FORM_SPOTLIGHT_ID = M),
      (l.IG_REELS_AD_PREVIEW_TOP_ROW_ID = w),
      (l.IG_REELS_AD_PREVIEW_CAROUSEL_AUTO_PACE_MS = A),
      (l.IG_REELS_AD_PREVIEW_TESTIMONIAL_MAX_LINES = F),
      (l.IG_REELS_AD_PREVIEW_TESTIMONIAL_MAX_WIDTH = O),
      (l.IG_REELS_AD_PREVIEW_TESTIMONIAL_FONT_SIZE = B),
      (l.IG_REELS_AD_PREVIEW_TESTIMONIAL_FONT_WEIGHT = W),
      (l.IG_REELS_AD_PREVIEW_TESTIMONIAL_FONT_FAMILY = q),
      (l.TRAILING_DOTS_FOR_ELLIPSIS = U),
      (l.TOKEN_DELIMITER = V));
  },
  98,
);
