__d(
  "AdsLeadGenFormRedesignExperiment",
  [],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = {
        canSeeNewCreationFeature: !1,
        canSeeConditionalQuestion: !1,
        canSeeSimplifiedConditionalQuestion: !1,
        canSeeVerticalBundleV2: !1,
        canSeeAutoFormCTA: !1,
        canSeeWebBasedFormGenerationTiles: !1,
        canSeeWebBasedFormGenerationTilesUseF2Url: !1,
        canSeeWebBasedFormGenerationV2: !1,
        canSeeNewFormEditorUI: !1,
        canSeeGatedPromoCode: !1,
        canSeeOptionalQuestions: !1,
        canSeeMultiAnswer: !1,
        canSeeDisablePrefill: !1,
        canSeeWhatsAppPIINoPhoneDefault: !1,
        canSeeWhatsAppPIIWithPhoneDefault: !1,
        canSeeOptionalPrivacyPolicy: !1,
        canSeeOptionalQuestionUpsell: !1,
        canSeeMultiAnswerUpsell: !1,
        canSeeLinkToCatalog: !1,
        selectedAdgroupsHaveCatalog: !1,
        canSeeShortAnswerQuestionValidation: !1,
        canSeeRichCreativeRedesign: !1,
        canSeeSAQPiiValidation: !1,
        canSeeImageMCQ: !1,
        canSeeVerticalDefaultedPII: !1,
        isConsumerPackagedGoodsVertical: !1,
        isEcommerceVertical: !1,
        isEducationVertical: !1,
        isBusinessToBusinessVertical: !1,
        isAdvertisingAndMarketingVertical: !1,
        isProfessionalServicesVertical: !1,
        isInsuranceVertical: !1,
        canSeeSAQGenAIAnswerSuggestions: !1,
        canSeeEZFormCreation: !1,
        canSeeFormManagement: !1,
        canSeeFormInsights: !1,
        canSeeMultiSubmitPreview: !1,
        canSeeStoreSetFiltering: !1,
        canSeeABTestingForms: !1,
      },
      l = e;
    i.default = l;
  },
  66,
);
