__d(
  "AdsActionTypes",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ADGROUP: {
        ASYNC_VALIDATION: { LOADED: "ADGROUP.ASYNC_VALIDATION.LOADED" },
      },
      CAMPAIGN: {
        ASYNC_VALIDATION: { LOADED: "CAMPAIGN.ASYNC_VALIDATION.LOADED" },
      },
      CAMPAIGN_GROUP: {
        ASYNC_VALIDATION: { LOADED: "CAMPAIGN_GROUP.ASYNC_VALIDATION.LOADED" },
        LIST: {
          LOADED: "CAMPAIGN_GROUP.LIST.LOADED",
          LOAD_ERROR: "CAMPAIGN_GROUP.LIST.LOAD_ERROR",
          PARTIAL_LOAD: "CAMPAIGN_GROUP.LIST.PARTIAL_LOAD",
        },
      },
      CANVAS: { RESET_SEARCH_SOURCE: "CANVAS.RESET_SEARCH_SOURCE" },
      DATASET: {
        HANDLE_CREATE: { SUCCESS: "DATASET.HANDLE_CREATE.SUCCESS" },
        HANDLE_DELETE: { SUCCESS: "DATASET.HANDLE_DELETE.SUCCESS" },
      },
      DELIVERY_INSIGHTS: {
        RUNWAY_UPSELL: {
          LOAD: "DELIVERY_INSIGHTS.RUNWAY_UPSELL.LOAD",
          CLICK: "DELIVERY_INSIGHTS.RUNWAY_UPSELL.CLICK",
          XOUT: "DELIVERY_INSIGHTS.RUNWAY_UPSELL.XOUT",
        },
      },
      PRODUCT_ITEM: {
        INSIGHTS: {
          LOADED: "PRODUCT_ITEM.INSIGHTS.LOADED",
          LOAD_ERROR: "PRODUCT_ITEM.INSIGHTS.LOAD_ERROR",
        },
        DISPLAY_PREVIEW: {
          LOADED: "PRODUCT_ITEM.DISPLAY_PREVIEW.LOADED",
          LOAD_ERROR: "PRODUCT_ITEM.DISPLAY_PREVIEW.LOAD_ERROR",
        },
      },
    });
    i.default = e;
  },
  66,
);
