__d(
  "AdsCreateCompletedAction",
  [
    "AdsAdBuilderCreateCompletedReducerPlugin",
    "AdsAdBuilderCreationProvider",
    "AdsAdBuilderDuplicateMockupLoggerPlugins",
    "AdsAdBuilderDuplicateMockupProvider",
    "AdsAdBuilderDuplicateMockupReducerPlugins",
    "AdsCFCampaignURLParamsProvider",
    "AdsCFClearCAFromURLParamsStoreReducerPlugin",
    "AdsCFExternalCreationCompleteCreateDraftReducerPlugin",
    "AdsCFExternalCreationConfirmationDialogUIDataProvider",
    "AdsCFReceiptDialogUIAdsCreateCompletedReducerPlugin",
    "AdsCFReceiptDialogUIDataProvider",
    "AdsCampaignEditorProvider",
    "AdsCampaignEditorReducerPlugins",
    "AdsCampaignStructureCreationCompleteUIReducerPlugin",
    "AdsCampaignStructureCreationLoadingUIDataProvider",
    "AdsConvergenceCreationCompleteUIReducerPlugin",
    "AdsConvergenceCreationLoadingUIDataProvider",
    "AdsCreationConvergenceEditorOpenMapObjectCreationCompleteReducerPlugin",
    "AdsCreationConvergenceEditorOpenMapProvider",
    "AdsMockupAdsCreateCompletedReducerPlugin",
    "AdsMockupProvider",
    "AdsPECreationUICreateCompletedReducerPlugin",
    "AdsPECreationUIProvider",
    "AdsPreviewSharingAdsCreateCompletedReducerPlugin",
    "AdsPreviewSharingProvider",
    "AdsReachFrequencyCreationFlowProvider",
    "AdsReachFrequencyRevampCreationFlowReducerPlugins",
    "AdsTargetFrequencyInAuctionInitializePredictionOnCreateCompleteReducerPlugin",
    "AdsTargetFrequencyInAuctionPredictionStatusProvider",
    "Laminar",
    "ifRequired_FOR_LAMINAR_CODEGEN",
  ],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("Laminar").__createAction(
      function () {
        return [
          n("Laminar").__createReducer(
            n("AdsAdBuilderCreateCompletedReducerPlugin"),
            n("AdsAdBuilderCreationProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsAdBuilderDuplicateMockupReducerPlugins").onMockupDuplicated,
            n("AdsAdBuilderDuplicateMockupProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsCFClearCAFromURLParamsStoreReducerPlugin"),
            n("AdsCFCampaignURLParamsProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsCFExternalCreationCompleteCreateDraftReducerPlugin"),
            n("AdsCFExternalCreationConfirmationDialogUIDataProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsCFReceiptDialogUIAdsCreateCompletedReducerPlugin"),
            n("AdsCFReceiptDialogUIDataProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsCampaignEditorReducerPlugins")
              .AdsCreateCompletedReducerPlugin,
            n("AdsCampaignEditorProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsCampaignStructureCreationCompleteUIReducerPlugin"),
            n("AdsCampaignStructureCreationLoadingUIDataProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsConvergenceCreationCompleteUIReducerPlugin"),
            n("AdsConvergenceCreationLoadingUIDataProvider"),
            {},
            "",
          ),
          n("ifRequired_FOR_LAMINAR_CODEGEN")(
            "AdsCreateCompletedReducerPlugin",
            function (e) {
              return n("ifRequired_FOR_LAMINAR_CODEGEN")(
                "AdsCFPlaceOrderProvider",
                function (t) {
                  return n("Laminar").__createReducer(e, t, {}, "");
                },
              );
            },
          ),
          n("Laminar").__createReducer(
            n(
              "AdsCreationConvergenceEditorOpenMapObjectCreationCompleteReducerPlugin",
            ),
            n("AdsCreationConvergenceEditorOpenMapProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsMockupAdsCreateCompletedReducerPlugin"),
            n("AdsMockupProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsPECreationUICreateCompletedReducerPlugin"),
            n("AdsPECreationUIProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsPreviewSharingAdsCreateCompletedReducerPlugin"),
            n("AdsPreviewSharingProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n("AdsReachFrequencyRevampCreationFlowReducerPlugins")
              .adsDraftDraftPublishFlow,
            n("AdsReachFrequencyCreationFlowProvider"),
            {},
            "",
          ),
          n("Laminar").__createReducer(
            n(
              "AdsTargetFrequencyInAuctionInitializePredictionOnCreateCompleteReducerPlugin",
            ),
            n("AdsTargetFrequencyInAuctionPredictionStatusProvider"),
            {},
            "",
          ),
        ];
      },
      function () {
        return [
          n("Laminar").__createLogger(
            "AdsAdBuilderDuplicateMockupLoggerPlugins.AdsAdBuilderDuplicateMockupCompletedLoggerPlugin",
            n("AdsAdBuilderDuplicateMockupLoggerPlugins")
              .AdsAdBuilderDuplicateMockupCompletedLoggerPlugin,
            {},
          ),
        ];
      },
      "CREATE.COMPLETED",
    );
    a.exports = e;
  },
  null,
);
