__d(
  "AdsPEFluxActionTypes",
  ["keyMirrorRecursive"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = r("keyMirrorRecursive")({
        ACCOUNT: { CHANGE_DEFAULT_DEMOGRAPHICS: "" },
        AD: {
          CREATE_WITH_AUDIENCES: "",
          CREATE: "",
          DELETE: "",
          INITIALIZE_WITH_APP: "",
          INLINE_POST_CREATIVE_CHANGE: { PHOTO: "", TEMPLATE: "" },
          PASTE: "",
          REVERT: "",
          SELECTION: { DOWN_KEY: "", ID_CLICKED: "", UP_KEY: "" },
          SET_DEEP_LINK: "",
          SET_DEEP_LINK_TITLE: "",
          SET_IMAGE: "",
          SET_PRODUCT_LINK: "",
          SET_STATUS: "",
          UPLOAD: "",
          VALIDATION_COMPLETE: "",
        },
        AD_ACCOUNT_TABLE: { SET_SORT_KEY: "" },
        BUSINESS: { FETCH_PRODUCT_CATALOGS: "" },
        CAMPAIGN: {
          CREATE: "",
          DELETE: "",
          REVERT: "",
          EXTERNAL_PASTE: "",
          ERRORS_LOADED: "",
          SELECTION: { DOWN_KEY: "", ID_CLICKED: "", UP_KEY: "" },
          SET_IMPRESSION_LIMIT: "",
          SPLIT_AUDIENCE: { OPEN: "", CLOSE: "" },
        },
        CAMPAIGN_GROUP: {
          REVERT: "",
          SELECTION: { DOWN_KEY: "", ID_CLICKED: "", UP_KEY: "" },
        },
        CUSTOM_THUMBNAIL: {
          RESET: "",
          LOAD_START: "",
          LOADED: "",
          SELECT: "",
          UPLOAD_SUCCESS: "",
        },
        IMPORT: {
          FILE_SELECTED: "",
          FILE_REMOVED: "",
          IMAGE_REMOVED: "",
          VIDEO_REMOVED: "",
          CHOOSE_FILE_CLICKED: "",
        },
        POST: { FETCH_BY_ID: "", FETCH_FOR_PAGE: "" },
        STATS: { FETCH: "", INIT_STAT_RANGE: "", SET_STAT_RANGE: "" },
        PAGE: { CLEAR_PAGE_CREATION: "", CREATE: "", DOWNLOADED: "" },
        PAGE_POST_COMPOSER: {
          RESET: "",
          VIDEO: { SELECT: "", SELECT_THUMBNAIL: "" },
        },
        CHANGE_LEVEL_BUTTON_CLICKED: "",
        CREATE_AUDIENCE: "",
        LEAVE_INTERFACE: "",
        TEST: {
          CHANGE: "",
          FETCH_GROUP: "",
          TAKE_GROUP_ACTION: "",
          TAKE_PER_AD_ACTION: "",
        },
        CAMPAIGN_GROUP_TABLE: {
          EDIT_FOCUS: "",
          EDIT_BLUR: "",
          INIT_COLUMN_WIDTHS: "",
          SET_COLUMN_WIDTHS: "",
          SET_HEIGHT: "",
          SET_SORT_KEY: "",
          SET_WIDTH: "",
        },
        CAMPAIGN_TABLE: {
          EDIT_FOCUS: "",
          EDIT_BLUR: "",
          INIT_COLUMN_WIDTHS: "",
          SET_COLUMN_WIDTHS: "",
          SET_HEIGHT: "",
          SET_SORT_KEY: "",
          SET_WIDTH: "",
        },
        AD_TABLE: {
          EDIT_FOCUS: "",
          EDIT_BLUR: "",
          INIT_COLUMN_WIDTHS: "",
          SET_COLUMN_WIDTHS: "",
          SET_HEIGHT: "",
          SET_SORT_KEY: "",
          SET_WIDTH: "",
        },
        TABLE: { SET_INLINE_EDIT: "", RESET_INLINE_EDIT: "" },
        TOP_NAV: {
          CLOSE_KEYBOARD_SHORTCUTS_DIALOG: "",
          OPEN_CLOSE_GEAR_MENU: "",
          OPEN_HELP_CENTER: "",
          OPEN_KEYBOARD_SHORTCUTS_DIALOG: "",
          OPEN_RELEASE_NOTES: "",
          REFRESH: "",
          RESET_APPLICATION: "",
          TAKE_TOUR: "",
        },
      }),
      s = e;
    l.default = s;
  },
  98,
);
