__d(
  "AdsInstagramInteractiveComponentConstants",
  [
    "$InternalEnum",
    "AdsInteractiveComponentConstants",
    "DateConsts",
    "DateTime",
    "IGAdsSensitiveVerticalsUtils",
    "Timezone",
    "gkx",
    "immutable",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s,
      u,
      c,
      d = 0,
      m = 30,
      p = 64,
      _ = 204,
      f = 318,
      g = 565,
      h = 4,
      y = 30,
      C = 100,
      b = 7,
      v = 90,
      S = 100,
      R = 10,
      L = 0,
      E = -90,
      k = 0,
      I = 54,
      T = 101,
      D = 16,
      x = "#000000",
      $ = "#000000",
      P = 0.5,
      N = 0.95,
      M = 0.88,
      w = 100,
      A = "ig_story_cta_sticker_data_test_id",
      F = "creative_editor_cta_sticker_location_customization_tool_panel_id",
      O = "cta_sticker_position_y_input_id",
      B = "cta_sticker_position_x_input_id",
      W = 0,
      q = 100,
      U = 80,
      V = 100,
      H = 96,
      G = 36,
      z = 152,
      j = (G / g) * w,
      K = (z / f) * w,
      Q = 3,
      X = 2,
      Y = r("immutable").Map(
        ((e = {}),
        (e.x = 0.5),
        (e.y = 0.5),
        (e.width = 0.65),
        (e.height = 1),
        (e.rotation = 0),
        e),
      ),
      J = r("immutable").Map(
        ((s = {}),
        (s.question_text = "Poll Question"),
        (s.option_a_text = "option 1"),
        (s.option_b_text = "option 2"),
        s),
      ),
      Z = o("Timezone").getEnvironmentTimezoneID(),
      ee =
        r("gkx")("15221") &&
        !o("IGAdsSensitiveVerticalsUtils").is_pharma_vertical,
      te = r("immutable").fromJS(
        ((u = {}),
        (u.end_time = (
          r("DateTime").now(Z).getUnixTimestampSeconds() +
          o("DateConsts").SEC_PER_DAY
        ).toString()),
        u),
      ),
      ne = n("$InternalEnum").Mirrored(["POLL", "COUNTDOWN"]),
      re = r("immutable").List([
        r("immutable").Map(
          ((c = {}),
          (c.type = o(
            "AdsInteractiveComponentConstants",
          ).INTERACTIVE_COMPONENT_POLL_TYPE),
          (c.position_spec = Y),
          (c.poll_spec = J),
          c),
        ),
      ]),
      oe = { x: P, y: ee ? M : N },
      ae = {
        background_opacity: 100,
        text_color: "#FFFFFF",
        text_size: 48,
        icon_color: "#0095F6",
      };
    ((l.DEFAULT_INDEX = d),
      (l.DEFAULT_OPTION_TEXT_SIZE = m),
      (l.DEFAULT_POLLING_STICKER_HEIGHT = p),
      (l.DEFAULT_POLLING_STICKER_WIDTH = _),
      (l.FRAME_WIDTH = f),
      (l.FRAME_HEIGHT = g),
      (l.MAX_OPTION_TEXT_LINE_COUNT = h),
      (l.MAX_OPTION_TEXT_SIZE = y),
      (l.MAX_POSITION_INPUT = C),
      (l.MAX_POSITION_TEXT_LENGTH = b),
      (l.MAX_ROTATION_DEGREE = v),
      (l.MAX_STICKER_WIDTH = S),
      (l.MIN_OPTION_TEXT_SIZE = R),
      (l.MIN_POSITION_INPUT = L),
      (l.MIN_ROTATION_DEGREE = E),
      (l.MIN_STICKER_WIDTH = k),
      (l.OPTION_BOX_TEXT_BLOCK_HEIGHT = I),
      (l.OPTION_BOX_TEXT_BLOCK_WIDTH = T),
      (l.POSITION_TEXTAREA_HEIGHT = D),
      (l.DEFAULT_CTA_STICKER_TEXT_COLOR = x),
      (l.BLACK_WHITE_STICKER_COLOR = $),
      (l.DEFAULT_X_POSITION = P),
      (l.DEFAULT_Y_POSITION = N),
      (l.NEW_SPONSORED_LABEL_POSITION_DEFAULT_Y_POSITION = M),
      (l.PERCENT_CONVERSION_RATE = w),
      (l.IG_STORY_CTA_STICKER_DATA_TEST_ID = A),
      (l.CREATIVE_EDITOR_CTA_STICKER_LOCATION_CUSTOMIZATION_TOOL_PANEL_ID = F),
      (l.CTA_STICKER_POSITION_Y_INPUT_ID = O),
      (l.CTA_STICKER_POSITION_X_INPUT_ID = B),
      (l.MIN_X_POSITION_BOTTOM_20 = W),
      (l.MAX_X_POSITION_BOTTOM_20 = q),
      (l.MIN_Y_POSITION_BOTTOM_20 = U),
      (l.MAX_Y_POSITION_BOTTOM_20 = V),
      (l.MAX_Y_POSITION_BOTTOM_20_NEW_SPONSORED_LABEL = H),
      (l.DEFAULT_CTA_STICKER_HEIGHT_IN_PERCENTAGE = j),
      (l.DEFAULT_CTA_STICKER_WIDTH_IN_PERCENTAGE = K),
      (l.WIDTH_PADDING = Q),
      (l.HEIGHT_PADDING = X),
      (l.isNewSponsoredPositionEnabled = ee),
      (l.DEFAULT_COUNTDOWN_SPEC = te),
      (l.StickerType = ne),
      (l.DEFAULT_POLL_COMPONENTS_SPEC = re),
      (l.DEFAULT_CTA_STICKER_POSITION_SPEC = oe),
      (l.DEFAULT_CTA_STICKER_STYLE_SPEC = ae));
  },
  98,
);
