__d(
  "WhatsAppBusinessAccountManagerHSMFormatValidatorRegex",
  [
    "WhatsAppHSMAuthContentRestrictionsConstants",
    "WhatsAppHSMURLShortenerConfig.experimental",
  ],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = /\{\{.*?\}\}|(^|[^\{])\{[A-Za-z0-9]+\}($|[^\}])|\[[A-Za-z0-9]+\]/gi,
      s = /\{\{[^0-9]*\}\}|\{\w*\}(?!\})/gi,
      u = /(^|[^\{])\{(?=\w\}\})/gi,
      c = /\{\{[a-z][a-z0-9_]*\}\}/g,
      d = /\{\{[0-9][a-z0-9_]*\}\}|\{\w*\}(?!\})|(^|[^\{])\{(?=\w*\}\})/gi,
      m = /\{\{(?:[A-Z_][a-zA-Z0-9_]*|[a-z][a-z0-9_]*[A-Z][a-zA-Z0-9_]*)\}\}/g,
      p = function (t) {
        return new RegExp("\\{\\{(?!(?:" + t + ")\\}\\})\\w+\\}\\}", "gi");
      },
      _ = r("WhatsAppHSMURLShortenerConfig.experimental").url_shortener;
    _ = _.replace(/\./g, "\\.");
    var f = new RegExp("\\b(" + _ + ")", "gi"),
      g = /\{\{[0-9]+\}\}/g,
      h = /\{\{[a-zA-Z]\w*\}\}/g,
      y = /\{\{[a-zA-Z]+.[a-zA-Z]\w*\}\}/g,
      C = /\{\{(.+?)\}\}/g,
      b =
        /[\u4E00-\u9FFF\u3400-\u4DBF\uF900-\uFAFF\u3040-\u309F\u30A0-\u30FF\uAC00-\uD7AF]/g,
      v = /[^\s]+/g,
      S = /[\xAD\u115F\u1160\u200B-\u200F\u2800-\u28FF\u3164\uFEFF\uFFA0]+/g,
      R = /\{\{\d+\}\}[\s*_~`]*\{\{\d+\}\}/g,
      L =
        /[~*_\s]*(`{3})*\{\{[\w]+\}\}[*~\s]*(`{3})*[*~\s]*\{\{[\w]+\}\}[~*_\s]*(`{3})*/g,
      E = /^[~*_\s]*(`{3})*\{\{[0-9]+\}\}[~*_\s]*(`{3})*/g,
      k = /[~*_\s]*(`{3})*\{\{[0-9]+\}\}[~*_\s]*(`{3})*(\!*\.*\?*$)/g,
      I = /^[~*_\s]*(`{3})*\{\{[\w]+\}\}/g,
      T = /\{\{[\w]+\}\}[~*_\s]*(`{3})*[!.?]*$/g,
      D =
        /^[~*_\s]*(`{3})*\{\{[0-9]+\}\}[~*_]*(`{3})*|[~*_]*(`{3})*\{\{[0-9]+\}\}[~*_\s]*(`{3})*(\!*\.*\?*$)/g,
      x = /(?:^|[\s\W_])\*(\S|\S[^\n]*?\S)\*(?=$|[[\s\W_])/g,
      $ = /(?:^|\s|_|[^\w\\])_(\S|\S[^\n]*?\S)_(?=$|[[\s\W_])/g,
      P = /(?:^|[\s\W_])~(\S|\S[^\n]*?\S)~(?=$|[[\s\W_])/g,
      N = /```([\s\S]*?\S[\s\S]*?)```/g,
      M = /[\n]/g,
      w = /[\n]{3,}/g,
      A = /\*/g,
      F = /(\*|_|~|```)/g,
      O = [x, $, P, N],
      B = [s, u, g],
      W = new RegExp(
        r("WhatsAppHSMAuthContentRestrictionsConstants").URL_REGEX,
        "g",
      ),
      q = /^[-+]?\d+$/,
      U = new RegExp(
        r("WhatsAppHSMAuthContentRestrictionsConstants").SIGNATURE_HASH_REGEX,
      ),
      V = new RegExp(
        r("WhatsAppHSMAuthContentRestrictionsConstants").PACKAGE_NAME_REGEX,
      );
    ((l.INVALID_PARAMETER_WARN_REGEX = e),
      (l.INVALID_PARAMETER_BLOCK_REGEX_1 = s),
      (l.INVALID_PARAMETER_BLOCK_REGEX_2 = u),
      (l.REGEX_PARAMS_NAMED = c),
      (l.INVALID_NAMED_PARAMETER_REGEX = d),
      (l.UPPERCASE_NAMED_PARAMETER_REGEX = m),
      (l.INVALID_ALIAS_REGEX = p),
      (l.SHORTENED_URL_REGEX = f),
      (l.REGEX_PARAMS = g),
      (l.REGEX_PARAMS_ALIAS = h),
      (l.REGEX_PARAMS_ALIAS_WITH_PERIOD = y),
      (l.REGEX_PARAMS_LIKE = C),
      (l.REGEX_WORDS_NON_LATIN = b),
      (l.REGEX_WORDS = v),
      (l.REGEX_INVISIBLE_CHARS = S),
      (l.FLOATING_PARAMETER_ADJ_REGEX = R),
      (l.FLOATING_NAMED_PARAMETER_ADJ_REGEX = L),
      (l.LEADING_PARAMETER_REGEX = E),
      (l.TRAILING_PARAMETER_REGEX = k),
      (l.LEADING_NAMED_PARAMETER_REGEX = I),
      (l.TRAILING_NAMED_PARAMETER_REGEX = T),
      (l.FLOATING_PARAMETER_DANGLE_REGEX = D),
      (l.BOLD_REGEX = x),
      (l.ITALIC_REGEX = $),
      (l.STRIKETHROUGH_REGEX = P),
      (l.CODE_REGEX = N),
      (l.NEWLINE_REGEX = M),
      (l.MULTIPLE_NEWLINES_REGEX = w),
      (l.ASTERISK_REGEX = A),
      (l.FORMATTING_MARKUP_REGEX = F),
      (l.FORMATTING_STYLE_REGEX_ARRAY = O),
      (l.INVALID_PARAMETER_REGEX_ARRAY = B),
      (l.URL_REGEX = W),
      (l.PHONE_NUMBER_REGEX = q),
      (l.SIGNATURE_HASH_REGEX = U),
      (l.PACKAGE_NAME_REGEX = V));
  },
  98,
);
