__d(
  "SUITextUniform.business",
  ["cssVar", "BUISystemFonts"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e,
      u = {
        header1: {
          fontFamily: (e = o("BUISystemFonts")).FONT_FAMILY,
          fontSize: 24,
          lineHeight: 28,
        },
        header2: { fontFamily: e.FONT_FAMILY, fontSize: 20, lineHeight: 24 },
        header3: { fontFamily: e.FONT_FAMILY, fontSize: 16, lineHeight: 20 },
        header4: { fontFamily: e.FONT_FAMILY, fontSize: 14, lineHeight: 18 },
        body1: { fontFamily: e.FONT_FAMILY, fontSize: 14, lineHeight: 18 },
        body1_DEPRECATED: {
          fontFamily: e.FONT_FAMILY,
          fontSize: 16,
          lineHeight: 20,
        },
        body2: { fontFamily: e.FONT_FAMILY, fontSize: 13, lineHeight: 17 },
        body2_DEPRECATED: {
          fontFamily: e.FONT_FAMILY,
          fontSize: 14,
          lineHeight: 18,
        },
        body3: { fontFamily: e.FONT_FAMILY, fontSize: 12, lineHeight: 16 },
        body3_DEPRECATED: {
          fontFamily: e.FONT_FAMILY,
          fontSize: 13,
          lineHeight: 17,
        },
        meta1: { fontFamily: e.FONT_FAMILY, fontSize: 12, lineHeight: 16 },
        display: { fontFamily: e.FONT_FAMILY, fontSize: 40, lineHeight: 48 },
        heading: { fontFamily: e.FONT_FAMILY, fontSize: 24, lineHeight: 32 },
        subheading: { fontFamily: e.FONT_FAMILY, fontSize: 20, lineHeight: 24 },
        headline: { fontFamily: e.FONT_FAMILY, fontSize: 16, lineHeight: 24 },
        regular: { fontFamily: e.FONT_FAMILY, fontSize: 14, lineHeight: 20 },
        regularUI: { fontFamily: e.FONT_FAMILY, fontSize: 14, lineHeight: 16 },
        large: { fontFamily: e.FONT_FAMILY, fontSize: 16, lineHeight: 20 },
        letterSpacing: "normal",
        medium: { fontFamily: e.FONT_FAMILY, fontSize: 14, lineHeight: 18 },
        shade: {
          dark: "#1d2129",
          light: "#90949c",
          link: "#365899",
          medium: "#4b4f56",
          white: "#FFFFFF",
        },
        small: { fontFamily: e.FONT_FAMILY, fontSize: 12, lineHeight: 16 },
        color: {
          blueLink: "#385898",
          disabled: "#BEC3C9",
          disabledDark: "#373737",
          interactive: "#1877F2",
          negative: "#FA383E",
          placeholder: "#8D949E",
          positive: "#00A400",
          primary: "#1C1E21",
          primaryDark: "#cccccc",
          secondary: "#606770",
          secondaryDark: "#4A4A4A",
          white: "#FFFFFF",
        },
        xlarge: { fontFamily: e.FONT_FAMILY, fontSize: 18, lineHeight: 24 },
        xsmall: { fontFamily: e.FONT_FAMILY, fontSize: 11, lineHeight: 14 },
        xxlarge: { fontFamily: e.FONT_FAMILY, fontSize: 24, lineHeight: 30 },
      },
      c = u;
    l.default = c;
  },
  98,
);
