__d(
  "SupportedEventsForContentType",
  [],
  function (t, n, r, o, a, i) {
    a.exports = {
      adoptable_pet: [],
      automotive_listing: ["ViewContent", "Purchase", "Lead"],
      automotive_model: [
        "Search",
        "ViewContent",
        "AddToCart",
        "AddToWishlist",
        "InitiateCheckout",
        "Purchase",
        "Lead",
      ],
      avatar: [],
      destination: ["Search", "ViewContent", "InitiateCheckout", "Purchase"],
      flight: ["Search", "ViewContent", "InitiateCheckout", "Purchase"],
      generic: ["ViewContent", "Purchase"],
      geo_based_item: [],
      home_listing: ["Search", "ViewContent", "InitiateCheckout", "Purchase"],
      hotel: ["Search", "ViewContent", "InitiateCheckout", "Purchase"],
      job: [],
      local_service_business: [
        "Search",
        "ViewContent",
        "AddToCart",
        "Purchase",
      ],
      location_based_item: [
        "Search",
        "ViewContent",
        "InitiateCheckout",
        "Purchase",
      ],
      media_title: ["ViewContent", "AddToCart", "Purchase", "Subscribe"],
      none: [],
      offer_item: [],
      offline_product: ["Purchase"],
      product: ["ViewContent", "AddToCart", "Purchase"],
      service: ["Search", "ViewContent", "InitiateCheckout", "Purchase"],
      test_vertical: [],
      vehicle: ["Search", "ViewContent", "AddToWishlist", "Lead"],
      vehicle_offer: ["Search", "ViewContent", "AddToWishlist", "Lead"],
    };
  },
  null,
);
