__d(
  "cdsMinificationMap",
  ["WebBloksModel"],
  function (t, n, r, o, a, i, l) {
    var e = o("WebBloksModel").defineWebBloksMinificationMap({
        㛫: {
          logicalStyleId: "bk.data.cds.OpenCdsBottomSheetOptions",
          attrs: {
            accessibility_title: "+",
            android_back_button_override: ",",
            back_button_override: "-",
            disable_drag_to_dismiss: "$",
            disable_gradient_background: ")",
            finish_activity_on_dismiss: "1",
            follow_app_level_rule: "2",
            force_autorotate: "3",
            force_landscape_left: "4",
            force_landscape_right: "5",
            force_portrait: "6",
            gradient_background_mode: ".",
            height_percent: "&",
            id: "!",
            is_fade_in: "7",
            on_dismiss_callback: "*",
            presentation_mode: "#",
            sheet_style: "(",
            top_most_view_controller_version: "0",
          },
        },
        㜿: {
          logicalStyleId: "bk.data.cds.DismissCdsBottomSheetOptions",
          attrs: {
            callback_params: "$",
            close_to_screen_id: "#",
            follow_app_level_rule: "&",
            force_autorotate: "(",
            force_landscape_left: ")",
            force_landscape_right: "*",
            force_portrait: "+",
            id: "!",
          },
        },
        㶡: {
          logicalStyleId: "bk.data.cds.Range",
          attrs: {
            follow_app_level_rule: "&",
            force_autorotate: "(",
            force_landscape_left: ")",
            force_landscape_right: "*",
            force_portrait: "+",
            id: "!",
            max: "#",
            min: "$",
          },
        },
        㶢: {
          logicalStyleId: "bk.components.cds.Glimmer",
          attrs: {
            color: "#",
            corner_radius: "$",
            dark_opacity: "&",
            extensions: "\x85",
            id: "!",
            index: "(",
            light_opacity: ")",
            motion_preset: "+",
            shape: "*",
          },
        },
        㻖: {
          logicalStyleId: "bk.data.cds.CloseScreenOptions",
          attrs: {
            callback: "#",
            follow_app_level_rule: "$",
            force_autorotate: "&",
            force_landscape_left: "(",
            force_landscape_right: ")",
            force_portrait: "*",
            id: "!",
          },
        },
        㻗: {
          logicalStyleId: "bk.data.cds.PushScreenOptions",
          attrs: {
            animation_type: "$",
            follow_app_level_rule: "(",
            force_autorotate: ")",
            force_landscape_left: "*",
            force_landscape_right: "+",
            force_portrait: ",",
            id: "!",
            props: "&",
            waffle_secure_transport_mode: "#",
          },
        },
        㻘: {
          logicalStyleId: "bk.data.cds.PopScreenOptions",
          attrs: {
            animation_type: "#",
            follow_app_level_rule: "$",
            force_autorotate: "&",
            force_landscape_left: "(",
            force_landscape_right: ")",
            force_portrait: "*",
            id: "!",
          },
        },
        㻯: {
          logicalStyleId: "bk.components.cds.internal.Popup",
          attrs: {
            anchor_view_id: "#",
            child: "(",
            children: " ",
            content: ")",
            extensions: "\x85",
            id: "!",
            x_offset: "$",
            y_offset: "&",
          },
        },
        䂞: {
          logicalStyleId: "bk.data.cds.ModalContainerConfig",
          attrs: {
            android_back_button_override: "3",
            android_enable_edge_to_edge: "A",
            animation_type: ")",
            background: ":",
            background_color: "\x8C",
            background_overlay_color: "6",
            bottom_sheet_margins: "7",
            dimmed_background_color: "4",
            dimmed_background_tap_to_dismiss: "1",
            "disable-bottom-sheet-top-margin": "B",
            disable_back_swipe: "0",
            disable_background_scaling: "5",
            disable_bottom_sheet_top_margin: "C",
            drag_to_dismiss: "&",
            floating_screens_metadata: "E",
            follow_app_level_rule: "*",
            force_autorotate: "+",
            force_landscape_left: ",",
            force_landscape_right: "-",
            force_portrait: ".",
            force_portrait_mode: "8",
            id: "!",
            ios_ignores_top_safe_area_inset: "I",
            keyboard_mode: ">",
            keyboard_soft_input_mode: "(",
            mode: "#",
            navbar: "$",
            on_back_pressed: "D",
            on_dismiss: "9",
            remove_gradient_background: "?",
            render_behind_navbar: "=",
            safe_area_padding: "2",
            screen_container_padding_config: "F",
            use_limited_theme: ";",
            use_loading_navbar: "H",
            use_underlay_background: "G",
          },
        },
        䄠: {
          logicalStyleId: "bk.data.screen.navbar.Cds",
          attrs: {
            content_component: "#",
            follow_app_level_rule: "$",
            force_autorotate: "&",
            force_landscape_left: "(",
            force_landscape_right: ")",
            force_portrait: "*",
            id: "!",
          },
        },
      }),
      s = e;
    l.default = s;
  },
  98,
);
