__d(
  "LayoutStyles",
  ["FlexboxStyles"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = {
        alignItems: o("FlexboxStyles").alignItems,
        flexDirection: o("FlexboxStyles").flexDirection,
        justifyContent: o("FlexboxStyles").justifyContent,
        borderBottomWidth: !0,
        borderLeftWidth: !0,
        borderRightWidth: !0,
        borderTopWidth: !0,
        borderWidth: !0,
        bottom: !0,
        height: !0,
        left: !0,
        margin: !0,
        marginBottom: !0,
        marginLeft: !0,
        marginRight: !0,
        marginTop: !0,
        maxHeight: !0,
        maxWidth: !0,
        minHeight: !0,
        minWidth: !0,
        opacity: !0,
        overflow: !0,
        padding: !0,
        paddingBottom: !0,
        paddingLeft: !0,
        paddingRight: !0,
        paddingTop: !0,
        position: !0,
        top: !0,
        transform: !0,
        transformOrigin: !0,
        width: !0,
      },
      s = e;
    l.default = s;
  },
  98,
);
