__d(
  "PEVisibleProductsFbtStrings",
  ["fbt", "AdExtensionStrategy", "getJSEnumSafe"],
  function (t, n, r, o, a, i, l, s) {
    "use strict";
    var e,
      u,
      c = s._(
        /*BTDS*/ "Display products from your catalog to make your ad more relevant for each audience. We'll automatically show the most relevant product based on your current ad setup, or you can choose a specific product set. Only the first image or video selected in Media will appear on the cover for your ad.",
      ),
      d = s._(/*BTDS*/ "Edit"),
      m = s._(/*BTDS*/ "Select products"),
      p = s._(/*BTDS*/ "Show products"),
      _ = s._(/*BTDS*/ "Show products"),
      f = s._(/*BTDS*/ "Select products"),
      g = s._(/*BTDS*/ "Turn on products to select a product set."),
      h = s._(/*BTDS*/ "Save"),
      y = s._(/*BTDS*/ "Catalog"),
      C = s._(/*BTDS*/ "Product set"),
      b = s._(/*BTDS*/ "Preview"),
      v = s._(/*BTDS*/ "Manage product selection"),
      S = s._(/*BTDS*/ "Selection strategy"),
      R = s._(/*BTDS*/ "Choose which products to show"),
      L = s._(
        /*BTDS*/ "Attributes we detected from your ad's destination and media. We use them to pick the products shown in your ad.",
      ),
      E = s._(/*BTDS*/ "Products"),
      k = s._(
        /*BTDS*/ "A sample of the products this option would show. The exact products can change as your catalog updates.",
      ),
      I = s._(/*BTDS*/ "Complementary products"),
      T = s._(/*BTDS*/ "Products of the same category"),
      D = s._(/*BTDS*/ "Similar products"),
      x = s._(/*BTDS*/ "Variants of your main product"),
      $ = s._(/*BTDS*/ "Products from your collection"),
      P = s._(/*BTDS*/ "Website collections"),
      N = s._(/*BTDS*/ "Promoted products"),
      M = s._(/*BTDS*/ "Best sellers"),
      w = s._(
        /*BTDS*/ "Show products that pair well or are often bought with your product",
      ),
      A = s._(/*BTDS*/ "Products that are similar to your main product"),
      F = s._(/*BTDS*/ "More products like this one"),
      O = s._(/*BTDS*/ "Products from the collection shown in your ad"),
      B = s._(
        /*BTDS*/ "Show products that are on sale or part of an ongoing promotion",
      ),
      W = s._(/*BTDS*/ "Show products with the most engagement or sales"),
      q = s._(/*BTDS*/ "More products like this one"),
      U = s._(/*BTDS*/ "Different styles or colors of your product"),
      V = s._(
        /*BTDS*/ "Products featured, recommended, or sourced from your destination URL",
      ),
      H = s._(/*BTDS*/ "Previously advertised products"),
      G = s._(/*BTDS*/ "Products you've promoted in past campaigns"),
      z = s._(/*BTDS*/ "Highest-engagement products from your website"),
      j = s._(/*BTDS*/ "Products people view, add to cart, and buy the most"),
      K =
        ((e = {}),
        (e.complete_the_look = I),
        (e.similar_category = T),
        (e.llm_similar_product = D),
        (e.embeddings_retrieval_qwen = D),
        (e.embeddings_retrieval_v1b = D),
        (e.product_variants = x),
        (e.collection = $),
        (e.promotions = N),
        (e.best_seller = M),
        (e.website_collection = P),
        (e.previously_advertised_products = H),
        (e.buyer_based_best_seller = z),
        e);
    function Q(e) {
      var t,
        n = r("getJSEnumSafe")(r("AdExtensionStrategy"), e);
      return n != null && (t = K[n]) != null ? t : null;
    }
    var X = s._(/*BTDS*/ "Custom products"),
      Y = s._(/*BTDS*/ "Select or create a product set"),
      J = s._(/*BTDS*/ "Identified in your ad setup"),
      Z = s._(/*BTDS*/ "Collection"),
      ee = s._(/*BTDS*/ "Product"),
      te = s._(/*BTDS*/ "Promo code"),
      ne = s._(/*BTDS*/ "Products selected"),
      re = s._(
        /*BTDS*/ "This ad will show products that have been matched to your ad setup.",
      ),
      oe = s._(/*BTDS*/ "Edit product selection"),
      ae =
        ((u = {}),
        (u.complete_the_look = w),
        (u.similar_category = A),
        (u.llm_similar_product = F),
        (u.collection = O),
        (u.promotions = B),
        (u.best_seller = W),
        (u.embeddings_retrieval_qwen = q),
        (u.embeddings_retrieval_v1b = q),
        (u.product_variants = U),
        (u.website_collection = V),
        (u.previously_advertised_products = G),
        (u.buyer_based_best_seller = j),
        u);
    ((l.PE_SELECT_PRODUCTS_SUBTITLE = c),
      (l.PE_EDIT_BUTTON_LABEL = d),
      (l.PE_SELECT_PRODUCTS_BUTTON_LABEL = m),
      (l.PE_VISIBLE_PRODUCTS_MODAL_TITLE = p),
      (l.PE_SHOW_PRODUCTS_TOGGLE_LABEL = _),
      (l.PE_SELECT_PRODUCTS_TOGGLE_LABEL = f),
      (l.PE_PRODUCTS_OFF_EMPTY_STATE_MESSAGE = g),
      (l.PE_SAVE_BUTTON_LABEL = h),
      (l.PE_CATALOG_LABEL = y),
      (l.PE_PRODUCT_SET_LABEL = C),
      (l.PE_PREVIEW_LABEL = b),
      (l.PE_MANAGE_PRODUCT_SELECTION_BUTTON_LABEL = v),
      (l.PE_SELECTION_STRATEGY_LABEL = S),
      (l.PE_CHOOSE_PRODUCTS_LABEL = R),
      (l.PE_AD_UNDERSTANDING_TOOLTIP = L),
      (l.PE_PRODUCTS_LABEL = E),
      (l.PE_PRODUCT_PREVIEW_TOOLTIP = k),
      (l.STRATEGY_TYPE_LABELS = K),
      (l.getStrategyTypeLabel = Q),
      (l.PE_CUSTOM_PRODUCTS_LABEL = X),
      (l.PE_CUSTOM_PRODUCTS_DESCRIPTION = Y),
      (l.PE_AD_UNDERSTANDING_SECTION_LABEL = J),
      (l.PE_AD_UNDERSTANDING_COLLECTION_LABEL = Z),
      (l.PE_AD_UNDERSTANDING_SEED_PRODUCT_LABEL = ee),
      (l.PE_AD_UNDERSTANDING_PROMO_CODE_LABEL = te),
      (l.PE_PRODUCTS_SELECTED_INFO_HEADER = ne),
      (l.PE_PRODUCTS_SELECTED_INFO_BODY = re),
      (l.PE_PRODUCTS_SELECTED_INFO_CTA = oe),
      (l.STRATEGY_TYPE_DESCRIPTIONS = ae));
  },
  226,
);
