__d(
  "SAIPAdAccountExperience",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACTIVATION_WITH_COUPON: "ACTIVATION_WITH_COUPON",
      COUPONLESS_ACTIVATION: "COUPONLESS_ACTIVATION",
      WINBACK_WITH_COUPON: "WINBACK_WITH_COUPON",
      SHOPS_ONBOARDING_NO_SMA: "SHOPS_ONBOARDING_NO_SMA",
      GA_RECOMMENDATION: "GA_RECOMMENDATION",
      SAOFF_COUPON_SHOPIFY: "SAOFF_COUPON_SHOPIFY",
      SAOFF_COUPON_BESH: "SAOFF_COUPON_BESH",
      SAOFF_ONBOARDING: "SAOFF_ONBOARDING",
    });
    i.default = e;
  },
  66,
);
