__d(
  "AdsSFMediaPickerDataProviderPlugin",
  ["AdsImageSelectorV2Types", "AdsVideoSelectionHeaderTabTypes", "immutable"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e,
      s = {
        initialState: {
          audiencePersonaChangeSets: (e = r("immutable")).Map(),
          burnInOverlayFailureReason: null,
          burnInOverlayStatus: "idle",
          burnInOverlayStatusMap: new Map(),
          croppingChangeSets: e.Map(),
          croppingMultiMediaChangeSets: e.Map(),
          isManualCrops: !1,
          optimizationChangeSets: e.Map(),
          pacRecompositionCustomization: null,
          smartPaddingUrls: e.Map(),
          selectedBaseAsset: null,
          selectedBaseAssetID: null,
          selectedBaseAssetSource: null,
          trimmingMultiMediaChangeSets: e.Map(),
          targetAspectRatio: null,
          imagePickerSource: o("AdsImageSelectorV2Types").AdsImageSource
            .ACCOUNT_IMAGE,
          videoPickerSource: r("AdsVideoSelectionHeaderTabTypes").ACCOUNT,
          initialStepPluginKey: null,
          optimizationStepSeen: !1,
          isOpened: !1,
          isReopened: !1,
          page: null,
          isExplicitFirstStep: !1,
          relatedMediaSelectionMap: e.OrderedMap(),
          pushAdsSelectionMap: e.OrderedMap(),
          recommendedTargetLanguages: [],
          recompositionResults: e.Map(),
          recompositionPreOverrideValues: {},
          recompositionTabSelections: {},
          hasPregenRecompositionResults: null,
          intentID: null,
          multiMediaVariantsMap: e.Map(),
          selectedMultiMediaAssets: null,
          selectedPlayableAssetID: void 0,
          selectedPlayableAssetIDs: void 0,
          selectedPlayableInsertionIndex: null,
          selectedPlayableInsertionIndexByID: void 0,
          multiMediaIGVideoData: e.Map(),
          multiMediaVariantGroupData: e.Map(),
          classifiedSingleHashes: e.Set(),
          userUngroupedHashes: e.Set(),
          voiceoverDubbingStatus: "idle",
        },
      },
      u = s;
    l.default = u;
  },
  98,
);
