__d(
  "WAWebLabyrinthWaWasm.pb",
  ["WAProtoConst"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = {},
      u = {},
      c = {},
      d = {},
      m = {},
      p = {},
      _ = {},
      f = {},
      g = {},
      h = {},
      y = {},
      C = {},
      b = {},
      v = {},
      S = {},
      R = {},
      L = {},
      E = {},
      k = {},
      I = {},
      T = {},
      D = {},
      x = {},
      $ = {},
      P = {},
      N = {};
    ((s.name = "CreateBackupInput"),
      (s.internalSpec = {
        recoveryCode: [
          1,
          (e = o("WAProtoConst")).FLAGS.REQUIRED | e.TYPES.STRING,
        ],
        userId: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (u.name = "EncryptMessageInput"),
      (u.internalSpec = {
        epochRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        mailboxRootKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        orfClientState: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAnonId: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochId: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        threadId: [6, e.FLAGS.REQUIRED | e.TYPES.STRING],
        waCanonicalUserFbid: [7, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        timestampMs: [8, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        backupId: [9, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        plaintextPayload: [10, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        stanzaId: [11, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (c.name = "DecryptMessageInput"),
      (c.internalSpec = {
        epochRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        threadId: [3, e.FLAGS.REQUIRED | e.TYPES.STRING],
        encryptionVersion: [4, e.FLAGS.REQUIRED | e.TYPES.INT32],
        ciphertext: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (d.name = "OrfThreadIdInput"),
      (d.internalSpec = {
        orfClientState: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        threadId: [2, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (m.name = "DeriveMessageKeyInput"),
      (m.internalSpec = {
        epochRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        threadId: [3, e.FLAGS.REQUIRED | e.TYPES.STRING],
      }),
      (p.name = "DeriveVirtualDeviceIdInput"),
      (p.internalSpec = {
        recoveryCode: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        userId: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (_.name = "PrepareAddDeviceInput"),
      (_.internalSpec = {
        recoveryCode: [1, e.FLAGS.REQUIRED | e.TYPES.STRING],
        userId: [2, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        encryptedSecretValuesJson: [3, e.FLAGS.REQUIRED | e.TYPES.STRING],
        virtualDeviceBaseEpochId: [4, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        activeEpochId: [5, e.FLAGS.REQUIRED | e.TYPES.UINT64],
      }),
      (f.name = "DeviceOutput"),
      (f.internalSpec = {
        publicKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAuthPublicKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAuthPublicKeySig: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePublicKey: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePublicKeySig: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        supportedEncryptionVersions: [6, e.FLAGS.REPEATED | e.TYPES.INT32],
        encryptionVersionSignature: [7, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        clientVersion: [8, e.FLAGS.REQUIRED | e.TYPES.INT32],
        ocmfClientState: [9, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePrivateKey: [10, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (g.name = "EncryptedSecretValuesOutput"),
      (g.internalSpec = {
        encryptedDevicePrivateKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedObliviousValidationTokenBlob: [
          2,
          e.FLAGS.REQUIRED | e.TYPES.BYTES,
        ],
        encryptedEpochStoragePrivateKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedOcmfClientState: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedOrfClientStateV2: [5, e.TYPES.BYTES],
        encryptedMailboxRootKeyBlob: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedEpochAnonId: [7, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedEpochRootKey: [8, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (h.name = "VirtualDeviceOutput"),
      (h.internalSpec = {
        vdId: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        vdPublicKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        vdEpochStoragePublicKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        vdEpochStoragePublicKeySig: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        ocmfRotationToken: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        deviceEpochHmac: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        encryptedSecretValues: [7, e.FLAGS.REQUIRED | e.TYPES.MESSAGE, g],
      }),
      (y.name = "Epoch0Output"),
      (y.internalSpec = {
        epochFbid: [1, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        epochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochData: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        wrappedRootKeyForSelf: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochSignature: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochRootKeyFingerprint: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochRootKey: [7, e.TYPES.BYTES],
      }),
      (C.name = "CreateBackupOutput"),
      (C.internalSpec = {
        device: [1, e.TYPES.MESSAGE, f],
        virtualDevice: [2, e.TYPES.MESSAGE, h],
        epoch0: [3, e.TYPES.MESSAGE, y],
        mailboxRootKey: [4, e.TYPES.BYTES],
        error: [5, e.TYPES.STRING],
      }),
      (b.name = "EncryptMessageOutput"),
      (b.internalSpec = {
        encryptedProtobuf: [1, e.TYPES.BYTES],
        orfThreadId: [2, e.TYPES.BYTES],
        valueSecretRef: [3, e.TYPES.STRING],
        offlineThreadingId: [4, e.TYPES.UINT64],
        timestampMs: [5, e.TYPES.UINT64],
        error: [7, e.TYPES.STRING],
      }),
      (v.name = "DecryptMessageOutput"),
      (v.internalSpec = {
        plaintextPayload: [1, e.TYPES.BYTES],
        error: [2, e.TYPES.STRING],
      }),
      (S.name = "OrfThreadIdOutput"),
      (S.internalSpec = {
        orfThreadId: [1, e.TYPES.BYTES],
        error: [2, e.TYPES.STRING],
      }),
      (R.name = "DeriveMessageKeyOutput"),
      (R.internalSpec = {
        messageKey: [1, e.TYPES.BYTES],
        error: [2, e.TYPES.STRING],
      }),
      (L.name = "DeriveVirtualDeviceIdOutput"),
      (L.internalSpec = {
        virtualDeviceId: [1, e.TYPES.BYTES],
        error: [2, e.TYPES.STRING],
      }),
      (E.name = "AddDeviceKeysOutput"),
      (E.internalSpec = {
        devicePublicKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAuthPublicKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochAuthPublicKeySig: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePublicKey: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePublicKeySig: [5, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochStoragePrivateKey: [6, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        orfClientState: [7, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (k.name = "AddDeviceEpochOutput"),
      (k.internalSpec = {
        serverEpochId: [1, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        epochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        epochRootKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (I.name = "PrepareAddDeviceOutput"),
      (I.internalSpec = {
        deviceKeys: [1, e.TYPES.MESSAGE, E],
        currentEpoch: [2, e.TYPES.MESSAGE, k],
        mailboxRootSalt: [3, e.TYPES.BYTES],
        orfRotationToken: [4, e.TYPES.BYTES],
        deviceEpochHmac: [5, e.TYPES.BYTES],
        epochRootKeyFingerprint: [6, e.TYPES.BYTES],
        supportedEncryptionVersions: [7, e.FLAGS.REPEATED | e.TYPES.INT32],
        encryptionVersionSignature: [8, e.TYPES.BYTES],
        clientVersion: [9, e.TYPES.INT32],
        error: [10, e.TYPES.STRING],
      }),
      (T.name = "RotateEpochMemberInput"),
      (T.internalSpec = {
        deviceId: [1, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        epochStoragePublicKey: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        devicePublicKey: [3, e.FLAGS.REQUIRED | e.TYPES.BYTES],
      }),
      (D.name = "RotateEpochInput"),
      (D.internalSpec = {
        currentEpochRootKey: [1, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        currentEpochAnonId: [2, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        currentEpochFbid: [3, e.FLAGS.REQUIRED | e.TYPES.UINT64],
        epochStoragePrivateKey: [4, e.FLAGS.REQUIRED | e.TYPES.BYTES],
        members: [5, e.FLAGS.REPEATED | e.TYPES.MESSAGE, T],
      }),
      (x.name = "RotateEpochMemberEdge"),
      (x.internalSpec = {
        deviceId: [1, e.TYPES.UINT64],
        encryptedEpochKey: [2, e.TYPES.BYTES],
        deviceEpochHmac: [3, e.TYPES.BYTES],
      }),
      ($.name = "BackwardEdge"),
      ($.internalSpec = {
        encryptedPrevEpochAnonId: [1, e.TYPES.BYTES],
        encryptedPrevEpochRootKey: [2, e.TYPES.BYTES],
        prevEpochRootKeyFingerprint: [3, e.TYPES.BYTES],
      }),
      (P.name = "RotateEpochOutput"),
      (P.internalSpec = {
        newEpochRootKey: [1, e.TYPES.BYTES],
        newEpochAnonId: [2, e.TYPES.UINT64],
        newEpochFbid: [8, e.TYPES.UINT64],
        epochAnonId: [3, e.TYPES.BYTES],
        backwardEdge: [4, e.TYPES.MESSAGE, $],
        memberEdges: [5, e.FLAGS.REPEATED | e.TYPES.MESSAGE, x],
        epochRootKeyFingerprint: [6, e.TYPES.BYTES],
        error: [7, e.TYPES.STRING],
      }),
      (N.name = "LabyrinthWaCommand"),
      (N.internalSpec = {
        createBackupInput: [1, e.TYPES.MESSAGE, s],
        encryptMessageInput: [2, e.TYPES.MESSAGE, u],
        decryptMessageInput: [3, e.TYPES.MESSAGE, c],
        orfThreadIdInput: [4, e.TYPES.MESSAGE, d],
        deriveMessageKeyInput: [5, e.TYPES.MESSAGE, m],
        rotateEpochInput: [6, e.TYPES.MESSAGE, D],
        deriveVirtualDeviceIdInput: [7, e.TYPES.MESSAGE, p],
        prepareAddDeviceInput: [8, e.TYPES.MESSAGE, _],
        __oneofs__: {
          commandInput: [
            "createBackupInput",
            "encryptMessageInput",
            "decryptMessageInput",
            "orfThreadIdInput",
            "deriveMessageKeyInput",
            "rotateEpochInput",
            "deriveVirtualDeviceIdInput",
            "prepareAddDeviceInput",
          ],
        },
      }),
      (l.CreateBackupInputSpec = s),
      (l.EncryptMessageInputSpec = u),
      (l.DecryptMessageInputSpec = c),
      (l.OrfThreadIdInputSpec = d),
      (l.DeriveMessageKeyInputSpec = m),
      (l.DeriveVirtualDeviceIdInputSpec = p),
      (l.PrepareAddDeviceInputSpec = _),
      (l.DeviceOutputSpec = f),
      (l.EncryptedSecretValuesOutputSpec = g),
      (l.VirtualDeviceOutputSpec = h),
      (l.Epoch0OutputSpec = y),
      (l.CreateBackupOutputSpec = C),
      (l.EncryptMessageOutputSpec = b),
      (l.DecryptMessageOutputSpec = v),
      (l.OrfThreadIdOutputSpec = S),
      (l.DeriveMessageKeyOutputSpec = R),
      (l.DeriveVirtualDeviceIdOutputSpec = L),
      (l.AddDeviceKeysOutputSpec = E),
      (l.AddDeviceEpochOutputSpec = k),
      (l.PrepareAddDeviceOutputSpec = I),
      (l.RotateEpochMemberInputSpec = T),
      (l.RotateEpochInputSpec = D),
      (l.RotateEpochMemberEdgeSpec = x),
      (l.BackwardEdgeSpec = $),
      (l.RotateEpochOutputSpec = P),
      (l.LabyrinthWaCommandSpec = N));
  },
  98,
);
