__d(
  "AdsInsightsColumnCategoryConsts",
  ["AdsApplicationUtils", "AdsInsightsColumnCategory"],
  function (t, n, r, o, a, i, l) {
    var e,
      s = o("AdsApplicationUtils").isPowerEditor(),
      u = [
        (e = r("AdsInsightsColumnCategory")).ROOT,
        e.PERFORMANCE,
        e.KEY_METRICS,
        e.RESULTS_AND_SPEND,
        e.ENGAGEMENT_KEY_METRICS,
        e.RESULTS,
        e.SPEND,
        e.DISTRIBUTION,
        e.AWARENESS_CATEGORY,
        e.MEDIA_AWARENESS_KEY_METRICS,
        e.IMPRESSIONS,
        e.VIEWS,
        e.DIAGNOSTICS,
        e.PERFORMANCE_PLACEHOLDER,
        e.ADVANCED_METRICS,
        e.PERFORMANCE_RELEVANCE_DIAGNOSTICS,
        e.AD_RELEVANCE,
        e.CLICKS_KEY_METRICS,
        e.DISTRIBUTION_ADVANCED,
        e.IMPRESSIONS_ADVANCED,
        e.OPTIMIZATION_ADVANCED,
        e.AWARENESS_ADVANCED,
        e.VIEWS_ADVANCED,
        e.BRAND_LIFT,
        e.ENGAGEMENT_ADVANCED,
        e.CONVERSIONS_ADVANCED,
        e.STANDARD_EVENTS_ADVANCED_SUBCATEGORY,
        e.MESSAGING_AND_CALLING,
        e.MEDIA_TRACKING_TAB,
        e.PERFORMANCE_COST,
        e.PERFORMANCE_FUNNEL,
        e.CLICKS_ADVANCED_SUBCATEGORY,
        e.PERFORMANCE_FUNNEL_ADVANCED,
        e.ENGAGEMENT,
        e.ENGAGEMENT_PAGE_AND_POST,
        e.ENGAGEMENT_PAGE_AND_POST_COST,
        e.ENGAGEMENT_PAGE_AND_POST_VALUE,
        e.TRAFFIC,
        e.LIKES,
        e.ENGAGEMENT_SUBCATEGORY,
        e.MESSAGING_ENGAGEMENT_KEY_METRICS,
        e.CALLING_ENGAGEMENT_KEY_METRICS,
        e.MESSAGING,
        e.CALLING,
        e.MESSAGING_COST,
        e.MEDIA,
        e.MEDIA_COST,
        e.CLICKS,
        e.CLICKS_COST,
        e.AWARENESS,
        e.AWARENESS_COST,
        e.CONVERSIONS,
        e.STANDARD_EVENTS,
        e.CUSTOM_CONVERSIONS,
        e.LEADS,
        e.WEBSITE,
        e.WEBSITE_ACTIONS_FB_PIXEL,
        e.WEBSITE_CPA_FB_PIXEL,
        e.WEBSITE_CONVERSIONS_FB_PIXEL,
        e.WEBSITE_ACTIONS_CONVERSION_PIXEL,
        e.WEBSITE_CPA_CONVERSION_PIXEL,
        e.WEBSITE_CONVERSIONS_CONVERSION_PIXEL,
        e.WEBSITE_ACTIONS_CUSTOM_CONVERSIONS,
        e.WEBSITE_CPA_CUSTOM_CONVERSIONS,
        e.WEBSITE_CONVERSIONS_CUSTOM_CONVERSIONS,
        e.APPS,
        e.APPS_CPA,
        e.APPS_CONVERSIONS,
        e.APPS_ACTIONS_CUSTOM_CONVERSIONS,
        e.APPS_CPA_CUSTOM_CONVERSIONS,
        e.APPS_CONVERSIONS_CUSTOM_CONVERSIONS,
        e.APPS_CONVERSIONS_OPTIMIZED_CUSTOM_EVENT,
        e.ON_FACEBOOK,
        e.ON_FACEBOOK_COST,
        e.ON_FACEBOOK_CONVERSION_VALUE,
        e.OFFLINE,
        e.OFFLINE_ACTIONS_CPA,
        e.OFFLINE_CONVERSIONS,
        e.OFFLINE_ACTIONS_CUSTOM_CONVERSIONS,
        e.OFFLINE_ACTIONS_CPA_CUSTOM_CONVERSIONS,
        e.OFFLINE_CONVERSIONS_CUSTOM_CONVERSIONS,
        e.COMMERCE,
        e.COMMERCE_CPA,
        e.COMMERCE_CONVERSIONS,
        e.SETTINGS,
      ]
        .concat(
          s
            ? []
            : [
                r("AdsInsightsColumnCategory").SETTINGS_PLACEHOLDER,
                r("AdsInsightsColumnCategory").SETTINGS_LEVEL_3,
                r("AdsInsightsColumnCategory").SETTINGS_LEVEL_2,
                r("AdsInsightsColumnCategory").SETTINGS_LEVEL_1,
              ],
        )
        .concat(
          (function () {
            var e,
              t = [
                (e = r("AdsInsightsColumnCategory")).TARGETING,
                e.AD_CREATIVE,
                e.STORE_VISITS,
                e.SPLIT_TEST,
                e.OPTIMIZATION,
                e.TRACKING,
                e.MARKETING_MESSAGES,
              ],
              n = [
                e.STATUS_AND_DATES,
                e.GOAL_BUDGET_AND_SCHEDULE,
                e.OBJECT_NAMES_AND_IDS,
              ];
            return [].concat(n, t);
          })(),
        );
    l.categoryIDs = u;
  },
  98,
);
