__d(
  "AdsCreativeOptimizationToolChangeSetRecord",
  ["immutable"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("immutable").Record({
        adapt_to_placement: void 0,
        add_text_overlay: void 0,
        ads_with_benefits: void 0,
        app_highlights: void 0,
        biz_ai: void 0,
        carousel_to_video: void 0,
        catalog_feed_tag: void 0,
        creative_stickers: void 0,
        cv_transformation: void 0,
        da_add_text_overlay: void 0,
        da_advantage_plus_creative: void 0,
        da_dynamic_media: void 0,
        description_automation: void 0,
        dha_optimization: void 0,
        dynamic_experience: void 0,
        dynamic_experience_bundle: void 0,
        dynamic_partner_content: void 0,
        enhance_cta: void 0,
        feed_caption_optimization: void 0,
        generate_cta: void 0,
        hide_price: void 0,
        ig_video_native_subtitle: void 0,
        image_animation: void 0,
        image_auto_crop: void 0,
        image_background_gen: void 0,
        image_brightness_and_contrast: void 0,
        image_enhancement: void 0,
        image_templates: void 0,
        image_touchups: void 0,
        image_uncrop: void 0,
        inline_comment: void 0,
        local_store_extension: void 0,
        media_liquidity_animated_image: void 0,
        media_music: void 0,
        media_order: void 0,
        multi_photo_to_video: void 0,
        product_browsing: void 0,
        pac_relaxation: void 0,
        product_extensions: void 0,
        product_metadata_automation: void 0,
        product_tagging: void 0,
        product_tags: void 0,
        profile_card: void 0,
        replace_media_text: void 0,
        reveal_details_over_time: void 0,
        show_destination_blurbs: void 0,
        show_summary: void 0,
        site_extensions: void 0,
        text_optimizations: void 0,
        text_translation: void 0,
        translate_voiceover: void 0,
        video_auto_crop: void 0,
        video_filtering: void 0,
        video_highlight: void 0,
        video_highlights: void 0,
        video_to_image: void 0,
        video_uncrop: void 0,
        video_voiceover: void 0,
        wa_mm_image_filtering: void 0,
      }),
      l = (function (e) {
        function t() {
          return e.apply(this, arguments) || this;
        }
        return (babelHelpers.inheritsLoose(t, e), t);
      })(e),
      s = l;
    i.default = s;
  },
  66,
);
