__d(
  "AdsPublishSourceTypes",
  ["$InternalEnum"],
  function (t, n, r, o, a, i) {
    "use strict";
    var e = n("$InternalEnum").Mirrored([
        "ASC_BUDGET_OPTIMIZATION",
        "ASC_FRAGMENTATION_MFR",
        "AUTOMATIC_PLACEMENT_MFR",
        "BUSINESS_AI_AGENT_UPSELL",
        "CAMPAIGN_EDITOR_BUDGET_UPSELL",
        "CAMPAIGN_GROUP_BUDGET_BULK_ADOPTION",
        "CAMPAIGN_GROUP_BUDGET_BULK_ADOPTION_EMAIL",
        "CAMPAIGN_GROUP_BUDGET_ELIGIBILITY",
        "CAMPAIGN_GROUP_EDITOR_BUDGET_SECTION",
        "CAMPAIGN_GROUP_EDITOR_BUDGET_UPSELL",
        "CONVERGENCE_EDITOR",
        "CONVERGENCE_EDITOR_BREADCRUMB_NARROW",
        "DELETION_DIALOG",
        "DELIVERY_CLARITY",
        "EDITOR",
        "EDITOR_DELETION_MODAL",
        "EDITOR_FOOTER_REVIEW_AND_PUBLISH",
        "EDITOR_HEADER",
        "EDITOR_ONE_NAV",
        "INITIAL_PAGE_LOAD_REMINDER",
        "LIGHTWEIGHT_AB_TEST_MODAL",
        "NES",
        "ODAX_DUPLICATE",
        "ODAX_EDITOR_DUPLICATE",
        "ONE_CLICK_EDITOR",
        "REMINDER_DIALOG",
        "REVIEW",
        "TABLE",
        "UPGRADE_DUPLICATE",
        "UPGRADE_PACKAGE_DUPLICATE",
        "MUSIC_MFR",
        "FRAGMENTATION_MFR",
      ]),
      l = e;
    i.default = l;
  },
  66,
);
