__d(
  "SignalsAppEventsUnifiedTypeEnum",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      FB_MOBILE_ACHIEVEMENT_UNLOCKED: "fb_mobile_achievement_unlocked",
      FB_MOBILE_ACTIVATE_APP: "fb_mobile_activate_app",
      FB_MOBILE_ADD_PAYMENT_INFO: "fb_mobile_add_payment_info",
      FB_MOBILE_ADD_TO_CART: "fb_mobile_add_to_cart",
      FB_MOBILE_ADD_TO_WISHLIST: "fb_mobile_add_to_wishlist",
      FB_MOBILE_COMPLETE_REGISTRATION: "fb_mobile_complete_registration",
      FB_MOBILE_CONTACT: "Contact",
      FB_MOBILE_CONTENT_VIEW: "fb_mobile_content_view",
      FB_MOBILE_CUSTOMIZE_PRODUCT: "CustomizeProduct",
      FB_MOBILE_D2_RETENTION: "fb_mobile_d2_retention",
      FB_MOBILE_D7_RETENTION: "fb_mobile_d7_retention",
      FB_MOBILE_DONATE: "Donate",
      FB_MOBILE_FIND_LOCATION: "FindLocation",
      FB_MOBILE_INITIATED_CHECKOUT: "fb_mobile_initiated_checkout",
      FB_MOBILE_LEVEL_ACHIEVED: "fb_mobile_level_achieved",
      FB_MOBILE_PURCHASE: "fb_mobile_purchase",
      FB_MOBILE_RATE: "fb_mobile_rate",
      FB_MOBILE_SCHEDULE: "Schedule",
      FB_MOBILE_SEARCH: "fb_mobile_search",
      FB_MOBILE_SPENT_CREDITS: "fb_mobile_spent_credits",
      FB_MOBILE_START_TRIAL: "StartTrial",
      FB_MOBILE_SUBMIT_APPLICATION: "SubmitApplication",
      FB_MOBILE_SUBSCRIBE: "Subscribe",
      FB_MOBILE_TUTORIAL_COMPLETION: "fb_mobile_tutorial_completion",
      FB_MOBILE_AD_CLICK: "AdClick",
      FB_MOBILE_AD_IMPRESSION: "AdImpression",
      FB_MOBILE_REFUND: "fb_mobile_refund",
      FB_MOBILE_LEAD_SUBMITTED: "lead_submitted",
      FB_MOBILE_ORDER_CREATED: "order_created",
      FB_MOBILE_ORDER_SHIPPED: "order_shipped",
    });
    i.default = e;
  },
  66,
);
