__d(
  "StandardEventsEnum",
  [],
  function (t, n, r, o, a, i) {
    var e = Object.freeze({
      ACHIEVEMENT_UNLOCKED: "AchievementUnlocked",
      ACTIVATE_APP: "ActivateApp",
      ADD_PAYMENT_INFO: "AddPaymentInfo",
      ADD_TO_CART: "AddToCart",
      ADD_TO_WISHLIST: "AddToWishlist",
      COMPLETE_REGISTRATION: "CompleteRegistration",
      CONTACT: "Contact",
      CUSTOMIZE_PRODUCT: "CustomizeProduct",
      DONATE: "Donate",
      FIND_LOCATION: "FindLocation",
      INITIATE_CHECKOUT: "InitiateCheckout",
      LEAD: "Lead",
      LEVEL_ACHIEVED: "LevelAchieved",
      LEAD_SUBMITTED: "LeadSubmitted",
      ORDER_CREATED: "OrderCreated",
      ORDER_SHIPPED: "OrderShipped",
      PAYMENT_RECEIVED: "PaymentReceived",
      PURCHASE: "Purchase",
      RATE: "Rate",
      SCHEDULE: "Schedule",
      SEARCH: "Search",
      SPENT_CREDITS: "SpentCredits",
      START_TRIAL: "StartTrial",
      SUBMIT_APPLICATION: "SubmitApplication",
      SUBSCRIBE: "Subscribe",
      TUTORIAL_COMPLETION: "TutorialCompletion",
      VIEW_CONTENT: "ViewContent",
      AD_CLICK: "AdClick",
      AD_IMPRESSION: "AdImpression",
      RECURRING_PAYMENT: "RecurringPayment",
      CANCEL: "Cancel",
      RECURRING_SUBSCRIPTION_PAYMENT: "RecurringSubscriptionPayment",
      CANCEL_SUBSCRIPTION: "CancelSubscription",
      APPEND_VALUE: "AppendValue",
      APPEND_CLICK_ATTRIBUTION: "AppendClickAttribution",
      UPDATE_CUSTOMER: "UpdateCustomer",
      APPEND_VIEW_ATTRIBUTION: "AppendViewAttribution",
      APPEND_ATTRIBUTION: "AppendAttribution",
      REPLY: "Reply",
      CONVERSATION: "Conversation",
    });
    i.default = e;
  },
  66,
);
