__d(
  "ProductsActionTypes",
  ["keyMirrorRecursive"],
  function (t, n, r, o, a, i, l) {
    "use strict";
    var e = r("keyMirrorRecursive")(
        {
          AD_ACCOUNT: {
            DPA_ELIGIBLE_CATALOGS: {
              LIST: {
                EXTEND: null,
                LOAD_ERROR: null,
                LOADED: null,
                RELOAD: null,
              },
            },
          },
          CATALOG: {
            ADD_EXTERNAL_EVENT_SOURCES: null,
            ADD_PRODUCT: null,
            ATTACH_TO_BUSINESS: null,
            ATTACH_TO_LOCATIONS_PAGE: null,
            BATCH_LOAD_ERROR: null,
            BATCH_LOADED: null,
            CREATE: null,
            CREATE_AND_FETCH: null,
            CREATED: null,
            DPA_ELIGIBLE_AD_ACCOUNT: {
              LIST: { LOAD_ERROR: null, LOADED: null },
            },
            EXTERNAL_EVENT_SOURCE_LIST_UPDATED: null,
            NAME_UPDATED: null,
            PARTIAL_RELOAD: null,
            PREVIEW: { ERROR: null, LOADED: null, RELOAD: null },
            RELOAD: null,
            SMART_PIXEL_SETTINGS: {
              CREATE: null,
              DELETE: null,
              DELETED: null,
              EMIT_CHANGE: null,
              LIST: { RELOAD: null },
              LOAD_ERROR: null,
              LOADED: null,
              UPDATE: null,
              UPDATED: null,
            },
            SMART_PIXEL_STATS: { LOAD_ERROR: null, LOADED: null, RELOAD: null },
            UNATTACH_FROM_LOCATIONS_PAGE: null,
          },
          CATALOG_SEGMENT: { CREATE: null, CREATED: null },
          DA_EVENT_SAMPLES: { LOAD_ERROR: null, LOADED: null },
          DESTINATION: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          DPA_AD_ACCOUNT: { LIST: { LOAD_ERROR: null, LOADED: null } },
          ERROR: { CLEAR: null, SET: null },
          EVENT_STATS: { LOAD_ERROR: null, LOADED: null },
          EXTERNAL_EVENT_SOURCE: {
            ASSOCIATION_DIALOG: { CLOSE: null, OPEN: null },
            LIST: { LOAD_ERROR: null, LOADED: null },
            LOADED: null,
            NO_SIGNAL: null,
          },
          FEED: {
            BATCH_LOAD_ERROR: null,
            BATCH_LOADED: null,
            LIST: { LOAD_ERROR: null, LOADED: null, PARTIAL_LOAD: null },
            RELOAD: null,
            RELOAD_NON_EXPENSIVE: null,
            RULE: {
              BATCH_CREATED: null,
              BATCH_DELETE_ERROR: null,
              BATCH_LOAD_ERROR: null,
              BATCH_LOADED: null,
              CREATE: null,
              DELETE_BATCH: null,
              LIST: { LOAD_ERROR: null, LOADED: null },
              RELOAD: null,
              SUGGESTION: { EMIT_CHANGE: null, LOAD_ERROR: null, LOADED: null },
              UPDATE: null,
              UPDATE_ERROR: null,
            },
            RULE_PREVIEW_SAMPLES: { LOAD_ERROR: null, LOADED: null },
            SUPPLEMENTARY_FEED: { UPDATE: null },
            UPDATE: null,
            UPDATE_ERROR: null,
            UPDATED: null,
            UPLOAD_FINISHED: null,
          },
          FEED_UPLOAD: {
            BATCH_LOAD_ERROR: null,
            BATCH_LOADED: null,
            CREATE: null,
            CREATED: null,
            FETCH: null,
            LIST: { LOAD_ERROR: null, LOADED: null },
          },
          FLIGHT: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          FLIGHT_CATALOG_SETTINGS: { LOAD_ERROR: "", LOADED: "" },
          HOME_LISTING: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          HOME_SERVICE_PROVIDER: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          HOTEL: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          JOBS_JOB: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          LOCAL_SERVICE_BUSINESS: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          LOCATION_BASED_ITEM: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          MEDIA_TITLE: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          OFFLINE_PRODUCTS: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          PAGINATION_SORT_AND_SEARCH: {
            INIT: "",
            NEXT_PAGE: "",
            RESET_OFFSET: "",
            SEARCH: "",
            SORT: "",
          },
          PRODUCT_SET: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          PRODUCT_SET_FIELD: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          PRODUCTS_CF_RECEIPT_DIALOG_UI: { CLEAR: null, SET_AD_TITLE: null },
          PRODUCTS_FACET_AGREGGATION: { LOAD_ERROR: null, LOADED: null },
          PRODUCTS_FACET_SEARCH: { LOAD_ERROR: null, LOADED: null },
          SMART_PIXEL: { LOAD_ERROR: "", LOADED: "", RELOAD: "" },
          TIME_LOGGING: { LOG: "", SET: "" },
          UPLOAD_ERROR: {
            BATCH_LOAD_ERROR: null,
            BATCH_LOADED: null,
            LIST: {
              LOAD_ERROR: null,
              LOADED: null,
              PARTIAL_LOAD: null,
              RELOAD: null,
            },
          },
          UPLOAD_ERROR_SAMPLE: {
            BATCH_LOAD_ERROR: null,
            BATCH_LOADED: null,
            LIST: { LOAD_ERROR: null, LOADED: null, PARTIAL_LOAD: null },
          },
          VEHICLE: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
          VEHICLE_OFFER: { BATCH_LOAD_ERROR: "", BATCH_LOADED: "" },
        },
        "ProductCatalog",
      ),
      s = e;
    l.default = s;
  },
  98,
);
